@startuml
skinparam linetype polyline
left to right direction
object "data:Mazak" as o1 {
 type = ex:Machine
 }
object "data:Mazak-xaxism" as o2 {
 type = ex:Structure
 }
object "data:Mazak-yaxism" as o3 {
 type = ex:Structure
 }
object "data:Mazak-zaxis" as o4 {
 type = ex:Structure
 }
object "data:Mazak-table" as o5 {
 type = ex:Structure
 }
object "data:Mazak-trundle" as o6 {
 type = ex:Structure
 }
object "data:Mazak-x" as o7 {
 type = ex:LinearMotionSystem
 }
object "data:Mazak-y" as o8 {
 type = ex:LinearMotionSystem
 }
object "data:Mazak-z" as o9 {
 type = ex:LinearMotionSystem
 }
object "data:Mazak-c" as o10 {
 type = ex:RotaryMotionSystem
 }
object "data:Mazak-br" as o11 {
 type = ex:RotaryMotionSystem
 }
object "data:Mazak-c2" as o12 {
 type = ex:RotaryMotionSystem
 }
object "data:Mazak-cont" as o13 {
 type = ex:ControlSystem
 }
object "data:Mazak-door1" as o14 {
 type = obo:object
 }
object "data:Mazak-partocc" as o15 {
 type = ex:Part
 }
object "data:Mazak-elec" as o16 {
 type = ex:ElectricalSystem
 }
object "data:Mazak-hydraulic" as o17 {
 type = ex:HydraulicSystem
 }
object "data:Mazak-coolant" as o18 {
 type = obo:object
 }
object "data:Mazak-pneumatic" as o19 {
 type = ex:PneumaticSystem
 }
object "data:Mazak-lubrication" as o20 {
 type = ex:LubricationSystem
 }
object "data:Mazak-personnelm" as o21 {
 type = core:Person
 }
object "data:Mazak-procstock" as o22 {
 type = ex:Stock
 }
object "data:Mazak-enclosurem" as o23 {
 type = ex:Structure
 }
object "data:Mazak-x-Xballscrew" as o24 {
 type = ex:Ballscrew
 }
object "data:Mazak-x-Xmotor" as o25 {
 type = ex:Motor
 }
object "data:Mazak-y-Yballscrew" as o26 {
 type = ex:Ballscrew
 }
object "data:Mazak-y-Ymotor" as o27 {
 type = ex:Motor
 }
object "data:Mazak-z-Zballscrew" as o28 {
 type = ex:Ballscrew
 }
object "data:Mazak-z-Zmotor" as o29 {
 type = ex:Motor
 }
object "data:Mazak-c-C2motor" as o30 {
 type = ex:Motor
 }
object "data:Mazak-br-Bmotor" as o31 {
 type = ex:Motor
 }
object "data:Mazak-c2-Cmotor" as o32 {
 type = ex:Motor
 }
object "data:Mazak-cont-path1" as o33 {
 type = ex:ControlSystemPath
 }
o1 --> o2 : obo:has member part at some time
o1 : cmns-dsg:hasName = Mazak
o1 --> o3 : obo:has member part at some time
o1 --> o4 : obo:has member part at some time
o1 --> o5 : obo:has member part at some time
o1 --> o6 : obo:has member part at some time
o1 --> o7 : obo:has member part at some time
o1 --> o8 : obo:has member part at some time
o1 --> o9 : obo:has member part at some time
o1 --> o10 : obo:has member part at some time
o1 --> o11 : obo:has member part at some time
o1 --> o12 : obo:has member part at some time
o1 --> o13 : obo:has member part at some time
o1 --> o14 : obo:has member part at some time
o1 --> o15 : obo:has member part at some time
o1 --> o16 : obo:has member part at some time
o1 --> o17 : obo:has member part at some time
o1 --> o18 : obo:has member part at some time
o1 --> o19 : obo:has member part at some time
o1 --> o20 : obo:has member part at some time
o1 --> o21 : obo:has member part at some time
o1 --> o22 : obo:has member part at some time
o1 --> o23 : obo:has member part at some time
o7 --> o24 : obo:has member part at some time
o7 : cmns-dsg:hasName = X
o7 --> o25 : obo:has member part at some time
o8 --> o26 : obo:has member part at some time
o8 : cmns-dsg:hasName = Y
o8 --> o27 : obo:has member part at some time
o9 --> o28 : obo:has member part at some time
o9 : cmns-dsg:hasName = Z
o9 --> o29 : obo:has member part at some time
o10 --> o30 : obo:has member part at some time
o10 : cmns-dsg:hasName = C1
o11 --> o31 : obo:has member part at some time
o11 : cmns-dsg:hasName = B
o12 --> o32 : obo:has member part at some time
o12 : cmns-dsg:hasName = C2
o13 --> o33 : obo:has member part at some time
o13 : cmns-dsg:hasName = controller
@enduml
