
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title test

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A" }
individual(o0, ontology2, owl.Ontology)
individual(o1, ontology1, owl.Ontology)
individual(o2, Mazak, Mazak.Mazak)
individual(o3, name1, Designators.Name)
individual(o4, MazakTurningCapability, example.TurningCapability)
individual(o5, MazakMillingCapability, example.MillingCapability)
individual(o6, Mazak_mstruct_X_AXIS, Mazak.MazakmstructX_AXIS)
individual(o7, name2, Designators.Name)
individual(o8, Mazak_mstruct_Y_AXIS, Mazak.MazakmstructY_AXIS)
individual(o9, name3, Designators.Name)
individual(o10, Mazak_mstruct_Z_AXIS, Mazak.MazakmstructZ_AXIS)
individual(o11, name4, Designators.Name)
individual(o12, Mazak_mstruct_TABLE, Mazak.MazakmstructTABLE)
individual(o13, name5, Designators.Name)
individual(o14, Mazak_mstruct_TRUNDLE, Mazak.MazakmstructTRUNDLE)
individual(o15, name6, Designators.Name)
individual(o16, Mazak_base_X_Xballscrew, Mazak.MazakbaseXXballscrew)
individual(o17, name7, Designators.Name)
individual(o18, Mazak_base_X_Xmotor, Mazak.MazakbaseXXmotor)
individual(o19, name8, Designators.Name)
individual(o20, Mazak_base_X, Mazak.MazakbaseX)
individual(o21, name9, Designators.Name)
individual(o22, mazakbasexdesign1, Mazak.MazakbaseXDesign)
individual(o23, Mazak_base_XLENGTHNominal, Core.ValueExpression)
individual(o24, Mazak_base_XLINEAR_FORCEMaximum, Core.ValueExpression)
individual(o25, Mazak_base_XLINEAR_FORCEMinimum, Core.ValueExpression)
individual(o26, Mazak_base_XVELOCITY_RAPIDMaximum, Core.ValueExpression)
individual(o27, Mazak_base_XVELOCITY_RAPIDMinimum, Core.ValueExpression)
individual(o28, Mazak_base_XVELOCITY_PROGRAMMEDMaximum, Core.ValueExpression)
individual(o29, Mazak_base_XVELOCITY_PROGRAMMEDMinimum, Core.ValueExpression)
individual(o30, Mazak_base_XPrismaticMotionCapability, example.PrismaticMotionCapability)
individual(o31, Mazak_base_XPOSITION_ACTUAL, IOF_Qualities-Physical.Displacement)
individual(o32, Mazak_base_XTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o33, Mazak_base_Y_Yballscrew, Mazak.MazakbaseYYballscrew)
individual(o34, name10, Designators.Name)
individual(o35, Mazak_base_Y_Ymotor, Mazak.MazakbaseYYmotor)
individual(o36, name11, Designators.Name)
individual(o37, Mazak_base_Y, Mazak.MazakbaseY)
individual(o38, name12, Designators.Name)
individual(o39, mazakbaseydesign1, Mazak.MazakbaseYDesign)
individual(o40, Mazak_base_YLENGTHNominal, Core.ValueExpression)
individual(o41, Mazak_base_YLINEAR_FORCEMaximum, Core.ValueExpression)
individual(o42, Mazak_base_YLINEAR_FORCEMinimum, Core.ValueExpression)
individual(o43, Mazak_base_YVELOCITY_RAPIDMaximum, Core.ValueExpression)
individual(o44, Mazak_base_YVELOCITY_RAPIDMinimum, Core.ValueExpression)
individual(o45, Mazak_base_YVELOCITY_PROGRAMMEDMaximum, Core.ValueExpression)
individual(o46, Mazak_base_YVELOCITY_PROGRAMMEDMinimum, Core.ValueExpression)
individual(o47, Mazak_base_YPrismaticMotionCapability, example.PrismaticMotionCapability)
individual(o48, Mazak_base_YPOSITION_ACTUAL, IOF_Qualities-Physical.Displacement)
individual(o49, Mazak_base_YTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o50, Mazak_base_Z_Zballscrew, Mazak.MazakbaseZZballscrew)
individual(o51, name13, Designators.Name)
individual(o52, Mazak_base_Z_Zmotor, Mazak.MazakbaseZZmotor)
individual(o53, name14, Designators.Name)
individual(o54, Mazak_base_Z, Mazak.MazakbaseZ)
individual(o55, name15, Designators.Name)
individual(o56, mazakbasezdesign1, Mazak.MazakbaseZDesign)
individual(o57, Mazak_base_ZLENGTHNominal, Core.ValueExpression)
individual(o58, Mazak_base_ZLINEAR_FORCEMaximum, Core.ValueExpression)
individual(o59, Mazak_base_ZLINEAR_FORCEMinimum, Core.ValueExpression)
individual(o60, Mazak_base_ZVELOCITY_RAPIDMaximum, Core.ValueExpression)
individual(o61, Mazak_base_ZVELOCITY_RAPIDMinimum, Core.ValueExpression)
individual(o62, Mazak_base_ZVELOCITY_PROGRAMMEDMaximum, Core.ValueExpression)
individual(o63, Mazak_base_ZVELOCITY_PROGRAMMEDMinimum, Core.ValueExpression)
individual(o64, Mazak_base_ZPrismaticMotionCapability, example.PrismaticMotionCapability)
individual(o65, Mazak_base_ZPOSITION_ACTUAL, IOF_Qualities-Physical.Displacement)
individual(o66, Mazak_base_ZTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o67, Mazak_base_C1_Cmotor, Mazak.MazakbaseC1Cmotor)
individual(o68, name16, Designators.Name)
individual(o69, Mazak_base_C1, Mazak.MazakbaseC1)
individual(o70, name17, Designators.Name)
individual(o71, mazakbasec1design1, Mazak.MazakbaseC1Design)
individual(o72, Mazak_base_C1ROTARY_VELOCITYMaximum, Core.ValueExpression)
individual(o73, Mazak_base_C1ROTARY_VELOCITYMinimum, Core.ValueExpression)
individual(o74, Mazak_base_C1ContinuousMotionCapability, example.ContinuousMotionCapability)
individual(o75, Mazak_base_C1ROTARY_VELOCITY_ACTUAL, example.RevoluteVelocity)
individual(o76, Mazak_base_C1TEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o77, Mazak_base_B_Bmotor, Mazak.MazakbaseBBmotor)
individual(o78, name18, Designators.Name)
individual(o79, Mazak_base_B, Mazak.MazakbaseB)
individual(o80, name19, Designators.Name)
individual(o81, mazakbasebdesign1, Mazak.MazakbaseBDesign)
individual(o82, Mazak_base_BANGLEMaximum, Core.ValueExpression)
individual(o83, Mazak_base_BANGLEMinimum, Core.ValueExpression)
individual(o84, Mazak_base_BTORQUEMaximum, Core.ValueExpression)
individual(o85, Mazak_base_BTORQUEMinimum, Core.ValueExpression)
individual(o86, Mazak_base_BRevoluteMotionCapability, example.RevoluteMotionCapability)
individual(o87, Mazak_base_BANGLE_ACTUAL, IOF_Qualities-Physical.Angle)
individual(o88, Mazak_base_C2_C2motor, Mazak.MazakbaseC2C2motor)
individual(o89, name20, Designators.Name)
individual(o90, Mazak_base_C2, Mazak.MazakbaseC2)
individual(o91, name21, Designators.Name)
individual(o92, mazakbasec2design1, Mazak.MazakbaseC2Design)
individual(o93, Mazak_base_C2ANGLEMaximum, Core.ValueExpression)
individual(o94, Mazak_base_C2ANGLEMinimum, Core.ValueExpression)
individual(o95, Mazak_base_C2TORQUEMaximum, Core.ValueExpression)
individual(o96, Mazak_base_C2TORQUEMinimum, Core.ValueExpression)
individual(o97, Mazak_base_C2RevoluteMotionCapability, example.RevoluteMotionCapability)
individual(o98, Mazak_base_C2ANGLE_ACTUAL, IOF_Qualities-Physical.Angle)
individual(o99, Mazak_controller, Mazak.Mazakcontroller)
individual(o100, name22, Designators.Name)
individual(o101, Mazak_controller_path, Mazak.Mazakcontrollerpath)
individual(o102, name23, Designators.Name)
individual(o103, Mazak_door, Mazak.Mazakdoor)
individual(o104, name24, Designators.Name)
individual(o105, Mazak_parts_partocc, Mazak.Mazakpartspartocc)
individual(o106, name25, Designators.Name)
individual(o107, Mazak_systems_electric, Mazak.Mazaksystemselectric)
individual(o108, name26, Designators.Name)
individual(o109, Mazak_systems_hydraulic, Mazak.Mazaksystemshydraulic)
individual(o110, name27, Designators.Name)
individual(o111, Mazak_systems_coolant, Mazak.Mazaksystemscoolant)
individual(o112, name28, Designators.Name)
individual(o113, Mazak_systems_coolantTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o114, Mazak_systems_pneumatic, Mazak.Mazaksystemspneumatic)
individual(o115, name29, Designators.Name)
individual(o116, Mazak_systems_lubrication, Mazak.Mazaksystemslubrication)
individual(o117, name30, Designators.Name)
individual(o118, Mazak_auxiliaries_environmental, Mazak.Mazakauxiliariesenvironmental)
individual(o119, name31, Designators.Name)
individual(o120, Mazak_auxiliaries_environmentalTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o121, Mazak_resources_materials_stock, Mazak.Mazakresourcesmaterialsstock)
individual(o122, name32, Designators.Name)
individual(o123, Mazak_enclosure, Mazak.Mazakenclosure)
individual(o124, name33, Designators.Name)
individual(o125, Mazak_enclosureTEMPERATURE, IOF_Qualities-Physical.Temperature)
property(o0, 81, o1)
property(o2, Designators.hasName, o3)
property(o2, Core.hasCapability, o4)
property(o2, Core.hasFunction, o5)
property(o2, obo.BFO_0000115, o6)
property(o6, Designators.hasName, o7)
property(o2, obo.BFO_0000115, o8)
property(o8, Designators.hasName, o9)
property(o2, obo.BFO_0000115, o10)
property(o10, Designators.hasName, o11)
property(o2, obo.BFO_0000115, o12)
property(o12, Designators.hasName, o13)
property(o2, obo.BFO_0000115, o14)
property(o14, Designators.hasName, o15)
property(o2, obo.BFO_0000115, o16)
property(o16, Designators.hasName, o17)
property(o2, obo.BFO_0000115, o18)
property(o18, Designators.hasName, o19)
property(o2, obo.BFO_0000115, o20)
property(o20, Designators.hasName, o21)
property(o20, Core.prescribedBy, o22)
property(o22, Core.hasValueExpressionAtAllTimes, o23)
property(o22, Core.hasValueExpressionAtAllTimes, o24)
property(o22, Core.hasValueExpressionAtAllTimes, o25)
property(o22, Core.hasValueExpressionAtAllTimes, o26)
property(o22, Core.hasValueExpressionAtAllTimes, o27)
property(o22, Core.hasValueExpressionAtAllTimes, o28)
property(o22, Core.hasValueExpressionAtAllTimes, o29)
property(o20, Core.hasFunction, o30)
property(o20, Core.hasQuality, o31)
property(o18, Core.hasQuality, o32)
property(o2, obo.BFO_0000115, o33)
property(o33, Designators.hasName, o34)
property(o2, obo.BFO_0000115, o35)
property(o35, Designators.hasName, o36)
property(o2, obo.BFO_0000115, o37)
property(o37, Designators.hasName, o38)
property(o37, Core.prescribedBy, o39)
property(o39, Core.hasValueExpressionAtAllTimes, o40)
property(o39, Core.hasValueExpressionAtAllTimes, o41)
property(o39, Core.hasValueExpressionAtAllTimes, o42)
property(o39, Core.hasValueExpressionAtAllTimes, o43)
property(o39, Core.hasValueExpressionAtAllTimes, o44)
property(o39, Core.hasValueExpressionAtAllTimes, o45)
property(o39, Core.hasValueExpressionAtAllTimes, o46)
property(o37, Core.hasFunction, o47)
property(o37, Core.hasQuality, o48)
property(o35, Core.hasQuality, o49)
property(o2, obo.BFO_0000115, o50)
property(o50, Designators.hasName, o51)
property(o2, obo.BFO_0000115, o52)
property(o52, Designators.hasName, o53)
property(o2, obo.BFO_0000115, o54)
property(o54, Designators.hasName, o55)
property(o54, Core.prescribedBy, o56)
property(o56, Core.hasValueExpressionAtAllTimes, o57)
property(o56, Core.hasValueExpressionAtAllTimes, o58)
property(o56, Core.hasValueExpressionAtAllTimes, o59)
property(o56, Core.hasValueExpressionAtAllTimes, o60)
property(o56, Core.hasValueExpressionAtAllTimes, o61)
property(o56, Core.hasValueExpressionAtAllTimes, o62)
property(o56, Core.hasValueExpressionAtAllTimes, o63)
property(o54, Core.hasFunction, o64)
property(o54, Core.hasQuality, o65)
property(o52, Core.hasQuality, o66)
property(o2, obo.BFO_0000115, o67)
property(o67, Designators.hasName, o68)
property(o2, obo.BFO_0000115, o69)
property(o69, Designators.hasName, o70)
property(o69, Core.prescribedBy, o71)
property(o71, Core.hasValueExpressionAtAllTimes, o72)
property(o71, Core.hasValueExpressionAtAllTimes, o73)
property(o69, Core.hasFunction, o74)
property(o69, Core.measuresAtSomeTime, o75)
property(o67, Core.hasQuality, o76)
property(o2, obo.BFO_0000115, o77)
property(o77, Designators.hasName, o78)
property(o2, obo.BFO_0000115, o79)
property(o79, Designators.hasName, o80)
property(o79, Core.prescribedBy, o81)
property(o81, Core.hasValueExpressionAtAllTimes, o82)
property(o81, Core.hasValueExpressionAtAllTimes, o83)
property(o81, Core.hasValueExpressionAtAllTimes, o84)
property(o81, Core.hasValueExpressionAtAllTimes, o85)
property(o79, Core.hasFunction, o86)
property(o79, Core.hasQuality, o87)
property(o2, obo.BFO_0000115, o88)
property(o88, Designators.hasName, o89)
property(o2, obo.BFO_0000115, o90)
property(o90, Designators.hasName, o91)
property(o90, Core.prescribedBy, o92)
property(o92, Core.hasValueExpressionAtAllTimes, o93)
property(o92, Core.hasValueExpressionAtAllTimes, o94)
property(o92, Core.hasValueExpressionAtAllTimes, o95)
property(o92, Core.hasValueExpressionAtAllTimes, o96)
property(o90, Core.hasFunction, o97)
property(o90, Core.hasQuality, o98)
property(o2, obo.BFO_0000115, o99)
property(o99, Designators.hasName, o100)
property(o99, obo.BFO_0000115, o101)
property(o101, Designators.hasName, o102)
property(o2, obo.BFO_0000115, o103)
property(o103, Designators.hasName, o104)
property(o2, obo.BFO_0000115, o105)
property(o105, Designators.hasName, o106)
property(o2, obo.BFO_0000115, o107)
property(o107, Designators.hasName, o108)
property(o2, obo.BFO_0000115, o109)
property(o109, Designators.hasName, o110)
property(o2, obo.BFO_0000115, o111)
property(o111, Designators.hasName, o112)
property(o111, Core.hasQuality, o113)
property(o2, obo.BFO_0000115, o114)
property(o114, Designators.hasName, o115)
property(o2, obo.BFO_0000115, o116)
property(o116, Designators.hasName, o117)
property(o2, obo.BFO_0000115, o118)
property(o118, Designators.hasName, o119)
property(o118, Core.hasQuality, o120)
property(o2, obo.BFO_0000115, o121)
property(o121, Designators.hasName, o122)
property(o2, obo.BFO_0000115, o123)
property(o123, Designators.hasName, o124)
property(o123, Core.hasQuality, o125)
property(o20, example.joinedTo, o123)
property(o20, example.joinedTo, o6)
property(o37, example.joinedTo, o6)
property(o37, example.joinedTo, o8)
property(o54, example.joinedTo, o8)
property(o54, example.joinedTo, o10)
property(o69, example.joinedTo, o10)
property(o79, example.joinedTo, o123)
property(o79, example.joinedTo, o14)
property(o90, example.joinedTo, o14)
property(o90, example.joinedTo, o12)
data(o2, rdf-schema.label, Mazak particular)
data(o3, Designators.hasTextualName, Mazak)
data(o6, rdf-schema.label, Mazak mstruct X_AXIS particular)
data(o7, Designators.hasTextualName, X_AXIS)
data(o8, rdf-schema.label, Mazak mstruct Y_AXIS particular)
data(o9, Designators.hasTextualName, Y_AXIS)
data(o10, rdf-schema.label, Mazak mstruct Z_AXIS particular)
data(o11, Designators.hasTextualName, Z_AXIS)
data(o12, rdf-schema.label, Mazak mstruct TABLE particular)
data(o13, Designators.hasTextualName, TABLE)
data(o14, rdf-schema.label, Mazak mstruct TRUNDLE particular)
data(o15, Designators.hasTextualName, TRUNDLE)
data(o16, rdf-schema.label, Mazak base X Xballscrew particular)
data(o17, Designators.hasTextualName, Xballscrew)
data(o18, rdf-schema.label, Mazak base X Xmotor particular)
data(o19, Designators.hasTextualName, Xmotor)
data(o20, rdf-schema.label, Mazak base X particular)
data(o21, Designators.hasTextualName, X)
data(o22, rdf-schema.label, MazakbaseXDesign particular)
data(o23, Core.hasSimpleExpressionValue, 650.0)
data(o24, Core.hasSimpleExpressionValue, 5200.0)
data(o25, Core.hasSimpleExpressionValue, 0.0)
data(o26, Core.hasSimpleExpressionValue, 7000.0)
data(o27, Core.hasSimpleExpressionValue, 1.0)
data(o28, Core.hasSimpleExpressionValue, 7000.0)
data(o29, Core.hasSimpleExpressionValue, 1.0)
data(o33, rdf-schema.label, Mazak base Y Yballscrew particular)
data(o34, Designators.hasTextualName, Yballscrew)
data(o35, rdf-schema.label, Mazak base Y Ymotor particular)
data(o36, Designators.hasTextualName, Ymotor)
data(o37, rdf-schema.label, Mazak base Y particular)
data(o38, Designators.hasTextualName, Y)
data(o39, rdf-schema.label, MazakbaseYDesign particular)
data(o40, Core.hasSimpleExpressionValue, 550.0)
data(o41, Core.hasSimpleExpressionValue, 5200.0)
data(o42, Core.hasSimpleExpressionValue, 0.0)
data(o43, Core.hasSimpleExpressionValue, 7000.0)
data(o44, Core.hasSimpleExpressionValue, 1.0)
data(o45, Core.hasSimpleExpressionValue, 7000.0)
data(o46, Core.hasSimpleExpressionValue, 1.0)
data(o50, rdf-schema.label, Mazak base Z Zballscrew particular)
data(o51, Designators.hasTextualName, Zballscrew)
data(o52, rdf-schema.label, Mazak base Z Zmotor particular)
data(o53, Designators.hasTextualName, Zmotor)
data(o54, rdf-schema.label, Mazak base Z particular)
data(o55, Designators.hasTextualName, Z)
data(o56, rdf-schema.label, MazakbaseZDesign particular)
data(o57, Core.hasSimpleExpressionValue, 530.0)
data(o58, Core.hasSimpleExpressionValue, 9600.0)
data(o59, Core.hasSimpleExpressionValue, 0.0)
data(o60, Core.hasSimpleExpressionValue, 7000.0)
data(o61, Core.hasSimpleExpressionValue, 1.0)
data(o62, Core.hasSimpleExpressionValue, 7000.0)
data(o63, Core.hasSimpleExpressionValue, 1.0)
data(o67, rdf-schema.label, Mazak base C1 Cmotor particular)
data(o68, Designators.hasTextualName, Cmotor)
data(o69, rdf-schema.label, Mazak base C1 particular)
data(o70, Designators.hasTextualName, C1)
data(o71, rdf-schema.label, MazakbaseC1Design particular)
data(o72, Core.hasSimpleExpressionValue, 12000.0)
data(o73, Core.hasSimpleExpressionValue, 0.0)
data(o77, rdf-schema.label, Mazak base B Bmotor particular)
data(o78, Designators.hasTextualName, Bmotor)
data(o79, rdf-schema.label, Mazak base B particular)
data(o80, Designators.hasTextualName, B)
data(o81, rdf-schema.label, MazakbaseBDesign particular)
data(o82, Core.hasSimpleExpressionValue, 120.0)
data(o83, Core.hasSimpleExpressionValue, -30.0)
data(o84, Core.hasSimpleExpressionValue, 400.0)
data(o85, Core.hasSimpleExpressionValue, 0.0)
data(o88, rdf-schema.label, Mazak base C2 C2motor particular)
data(o89, Designators.hasTextualName, C2motor)
data(o90, rdf-schema.label, Mazak base C2 particular)
data(o91, Designators.hasTextualName, C2)
data(o92, rdf-schema.label, MazakbaseC2Design particular)
data(o93, Core.hasSimpleExpressionValue, 360.0)
data(o94, Core.hasSimpleExpressionValue, -360.0)
data(o95, Core.hasSimpleExpressionValue, 400.0)
data(o96, Core.hasSimpleExpressionValue, 0.0)
data(o99, rdf-schema.label, Mazak controller particular)
data(o100, Designators.hasTextualName, controller)
data(o101, rdf-schema.label, Mazak controller path particular)
data(o102, Designators.hasTextualName, path)
data(o103, rdf-schema.label, Mazak door particular)
data(o104, Designators.hasTextualName, door)
data(o105, rdf-schema.label, Mazak parts partocc particular)
data(o106, Designators.hasTextualName, partocc)
data(o107, rdf-schema.label, Mazak systems electric particular)
data(o108, Designators.hasTextualName, electric)
data(o109, rdf-schema.label, Mazak systems hydraulic particular)
data(o110, Designators.hasTextualName, hydraulic)
data(o111, rdf-schema.label, Mazak systems coolant particular)
data(o112, Designators.hasTextualName, coolant)
data(o114, rdf-schema.label, Mazak systems pneumatic particular)
data(o115, Designators.hasTextualName, pneumatic)
data(o116, rdf-schema.label, Mazak systems lubrication particular)
data(o117, Designators.hasTextualName, lubrication)
data(o118, rdf-schema.label, Mazak auxiliaries environmental particular)
data(o119, Designators.hasTextualName, environmental)
data(o121, rdf-schema.label, Mazak resources materials stock particular)
data(o122, Designators.hasTextualName, stock)
data(o123, rdf-schema.label, Mazak enclosure particular)
data(o124, Designators.hasTextualName, enclosure)
@enduml
