
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title test

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A" }
individual(o0, ontology2, owl.Ontology)
individual(o1, ontology1, owl.Ontology)
individual(o2, Mazak, Mazak.Mazak)
individual(o3, name1, Designators.Name)
individual(o4, MazakTurningCapability, example.TurningCapability)
individual(o5, MazakMillingCapability, example.MillingCapability)
individual(o6, Mazak_mstruct_X_AXIS, Mazak.MazakmstructX_AXIS)
individual(o7, name2, Designators.Name)
individual(o8, Mazak_mstruct_Y_AXIS, Mazak.MazakmstructY_AXIS)
individual(o9, name3, Designators.Name)
individual(o10, Mazak_mstruct_Z_AXIS, Mazak.MazakmstructZ_AXIS)
individual(o11, name4, Designators.Name)
individual(o12, Mazak_mstruct_TABLE, Mazak.MazakmstructTABLE)
individual(o13, name5, Designators.Name)
individual(o14, Mazak_mstruct_TRUNDLE, Mazak.MazakmstructTRUNDLE)
individual(o15, name6, Designators.Name)
individual(o16, Mazak_base_X_Xballscrew, Mazak.MazakbaseXXballscrew)
individual(o17, name7, Designators.Name)
individual(o18, Mazak_base_X_Xmotor, Mazak.MazakbaseXXmotor)
individual(o19, name8, Designators.Name)
individual(o20, Mazak_base_X, Mazak.MazakbaseX)
individual(o21, name9, Designators.Name)
individual(o22, mazakbasexdesign1, Mazak.MazakbaseXDesign)
individual(o23, Mazak_base_XLENGTHNominal, Core.ValueExpression)
individual(o24, MilliM, unit.Unit)
individual(o25, Mazak_base_XLINEAR_FORCEMaximum, Core.ValueExpression)
individual(o26, N, unit.Unit)
individual(o27, Mazak_base_XLINEAR_FORCEMinimum, Core.ValueExpression)
individual(o28, Mazak_base_XVELOCITY_RAPIDMaximum, Core.ValueExpression)
individual(o29, MilliM-PER-SEC, unit.Unit)
individual(o30, Mazak_base_XVELOCITY_RAPIDMinimum, Core.ValueExpression)
individual(o31, Mazak_base_XVELOCITY_PROGRAMMEDMaximum, Core.ValueExpression)
individual(o32, Mazak_base_XVELOCITY_PROGRAMMEDMinimum, Core.ValueExpression)
individual(o33, Mazak_base_XPrismaticMotionCapability, example.PrismaticMotionCapability)
individual(o34, Mazak_base_XPOSITION_ACTUAL, IOF_Qualities-Physical.Displacement)
individual(o35, Mazak_base_XTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o36, Mazak_base_Y_Yballscrew, Mazak.MazakbaseYYballscrew)
individual(o37, name10, Designators.Name)
individual(o38, Mazak_base_Y_Ymotor, Mazak.MazakbaseYYmotor)
individual(o39, name11, Designators.Name)
individual(o40, Mazak_base_Y, Mazak.MazakbaseY)
individual(o41, name12, Designators.Name)
individual(o42, mazakbaseydesign1, Mazak.MazakbaseYDesign)
individual(o43, Mazak_base_YLENGTHNominal, Core.ValueExpression)
individual(o44, Mazak_base_YLINEAR_FORCEMaximum, Core.ValueExpression)
individual(o45, Mazak_base_YLINEAR_FORCEMinimum, Core.ValueExpression)
individual(o46, Mazak_base_YVELOCITY_RAPIDMaximum, Core.ValueExpression)
individual(o47, Mazak_base_YVELOCITY_RAPIDMinimum, Core.ValueExpression)
individual(o48, Mazak_base_YVELOCITY_PROGRAMMEDMaximum, Core.ValueExpression)
individual(o49, Mazak_base_YVELOCITY_PROGRAMMEDMinimum, Core.ValueExpression)
individual(o50, Mazak_base_YPrismaticMotionCapability, example.PrismaticMotionCapability)
individual(o51, Mazak_base_YPOSITION_ACTUAL, IOF_Qualities-Physical.Displacement)
individual(o52, Mazak_base_YTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o53, Mazak_base_Z_Zballscrew, Mazak.MazakbaseZZballscrew)
individual(o54, name13, Designators.Name)
individual(o55, Mazak_base_Z_Zmotor, Mazak.MazakbaseZZmotor)
individual(o56, name14, Designators.Name)
individual(o57, Mazak_base_Z, Mazak.MazakbaseZ)
individual(o58, name15, Designators.Name)
individual(o59, mazakbasezdesign1, Mazak.MazakbaseZDesign)
individual(o60, Mazak_base_ZLENGTHNominal, Core.ValueExpression)
individual(o61, Mazak_base_ZLINEAR_FORCEMaximum, Core.ValueExpression)
individual(o62, Mazak_base_ZLINEAR_FORCEMinimum, Core.ValueExpression)
individual(o63, Mazak_base_ZVELOCITY_RAPIDMaximum, Core.ValueExpression)
individual(o64, Mazak_base_ZVELOCITY_RAPIDMinimum, Core.ValueExpression)
individual(o65, Mazak_base_ZVELOCITY_PROGRAMMEDMaximum, Core.ValueExpression)
individual(o66, Mazak_base_ZVELOCITY_PROGRAMMEDMinimum, Core.ValueExpression)
individual(o67, Mazak_base_ZPrismaticMotionCapability, example.PrismaticMotionCapability)
individual(o68, Mazak_base_ZPOSITION_ACTUAL, IOF_Qualities-Physical.Displacement)
individual(o69, Mazak_base_ZTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o70, Mazak_base_C1_Cmotor, Mazak.MazakbaseC1Cmotor)
individual(o71, name16, Designators.Name)
individual(o72, Mazak_base_C1, Mazak.MazakbaseC1)
individual(o73, name17, Designators.Name)
individual(o74, mazakbasec1design1, Mazak.MazakbaseC1Design)
individual(o75, Mazak_base_C1ROTARY_VELOCITYMaximum, Core.ValueExpression)
individual(o76, REV-PER-MIN, unit.Unit)
individual(o77, Mazak_base_C1ROTARY_VELOCITYMinimum, Core.ValueExpression)
individual(o78, Mazak_base_C1ContinuousMotionCapability, example.ContinuousMotionCapability)
individual(o79, Mazak_base_C1ROTARY_VELOCITY_ACTUAL, example.RevoluteVelocity)
individual(o80, Mazak_base_C1TEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o81, Mazak_base_B_Bmotor, Mazak.MazakbaseBBmotor)
individual(o82, name18, Designators.Name)
individual(o83, Mazak_base_B, Mazak.MazakbaseB)
individual(o84, name19, Designators.Name)
individual(o85, mazakbasebdesign1, Mazak.MazakbaseBDesign)
individual(o86, Mazak_base_BANGLEMaximum, Core.ValueExpression)
individual(o87, Mazak_base_BANGLEMinimum, Core.ValueExpression)
individual(o88, Mazak_base_BTORQUEMaximum, Core.ValueExpression)
individual(o89, N-M, unit.Unit)
individual(o90, Mazak_base_BTORQUEMinimum, Core.ValueExpression)
individual(o91, Mazak_base_BRevoluteMotionCapability, example.RevoluteMotionCapability)
individual(o92, Mazak_base_BANGLE_ACTUAL, IOF_Qualities-Physical.Angle)
individual(o93, Mazak_base_C2_C2motor, Mazak.MazakbaseC2C2motor)
individual(o94, name20, Designators.Name)
individual(o95, Mazak_base_C2, Mazak.MazakbaseC2)
individual(o96, name21, Designators.Name)
individual(o97, mazakbasec2design1, Mazak.MazakbaseC2Design)
individual(o98, Mazak_base_C2ANGLEMaximum, Core.ValueExpression)
individual(o99, Mazak_base_C2ANGLEMinimum, Core.ValueExpression)
individual(o100, Mazak_base_C2TORQUEMaximum, Core.ValueExpression)
individual(o101, Mazak_base_C2TORQUEMinimum, Core.ValueExpression)
individual(o102, Mazak_base_C2RevoluteMotionCapability, example.RevoluteMotionCapability)
individual(o103, Mazak_base_C2ANGLE_ACTUAL, IOF_Qualities-Physical.Angle)
individual(o104, Mazak_controller, Mazak.Mazakcontroller)
individual(o105, name22, Designators.Name)
individual(o106, Mazak_controller_path, Mazak.Mazakcontrollerpath)
individual(o107, name23, Designators.Name)
individual(o108, Mazak_door, Mazak.Mazakdoor)
individual(o109, name24, Designators.Name)
individual(o110, Mazak_parts_partocc, Mazak.Mazakpartspartocc)
individual(o111, name25, Designators.Name)
individual(o112, Mazak_systems_electric, Mazak.Mazaksystemselectric)
individual(o113, name26, Designators.Name)
individual(o114, Mazak_systems_hydraulic, Mazak.Mazaksystemshydraulic)
individual(o115, name27, Designators.Name)
individual(o116, Mazak_systems_coolant, Mazak.Mazaksystemscoolant)
individual(o117, name28, Designators.Name)
individual(o118, Mazak_systems_coolantTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o119, Mazak_systems_pneumatic, Mazak.Mazaksystemspneumatic)
individual(o120, name29, Designators.Name)
individual(o121, Mazak_systems_lubrication, Mazak.Mazaksystemslubrication)
individual(o122, name30, Designators.Name)
individual(o123, Mazak_auxiliaries_environmental, Mazak.Mazakauxiliariesenvironmental)
individual(o124, name31, Designators.Name)
individual(o125, Mazak_auxiliaries_environmentalTEMPERATURE, IOF_Qualities-Physical.Temperature)
individual(o126, Mazak_resources_materials_stock, Mazak.Mazakresourcesmaterialsstock)
individual(o127, name32, Designators.Name)
individual(o128, Mazak_enclosure, Mazak.Mazakenclosure)
individual(o129, name33, Designators.Name)
individual(o130, Mazak_enclosureTEMPERATURE, IOF_Qualities-Physical.Temperature)
property(o0, 81, o1)
property(o2, Designators.hasName, o3)
property(o2, Core.hasCapability, o4)
property(o2, Core.hasFunction, o5)
property(o2, obo.BFO_0000115, o6)
property(o6, Designators.hasName, o7)
property(o2, obo.BFO_0000115, o8)
property(o8, Designators.hasName, o9)
property(o2, obo.BFO_0000115, o10)
property(o10, Designators.hasName, o11)
property(o2, obo.BFO_0000115, o12)
property(o12, Designators.hasName, o13)
property(o2, obo.BFO_0000115, o14)
property(o14, Designators.hasName, o15)
property(o2, obo.BFO_0000115, o16)
property(o16, Designators.hasName, o17)
property(o2, obo.BFO_0000115, o18)
property(o18, Designators.hasName, o19)
property(o2, obo.BFO_0000115, o20)
property(o20, Designators.hasName, o21)
property(o20, Core.prescribedBy, o22)
property(o22, Core.hasValueExpressionAtAllTimes, o23)
property(o23, example.hasUnit, o24)
property(o22, Core.hasValueExpressionAtAllTimes, o25)
property(o25, example.hasUnit, o26)
property(o22, Core.hasValueExpressionAtAllTimes, o27)
property(o27, example.hasUnit, o26)
property(o22, Core.hasValueExpressionAtAllTimes, o28)
property(o28, example.hasUnit, o29)
property(o22, Core.hasValueExpressionAtAllTimes, o30)
property(o30, example.hasUnit, o29)
property(o22, Core.hasValueExpressionAtAllTimes, o31)
property(o31, example.hasUnit, o29)
property(o22, Core.hasValueExpressionAtAllTimes, o32)
property(o32, example.hasUnit, o29)
property(o20, Core.hasFunction, o33)
property(o20, Core.hasQuality, o34)
property(o18, Core.hasQuality, o35)
property(o2, obo.BFO_0000115, o36)
property(o36, Designators.hasName, o37)
property(o2, obo.BFO_0000115, o38)
property(o38, Designators.hasName, o39)
property(o2, obo.BFO_0000115, o40)
property(o40, Designators.hasName, o41)
property(o40, Core.prescribedBy, o42)
property(o42, Core.hasValueExpressionAtAllTimes, o43)
property(o43, example.hasUnit, o24)
property(o42, Core.hasValueExpressionAtAllTimes, o44)
property(o44, example.hasUnit, o26)
property(o42, Core.hasValueExpressionAtAllTimes, o45)
property(o45, example.hasUnit, o26)
property(o42, Core.hasValueExpressionAtAllTimes, o46)
property(o46, example.hasUnit, o29)
property(o42, Core.hasValueExpressionAtAllTimes, o47)
property(o47, example.hasUnit, o29)
property(o42, Core.hasValueExpressionAtAllTimes, o48)
property(o48, example.hasUnit, o29)
property(o42, Core.hasValueExpressionAtAllTimes, o49)
property(o49, example.hasUnit, o29)
property(o40, Core.hasFunction, o50)
property(o40, Core.hasQuality, o51)
property(o38, Core.hasQuality, o52)
property(o2, obo.BFO_0000115, o53)
property(o53, Designators.hasName, o54)
property(o2, obo.BFO_0000115, o55)
property(o55, Designators.hasName, o56)
property(o2, obo.BFO_0000115, o57)
property(o57, Designators.hasName, o58)
property(o57, Core.prescribedBy, o59)
property(o59, Core.hasValueExpressionAtAllTimes, o60)
property(o60, example.hasUnit, o24)
property(o59, Core.hasValueExpressionAtAllTimes, o61)
property(o61, example.hasUnit, o26)
property(o59, Core.hasValueExpressionAtAllTimes, o62)
property(o62, example.hasUnit, o26)
property(o59, Core.hasValueExpressionAtAllTimes, o63)
property(o63, example.hasUnit, o29)
property(o59, Core.hasValueExpressionAtAllTimes, o64)
property(o64, example.hasUnit, o29)
property(o59, Core.hasValueExpressionAtAllTimes, o65)
property(o65, example.hasUnit, o29)
property(o59, Core.hasValueExpressionAtAllTimes, o66)
property(o66, example.hasUnit, o29)
property(o57, Core.hasFunction, o67)
property(o57, Core.hasQuality, o68)
property(o55, Core.hasQuality, o69)
property(o2, obo.BFO_0000115, o70)
property(o70, Designators.hasName, o71)
property(o2, obo.BFO_0000115, o72)
property(o72, Designators.hasName, o73)
property(o72, Core.prescribedBy, o74)
property(o74, Core.hasValueExpressionAtAllTimes, o75)
property(o75, example.hasUnit, o76)
property(o74, Core.hasValueExpressionAtAllTimes, o77)
property(o77, example.hasUnit, o76)
property(o72, Core.hasFunction, o78)
property(o72, Core.measuresAtSomeTime, o79)
property(o70, Core.hasQuality, o80)
property(o2, obo.BFO_0000115, o81)
property(o81, Designators.hasName, o82)
property(o2, obo.BFO_0000115, o83)
property(o83, Designators.hasName, o84)
property(o83, Core.prescribedBy, o85)
property(o85, Core.hasValueExpressionAtAllTimes, o86)
property(o85, Core.hasValueExpressionAtAllTimes, o87)
property(o85, Core.hasValueExpressionAtAllTimes, o88)
property(o88, example.hasUnit, o89)
property(o85, Core.hasValueExpressionAtAllTimes, o90)
property(o90, example.hasUnit, o89)
property(o83, Core.hasFunction, o91)
property(o83, Core.hasQuality, o92)
property(o2, obo.BFO_0000115, o93)
property(o93, Designators.hasName, o94)
property(o2, obo.BFO_0000115, o95)
property(o95, Designators.hasName, o96)
property(o95, Core.prescribedBy, o97)
property(o97, Core.hasValueExpressionAtAllTimes, o98)
property(o97, Core.hasValueExpressionAtAllTimes, o99)
property(o97, Core.hasValueExpressionAtAllTimes, o100)
property(o100, example.hasUnit, o89)
property(o97, Core.hasValueExpressionAtAllTimes, o101)
property(o101, example.hasUnit, o89)
property(o95, Core.hasFunction, o102)
property(o95, Core.hasQuality, o103)
property(o2, obo.BFO_0000115, o104)
property(o104, Designators.hasName, o105)
property(o104, obo.BFO_0000115, o106)
property(o106, Designators.hasName, o107)
property(o2, obo.BFO_0000115, o108)
property(o108, Designators.hasName, o109)
property(o2, obo.BFO_0000115, o110)
property(o110, Designators.hasName, o111)
property(o2, obo.BFO_0000115, o112)
property(o112, Designators.hasName, o113)
property(o2, obo.BFO_0000115, o114)
property(o114, Designators.hasName, o115)
property(o2, obo.BFO_0000115, o116)
property(o116, Designators.hasName, o117)
property(o116, Core.hasQuality, o118)
property(o2, obo.BFO_0000115, o119)
property(o119, Designators.hasName, o120)
property(o2, obo.BFO_0000115, o121)
property(o121, Designators.hasName, o122)
property(o2, obo.BFO_0000115, o123)
property(o123, Designators.hasName, o124)
property(o123, Core.hasQuality, o125)
property(o2, obo.BFO_0000115, o126)
property(o126, Designators.hasName, o127)
property(o2, obo.BFO_0000115, o128)
property(o128, Designators.hasName, o129)
property(o128, Core.hasQuality, o130)
property(o20, example.joinedTo, o128)
property(o20, example.joinedTo, o6)
property(o40, example.joinedTo, o6)
property(o40, example.joinedTo, o8)
property(o57, example.joinedTo, o8)
property(o57, example.joinedTo, o10)
property(o72, example.joinedTo, o10)
property(o83, example.joinedTo, o128)
property(o83, example.joinedTo, o14)
property(o95, example.joinedTo, o14)
property(o95, example.joinedTo, o12)
data(o2, rdf-schema.label, Mazak particular)
data(o3, Designators.hasTextualName, Mazak)
data(o6, rdf-schema.label, Mazak mstruct X_AXIS particular)
data(o7, Designators.hasTextualName, X_AXIS)
data(o8, rdf-schema.label, Mazak mstruct Y_AXIS particular)
data(o9, Designators.hasTextualName, Y_AXIS)
data(o10, rdf-schema.label, Mazak mstruct Z_AXIS particular)
data(o11, Designators.hasTextualName, Z_AXIS)
data(o12, rdf-schema.label, Mazak mstruct TABLE particular)
data(o13, Designators.hasTextualName, TABLE)
data(o14, rdf-schema.label, Mazak mstruct TRUNDLE particular)
data(o15, Designators.hasTextualName, TRUNDLE)
data(o16, rdf-schema.label, Mazak base X Xballscrew particular)
data(o17, Designators.hasTextualName, Xballscrew)
data(o18, rdf-schema.label, Mazak base X Xmotor particular)
data(o19, Designators.hasTextualName, Xmotor)
data(o20, rdf-schema.label, Mazak base X particular)
data(o21, Designators.hasTextualName, X)
data(o22, rdf-schema.label, MazakbaseXDesign particular)
data(o23, Core.hasSimpleExpressionValue, 650.0)
data(o25, Core.hasSimpleExpressionValue, 5200.0)
data(o27, Core.hasSimpleExpressionValue, 0.0)
data(o28, Core.hasSimpleExpressionValue, 7000.0)
data(o30, Core.hasSimpleExpressionValue, 1.0)
data(o31, Core.hasSimpleExpressionValue, 7000.0)
data(o32, Core.hasSimpleExpressionValue, 1.0)
data(o36, rdf-schema.label, Mazak base Y Yballscrew particular)
data(o37, Designators.hasTextualName, Yballscrew)
data(o38, rdf-schema.label, Mazak base Y Ymotor particular)
data(o39, Designators.hasTextualName, Ymotor)
data(o40, rdf-schema.label, Mazak base Y particular)
data(o41, Designators.hasTextualName, Y)
data(o42, rdf-schema.label, MazakbaseYDesign particular)
data(o43, Core.hasSimpleExpressionValue, 550.0)
data(o44, Core.hasSimpleExpressionValue, 5200.0)
data(o45, Core.hasSimpleExpressionValue, 0.0)
data(o46, Core.hasSimpleExpressionValue, 7000.0)
data(o47, Core.hasSimpleExpressionValue, 1.0)
data(o48, Core.hasSimpleExpressionValue, 7000.0)
data(o49, Core.hasSimpleExpressionValue, 1.0)
data(o53, rdf-schema.label, Mazak base Z Zballscrew particular)
data(o54, Designators.hasTextualName, Zballscrew)
data(o55, rdf-schema.label, Mazak base Z Zmotor particular)
data(o56, Designators.hasTextualName, Zmotor)
data(o57, rdf-schema.label, Mazak base Z particular)
data(o58, Designators.hasTextualName, Z)
data(o59, rdf-schema.label, MazakbaseZDesign particular)
data(o60, Core.hasSimpleExpressionValue, 530.0)
data(o61, Core.hasSimpleExpressionValue, 9600.0)
data(o62, Core.hasSimpleExpressionValue, 0.0)
data(o63, Core.hasSimpleExpressionValue, 7000.0)
data(o64, Core.hasSimpleExpressionValue, 1.0)
data(o65, Core.hasSimpleExpressionValue, 7000.0)
data(o66, Core.hasSimpleExpressionValue, 1.0)
data(o70, rdf-schema.label, Mazak base C1 Cmotor particular)
data(o71, Designators.hasTextualName, Cmotor)
data(o72, rdf-schema.label, Mazak base C1 particular)
data(o73, Designators.hasTextualName, C1)
data(o74, rdf-schema.label, MazakbaseC1Design particular)
data(o75, Core.hasSimpleExpressionValue, 12000.0)
data(o77, Core.hasSimpleExpressionValue, 0.0)
data(o81, rdf-schema.label, Mazak base B Bmotor particular)
data(o82, Designators.hasTextualName, Bmotor)
data(o83, rdf-schema.label, Mazak base B particular)
data(o84, Designators.hasTextualName, B)
data(o85, rdf-schema.label, MazakbaseBDesign particular)
data(o86, Core.hasSimpleExpressionValue, 120.0)
data(o87, Core.hasSimpleExpressionValue, -30.0)
data(o88, Core.hasSimpleExpressionValue, 400.0)
data(o90, Core.hasSimpleExpressionValue, 0.0)
data(o93, rdf-schema.label, Mazak base C2 C2motor particular)
data(o94, Designators.hasTextualName, C2motor)
data(o95, rdf-schema.label, Mazak base C2 particular)
data(o96, Designators.hasTextualName, C2)
data(o97, rdf-schema.label, MazakbaseC2Design particular)
data(o98, Core.hasSimpleExpressionValue, 360.0)
data(o99, Core.hasSimpleExpressionValue, -360.0)
data(o100, Core.hasSimpleExpressionValue, 400.0)
data(o101, Core.hasSimpleExpressionValue, 0.0)
data(o104, rdf-schema.label, Mazak controller particular)
data(o105, Designators.hasTextualName, controller)
data(o106, rdf-schema.label, Mazak controller path particular)
data(o107, Designators.hasTextualName, path)
data(o108, rdf-schema.label, Mazak door particular)
data(o109, Designators.hasTextualName, door)
data(o110, rdf-schema.label, Mazak parts partocc particular)
data(o111, Designators.hasTextualName, partocc)
data(o112, rdf-schema.label, Mazak systems electric particular)
data(o113, Designators.hasTextualName, electric)
data(o114, rdf-schema.label, Mazak systems hydraulic particular)
data(o115, Designators.hasTextualName, hydraulic)
data(o116, rdf-schema.label, Mazak systems coolant particular)
data(o117, Designators.hasTextualName, coolant)
data(o119, rdf-schema.label, Mazak systems pneumatic particular)
data(o120, Designators.hasTextualName, pneumatic)
data(o121, rdf-schema.label, Mazak systems lubrication particular)
data(o122, Designators.hasTextualName, lubrication)
data(o123, rdf-schema.label, Mazak auxiliaries environmental particular)
data(o124, Designators.hasTextualName, environmental)
data(o126, rdf-schema.label, Mazak resources materials stock particular)
data(o127, Designators.hasTextualName, stock)
data(o128, rdf-schema.label, Mazak enclosure particular)
data(o129, Designators.hasTextualName, enclosure)
@enduml
