
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseZ

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o1, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o2, data:Mazak317641baseZLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:Mazak317641baseZVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseZVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseZVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak317641baseZVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:Mazak317641baseZCapability, core:Capability)
individual(o8, data:Mazak317641baseZPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o9, data:Mazak317641baseZPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o10, data:name13, des:Name)
individual(o11, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o12, data:Mazak317641mstructY_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o13, data:Mazak317641mstructY_AXISCapability, core:Capability)
individual(o14, data:name3, des:Name)
individual(o15, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o16, data:Mazak317641mstructZ_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o17, data:Mazak317641mstructZ_AXISCapability, core:Capability)
individual(o18, data:name4, des:Name)
individual(o19, data:[[./Mazak317641baseZZballscrew.html Mazak317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o20, data:Mazak317641baseZZballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o21, data:Mazak317641baseZZballscrewCapability, core:Capability)
individual(o22, data:name14, des:Name)
individual(o23, data:[[./Mazak317641baseZZmotor.html Mazak317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600 Mazak800iMotorLINEAR_FORCE9600]])
individual(o24, data:Mazak317641baseZZmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o25, data:mazak800imotorlinear_force9600design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600Design Mazak800iMotorLINEAR_FORCE9600Design]])
individual(o26, data:Mazak317641baseZZmotorCapability, core:Capability)
individual(o27, data:Mazak317641baseZTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o28, data:name15, des:Name)
individual(o29, data:, owl:Thing)
individual(o30, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "Mazak800ibaseZDesign particular")
property(o1, "core:hasValueExpressionAtSomeTime", o2)
property(o1, "core:hasValueExpressionAtSomeTime", o3)
property(o1, "core:hasValueExpressionAtSomeTime", o4)
property(o1, "core:hasValueExpressionAtSomeTime", o5)
property(o1, "core:hasValueExpressionAtSomeTime", o6)
property(o0, "core:hasCapability", o7)
property(o0, "core:hasFunction", o8)
property(o8, "core:prescribedBy", o1)
property(o0, "core:hasQuality", o9)
property(o0, "des:hasName", o10)
data(o10, "des:hasTextualName", "Z")
property(o0, "ex:connectedTo", o11)
data(o11, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
property(o11, "core:hasRole", o12)
property(o11, "core:hasCapability", o13)
property(o11, "des:hasName", o14)
property(o0, "ex:connectedTo", o15)
data(o15, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
property(o15, "core:hasRole", o16)
property(o15, "core:hasCapability", o17)
property(o15, "des:hasName", o18)
property(o0, "ex:hasComponent", o19)
data(o19, "rdfs:label", "Mazak 317641 base Z Zballscrew particular")
property(o19, "core:hasRole", o20)
property(o19, "core:hasCapability", o21)
property(o19, "des:hasName", o22)
property(o0, "ex:hasComponent", o23)
data(o23, "rdfs:label", "Mazak 317641 base Z Zmotor particular")
property(o23, "core:hasRole", o24)
property(o23, "core:prescribedBy", o25)
property(o23, "core:hasCapability", o26)
property(o23, "core:hasQuality", o27)
property(o23, "des:hasName", o28)
property(o29, "rdf:first", o0)
property(o30, "ex:hasComponent", o0)
@enduml
