@startuml
skinparam linetype polyline
left to right direction
title Mazak-room

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-room.html data:Mazak-room]]" as o1 #76608A {
 <back:#Green>type: ex:Room</back> 
---
 }
object "data:Mazak-room-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "data:Mazak-room-temperature" as o3 #76608A {
 <back:#1E90FF>type: qp:Temperature</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: environmental
o1 --> o3 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
@enduml
