
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak.html Mazak]], vendor:[[../Mazak.html#Mazak Mazak]])
individual(o1, data:[[./Mazak_mstruct_X_AXIS.html Mazak_mstruct_X_AXIS]], vendor:[[../Mazak.html#MazakmstructX_AXIS MazakmstructX_AXIS]])
individual(o2, data:name2, des:Name)
individual(o3, data:[[./Mazak_mstruct_Y_AXIS.html Mazak_mstruct_Y_AXIS]], vendor:[[../Mazak.html#MazakmstructY_AXIS MazakmstructY_AXIS]])
individual(o4, data:name3, des:Name)
individual(o5, data:[[./Mazak_mstruct_Z_AXIS.html Mazak_mstruct_Z_AXIS]], vendor:[[../Mazak.html#MazakmstructZ_AXIS MazakmstructZ_AXIS]])
individual(o6, data:name4, des:Name)
individual(o7, data:[[./Mazak_mstruct_TABLE.html Mazak_mstruct_TABLE]], vendor:[[../Mazak.html#MazakmstructTABLE MazakmstructTABLE]])
individual(o8, data:name5, des:Name)
individual(o9, data:[[./Mazak_mstruct_TRUNDLE.html Mazak_mstruct_TRUNDLE]], vendor:[[../Mazak.html#MazakmstructTRUNDLE MazakmstructTRUNDLE]])
individual(o10, data:name6, des:Name)
individual(o11, data:[[./Mazak_base_X.html Mazak_base_X]], vendor:[[../Mazak.html#MazakbaseX MazakbaseX]])
individual(o12, data:[[./Mazak_base_X_Xballscrew.html Mazak_base_X_Xballscrew]], vendor:[[../Mazak.html#MazakbaseXXballscrew MazakbaseXXballscrew]])
individual(o13, data:[[./Mazak_base_X_Xmotor.html Mazak_base_X_Xmotor]], vendor:[[../Mazak.html#MazakbaseXXmotor MazakbaseXXmotor]])
individual(o14, data:mazakbasexdesign1, vendor:[[../Mazak.html#MazakbaseXDesign MazakbaseXDesign]])
individual(o15, data:Mazak_base_XPrismaticMotionCapability, ex:PrismaticMotionCapability)
individual(o16, data:Mazak_base_XPOSITION_ACTUAL, qualphys:Displacement)
individual(o17, data:name7, des:Name)
individual(o18, data:[[./Mazak_enclosure.html Mazak_enclosure]], vendor:[[../Mazak.html#Mazakenclosure Mazakenclosure]])
individual(o19, data:[[./Mazak_base_Y.html Mazak_base_Y]], vendor:[[../Mazak.html#MazakbaseY MazakbaseY]])
individual(o20, data:[[./Mazak_base_Y_Yballscrew.html Mazak_base_Y_Yballscrew]], vendor:[[../Mazak.html#MazakbaseYYballscrew MazakbaseYYballscrew]])
individual(o21, data:[[./Mazak_base_Y_Ymotor.html Mazak_base_Y_Ymotor]], vendor:[[../Mazak.html#MazakbaseYYmotor MazakbaseYYmotor]])
individual(o22, data:mazakbaseydesign1, vendor:[[../Mazak.html#MazakbaseYDesign MazakbaseYDesign]])
individual(o23, data:Mazak_base_YPrismaticMotionCapability, ex:PrismaticMotionCapability)
individual(o24, data:Mazak_base_YPOSITION_ACTUAL, qualphys:Displacement)
individual(o25, data:name10, des:Name)
individual(o26, data:[[./Mazak_base_Z.html Mazak_base_Z]], vendor:[[../Mazak.html#MazakbaseZ MazakbaseZ]])
individual(o27, data:[[./Mazak_base_Z_Zballscrew.html Mazak_base_Z_Zballscrew]], vendor:[[../Mazak.html#MazakbaseZZballscrew MazakbaseZZballscrew]])
individual(o28, data:[[./Mazak_base_Z_Zmotor.html Mazak_base_Z_Zmotor]], vendor:[[../Mazak.html#MazakbaseZZmotor MazakbaseZZmotor]])
individual(o29, data:mazakbasezdesign1, vendor:[[../Mazak.html#MazakbaseZDesign MazakbaseZDesign]])
individual(o30, data:Mazak_base_ZPrismaticMotionCapability, ex:PrismaticMotionCapability)
individual(o31, data:Mazak_base_ZPOSITION_ACTUAL, qualphys:Displacement)
individual(o32, data:name13, des:Name)
individual(o33, data:[[./Mazak_base_C1.html Mazak_base_C1]], vendor:[[../Mazak.html#MazakbaseC1 MazakbaseC1]])
individual(o34, data:[[./Mazak_base_C1_Cmotor.html Mazak_base_C1_Cmotor]], vendor:[[../Mazak.html#MazakbaseC1Cmotor MazakbaseC1Cmotor]])
individual(o35, data:mazakbasec1design1, vendor:[[../Mazak.html#MazakbaseC1Design MazakbaseC1Design]])
individual(o36, data:Mazak_base_C1ROTARY_VELOCITY_ACTUAL, ex:RevoluteVelocity)
individual(o37, data:Mazak_base_C1ContinuousMotionCapability, ex:ContinuousMotionCapability)
individual(o38, data:name16, des:Name)
individual(o39, data:[[./Mazak_base_B.html Mazak_base_B]], vendor:[[../Mazak.html#MazakbaseB MazakbaseB]])
individual(o40, data:[[./Mazak_base_B_Bmotor.html Mazak_base_B_Bmotor]], vendor:[[../Mazak.html#MazakbaseBBmotor MazakbaseBBmotor]])
individual(o41, data:mazakbasebdesign1, vendor:[[../Mazak.html#MazakbaseBDesign MazakbaseBDesign]])
individual(o42, data:Mazak_base_BRevoluteMotionCapability, ex:RevoluteMotionCapability)
individual(o43, data:Mazak_base_BANGLE_ACTUAL, qualphys:Angle)
individual(o44, data:name18, des:Name)
individual(o45, data:[[./Mazak_base_C2.html Mazak_base_C2]], vendor:[[../Mazak.html#MazakbaseC2 MazakbaseC2]])
individual(o46, data:[[./Mazak_base_C2_C2motor.html Mazak_base_C2_C2motor]], vendor:[[../Mazak.html#MazakbaseC2C2motor MazakbaseC2C2motor]])
individual(o47, data:mazakbasec2design1, vendor:[[../Mazak.html#MazakbaseC2Design MazakbaseC2Design]])
individual(o48, data:Mazak_base_C2RevoluteMotionCapability, ex:RevoluteMotionCapability)
individual(o49, data:Mazak_base_C2ANGLE_ACTUAL, qualphys:Angle)
individual(o50, data:name20, des:Name)
individual(o51, data:[[./Mazak_controller.html Mazak_controller]], vendor:[[../Mazak.html#Mazakcontroller Mazakcontroller]])
individual(o52, data:[[./Mazak_controller_path.html Mazak_controller_path]], vendor:[[../Mazak.html#Mazakcontrollerpath Mazakcontrollerpath]])
individual(o53, data:name22, des:Name)
individual(o54, data:[[./Mazak_door.html Mazak_door]], vendor:[[../Mazak.html#Mazakdoor Mazakdoor]])
individual(o55, data:name24, des:Name)
individual(o56, data:[[./Mazak_parts_partocc.html Mazak_parts_partocc]], vendor:[[../Mazak.html#Mazakpartspartocc Mazakpartspartocc]])
individual(o57, data:name25, des:Name)
individual(o58, data:[[./Mazak_systems_electric.html Mazak_systems_electric]], vendor:[[../Mazak.html#Mazaksystemselectric Mazaksystemselectric]])
individual(o59, data:name26, des:Name)
individual(o60, data:[[./Mazak_systems_hydraulic.html Mazak_systems_hydraulic]], vendor:[[../Mazak.html#Mazaksystemshydraulic Mazaksystemshydraulic]])
individual(o61, data:name27, des:Name)
individual(o62, data:[[./Mazak_systems_coolant.html Mazak_systems_coolant]], vendor:[[../Mazak.html#Mazaksystemscoolant Mazaksystemscoolant]])
individual(o63, data:Mazak_systems_coolantTEMPERATURE, qualphys:Temperature)
individual(o64, data:name28, des:Name)
individual(o65, data:[[./Mazak_systems_pneumatic.html Mazak_systems_pneumatic]], vendor:[[../Mazak.html#Mazaksystemspneumatic Mazaksystemspneumatic]])
individual(o66, data:name29, des:Name)
individual(o67, data:[[./Mazak_systems_lubrication.html Mazak_systems_lubrication]], vendor:[[../Mazak.html#Mazaksystemslubrication Mazaksystemslubrication]])
individual(o68, data:name30, des:Name)
individual(o69, data:[[./Mazak_auxiliaries_environmental.html Mazak_auxiliaries_environmental]], vendor:[[../Mazak.html#Mazakauxiliariesenvironmental Mazakauxiliariesenvironmental]])
individual(o70, data:Mazak_auxiliaries_environmentalTEMPERATURE, qualphys:Temperature)
individual(o71, data:name31, des:Name)
individual(o72, data:[[./Mazak_resources_materials_stock.html Mazak_resources_materials_stock]], vendor:[[../Mazak.html#Mazakresourcesmaterialsstock Mazakresourcesmaterialsstock]])
individual(o73, data:name32, des:Name)
individual(o74, data:Mazak_enclosureTEMPERATURE, qualphys:Temperature)
individual(o75, data:name33, des:Name)
individual(o76, data:MazakTurningCapability, ex:TurningCapability)
individual(o77, data:MazakMillingCapability, ex:MillingCapability)
individual(o78, data:name1, des:Name)
property(o0, "core:hasComponentPartAtAllTimes", o1)
data(o1, "rdfs:label", "Mazak mstruct X_AXIS particular")
property(o1, "des:hasName", o2)
property(o0, "core:hasComponentPartAtAllTimes", o3)
data(o3, "rdfs:label", "Mazak mstruct Y_AXIS particular")
property(o3, "des:hasName", o4)
property(o0, "core:hasComponentPartAtAllTimes", o5)
data(o5, "rdfs:label", "Mazak mstruct Z_AXIS particular")
property(o5, "des:hasName", o6)
property(o0, "core:hasComponentPartAtAllTimes", o7)
data(o7, "rdfs:label", "Mazak mstruct TABLE particular")
property(o7, "des:hasName", o8)
property(o0, "core:hasComponentPartAtAllTimes", o9)
data(o9, "rdfs:label", "Mazak mstruct TRUNDLE particular")
property(o9, "des:hasName", o10)
property(o0, "core:hasComponentPartAtAllTimes", o11)
data(o11, "rdfs:label", "Mazak base X particular")
property(o11, "core:hasComponentPartAtAllTimes", o12)
property(o11, "core:hasComponentPartAtAllTimes", o13)
property(o11, "core:prescribedBy", o14)
property(o11, "core:hasFunction", o15)
property(o11, "core:hasQuality", o16)
property(o11, "des:hasName", o17)
property(o11, "ex:joinedTo", o1)
property(o11, "ex:joinedTo", o18)
property(o0, "core:hasComponentPartAtAllTimes", o19)
data(o19, "rdfs:label", "Mazak base Y particular")
property(o19, "core:hasComponentPartAtAllTimes", o20)
property(o19, "core:hasComponentPartAtAllTimes", o21)
property(o19, "core:prescribedBy", o22)
property(o19, "core:hasFunction", o23)
property(o19, "core:hasQuality", o24)
property(o19, "des:hasName", o25)
property(o19, "ex:joinedTo", o1)
property(o19, "ex:joinedTo", o3)
property(o0, "core:hasComponentPartAtAllTimes", o26)
data(o26, "rdfs:label", "Mazak base Z particular")
property(o26, "core:hasComponentPartAtAllTimes", o27)
property(o26, "core:hasComponentPartAtAllTimes", o28)
property(o26, "core:prescribedBy", o29)
property(o26, "core:hasFunction", o30)
property(o26, "core:hasQuality", o31)
property(o26, "des:hasName", o32)
property(o26, "ex:joinedTo", o3)
property(o26, "ex:joinedTo", o5)
property(o0, "core:hasComponentPartAtAllTimes", o33)
data(o33, "rdfs:label", "Mazak base C1 particular")
property(o33, "core:hasComponentPartAtAllTimes", o34)
property(o33, "core:prescribedBy", o35)
property(o33, "core:measuresAtSomeTime", o36)
property(o33, "core:hasFunction", o37)
property(o33, "des:hasName", o38)
property(o33, "ex:joinedTo", o5)
property(o0, "core:hasComponentPartAtAllTimes", o39)
data(o39, "rdfs:label", "Mazak base B particular")
property(o39, "core:hasComponentPartAtAllTimes", o40)
property(o39, "core:prescribedBy", o41)
property(o39, "core:hasFunction", o42)
property(o39, "core:hasQuality", o43)
property(o39, "des:hasName", o44)
property(o39, "ex:joinedTo", o9)
property(o39, "ex:joinedTo", o18)
property(o0, "core:hasComponentPartAtAllTimes", o45)
data(o45, "rdfs:label", "Mazak base C2 particular")
property(o45, "core:hasComponentPartAtAllTimes", o46)
property(o45, "core:prescribedBy", o47)
property(o45, "core:hasFunction", o48)
property(o45, "core:hasQuality", o49)
property(o45, "des:hasName", o50)
property(o45, "ex:joinedTo", o7)
property(o45, "ex:joinedTo", o9)
property(o0, "core:hasComponentPartAtAllTimes", o51)
data(o51, "rdfs:label", "Mazak controller particular")
property(o51, "core:hasComponentPartAtAllTimes", o52)
property(o51, "des:hasName", o53)
property(o0, "core:hasComponentPartAtAllTimes", o54)
data(o54, "rdfs:label", "Mazak door particular")
property(o54, "des:hasName", o55)
property(o0, "core:hasComponentPartAtAllTimes", o56)
data(o56, "rdfs:label", "Mazak parts partocc particular")
property(o56, "des:hasName", o57)
property(o0, "core:hasComponentPartAtAllTimes", o58)
data(o58, "rdfs:label", "Mazak systems electric particular")
property(o58, "des:hasName", o59)
property(o0, "core:hasComponentPartAtAllTimes", o60)
data(o60, "rdfs:label", "Mazak systems hydraulic particular")
property(o60, "des:hasName", o61)
property(o0, "core:hasComponentPartAtAllTimes", o62)
data(o62, "rdfs:label", "Mazak systems coolant particular")
property(o62, "core:hasQuality", o63)
property(o62, "des:hasName", o64)
property(o0, "core:hasComponentPartAtAllTimes", o65)
data(o65, "rdfs:label", "Mazak systems pneumatic particular")
property(o65, "des:hasName", o66)
property(o0, "core:hasComponentPartAtAllTimes", o67)
data(o67, "rdfs:label", "Mazak systems lubrication particular")
property(o67, "des:hasName", o68)
property(o0, "core:hasComponentPartAtAllTimes", o69)
data(o69, "rdfs:label", "Mazak auxiliaries environmental particular")
property(o69, "core:hasQuality", o70)
property(o69, "des:hasName", o71)
property(o0, "core:hasComponentPartAtAllTimes", o72)
data(o72, "rdfs:label", "Mazak resources materials stock particular")
property(o72, "des:hasName", o73)
property(o0, "core:hasComponentPartAtAllTimes", o18)
data(o18, "rdfs:label", "Mazak enclosure particular")
property(o18, "core:hasQuality", o74)
property(o18, "des:hasName", o75)
property(o0, "core:hasCapability", o76)
property(o0, "core:hasFunction", o77)
property(o0, "des:hasName", o78)
data(o78, "des:hasTextualName", "Mazak")
@enduml
