
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseX

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o1, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o2, data:Mazak317641baseXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:Mazak317641baseXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak317641baseXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:Mazak317641baseXCapability, core:Capability)
individual(o8, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o9, data:Mazak317641baseXXballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o10, data:Mazak317641baseXXballscrewCapability, core:Capability)
individual(o11, data:name8, des:Name)
individual(o12, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o13, data:Mazak317641baseXXmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o14, data:mazak800imotorlinear_force5200design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o15, data:Mazak317641baseXXmotorCapability, core:Capability)
individual(o16, data:Mazak317641baseXTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o17, data:name9, des:Name)
individual(o18, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o19, data:Mazak317641baseXPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o20, data:name7, des:Name)
individual(o21, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o22, data:Mazak317641enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o23, data:Mazak317641enclosureCapability, core:Capability)
individual(o24, data:Mazak317641enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o25, data:name33, des:Name)
individual(o26, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o27, data:Mazak317641mstructX_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o28, data:Mazak317641mstructX_AXISCapability, core:Capability)
individual(o29, data:name2, des:Name)
individual(o30, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "Mazak800ibaseXDesign particular")
property(o1, "core:hasValueExpressionAtSomeTime", o2)
property(o1, "core:hasValueExpressionAtSomeTime", o3)
property(o1, "core:hasValueExpressionAtSomeTime", o4)
property(o1, "core:hasValueExpressionAtSomeTime", o5)
property(o1, "core:hasValueExpressionAtSomeTime", o6)
property(o0, "core:hasCapability", o7)
property(o0, "core:hasComponentPartAtSomeTime", o8)
data(o8, "rdfs:label", "Mazak 317641 base X Xballscrew particular")
property(o8, "core:hasRole", o9)
property(o8, "core:hasCapability", o10)
property(o8, "des:hasName", o11)
property(o0, "core:hasComponentPartAtSomeTime", o12)
data(o12, "rdfs:label", "Mazak 317641 base X Xmotor particular")
property(o12, "core:hasRole", o13)
property(o12, "core:prescribedBy", o14)
property(o12, "core:hasCapability", o15)
property(o12, "core:hasQuality", o16)
property(o12, "des:hasName", o17)
property(o0, "core:hasFunction", o18)
property(o18, "core:prescribedBy", o1)
property(o0, "core:hasQuality", o19)
property(o0, "des:hasName", o20)
data(o20, "des:hasTextualName", "X")
property(o0, "ex:connectedTo", o21)
data(o21, "rdfs:label", "Mazak 317641 enclosure particular")
property(o21, "core:hasRole", o22)
property(o21, "core:hasCapability", o23)
property(o21, "core:hasQuality", o24)
property(o21, "des:hasName", o25)
property(o0, "ex:connectedTo", o26)
data(o26, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o26, "core:hasRole", o27)
property(o26, "core:hasCapability", o28)
property(o26, "des:hasName", o29)
property(o30, "core:hasComponentPartAtSomeTime", o0)
@enduml
