
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title MazakMere

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak.html Mazak]], vendor:[[../Mazak.html#Mazak Mazak]])
individual(o1, data:[[./Mazak_mstruct_X_AXIS.html Mazak_mstruct_X_AXIS]], vendor:[[../Mazak.html#MazakmstructX_AXIS MazakmstructX_AXIS]])
individual(o2, data:[[./Mazak_mstruct_Y_AXIS.html Mazak_mstruct_Y_AXIS]], vendor:[[../Mazak.html#MazakmstructY_AXIS MazakmstructY_AXIS]])
individual(o3, data:[[./Mazak_mstruct_Z_AXIS.html Mazak_mstruct_Z_AXIS]], vendor:[[../Mazak.html#MazakmstructZ_AXIS MazakmstructZ_AXIS]])
individual(o4, data:[[./Mazak_mstruct_TABLE.html Mazak_mstruct_TABLE]], vendor:[[../Mazak.html#MazakmstructTABLE MazakmstructTABLE]])
individual(o5, data:[[./Mazak_mstruct_TRUNDLE.html Mazak_mstruct_TRUNDLE]], vendor:[[../Mazak.html#MazakmstructTRUNDLE MazakmstructTRUNDLE]])
individual(o6, data:[[./Mazak_base_X_Xballscrew.html Mazak_base_X_Xballscrew]], vendor:[[../Mazak.html#MazakbaseXXballscrew MazakbaseXXballscrew]])
individual(o7, data:[[./Mazak_base_X_Xmotor.html Mazak_base_X_Xmotor]], vendor:[[../Mazak.html#MazakbaseXXmotor MazakbaseXXmotor]])
individual(o8, data:[[./Mazak_base_X.html Mazak_base_X]], vendor:[[../Mazak.html#MazakbaseX MazakbaseX]])
individual(o9, data:[[./Mazak_base_Y_Yballscrew.html Mazak_base_Y_Yballscrew]], vendor:[[../Mazak.html#MazakbaseYYballscrew MazakbaseYYballscrew]])
individual(o10, data:[[./Mazak_base_Y_Ymotor.html Mazak_base_Y_Ymotor]], vendor:[[../Mazak.html#MazakbaseYYmotor MazakbaseYYmotor]])
individual(o11, data:[[./Mazak_base_Y.html Mazak_base_Y]], vendor:[[../Mazak.html#MazakbaseY MazakbaseY]])
individual(o12, data:[[./Mazak_base_Z_Zballscrew.html Mazak_base_Z_Zballscrew]], vendor:[[../Mazak.html#MazakbaseZZballscrew MazakbaseZZballscrew]])
individual(o13, data:[[./Mazak_base_Z_Zmotor.html Mazak_base_Z_Zmotor]], vendor:[[../Mazak.html#MazakbaseZZmotor MazakbaseZZmotor]])
individual(o14, data:[[./Mazak_base_Z.html Mazak_base_Z]], vendor:[[../Mazak.html#MazakbaseZ MazakbaseZ]])
individual(o15, data:[[./Mazak_base_C1_Cmotor.html Mazak_base_C1_Cmotor]], vendor:[[../Mazak.html#MazakbaseC1Cmotor MazakbaseC1Cmotor]])
individual(o16, data:[[./Mazak_base_C1.html Mazak_base_C1]], vendor:[[../Mazak.html#MazakbaseC1 MazakbaseC1]])
individual(o17, data:[[./Mazak_base_B_Bmotor.html Mazak_base_B_Bmotor]], vendor:[[../Mazak.html#MazakbaseBBmotor MazakbaseBBmotor]])
individual(o18, data:[[./Mazak_base_B.html Mazak_base_B]], vendor:[[../Mazak.html#MazakbaseB MazakbaseB]])
individual(o19, data:[[./Mazak_base_C2_C2motor.html Mazak_base_C2_C2motor]], vendor:[[../Mazak.html#MazakbaseC2C2motor MazakbaseC2C2motor]])
individual(o20, data:[[./Mazak_base_C2.html Mazak_base_C2]], vendor:[[../Mazak.html#MazakbaseC2 MazakbaseC2]])
individual(o21, data:[[./Mazak_controller.html Mazak_controller]], vendor:[[../Mazak.html#Mazakcontroller Mazakcontroller]])
individual(o22, data:[[./Mazak_controller_path.html Mazak_controller_path]], vendor:[[../Mazak.html#Mazakcontrollerpath Mazakcontrollerpath]])
individual(o23, data:[[./Mazak_door.html Mazak_door]], vendor:[[../Mazak.html#Mazakdoor Mazakdoor]])
individual(o24, data:[[./Mazak_parts_partocc.html Mazak_parts_partocc]], vendor:[[../Mazak.html#Mazakpartspartocc Mazakpartspartocc]])
individual(o25, data:[[./Mazak_systems_electric.html Mazak_systems_electric]], vendor:[[../Mazak.html#Mazaksystemselectric Mazaksystemselectric]])
individual(o26, data:[[./Mazak_systems_hydraulic.html Mazak_systems_hydraulic]], vendor:[[../Mazak.html#Mazaksystemshydraulic Mazaksystemshydraulic]])
individual(o27, data:[[./Mazak_systems_coolant.html Mazak_systems_coolant]], vendor:[[../Mazak.html#Mazaksystemscoolant Mazaksystemscoolant]])
individual(o28, data:[[./Mazak_systems_pneumatic.html Mazak_systems_pneumatic]], vendor:[[../Mazak.html#Mazaksystemspneumatic Mazaksystemspneumatic]])
individual(o29, data:[[./Mazak_systems_lubrication.html Mazak_systems_lubrication]], vendor:[[../Mazak.html#Mazaksystemslubrication Mazaksystemslubrication]])
individual(o30, data:[[./Mazak_auxiliaries_environmental.html Mazak_auxiliaries_environmental]], vendor:[[../Mazak.html#Mazakauxiliariesenvironmental Mazakauxiliariesenvironmental]])
individual(o31, data:[[./Mazak_resources_materials_stock.html Mazak_resources_materials_stock]], vendor:[[../Mazak.html#Mazakresourcesmaterialsstock Mazakresourcesmaterialsstock]])
individual(o32, data:[[./Mazak_enclosure.html Mazak_enclosure]], vendor:[[../Mazak.html#Mazakenclosure Mazakenclosure]])
property(o0, "bfo:has_member_part_at_some_time", o1)
property(o0, "bfo:has_member_part_at_some_time", o2)
property(o0, "bfo:has_member_part_at_some_time", o3)
property(o0, "bfo:has_member_part_at_some_time", o4)
property(o0, "bfo:has_member_part_at_some_time", o5)
property(o0, "bfo:has_member_part_at_some_time", o6)
property(o0, "bfo:has_member_part_at_some_time", o7)
property(o0, "bfo:has_member_part_at_some_time", o8)
property(o0, "bfo:has_member_part_at_some_time", o9)
property(o0, "bfo:has_member_part_at_some_time", o10)
property(o0, "bfo:has_member_part_at_some_time", o11)
property(o0, "bfo:has_member_part_at_some_time", o12)
property(o0, "bfo:has_member_part_at_some_time", o13)
property(o0, "bfo:has_member_part_at_some_time", o14)
property(o0, "bfo:has_member_part_at_some_time", o15)
property(o0, "bfo:has_member_part_at_some_time", o16)
property(o0, "bfo:has_member_part_at_some_time", o17)
property(o0, "bfo:has_member_part_at_some_time", o18)
property(o0, "bfo:has_member_part_at_some_time", o19)
property(o0, "bfo:has_member_part_at_some_time", o20)
property(o0, "bfo:has_member_part_at_some_time", o21)
property(o21, "bfo:has_member_part_at_some_time", o22)
property(o0, "bfo:has_member_part_at_some_time", o23)
property(o0, "bfo:has_member_part_at_some_time", o24)
property(o0, "bfo:has_member_part_at_some_time", o25)
property(o0, "bfo:has_member_part_at_some_time", o26)
property(o0, "bfo:has_member_part_at_some_time", o27)
property(o0, "bfo:has_member_part_at_some_time", o28)
property(o0, "bfo:has_member_part_at_some_time", o29)
property(o0, "bfo:has_member_part_at_some_time", o30)
property(o0, "bfo:has_member_part_at_some_time", o31)
property(o0, "bfo:has_member_part_at_some_time", o32)
@enduml
