@startuml
skinparam linetype polyline
left to right direction
title Mazak-procstock
object "[[./Mazak-procstock.html data:Mazak-procstock]]" as o1 {
 type = ex:Stock
 }
object "data:Mazak-procstock-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./Mazak.html data:Mazak]]" as o3 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = stock
o3 --> o1 : obo:has member part at some time
@enduml
