@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-x-Xmotor

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./Mazak-x-Xmotor.html Mazak-x-Xmotor]], ex:Motor)
individual(o2, data:Mazak-x-Xmotor-temperature, qp:Temperature)
individual(o3, data:Mazak-x-Xmotor-name, cmns-dsg:Name)
individual(o4, data:[[./Mazak-x.html Mazak-x]], ex:LinearMotionSystem)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o2)
property(o1, cmns-dsg:hasName, o3)
data(o3, cmns-dsg:hasTextualName, Xmotor)
property(o4, "bfo:has member part at some time", o1)
@enduml
