
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseC1

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o1, data:mazak800ibasec1design1, vendor:[[../Mazak.html#Mazak800ibaseC1Design Mazak800ibaseC1Design]])
individual(o2, data:Mazak317641baseC1Rotary_velocityMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:Mazak317641baseC1Rotary_velocityMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseC1Capability, core:Capability)
individual(o5, data:Mazak317641baseC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o6, data:Mazak317641baseC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o7, data:name16, des:Name)
individual(o8, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o9, data:Mazak317641mstructZ_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o10, data:Mazak317641mstructZ_AXISCapability, core:Capability)
individual(o11, data:name4, des:Name)
individual(o12, data:[[./Mazak317641baseC1Cmotor.html Mazak317641baseC1Cmotor]], vendor:[[../Mazak.html#Mazak800ibaseC1Cmotor Mazak800ibaseC1Cmotor]])
individual(o13, data:Mazak317641baseC1CmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o14, data:Mazak317641baseC1CmotorCapability, core:Capability)
individual(o15, data:Mazak317641baseC1TEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o16, data:name17, des:Name)
individual(o17, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "Mazak800ibaseC1Design particular")
property(o1, "core:hasValueExpressionAtSomeTime", o2)
property(o1, "core:hasValueExpressionAtSomeTime", o3)
property(o0, "core:hasCapability", o4)
property(o0, "core:measuresAtSomeTime", o5)
property(o0, "core:hasFunction", o6)
property(o6, "core:prescribedBy", o1)
property(o0, "des:hasName", o7)
data(o7, "des:hasTextualName", "C1")
property(o0, "ex:connectedTo", o8)
data(o8, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
property(o8, "core:hasRole", o9)
property(o8, "core:hasCapability", o10)
property(o8, "des:hasName", o11)
property(o0, "ex:hasComponent", o12)
data(o12, "rdfs:label", "Mazak 317641 base C1 Cmotor particular")
property(o12, "core:hasRole", o13)
property(o12, "core:hasCapability", o14)
property(o12, "core:hasQuality", o15)
property(o12, "des:hasName", o16)
property(o17, "ex:hasComponent", o0)
@enduml
