@startuml Mazak-y
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak-y

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
oIndividual(data:Mazak-y, ex:LinearMotionSystem)
oIndividual(data:Mazak-y-name, cmns-dsg:Name)
oIndividual(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-y-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-y-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-y-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-y-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-y-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-y-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-y-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-xaxism, ex:Structure)
oIndividual(data:Mazak-xaxism-name, cmns-dsg:Name)
oIndividual(data:Mazak-yaxism, ex:Structure)
oIndividual(data:Mazak-yaxism-name, cmns-dsg:Name)
oIndividual(data:Mazak-y-function, ex:PrismaticMotionCapability)
oIndividual(data:Mazak-y-position-actual, qp:Displacement)
oIndividual(data:Mazak-y-Yballscrew, ex:Ballscrew)
oIndividual(data:Mazak-y-Yballscrew-name, cmns-dsg:Name)
oIndividual(data:Mazak-y-Ymotor, ex:Motor)
oIndividual(data:Mazak-y-Ymotor-temperature, qp:Temperature)
oIndividual(data:Mazak-y-Ymotor-name, cmns-dsg:Name)
oIndividual(data:Mazak, ex:Machine)
property(data:Mazak-y, cmns-dsg:hasName, data:Mazak-y-name, down)
data(data:Mazak-y-name, cmns-dsg:hasTextualName, Y)
property(data:Mazak-y, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-y-spec, down)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-LENGTH-Nominal, down)
data(data:Mazak-y-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 550.0)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-LINEAR_FORCE-Maximum, down)
data(data:Mazak-y-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 5200.0)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-LINEAR_FORCE-Minimum, down)
data(data:Mazak-y-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-VELOCITY-RAPID-Maximum, down)
data(data:Mazak-y-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-VELOCITY-RAPID-Minimum, down)
data(data:Mazak-y-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-VELOCITY-PROGRAMMED-Maximum, down)
data(data:Mazak-y-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-y-spec-VELOCITY-PROGRAMMED-Minimum, down)
data(data:Mazak-y-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(data:Mazak-y, ex:joinedTo, data:Mazak-xaxism, down)
property(data:Mazak-xaxism, cmns-dsg:hasName, data:Mazak-xaxism-name, down)
property(data:Mazak-y, ex:joinedTo, data:Mazak-yaxism, down)
property(data:Mazak-yaxism, cmns-dsg:hasName, data:Mazak-yaxism-name, down)
property(data:Mazak-y, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-y-function, down)
property(data:Mazak-y, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-y-position-actual, down)
property(data:Mazak-y, "bfo:has member part at some time", data:Mazak-y-Yballscrew, down)
property(data:Mazak-y-Yballscrew, cmns-dsg:hasName, data:Mazak-y-Yballscrew-name, down)
property(data:Mazak-y, "bfo:has member part at some time", data:Mazak-y-Ymotor, down)
property(data:Mazak-y-Ymotor, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-y-Ymotor-temperature, down)
property(data:Mazak-y-Ymotor, cmns-dsg:hasName, data:Mazak-y-Ymotor-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-y, down)
@enduml
