@startuml
skinparam linetype polyline
left to right direction
title Mazak-y-Yballscrew
object "[[./Mazak-y-Yballscrew.html data:Mazak-y-Yballscrew]]" as o1 {
 type: ex:Ballscrew 
}
object "data:Mazak-y-Yballscrew-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak-y.html data:Mazak-y]]" as o3 {
 type: ex:LinearMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Yballscrew
o3 --> o1 : obo:has member part at some time
@enduml
