@startuml
skinparam linetype polyline
left to right direction
title Mazak-z

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-z.html data:Mazak-z]]" as o1 #76608A {
 <back:#Green>type: ex:LinearMotionSystem</back> 
---
 }
object "data:Mazak-z-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "data:Mazak-z-spec" as o3 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]]</back> 
---
 }
object "data:Mazak-z-spec-LENGTH-Nominal" as o4 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "data:Mazak-z-spec-LINEAR_FORCE-Maximum" as o5 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "data:Mazak-z-spec-LINEAR_FORCE-Minimum" as o6 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "data:Mazak-z-spec-VELOCITY-RAPID-Maximum" as o7 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "data:Mazak-z-spec-VELOCITY-RAPID-Minimum" as o8 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "data:Mazak-z-spec-VELOCITY-PROGRAMMED-Maximum" as o9 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "data:Mazak-z-spec-VELOCITY-PROGRAMMED-Minimum" as o10 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]]</back> 
---
 }
object "[[./Mazak-yaxism.html data:Mazak-yaxism]]" as o11 #76608A {
 <back:#Green>type: ex:Structure</back> 
---
 }
object "data:Mazak-yaxism-name" as o12 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak-zaxis.html data:Mazak-zaxis]]" as o13 #76608A {
 <back:#Green>type: ex:Structure</back> 
---
 }
object "data:Mazak-zaxis-name" as o14 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "data:Mazak-z-function" as o15 #76608A {
 <back:#Green>type: ex:PrismaticMotionCapability</back> 
---
 }
object "data:Mazak-z-position-actual" as o16 #76608A {
 <back:#1E90FF>type: qp:Displacement</back> 
---
 }
object "[[./Mazak-z-Zballscrew.html data:Mazak-z-Zballscrew]]" as o17 #76608A {
 <back:#Green>type: ex:Ballscrew</back> 
---
 }
object "data:Mazak-z-Zballscrew-name" as o18 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak-z-Zmotor.html data:Mazak-z-Zmotor]]" as o19 #76608A {
 <back:#Green>type: ex:Motor</back> 
---
 }
object "data:Mazak-z-Zmotor-temperature" as o20 #76608A {
 <back:#1E90FF>type: qp:Temperature</back> 
---
 }
object "data:Mazak-z-Zmotor-name" as o21 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak.html data:Mazak]]" as o22 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Z
o1 --> o3 : [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]]
o3 --> o4 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o4 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 530.0
o3 --> o5 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o5 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 9600.0
o3 --> o6 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o6 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 0.0
o3 --> o7 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o7 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 7000.0
o3 --> o8 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o8 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 1.0
o3 --> o9 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o9 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 7000.0
o3 --> o10 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o10 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 1.0
o1 --> o11 : ex:joinedTo
o11 --> o12 : cmns-dsg:hasName
o1 --> o13 : ex:joinedTo
o13 --> o14 : cmns-dsg:hasName
o1 --> o15 : [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]]
o1 --> o16 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o1 --> o17 : obo:has member part at some time
o17 --> o18 : cmns-dsg:hasName
o1 --> o19 : obo:has member part at some time
o19 --> o20 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o19 --> o21 : cmns-dsg:hasName
o22 --> o1 : obo:has member part at some time
@enduml
