
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseY

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o1, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o2, data:Mazak317641baseYLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:Mazak317641baseYVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseYVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseYVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak317641baseYVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:Mazak317641baseYCapability, core:Capability)
individual(o8, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o9, data:Mazak317641baseYYballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o10, data:Mazak317641baseYYballscrewCapability, core:Capability)
individual(o11, data:name11, des:Name)
individual(o12, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o13, data:Mazak317641baseYYmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o14, data:mazak800imotorlinear_force5200design2, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o15, data:Mazak317641baseYYmotorCapability, core:Capability)
individual(o16, data:Mazak317641baseYTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o17, data:name12, des:Name)
individual(o18, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o19, data:Mazak317641baseYPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o20, data:name10, des:Name)
individual(o21, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o22, data:Mazak317641mstructX_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o23, data:Mazak317641mstructX_AXISCapability, core:Capability)
individual(o24, data:name2, des:Name)
individual(o25, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o26, data:Mazak317641mstructY_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o27, data:Mazak317641mstructY_AXISCapability, core:Capability)
individual(o28, data:name3, des:Name)
individual(o29, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "Mazak800ibaseYDesign particular")
property(o1, "core:hasValueExpressionAtSomeTime", o2)
property(o1, "core:hasValueExpressionAtSomeTime", o3)
property(o1, "core:hasValueExpressionAtSomeTime", o4)
property(o1, "core:hasValueExpressionAtSomeTime", o5)
property(o1, "core:hasValueExpressionAtSomeTime", o6)
property(o0, "core:hasCapability", o7)
property(o0, "core:hasComponentPartAtSomeTime", o8)
data(o8, "rdfs:label", "Mazak 317641 base Y Yballscrew particular")
property(o8, "core:hasRole", o9)
property(o8, "core:hasCapability", o10)
property(o8, "des:hasName", o11)
property(o0, "core:hasComponentPartAtSomeTime", o12)
data(o12, "rdfs:label", "Mazak 317641 base Y Ymotor particular")
property(o12, "core:hasRole", o13)
property(o12, "core:prescribedBy", o14)
property(o12, "core:hasCapability", o15)
property(o12, "core:hasQuality", o16)
property(o12, "des:hasName", o17)
property(o0, "core:hasFunction", o18)
property(o18, "core:prescribedBy", o1)
property(o0, "core:hasQuality", o19)
property(o0, "des:hasName", o20)
data(o20, "des:hasTextualName", "Y")
property(o0, "ex:connectedTo", o21)
data(o21, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o21, "core:hasRole", o22)
property(o21, "core:hasCapability", o23)
property(o21, "des:hasName", o24)
property(o0, "ex:connectedTo", o25)
data(o25, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
property(o25, "core:hasRole", o26)
property(o25, "core:hasCapability", o27)
property(o25, "des:hasName", o28)
property(o29, "core:hasComponentPartAtSomeTime", o0)
@enduml
