@startuml Mazak-trundle
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor LightBlue
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-trundle

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:[[./Mazak-trundle.html Mazak-trundle]], ex:Structure)
individual(o2, data:Mazak-trundle-name, cmns-dsg:Name)
individual(o3, data:[[./Mazak.html Mazak]], ex:Machine)
individual(o4, data:[[./Mazak-br.html Mazak-br]], ex:RotaryMotionSystem)
individual(o5, data:[[./Mazak-c2.html Mazak-c2]], ex:RotaryMotionSystem)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, TRUNDLE)
property(o3, "bfo:has member part at some time", o1)
property(o4, ex:joinedTo, o1)
property(o5, ex:joinedTo, o1)
@enduml
