
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak_base_X

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak_base_X.html Mazak_base_X]], vendor:[[../Mazak.html#MazakbaseX MazakbaseX]])
individual(o1, data:[[./Mazak_base_X_Xballscrew.html Mazak_base_X_Xballscrew]], vendor:[[../Mazak.html#MazakbaseXXballscrew MazakbaseXXballscrew]])
individual(o2, data:name8, des:Name)
individual(o3, data:[[./Mazak_base_X_Xmotor.html Mazak_base_X_Xmotor]], vendor:[[../Mazak.html#MazakbaseXXmotor MazakbaseXXmotor]])
individual(o4, data:Mazak_base_XTEMPERATURE, qualphys:Temperature)
individual(o5, data:name9, des:Name)
individual(o6, data:mazakbasexdesign1, vendor:[[../Mazak.html#MazakbaseXDesign MazakbaseXDesign]])
individual(o7, data:Mazak_base_XLengthNominal, core:ValueExpression)
individual(o8, data:Mazak_base_XLinear_forceMaximum, core:ValueExpression)
individual(o9, data:Mazak_base_XLinear_forceMinimum, core:ValueExpression)
individual(o10, data:Mazak_base_XVelocityRapidMaximum, core:ValueExpression)
individual(o11, data:Mazak_base_XVelocityRapidMinimum, core:ValueExpression)
individual(o12, data:Mazak_base_XVelocityProgrammedMaximum, core:ValueExpression)
individual(o13, data:Mazak_base_XVelocityProgrammedMinimum, core:ValueExpression)
individual(o14, data:Mazak_base_XPrismaticMotionCapability, ex:PrismaticMotionCapability)
individual(o15, data:Mazak_base_XPOSITION_ACTUAL, qualphys:Displacement)
individual(o16, data:name7, des:Name)
individual(o17, data:[[./Mazak_enclosure.html Mazak_enclosure]], vendor:[[../Mazak.html#Mazakenclosure Mazakenclosure]])
individual(o18, data:Mazak_enclosureTEMPERATURE, qualphys:Temperature)
individual(o19, data:name33, des:Name)
individual(o20, data:[[./Mazak_mstruct_X_AXIS.html Mazak_mstruct_X_AXIS]], vendor:[[../Mazak.html#MazakmstructX_AXIS MazakmstructX_AXIS]])
individual(o21, data:name2, des:Name)
individual(o22, data:[[./Mazak.html Mazak]], vendor:[[../Mazak.html#Mazak Mazak]])
property(o0, "core:hasComponentPartAtAllTimes", o1)
data(o1, "rdfs:label", "Mazak base X Xballscrew particular")
property(o1, "des:hasName", o2)
property(o0, "core:hasComponentPartAtAllTimes", o3)
data(o3, "rdfs:label", "Mazak base X Xmotor particular")
property(o3, "core:hasQuality", o4)
property(o3, "des:hasName", o5)
property(o0, "core:prescribedBy", o6)
data(o6, "rdfs:label", "MazakbaseXDesign particular")
property(o6, "core:hasValueExpressionAtAllTimes", o7)
property(o6, "core:hasValueExpressionAtAllTimes", o8)
property(o6, "core:hasValueExpressionAtAllTimes", o9)
property(o6, "core:hasValueExpressionAtAllTimes", o10)
property(o6, "core:hasValueExpressionAtAllTimes", o11)
property(o6, "core:hasValueExpressionAtAllTimes", o12)
property(o6, "core:hasValueExpressionAtAllTimes", o13)
property(o0, "core:hasFunction", o14)
property(o0, "core:hasQuality", o15)
property(o0, "des:hasName", o16)
data(o16, "des:hasTextualName", "X")
property(o0, "ex:joinedTo", o17)
data(o17, "rdfs:label", "Mazak enclosure particular")
property(o17, "core:hasQuality", o18)
property(o17, "des:hasName", o19)
property(o0, "ex:joinedTo", o20)
data(o20, "rdfs:label", "Mazak mstruct X_AXIS particular")
property(o20, "des:hasName", o21)
property(o22, "core:hasComponentPartAtAllTimes", o0)
@enduml
