@startuml Mazak-table
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak-table

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
oIndividual(data:Mazak-table, ex:Structure)
oIndividual(data:Mazak-table-name, cmns-dsg:Name)
oIndividual(data:Mazak, ex:Machine)
oIndividual(data:Mazak-c2, ex:RotaryMotionSystem)
property(data:Mazak-table, cmns-dsg:hasName, data:Mazak-table-name, down)
data(data:Mazak-table-name, cmns-dsg:hasTextualName, TABLE)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-table, down)
property(data:Mazak-c2, ex:joinedTo, data:Mazak-table, down)
@enduml
