@startuml
skinparam linetype polyline
left to right direction
title Mazak-table
object "[[./Mazak-table.html data:Mazak-table]]" as o1 {
 type: ex:Structure 
}
object "data:Mazak-table-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o3 {
 type: ex:Machine 
}
object "[[./Mazak-c2.html data:Mazak-c2]]" as o4 {
 type: ex:RotaryMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: TABLE
o3 --> o1 : obo:has member part at some time
o4 --> o1 : ex:joinedTo
@enduml
