@startuml Mazak-c2
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak-c2

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
oIndividual(data:Mazak-c2, ex:RotaryMotionSystem)
oIndividual(data:Mazak-c2-name, cmns-dsg:Name)
oIndividual(data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-c2-spec-ANGLE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-c2-spec-ANGLE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-c2-spec-TORQUE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-c2-spec-TORQUE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-trundle, ex:Structure)
oIndividual(data:Mazak-trundle-name, cmns-dsg:Name)
oIndividual(data:Mazak-table, ex:Structure)
oIndividual(data:Mazak-table-name, cmns-dsg:Name)
oIndividual(data:Mazak-c2-function, ex:RevoluteMotionCapability)
oIndividual(data:Mazak-c2-angle-actual, qp:Angle)
oIndividual(data:Mazak-c2-Cmotor, ex:Motor)
oIndividual(data:Mazak-c2-Cmotor-name, cmns-dsg:Name)
oIndividual(data:Mazak, ex:Machine)
property(data:Mazak-c2, cmns-dsg:hasName, data:Mazak-c2-name, down)
data(data:Mazak-c2-name, cmns-dsg:hasTextualName, C2)
property(data:Mazak-c2, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-c2-spec, down)
property(data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-c2-spec-ANGLE-Maximum, down)
data(data:Mazak-c2-spec-ANGLE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 360.0)
property(data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-c2-spec-ANGLE-Minimum, down)
data(data:Mazak-c2-spec-ANGLE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], -360.0)
property(data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-c2-spec-TORQUE-Maximum, down)
data(data:Mazak-c2-spec-TORQUE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 400.0)
property(data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-c2-spec-TORQUE-Minimum, down)
data(data:Mazak-c2-spec-TORQUE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(data:Mazak-c2, ex:joinedTo, data:Mazak-trundle, down)
property(data:Mazak-trundle, cmns-dsg:hasName, data:Mazak-trundle-name, down)
property(data:Mazak-c2, ex:joinedTo, data:Mazak-table, down)
property(data:Mazak-table, cmns-dsg:hasName, data:Mazak-table-name, down)
property(data:Mazak-c2, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-c2-function, down)
property(data:Mazak-c2, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-c2-angle-actual, down)
property(data:Mazak-c2, "bfo:has member part at some time", data:Mazak-c2-Cmotor, down)
property(data:Mazak-c2-Cmotor, cmns-dsg:hasName, data:Mazak-c2-Cmotor-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-c2, down)
@enduml
