@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-y

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./Mazak-y.html Mazak-y]], ex:LinearMotionSystem)
individual(o2, data:Mazak-y-name, cmns-dsg:Name)
individual(o3, data:Mazak-y-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o4, data:Mazak-y-spec-LENGTH-Nominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak-y-spec-LINEAR_FORCE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak-y-spec-LINEAR_FORCE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:Mazak-y-spec-VELOCITY-RAPID-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o8, data:Mazak-y-spec-VELOCITY-RAPID-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o9, data:Mazak-y-spec-VELOCITY-PROGRAMMED-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o10, data:Mazak-y-spec-VELOCITY-PROGRAMMED-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o11, data:[[./Mazak-xaxism.html Mazak-xaxism]], ex:Structure)
individual(o12, data:Mazak-xaxism-name, cmns-dsg:Name)
individual(o13, data:[[./Mazak-yaxism.html Mazak-yaxism]], ex:Structure)
individual(o14, data:Mazak-yaxism-name, cmns-dsg:Name)
individual(o15, data:Mazak-y-function, ex:PrismaticMotionCapability)
individual(o16, data:Mazak-y-position-actual, qp:Displacement)
individual(o17, data:[[./Mazak-y-Yballscrew.html Mazak-y-Yballscrew]], ex:Ballscrew)
individual(o18, data:Mazak-y-Yballscrew-name, cmns-dsg:Name)
individual(o19, data:[[./Mazak-y-Ymotor.html Mazak-y-Ymotor]], ex:Motor)
individual(o20, data:Mazak-y-Ymotor-temperature, qp:Temperature)
individual(o21, data:Mazak-y-Ymotor-name, cmns-dsg:Name)
individual(o22, data:[[./Mazak.html Mazak]], ex:Machine)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, Y)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o3)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o4)
data(o4, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 550.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o5)
data(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 5200.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o6)
data(o6, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o7)
data(o7, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o8)
data(o8, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o9)
data(o9, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o10)
data(o10, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o1, ex:joinedTo, o11)
property(o11, cmns-dsg:hasName, o12)
property(o1, ex:joinedTo, o13)
property(o13, cmns-dsg:hasName, o14)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o15)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o16)
property(o1, "bfo:has member part at some time", o17)
property(o17, cmns-dsg:hasName, o18)
property(o1, "bfo:has member part at some time", o19)
property(o19, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o20)
property(o19, cmns-dsg:hasName, o21)
property(o22, "bfo:has member part at some time", o1)
@enduml
