
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak800i317641baseZ

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak800i317641baseZ.html Mazak800i317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o1, data:[[./Mazak800i317641baseZZballscrew.html Mazak800i317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o2, data:name14, des:Name)
individual(o3, data:[[./Mazak800i317641baseZZmotor.html Mazak800i317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800ibaseZZmotor Mazak800ibaseZZmotor]])
individual(o4, data:Mazak800i317641baseZTEMPERATURE, qualphys:Temperature)
individual(o5, data:name15, des:Name)
individual(o6, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o7, data:Mazak800i317641baseZLengthNominal, core:ValueExpression)
individual(o8, data:Mazak800i317641baseZLinear_forceMaximum, core:ValueExpression)
individual(o9, data:Mazak800i317641baseZLinear_forceMinimum, core:ValueExpression)
individual(o10, data:Mazak800i317641baseZVelocityRapidMaximum, core:ValueExpression)
individual(o11, data:Mazak800i317641baseZVelocityRapidMinimum, core:ValueExpression)
individual(o12, data:Mazak800i317641baseZVelocityProgrammedMaximum, core:ValueExpression)
individual(o13, data:Mazak800i317641baseZVelocityProgrammedMinimum, core:ValueExpression)
individual(o14, data:Mazak800i317641baseZPrismaticMotionCapability, ex:PrismaticMotionCapability)
individual(o15, data:Mazak800i317641baseZPOSITION_ACTUAL, qualphys:Displacement)
individual(o16, data:name13, des:Name)
individual(o17, data:[[./Mazak800i317641mstructY_AXIS.html Mazak800i317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o18, data:name3, des:Name)
individual(o19, data:[[./Mazak800i317641mstructZ_AXIS.html Mazak800i317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o20, data:name4, des:Name)
individual(o21, data:[[./Mazak800i317641.html Mazak800i317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasComponentPartAtAllTimes", o1)
data(o1, "rdfs:label", "Mazak800i 317641 base Z Zballscrew particular")
property(o1, "des:hasName", o2)
property(o0, "core:hasComponentPartAtAllTimes", o3)
data(o3, "rdfs:label", "Mazak800i 317641 base Z Zmotor particular")
property(o3, "core:hasQuality", o4)
property(o3, "des:hasName", o5)
property(o0, "core:prescribedBy", o6)
data(o6, "rdfs:label", "Mazak800ibaseZDesign particular")
property(o6, "core:hasValueExpressionAtAllTimes", o7)
property(o6, "core:hasValueExpressionAtAllTimes", o8)
property(o6, "core:hasValueExpressionAtAllTimes", o9)
property(o6, "core:hasValueExpressionAtAllTimes", o10)
property(o6, "core:hasValueExpressionAtAllTimes", o11)
property(o6, "core:hasValueExpressionAtAllTimes", o12)
property(o6, "core:hasValueExpressionAtAllTimes", o13)
property(o0, "core:hasFunction", o14)
property(o0, "core:hasQuality", o15)
property(o0, "des:hasName", o16)
data(o16, "des:hasTextualName", "Z")
property(o0, "ex:joinedTo", o17)
data(o17, "rdfs:label", "Mazak800i 317641 mstruct Y_AXIS particular")
property(o17, "des:hasName", o18)
property(o0, "ex:joinedTo", o19)
data(o19, "rdfs:label", "Mazak800i 317641 mstruct Z_AXIS particular")
property(o19, "des:hasName", o20)
property(o21, "core:hasComponentPartAtAllTimes", o0)
@enduml
