
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseB

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o1, data:Mazak317641baseBEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o2, data:mazak800ibasebdesign1, vendor:[[../Mazak.html#Mazak800ibaseBDesign Mazak800ibaseBDesign]])
individual(o3, data:Mazak317641baseBAngleMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseBAngleMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseBTorqueMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak317641baseBTorqueMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:[[./Mazak317641baseBBmotor.html Mazak317641baseBBmotor]], vendor:[[../Mazak.html#Mazak800ibaseBBmotor Mazak800ibaseBBmotor]])
individual(o8, data:Mazak317641baseBBmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o9, data:name19, des:Name)
individual(o10, data:Mazak317641baseBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o11, data:Mazak317641baseBANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o12, data:name18, des:Name)
individual(o13, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o14, data:Mazak317641enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o15, data:Mazak317641enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o16, data:name33, des:Name)
individual(o17, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o18, data:Mazak317641mstructTRUNDLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o19, data:name6, des:Name)
individual(o20, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasRole", o1)
property(o0, "core:prescribedBy", o2)
data(o2, "rdfs:label", "Mazak800ibaseBDesign particular")
property(o2, "core:hasValueExpressionAtSomeTime", o3)
property(o2, "core:hasValueExpressionAtSomeTime", o4)
property(o2, "core:hasValueExpressionAtSomeTime", o5)
property(o2, "core:hasValueExpressionAtSomeTime", o6)
property(o0, "core:hasComponentPartAtSomeTime", o7)
data(o7, "rdfs:label", "Mazak 317641 base B Bmotor particular")
property(o7, "core:hasRole", o8)
property(o7, "des:hasName", o9)
property(o0, "core:hasFunction", o10)
property(o10, "core:prescribedBy", o2)
property(o0, "core:hasQuality", o11)
property(o0, "des:hasName", o12)
data(o12, "des:hasTextualName", "B")
property(o0, "ex:connectedTo", o13)
data(o13, "rdfs:label", "Mazak 317641 enclosure particular")
property(o13, "core:hasRole", o14)
property(o13, "core:hasQuality", o15)
property(o13, "des:hasName", o16)
property(o0, "ex:connectedTo", o17)
data(o17, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
property(o17, "core:hasRole", o18)
property(o17, "des:hasName", o19)
property(o20, "core:hasComponentPartAtSomeTime", o0)
@enduml
