@startuml
skinparam linetype polyline
left to right direction
title Mazak-personnelm

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-personnelm.html data:Mazak-personnelm]]" as o1 #76608A {
 <back:#1E90FF>type: [[https://spec.industrialontologies.org/ontology/core/Core/Person core:Person]]</back> 
---
 }
object "data:Mazak-personnelm-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak.html data:Mazak]]" as o3 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: personnel
o3 --> o1 : obo:has member part at some time
@enduml
