@startuml
skinparam linetype polyline
left to right direction
title Mazak-z-Zmotor
object "[[./Mazak-z-Zmotor.html data:Mazak-z-Zmotor]]" as o1 {
 type = ex:Motor
 }
object "data:Mazak-z-Zmotor-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./Mazak-z.html data:Mazak-z]]" as o3 {
 type = ex:LinearMotionSystem
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = Zmotor
o3 --> o1 : obo:has member part at some time
@enduml
