@startuml
skinparam linetype polyline
left to right direction
title Mazak-c2-Cmotor

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-c2-Cmotor.html data:Mazak-c2-Cmotor]]" as o1 #76608A {
 <back:#Green>type: ex:Motor</back> 
---
 }
object "data:Mazak-c2-Cmotor-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak-c2.html data:Mazak-c2]]" as o3 #76608A {
 <back:#Green>type: ex:RotaryMotionSystem</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Cmotor
o3 --> o1 : obo:has member part at some time
@enduml
