@startuml
skinparam linetype polyline
left to right direction
title Mazak-y-Yballscrew

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-y-Yballscrew.html data:Mazak-y-Yballscrew]]" as o1 #76608A {
 <back:#Green>type: ex:Ballscrew</back> 
---
 }
object "data:Mazak-y-Yballscrew-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak-y.html data:Mazak-y]]" as o3 #76608A {
 <back:#Green>type: ex:LinearMotionSystem</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Yballscrew
o3 --> o1 : obo:has member part at some time
@enduml
