@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-c

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./Mazak-c.html Mazak-c]], ex:RotaryMotionSystem)
individual(o2, data:Mazak-c-name, cmns-dsg:Name)
individual(o3, data:Mazak-c-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o4, data:Mazak-c-spec-VELOCITY-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak-c-spec-VELOCITY-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:[[./Mazak-zaxis.html Mazak-zaxis]], ex:Structure)
individual(o7, data:Mazak-zaxis-name, cmns-dsg:Name)
individual(o8, data:Mazak-c-function, ex:ContinuousMotionCapability)
individual(o9, data:Mazak-c-rotary_velocity-actual, qp:Speed)
individual(o10, data:[[./Mazak-c-Cmotor.html Mazak-c-Cmotor]], ex:Motor)
individual(o11, data:Mazak-c-Cmotor-temperature, qp:Temperature)
individual(o12, data:Mazak-c-Cmotor-name, cmns-dsg:Name)
individual(o13, data:[[./Mazak.html Mazak]], ex:Machine)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, C1)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o3)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o4)
data(o4, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 12000.0)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o5)
data(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o1, ex:joinedTo, o6)
property(o6, cmns-dsg:hasName, o7)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o8)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime measuresAtSomeTime]], o9)
property(o1, "bfo:has member part at some time", o10)
property(o10, core:[[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime measuresAtSomeTime]], o11)
property(o10, cmns-dsg:hasName, o12)
property(o13, "bfo:has member part at some time", o1)
@enduml
