@startuml
skinparam linetype polyline
left to right direction
object "[[./Mazak-x.html data:Mazak-x]]" as o1 {
 type = ex:LinearMotionSystem
 }
object "data:Mazak-x-name" as o2 {
 type = cmns-dsg:Name
 }
object "data:Mazak-x-spec" as o3 {
 type = core:DesignSpecification
 }
object "data:Mazak-x-spec-LENGTH-Nominal" as o4 {
 type = core:ValueExpression
 }
object "data:Mazak-x-spec-LINEAR_FORCE-Maximum" as o5 {
 type = core:ValueExpression
 }
object "data:Mazak-x-spec-LINEAR_FORCE-Minimum" as o6 {
 type = core:ValueExpression
 }
object "data:Mazak-x-spec-VELOCITY-RAPID-Maximum" as o7 {
 type = core:ValueExpression
 }
object "data:Mazak-x-spec-VELOCITY-RAPID-Minimum" as o8 {
 type = core:ValueExpression
 }
object "data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum" as o9 {
 type = core:ValueExpression
 }
object "data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum" as o10 {
 type = core:ValueExpression
 }
object "[[./Mazak-enclosurem.html data:Mazak-enclosurem]]" as o11 {
 type = ex:Structure
 }
object "data:Mazak-enclosurem-name" as o12 {
 type = cmns-dsg:Name
 }
object "data:Mazak-enclosurem-temperature" as o13 {
 type = qp:Temperature
 }
object "[[./Mazak-xaxism.html data:Mazak-xaxism]]" as o14 {
 type = ex:Structure
 }
object "data:Mazak-xaxism-name" as o15 {
 type = cmns-dsg:Name
 }
object "data:Mazak-x-function" as o16 {
 type = ex:PrismaticMotionCapability
 }
object "data:Mazak-x-position-actual" as o17 {
 type = qp:Displacement
 }
object "data:Mazak-x-position" as o18 {
 type = qp:Displacement
 }
object "data:Mazak-x-temperature" as o19 {
 type = qp:Temperature
 }
object "[[./Mazak-x-Xballscrew.html data:Mazak-x-Xballscrew]]" as o20 {
 type = ex:Ballscrew
 }
object "data:Mazak-x-Xballscrew-name" as o21 {
 type = cmns-dsg:Name
 }
object "[[./Mazak-x-Xmotor.html data:Mazak-x-Xmotor]]" as o22 {
 type = ex:Motor
 }
object "data:Mazak-x-Xmotor-name" as o23 {
 type = cmns-dsg:Name
 }
object "[[./Mazak.html data:Mazak]]" as o24 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = X
o1 --> o3 : core:prescribedBy
o3 --> o4 : core:hasValueExpressionAtAllTimes
o3 --> o5 : core:hasValueExpressionAtAllTimes
o3 --> o6 : core:hasValueExpressionAtAllTimes
o3 --> o7 : core:hasValueExpressionAtAllTimes
o3 --> o8 : core:hasValueExpressionAtAllTimes
o3 --> o9 : core:hasValueExpressionAtAllTimes
o3 --> o10 : core:hasValueExpressionAtAllTimes
o1 --> o11 : ex:joinedTo
o11 --> o12 : cmns-dsg:hasName
o11 --> o13 : core:measuresAtSomeTime
o1 --> o14 : ex:joinedTo
o14 --> o15 : cmns-dsg:hasName
o1 --> o16 : core:hasFunction
o1 --> o17 : core:measuresAtSomeTime
o1 --> o18 : core:measuresAtSomeTime
o1 --> o19 : core:measuresAtSomeTime
o1 --> o20 : obo:has member part at some time
o20 --> o21 : cmns-dsg:hasName
o1 --> o22 : obo:has member part at some time
o22 --> o23 : cmns-dsg:hasName
o24 --> o1 : obo:has member part at some time
@enduml
