
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641mstructY_AXIS

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o1, data:Mazak317641mstructY_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o2, data:Mazak317641mstructY_AXISCapability, core:Capability)
individual(o3, data:name3, des:Name)
individual(o4, data:, owl:Thing)
individual(o5, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o6, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o7, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasRole", o1)
property(o0, "core:hasCapability", o2)
property(o0, "des:hasName", o3)
data(o3, "des:hasTextualName", "Y_AXIS")
property(o4, "rdf:first", o0)
property(o5, "ex:connectedTo", o0)
property(o6, "ex:connectedTo", o0)
property(o7, "ex:hasComponent", o0)
@enduml
