@startuml
skinparam linetype polyline
left to right direction
title Mazak-cont
object "[[./Mazak-cont.html data:Mazak-cont]]" as o1 {
 type: ex:ControlSystem 
}
object "data:Mazak-cont-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak-cont-path1.html data:Mazak-cont-path1]]" as o3 {
 type: ex:ControlSystemPath 
}
object "data:Mazak-cont-path1-name" as o4 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o5 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: controller
o1 --> o3 : obo:has member part at some time
o3 --> o4 : cmns-dsg:hasName
o5 --> o1 : obo:has member part at some time
@enduml
