@startuml
skinparam linetype polyline
left to right direction
title Mazak-elec
object "[[./Mazak-elec.html data:Mazak-elec]]" as o1 {
 type: ex:ElectricalSystem 
}
object "data:Mazak-elec-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o3 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: electric
o3 --> o1 : obo:has member part at some time
@enduml
