@startuml
skinparam linetype polyline
left to right direction
title Mazak-coolant

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-coolant.html data:Mazak-coolant]]" as o1 #76608A {
 <back:#DFA702>type: obo:object</back> 
---
 }
object "data:Mazak-coolant-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "data:Mazak-coolant-temperature" as o3 #76608A {
 <back:#1E90FF>type: qp:Temperature</back> 
---
 }
object "[[./Mazak.html data:Mazak]]" as o4 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: coolant
o1 --> o3 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o4 --> o1 : obo:has member part at some time
@enduml
