@startuml Mazak-x
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak-x

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
oIndividual(data:Mazak-x, ex:LinearMotionSystem)
oIndividual(data:Mazak-x-name, cmns-dsg:Name)
oIndividual(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-x-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-x-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-x-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-x-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-x-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
oIndividual(data:Mazak-enclosurem, ex:Structure)
oIndividual(data:Mazak-enclosurem-name, cmns-dsg:Name)
oIndividual(data:Mazak-enclosurem-temperature, qp:Temperature)
oIndividual(data:Mazak-xaxism, ex:Structure)
oIndividual(data:Mazak-xaxism-name, cmns-dsg:Name)
oIndividual(data:Mazak-x-function, ex:PrismaticMotionCapability)
oIndividual(data:Mazak-x-position-actual, qp:Displacement)
oIndividual(data:Mazak-x-Xballscrew, ex:Ballscrew)
oIndividual(data:Mazak-x-Xballscrew-name, cmns-dsg:Name)
oIndividual(data:Mazak-x-Xmotor, ex:Motor)
oIndividual(data:Mazak-x-Xmotor-temperature, qp:Temperature)
oIndividual(data:Mazak-x-Xmotor-name, cmns-dsg:Name)
oIndividual(data:Mazak, ex:Machine)
property(data:Mazak-x, cmns-dsg:hasName, data:Mazak-x-name, down)
data(data:Mazak-x-name, cmns-dsg:hasTextualName, X)
property(data:Mazak-x, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-x-spec, down)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-LENGTH-Nominal, down)
data(data:Mazak-x-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 650.0)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-LINEAR_FORCE-Maximum, down)
data(data:Mazak-x-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 5200.0)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-LINEAR_FORCE-Minimum, down)
data(data:Mazak-x-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-VELOCITY-RAPID-Maximum, down)
data(data:Mazak-x-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-VELOCITY-RAPID-Minimum, down)
data(data:Mazak-x-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum, down)
data(data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum, down)
data(data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(data:Mazak-x, ex:joinedTo, data:Mazak-enclosurem, down)
property(data:Mazak-enclosurem, cmns-dsg:hasName, data:Mazak-enclosurem-name, down)
property(data:Mazak-enclosurem, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-enclosurem-temperature, down)
property(data:Mazak-x, ex:joinedTo, data:Mazak-xaxism, down)
property(data:Mazak-xaxism, cmns-dsg:hasName, data:Mazak-xaxism-name, down)
property(data:Mazak-x, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-x-function, down)
property(data:Mazak-x, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-x-position-actual, down)
property(data:Mazak-x, "bfo:has member part at some time", data:Mazak-x-Xballscrew, down)
property(data:Mazak-x-Xballscrew, cmns-dsg:hasName, data:Mazak-x-Xballscrew-name, down)
property(data:Mazak-x, "bfo:has member part at some time", data:Mazak-x-Xmotor, down)
property(data:Mazak-x-Xmotor, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-x-Xmotor-temperature, down)
property(data:Mazak-x-Xmotor, cmns-dsg:hasName, data:Mazak-x-Xmotor-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-x, down)
@enduml
