
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseXXmotor

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o1, data:Mazak317641baseXXmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o2, data:mazak800imotorlinear_force5200design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o3, data:Mazak317641baseXXmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseXXmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseXTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o6, data:name9, des:Name)
individual(o7, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
property(o0, "core:hasRole", o1)
property(o0, "core:prescribedBy", o2)
data(o2, "rdfs:label", "Mazak800iMotorLINEAR_FORCE5200Design particular")
property(o2, "core:hasValueExpressionAtSomeTime", o3)
property(o2, "core:hasValueExpressionAtSomeTime", o4)
property(o0, "core:hasQuality", o5)
property(o0, "des:hasName", o6)
data(o6, "des:hasTextualName", "Xmotor")
property(o7, "core:hasComponentPartAtSomeTime", o0)
@enduml
