@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor LightBlue
}
</style>

left to right direction
skinparam linetype polyline
title MazakFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:, owl:Ontology)
individual(o2, ex:)
individual(o3, data:[[./Mazak.html Mazak]], ex:Machine)
individual(o4, data:Mazak-name, cmns-dsg:Name)
individual(o5, data:Mazak-function, ex:MillingCapability)
individual(o6, data:Mazak-capability, ex:TurningCapability)
individual(o7, data:Mazak-role, [[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole core:EquipmentRole]])
individual(o8, data:[[./Mazak-xaxism.html Mazak-xaxism]], ex:Structure)
individual(o9, data:[[./Mazak-yaxism.html Mazak-yaxism]], ex:Structure)
individual(o10, data:[[./Mazak-zaxis.html Mazak-zaxis]], ex:Structure)
individual(o11, data:[[./Mazak-table.html Mazak-table]], ex:Structure)
individual(o12, data:[[./Mazak-trundle.html Mazak-trundle]], ex:Structure)
individual(o13, data:[[./Mazak-x.html Mazak-x]], ex:LinearMotionSystem)
individual(o14, data:[[./Mazak-y.html Mazak-y]], ex:LinearMotionSystem)
individual(o15, data:[[./Mazak-z.html Mazak-z]], ex:LinearMotionSystem)
individual(o16, data:[[./Mazak-c.html Mazak-c]], ex:RotaryMotionSystem)
individual(o17, data:[[./Mazak-br.html Mazak-br]], ex:RotaryMotionSystem)
individual(o18, data:[[./Mazak-c2.html Mazak-c2]], ex:RotaryMotionSystem)
individual(o19, data:[[./Mazak-cont.html Mazak-cont]], ex:ControlSystem)
individual(o20, data:[[./Mazak-door1.html Mazak-door1]], "bfo:object")
individual(o21, data:[[./Mazak-partocc.html Mazak-partocc]], ex:Part)
individual(o22, data:[[./Mazak-elec.html Mazak-elec]], ex:ElectricalSystem)
individual(o23, data:[[./Mazak-hydraulic.html Mazak-hydraulic]], ex:HydraulicSystem)
individual(o24, data:[[./Mazak-coolant.html Mazak-coolant]], "bfo:object")
individual(o25, data:[[./Mazak-pneumatic.html Mazak-pneumatic]], ex:PneumaticSystem)
individual(o26, data:[[./Mazak-lubrication.html Mazak-lubrication]], ex:LubricationSystem)
individual(o27, data:[[./Mazak-procstock.html Mazak-procstock]], ex:Stock)
individual(o28, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], ex:Structure)
individual(o29, data:Mazak-xaxism-name, cmns-dsg:Name)
individual(o30, data:Mazak-yaxism-name, cmns-dsg:Name)
individual(o31, data:Mazak-zaxis-name, cmns-dsg:Name)
individual(o32, data:Mazak-table-name, cmns-dsg:Name)
individual(o33, data:Mazak-trundle-name, cmns-dsg:Name)
individual(o34, data:Mazak-x-name, cmns-dsg:Name)
individual(o35, data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o36, data:Mazak-x-function, ex:PrismaticMotionCapability)
individual(o37, data:Mazak-x-position-actual, qp:Displacement)
individual(o38, data:[[./Mazak-x-Xballscrew.html Mazak-x-Xballscrew]], ex:Ballscrew)
individual(o39, data:[[./Mazak-x-Xmotor.html Mazak-x-Xmotor]], ex:Motor)
individual(o40, data:Mazak-x-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o41, data:Mazak-x-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o42, data:Mazak-x-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o43, data:Mazak-x-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o44, data:Mazak-x-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o45, data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o46, data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o47, units:MilliM)
individual(o48, units:N)
individual(o49, units:MilliM-PER-SEC)
individual(o50, data:Mazak-x-Xmotor-temperature, qp:Temperature)
individual(o51, data:Mazak-x-Xmotor-name, cmns-dsg:Name)
individual(o52, data:Mazak-x-Xballscrew-name, cmns-dsg:Name)
individual(o53, data:Mazak-y-name, cmns-dsg:Name)
individual(o54, data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o55, data:Mazak-y-function, ex:PrismaticMotionCapability)
individual(o56, data:Mazak-y-position-actual, qp:Displacement)
individual(o57, data:[[./Mazak-y-Yballscrew.html Mazak-y-Yballscrew]], ex:Ballscrew)
individual(o58, data:[[./Mazak-y-Ymotor.html Mazak-y-Ymotor]], ex:Motor)
individual(o59, data:Mazak-y-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o60, data:Mazak-y-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o61, data:Mazak-y-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o62, data:Mazak-y-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o63, data:Mazak-y-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o64, data:Mazak-y-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o65, data:Mazak-y-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o66, data:Mazak-y-Ymotor-temperature, qp:Temperature)
individual(o67, data:Mazak-y-Ymotor-name, cmns-dsg:Name)
individual(o68, data:Mazak-y-Yballscrew-name, cmns-dsg:Name)
individual(o69, data:Mazak-z-name, cmns-dsg:Name)
individual(o70, data:Mazak-z-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o71, data:Mazak-z-function, ex:PrismaticMotionCapability)
individual(o72, data:Mazak-z-position-actual, qp:Displacement)
individual(o73, data:[[./Mazak-z-Zballscrew.html Mazak-z-Zballscrew]], ex:Ballscrew)
individual(o74, data:[[./Mazak-z-Zmotor.html Mazak-z-Zmotor]], ex:Motor)
individual(o75, data:Mazak-z-spec-LENGTH-Nominal, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o76, data:Mazak-z-spec-LINEAR_FORCE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o77, data:Mazak-z-spec-LINEAR_FORCE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o78, data:Mazak-z-spec-VELOCITY-RAPID-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o79, data:Mazak-z-spec-VELOCITY-RAPID-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o80, data:Mazak-z-spec-VELOCITY-PROGRAMMED-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o81, data:Mazak-z-spec-VELOCITY-PROGRAMMED-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o82, data:Mazak-z-Zmotor-temperature, qp:Temperature)
individual(o83, data:Mazak-z-Zmotor-name, cmns-dsg:Name)
individual(o84, data:Mazak-z-Zballscrew-name, cmns-dsg:Name)
individual(o85, data:Mazak-c-name, cmns-dsg:Name)
individual(o86, data:Mazak-c-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o87, data:Mazak-c-function, ex:ContinuousMotionCapability)
individual(o88, data:Mazak-c-rotary_velocity-actual, qp:Speed)
individual(o89, data:[[./Mazak-c-C2motor.html Mazak-c-C2motor]], ex:Motor)
individual(o90, data:Mazak-c-spec-VELOCITY-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o91, data:Mazak-c-spec-VELOCITY-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o92, units:REV-PER-MIN)
individual(o93, data:[[./Mazak-c-Cmotor.html Mazak-c-Cmotor]])
individual(o94, data:Mazak-c-Cmotor-temperature, qp:Temperature)
individual(o95, data:Mazak-c-C2motor-name, cmns-dsg:Name)
individual(o96, data:Mazak-br-name, cmns-dsg:Name)
individual(o97, data:Mazak-br-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o98, data:Mazak-br-function, ex:RevoluteMotionCapability)
individual(o99, data:Mazak-br-angle-actual, qp:Angle)
individual(o100, data:[[./Mazak-br-Bmotor.html Mazak-br-Bmotor]], ex:Motor)
individual(o101, data:Mazak-br-spec-ANGLE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o102, data:Mazak-br-spec-ANGLE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o103, data:Mazak-br-spec-TORQUE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o104, data:Mazak-br-spec-TORQUE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o105, units:DEG)
individual(o106, units:N-M)
individual(o107, data:Mazak-br-Bmotor-name, cmns-dsg:Name)
individual(o108, data:Mazak-c2-name, cmns-dsg:Name)
individual(o109, data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o110, data:Mazak-c2-function, ex:RevoluteMotionCapability)
individual(o111, data:Mazak-c2-angle-actual, qp:Angle)
individual(o112, data:[[./Mazak-c2-Cmotor.html Mazak-c2-Cmotor]], ex:Motor)
individual(o113, data:Mazak-c2-spec-ANGLE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o114, data:Mazak-c2-spec-ANGLE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o115, data:Mazak-c2-spec-TORQUE-Maximum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o116, data:Mazak-c2-spec-TORQUE-Minimum, [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]])
individual(o117, data:Mazak-c2-Cmotor-name, cmns-dsg:Name)
individual(o118, data:Mazak-cont-name, cmns-dsg:Name)
individual(o119, data:[[./Mazak-cont-path1.html Mazak-cont-path1]], ex:ControlSystemPath)
individual(o120, data:Mazak-cont-path1-name, cmns-dsg:Name)
individual(o121, data:Mazak-door1-name, cmns-dsg:Name)
individual(o122, data:Mazak-partocc-name, cmns-dsg:Name)
individual(o123, data:Mazak-elec-name, cmns-dsg:Name)
individual(o124, data:Mazak-hydraulic-name, cmns-dsg:Name)
individual(o125, data:Mazak-coolant-name, cmns-dsg:Name)
individual(o126, data:Mazak-coolant-temperature, qp:Temperature)
individual(o127, data:Mazak-pneumatic-name, cmns-dsg:Name)
individual(o128, data:Mazak-lubrication-name, cmns-dsg:Name)
individual(o129, data:[[./Mazak-room.html Mazak-room]], ex:Room)
individual(o130, data:Mazak-room-name, cmns-dsg:Name)
individual(o131, data:Mazak-room-temperature, qp:Temperature)
individual(o132, data:[[./Mazak-personnelm.html Mazak-personnelm]], [[https://spec.industrialontologies.org/ontology/core/Core/Person core:Person]])
individual(o133, data:Mazak-personnelm-name, cmns-dsg:Name)
individual(o134, data:Mazak-procstock-name, cmns-dsg:Name)
individual(o135, data:Mazak-enclosurem-name, cmns-dsg:Name)
individual(o136, data:Mazak-enclosurem-temperature, qp:Temperature)
data(o1, rdfs:label, Machine Ontology)
property(o1, owl:imports, o2)
property(o3, cmns-dsg:hasName, o4)
property(o3, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o5)
property(o3, [[https://spec.industrialontologies.org/ontology/core/Core/hasCapability core:hasCapability]], o6)
property(o3, [[https://spec.industrialontologies.org/ontology/core/Core/hasRole core:hasRole]], o7)
property(o3, "bfo:has member part at some time", o8)
property(o3, "bfo:has member part at some time", o9)
property(o3, "bfo:has member part at some time", o10)
property(o3, "bfo:has member part at some time", o11)
property(o3, "bfo:has member part at some time", o12)
property(o3, "bfo:has member part at some time", o13)
property(o3, "bfo:has member part at some time", o14)
property(o3, "bfo:has member part at some time", o15)
property(o3, "bfo:has member part at some time", o16)
property(o3, "bfo:has member part at some time", o17)
property(o3, "bfo:has member part at some time", o18)
property(o3, "bfo:has member part at some time", o19)
property(o3, "bfo:has member part at some time", o20)
property(o3, "bfo:has member part at some time", o21)
property(o3, "bfo:has member part at some time", o22)
property(o3, "bfo:has member part at some time", o23)
property(o3, "bfo:has member part at some time", o24)
property(o3, "bfo:has member part at some time", o25)
property(o3, "bfo:has member part at some time", o26)
property(o3, "bfo:has member part at some time", o27)
property(o3, "bfo:has member part at some time", o28)
data(o4, cmns-dsg:hasTextualName, Mazak)
property(o8, cmns-dsg:hasName, o29)
data(o29, cmns-dsg:hasTextualName, X_AXIS)
property(o9, cmns-dsg:hasName, o30)
data(o30, cmns-dsg:hasTextualName, Y_AXIS)
property(o10, cmns-dsg:hasName, o31)
data(o31, cmns-dsg:hasTextualName, Z_AXIS)
property(o11, cmns-dsg:hasName, o32)
data(o32, cmns-dsg:hasTextualName, TABLE)
property(o12, cmns-dsg:hasName, o33)
data(o33, cmns-dsg:hasTextualName, TRUNDLE)
property(o13, cmns-dsg:hasName, o34)
property(o13, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o35)
property(o13, ex:joinedTo, o28)
property(o13, ex:joinedTo, o8)
property(o13, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o36)
property(o13, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o37)
property(o13, "bfo:has member part at some time", o38)
property(o13, "bfo:has member part at some time", o39)
data(o34, cmns-dsg:hasTextualName, X)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o40)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o41)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o42)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o43)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o44)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o45)
property(o35, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o46)
data(o40, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 650.0)
property(o40, units:hasUnit, o47)
data(o41, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 5200.0)
property(o41, units:hasUnit, o48)
data(o42, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(o42, units:hasUnit, o48)
data(o43, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(o43, units:hasUnit, o49)
data(o44, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(o44, units:hasUnit, o49)
data(o45, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(o45, units:hasUnit, o49)
data(o46, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(o46, units:hasUnit, o49)
property(o39, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o50)
property(o39, cmns-dsg:hasName, o51)
property(o38, cmns-dsg:hasName, o52)
data(o52, cmns-dsg:hasTextualName, Xballscrew)
data(o51, cmns-dsg:hasTextualName, Xmotor)
property(o14, cmns-dsg:hasName, o53)
property(o14, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o54)
property(o14, ex:joinedTo, o8)
property(o14, ex:joinedTo, o9)
property(o14, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o55)
property(o14, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o56)
property(o14, "bfo:has member part at some time", o57)
property(o14, "bfo:has member part at some time", o58)
data(o53, cmns-dsg:hasTextualName, Y)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o59)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o60)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o61)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o62)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o63)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o64)
property(o54, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o65)
data(o59, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 550.0)
property(o59, units:hasUnit, o47)
data(o60, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 5200.0)
property(o60, units:hasUnit, o48)
data(o61, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(o61, units:hasUnit, o48)
data(o62, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(o62, units:hasUnit, o49)
data(o63, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(o63, units:hasUnit, o49)
data(o64, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(o64, units:hasUnit, o49)
data(o65, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(o65, units:hasUnit, o49)
property(o58, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o66)
property(o58, cmns-dsg:hasName, o67)
property(o57, cmns-dsg:hasName, o68)
data(o68, cmns-dsg:hasTextualName, Yballscrew)
data(o67, cmns-dsg:hasTextualName, Ymotor)
property(o15, cmns-dsg:hasName, o69)
property(o15, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o70)
property(o15, ex:joinedTo, o9)
property(o15, ex:joinedTo, o10)
property(o15, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o71)
property(o15, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o72)
property(o15, "bfo:has member part at some time", o73)
property(o15, "bfo:has member part at some time", o74)
data(o69, cmns-dsg:hasTextualName, Z)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o75)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o76)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o77)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o78)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o79)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o80)
property(o70, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o81)
data(o75, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 530.0)
property(o75, units:hasUnit, o47)
data(o76, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 9600.0)
property(o76, units:hasUnit, o48)
data(o77, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(o77, units:hasUnit, o48)
data(o78, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(o78, units:hasUnit, o49)
data(o79, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(o79, units:hasUnit, o49)
data(o80, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 7000.0)
property(o80, units:hasUnit, o49)
data(o81, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 1.0)
property(o81, units:hasUnit, o49)
property(o74, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o82)
property(o74, cmns-dsg:hasName, o83)
property(o73, cmns-dsg:hasName, o84)
data(o84, cmns-dsg:hasTextualName, Zballscrew)
data(o83, cmns-dsg:hasTextualName, Zmotor)
property(o16, cmns-dsg:hasName, o85)
property(o16, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o86)
property(o16, ex:joinedTo, o10)
property(o16, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o87)
property(o16, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o88)
property(o16, "bfo:has member part at some time", o89)
data(o85, cmns-dsg:hasTextualName, C1)
property(o86, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o90)
property(o86, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o91)
data(o90, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 12000.0)
property(o90, units:hasUnit, o92)
data(o91, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(o91, units:hasUnit, o92)
property(o93, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o94)
property(o89, cmns-dsg:hasName, o95)
data(o95, cmns-dsg:hasTextualName, C2motor)
property(o17, cmns-dsg:hasName, o96)
property(o17, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o97)
property(o17, ex:joinedTo, o28)
property(o17, ex:joinedTo, o12)
property(o17, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o98)
property(o17, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o99)
property(o17, "bfo:has member part at some time", o100)
data(o96, cmns-dsg:hasTextualName, B)
property(o97, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o101)
property(o97, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o102)
property(o97, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o103)
property(o97, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o104)
data(o101, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 120.0)
property(o101, units:hasUnit, o105)
data(o102, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], -30.0)
property(o102, units:hasUnit, o105)
data(o103, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 400.0)
property(o103, units:hasUnit, o106)
data(o104, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(o104, units:hasUnit, o106)
property(o100, cmns-dsg:hasName, o107)
data(o107, cmns-dsg:hasTextualName, Bmotor)
property(o18, cmns-dsg:hasName, o108)
property(o18, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o109)
property(o18, ex:joinedTo, o12)
property(o18, ex:joinedTo, o11)
property(o18, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o110)
property(o18, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o111)
property(o18, "bfo:has member part at some time", o112)
data(o108, cmns-dsg:hasTextualName, C2)
property(o109, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o113)
property(o109, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o114)
property(o109, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o115)
property(o109, [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]], o116)
data(o113, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 360.0)
property(o113, units:hasUnit, o105)
data(o114, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], -360.0)
property(o114, units:hasUnit, o105)
data(o115, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 400.0)
property(o115, units:hasUnit, o106)
data(o116, [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]], 0.0)
property(o116, units:hasUnit, o106)
property(o112, cmns-dsg:hasName, o117)
data(o117, cmns-dsg:hasTextualName, Cmotor)
property(o19, cmns-dsg:hasName, o118)
property(o19, "bfo:has member part at some time", o119)
data(o118, cmns-dsg:hasTextualName, controller)
property(o119, cmns-dsg:hasName, o120)
data(o120, cmns-dsg:hasTextualName, path)
property(o20, cmns-dsg:hasName, o121)
data(o121, cmns-dsg:hasTextualName, door)
property(o21, cmns-dsg:hasName, o122)
data(o122, cmns-dsg:hasTextualName, partocc)
property(o22, cmns-dsg:hasName, o123)
data(o123, cmns-dsg:hasTextualName, electric)
property(o23, cmns-dsg:hasName, o124)
data(o124, cmns-dsg:hasTextualName, hydraulic)
property(o24, cmns-dsg:hasName, o125)
property(o24, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o126)
data(o125, cmns-dsg:hasTextualName, coolant)
property(o25, cmns-dsg:hasName, o127)
data(o127, cmns-dsg:hasTextualName, pneumatic)
property(o26, cmns-dsg:hasName, o128)
data(o128, cmns-dsg:hasTextualName, lubrication)
property(o129, cmns-dsg:hasName, o130)
property(o129, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o131)
data(o130, cmns-dsg:hasTextualName, environmental)
property(o132, cmns-dsg:hasName, o133)
data(o133, cmns-dsg:hasTextualName, personnel)
property(o27, cmns-dsg:hasName, o134)
data(o134, cmns-dsg:hasTextualName, stock)
property(o28, cmns-dsg:hasName, o135)
property(o28, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o136)
data(o135, cmns-dsg:hasTextualName, enclosure)
@enduml
