
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak800i317641baseZZballscrew

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak800i317641baseZZballscrew.html Mazak800i317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o1, data:name14, des:Name)
individual(o2, data:[[./Mazak800i317641baseZ.html Mazak800i317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
property(o0, "des:hasName", o1)
data(o1, "des:hasTextualName", "Zballscrew")
property(o2, "core:hasComponentPartAtAllTimes", o0)
@enduml
