@startuml
skinparam linetype polyline
left to right direction
title Mazak-enclosurem
object "[[./Mazak-enclosurem.html data:Mazak-enclosurem]]" as o1 {
 type: ex:Structure 
}
object "data:Mazak-enclosurem-name" as o2 {
 type: cmns-dsg:Name 
}
object "data:Mazak-enclosurem-temperature" as o3 {
 type: qp:Temperature 
}
object "[[./Mazak.html data:Mazak]]" as o4 {
 type: ex:Machine 
}
object "[[./Mazak-x.html data:Mazak-x]]" as o5 {
 type: ex:LinearMotionSystem 
}
object "[[./Mazak-br.html data:Mazak-br]]" as o6 {
 type: ex:RotaryMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: enclosure
o1 --> o3 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o4 --> o1 : obo:has member part at some time
o5 --> o1 : ex:joinedTo
o6 --> o1 : ex:joinedTo
@enduml
