@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-yaxism

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./Mazak-yaxism.html Mazak-yaxism]], ex:Structure)
individual(o2, data:Mazak-yaxism-name, cmns-dsg:Name)
individual(o3, data:[[./Mazak.html Mazak]], ex:Machine)
individual(o4, data:[[./Mazak-y.html Mazak-y]], ex:LinearMotionSystem)
individual(o5, data:[[./Mazak-z.html Mazak-z]], ex:LinearMotionSystem)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, Y_AXIS)
property(o3, "bfo:has member part at some time", o1)
property(o4, ex:joinedTo, o1)
property(o5, ex:joinedTo, o1)
@enduml
