@startuml
skinparam linetype polyline
left to right direction
title Mazak-br-Bmotor

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-br-Bmotor.html data:Mazak-br-Bmotor]]" as o1 #76608A {
 <back:#Green>type: ex:Motor</back> 
---
 }
object "data:Mazak-br-Bmotor-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak-br.html data:Mazak-br]]" as o3 #76608A {
 <back:#Green>type: ex:RotaryMotionSystem</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Bmotor
o3 --> o1 : obo:has member part at some time
@enduml
