@startuml
skinparam linetype polyline
left to right direction
object "[[./Mazak-x-Xballscrew.html data:Mazak-x-Xballscrew]]" as o1 {
 type = ex:Ballscrew
 }
object "data:Mazak-x-Xballscrew-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./Mazak-x.html data:Mazak-x]]" as o3 {
 type = ex:LinearMotionSystem
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = Xballscrew
o3 --> o1 : obo:has member part at some time
@enduml
