@startuml Mazak-enclosurem
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak-enclosurem

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
oIndividual(data:Mazak-enclosurem, ex:Structure)
oIndividual(data:Mazak-enclosurem-name, cmns-dsg:Name)
oIndividual(data:Mazak-enclosurem-temperature, qp:Temperature)
oIndividual(data:Mazak, ex:Machine)
oIndividual(data:Mazak-x, ex:LinearMotionSystem)
oIndividual(data:Mazak-br, ex:RotaryMotionSystem)
property(data:Mazak-enclosurem, cmns-dsg:hasName, data:Mazak-enclosurem-name, down)
data(data:Mazak-enclosurem-name, cmns-dsg:hasTextualName, enclosure)
property(data:Mazak-enclosurem, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-enclosurem-temperature, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-enclosurem, down)
property(data:Mazak-x, ex:joinedTo, data:Mazak-enclosurem, down)
property(data:Mazak-br, ex:joinedTo, data:Mazak-enclosurem, down)
@enduml
