@startuml
skinparam linetype polyline
left to right direction
object "[[./Mazak-x.html data:Mazak-x]]" as o1 {
 type = ex:LinearMotionSystem
 }
object "[[./Mazak-enclosurem.html data:Mazak-enclosurem]]" as o2 {
 type = ex:Structure
 }
object "[[./Mazak-xaxism.html data:Mazak-xaxism]]" as o3 {
 type = ex:Structure
 }
object "[[./Mazak-y.html data:Mazak-y]]" as o4 {
 type = ex:LinearMotionSystem
 }
object "[[./Mazak-yaxism.html data:Mazak-yaxism]]" as o5 {
 type = ex:Structure
 }
object "[[./Mazak-z.html data:Mazak-z]]" as o6 {
 type = ex:LinearMotionSystem
 }
object "[[./Mazak-zaxis.html data:Mazak-zaxis]]" as o7 {
 type = ex:Structure
 }
object "[[./Mazak-c.html data:Mazak-c]]" as o8 {
 type = ex:RotaryMotionSystem
 }
object "[[./Mazak-br.html data:Mazak-br]]" as o9 {
 type = ex:RotaryMotionSystem
 }
object "[[./Mazak-trundle.html data:Mazak-trundle]]" as o10 {
 type = ex:Structure
 }
object "[[./Mazak-c2.html data:Mazak-c2]]" as o11 {
 type = ex:RotaryMotionSystem
 }
object "[[./Mazak-table.html data:Mazak-table]]" as o12 {
 type = ex:Structure
 }
o1 --> o2 : ex:joinedTo
o1 : cmns-dsg:hasName = X
o1 --> o3 : ex:joinedTo
o4 --> o3 : ex:joinedTo
o4 : cmns-dsg:hasName = Y
o4 --> o5 : ex:joinedTo
o6 --> o5 : ex:joinedTo
o6 : cmns-dsg:hasName = Z
o6 --> o7 : ex:joinedTo
o8 --> o7 : ex:joinedTo
o8 : cmns-dsg:hasName = C1
o9 --> o2 : ex:joinedTo
o9 : cmns-dsg:hasName = B
o9 --> o10 : ex:joinedTo
o11 --> o10 : ex:joinedTo
o11 : cmns-dsg:hasName = C2
o11 --> o12 : ex:joinedTo
@enduml
