@startuml
skinparam linetype polyline
left to right direction
title Mazak-c2-Cmotor
object "[[./Mazak-c2-Cmotor.html data:Mazak-c2-Cmotor]]" as o1 {
 type: ex:Motor 
}
object "data:Mazak-c2-Cmotor-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak-c2.html data:Mazak-c2]]" as o3 {
 type: ex:RotaryMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: Cmotor
o3 --> o1 : obo:has member part at some time
@enduml
