@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor LightBlue
}
</style>

left to right direction
skinparam linetype polyline
title MazakTopo

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:[[./Mazak-x.html Mazak-x]], ex:LinearMotionSystem)
individual(o2, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], ex:Structure)
individual(o3, data:[[./Mazak-xaxism.html Mazak-xaxism]], ex:Structure)
individual(o4, data:[[./Mazak-y.html Mazak-y]], ex:LinearMotionSystem)
individual(o5, data:[[./Mazak-yaxism.html Mazak-yaxism]], ex:Structure)
individual(o6, data:[[./Mazak-z.html Mazak-z]], ex:LinearMotionSystem)
individual(o7, data:[[./Mazak-zaxis.html Mazak-zaxis]], ex:Structure)
individual(o8, data:[[./Mazak-c.html Mazak-c]], ex:RotaryMotionSystem)
individual(o9, data:[[./Mazak-br.html Mazak-br]], ex:RotaryMotionSystem)
individual(o10, data:[[./Mazak-trundle.html Mazak-trundle]], ex:Structure)
individual(o11, data:[[./Mazak-c2.html Mazak-c2]], ex:RotaryMotionSystem)
individual(o12, data:[[./Mazak-table.html Mazak-table]], ex:Structure)
property(o1, ex:joinedTo, o2)
data(o1, cmns-dsg:hasName, X)
property(o1, ex:joinedTo, o3)
property(o4, ex:joinedTo, o3)
data(o4, cmns-dsg:hasName, Y)
property(o4, ex:joinedTo, o5)
property(o6, ex:joinedTo, o5)
data(o6, cmns-dsg:hasName, Z)
property(o6, ex:joinedTo, o7)
property(o8, ex:joinedTo, o7)
data(o8, cmns-dsg:hasName, C1)
property(o9, ex:joinedTo, o2)
data(o9, cmns-dsg:hasName, B)
property(o9, ex:joinedTo, o10)
property(o11, ex:joinedTo, o10)
data(o11, cmns-dsg:hasName, C2)
property(o11, ex:joinedTo, o12)
@enduml
