@startuml
skinparam linetype polyline
left to right direction
title Mazak-y-Ymotor
object "[[./Mazak-y-Ymotor.html data:Mazak-y-Ymotor]]" as o1 {
 type: ex:Motor 
}
object "data:Mazak-y-Ymotor-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak-y.html data:Mazak-y]]" as o3 {
 type: ex:LinearMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Ymotor
o3 --> o1 : obo:has member part at some time
@enduml
