
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641enclosure

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o1, data:Mazak317641enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o2, data:Mazak317641enclosureCapability, core:Capability)
individual(o3, data:Mazak317641enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o4, data:name33, des:Name)
individual(o5, data:, owl:Thing)
individual(o6, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o7, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o8, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasRole", o1)
property(o0, "core:hasCapability", o2)
property(o0, "core:hasQuality", o3)
property(o0, "des:hasName", o4)
data(o4, "des:hasTextualName", "enclosure")
property(o5, "rdf:first", o0)
property(o6, "ex:connectedTo", o0)
property(o7, "ex:connectedTo", o0)
property(o8, "ex:hasComponent", o0)
@enduml
