
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseYYballscrew

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o1, data:Mazak317641baseYYballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o2, data:name11, des:Name)
individual(o3, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
property(o0, "core:hasRole", o1)
property(o0, "des:hasName", o2)
data(o2, "des:hasTextualName", "Yballscrew")
property(o3, "core:hasComponentPartAtSomeTime", o0)
@enduml
