
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title MazakFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, vendor:ontology1, owl:Ontology)
individual(o2, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
individual(o3, data:name1, des:Name)
individual(o4, data:Mazak317641TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o5, data:Mazak317641MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o6, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o7, data:name2, des:Name)
individual(o8, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o9, data:name3, des:Name)
individual(o10, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o11, data:name4, des:Name)
individual(o12, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o13, data:name5, des:Name)
individual(o14, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o15, data:name6, des:Name)
individual(o16, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o17, data:name7, des:Name)
individual(o18, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o19, data:Mazak317641baseXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o20, units:MilliM, units:Unit)
individual(o21, data:Mazak317641baseXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o22, units:MilliM-PER-SEC, units:Unit)
individual(o23, data:Mazak317641baseXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o24, data:Mazak317641baseXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o25, data:Mazak317641baseXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o26, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o27, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o28, data:name8, des:Name)
individual(o29, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o30, data:name9, des:Name)
individual(o31, data:mazak800imotorlinear_force5200design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o32, data:Mazak317641baseXXmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o33, units:N, units:Unit)
individual(o34, data:Mazak317641baseXXmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o35, data:Mazak317641baseXPOSITION_ACTUAL, qualphys:Displacement)
individual(o36, data:Mazak317641baseXTEMPERATURE, qualphys:Temperature)
individual(o37, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o38, data:name10, des:Name)
individual(o39, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o40, data:Mazak317641baseYLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o41, data:Mazak317641baseYVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o42, data:Mazak317641baseYVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o43, data:Mazak317641baseYVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o44, data:Mazak317641baseYVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o45, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o46, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o47, data:name11, des:Name)
individual(o48, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o49, data:name12, des:Name)
individual(o50, data:mazak800imotorlinear_force5200design2, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o51, data:Mazak317641baseYYmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o52, data:Mazak317641baseYYmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o53, data:Mazak317641baseYPOSITION_ACTUAL, qualphys:Displacement)
individual(o54, data:Mazak317641baseYTEMPERATURE, qualphys:Temperature)
individual(o55, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o56, data:name13, des:Name)
individual(o57, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o58, data:Mazak317641baseZLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o59, data:Mazak317641baseZVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o60, data:Mazak317641baseZVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o61, data:Mazak317641baseZVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o62, data:Mazak317641baseZVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o63, data:Mazak317641baseZPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o64, data:[[./Mazak317641baseZZballscrew.html Mazak317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o65, data:name14, des:Name)
individual(o66, data:[[./Mazak317641baseZZmotor.html Mazak317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600 Mazak800iMotorLINEAR_FORCE9600]])
individual(o67, data:name15, des:Name)
individual(o68, data:mazak800imotorlinear_force9600design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600Design Mazak800iMotorLINEAR_FORCE9600Design]])
individual(o69, data:Mazak317641baseZZmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o70, data:Mazak317641baseZZmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o71, data:Mazak317641baseZPOSITION_ACTUAL, qualphys:Displacement)
individual(o72, data:Mazak317641baseZTEMPERATURE, qualphys:Temperature)
individual(o73, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o74, data:name16, des:Name)
individual(o75, data:mazak800ibasec1design1, vendor:[[../Mazak.html#Mazak800ibaseC1Design Mazak800ibaseC1Design]])
individual(o76, data:Mazak317641baseC1Rotary_velocityMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o77, units:REV-PER-MIN, units:Unit)
individual(o78, data:Mazak317641baseC1Rotary_velocityMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o79, data:Mazak317641baseC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o80, data:[[./Mazak317641baseC1Cmotor.html Mazak317641baseC1Cmotor]], vendor:[[../Mazak.html#Mazak800ibaseC1Cmotor Mazak800ibaseC1Cmotor]])
individual(o81, data:name17, des:Name)
individual(o82, data:Mazak317641baseC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o83, data:Mazak317641baseC1TEMPERATURE, qualphys:Temperature)
individual(o84, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o85, data:name18, des:Name)
individual(o86, data:mazak800ibasebdesign1, vendor:[[../Mazak.html#Mazak800ibaseBDesign Mazak800ibaseBDesign]])
individual(o87, data:Mazak317641baseBAngleMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o88, data:Mazak317641baseBAngleMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o89, data:Mazak317641baseBTorqueMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o90, units:N-M, units:Unit)
individual(o91, data:Mazak317641baseBTorqueMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o92, data:Mazak317641baseBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o93, data:[[./Mazak317641baseBBmotor.html Mazak317641baseBBmotor]], vendor:[[../Mazak.html#Mazak800ibaseBBmotor Mazak800ibaseBBmotor]])
individual(o94, data:name19, des:Name)
individual(o95, data:Mazak317641baseBANGLE_ACTUAL, qualphys:Angle)
individual(o96, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o97, data:name20, des:Name)
individual(o98, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o99, data:Mazak317641baseC2AngleMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o100, data:Mazak317641baseC2AngleMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o101, data:Mazak317641baseC2TorqueMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o102, data:Mazak317641baseC2TorqueMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o103, data:Mazak317641baseC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o104, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o105, data:name21, des:Name)
individual(o106, data:Mazak317641baseC2ANGLE_ACTUAL, qualphys:Angle)
individual(o107, data:[[./Mazak317641controller.html Mazak317641controller]], vendor:[[../Mazak.html#Mazak800icontroller Mazak800icontroller]])
individual(o108, data:name22, des:Name)
individual(o109, data:[[./Mazak317641controllerpath.html Mazak317641controllerpath]], vendor:[[../Mazak.html#Mazak800icontrollerpath Mazak800icontrollerpath]])
individual(o110, data:name23, des:Name)
individual(o111, data:[[./Mazak317641door.html Mazak317641door]], vendor:[[../Mazak.html#Mazak800idoor Mazak800idoor]])
individual(o112, data:name24, des:Name)
individual(o113, data:[[./Mazak317641partspartocc.html Mazak317641partspartocc]], vendor:[[../Mazak.html#Mazak800ipartspartocc Mazak800ipartspartocc]])
individual(o114, data:name25, des:Name)
individual(o115, data:[[./Mazak317641systemselectric.html Mazak317641systemselectric]], vendor:[[../Mazak.html#Mazak800isystemselectric Mazak800isystemselectric]])
individual(o116, data:name26, des:Name)
individual(o117, data:[[./Mazak317641systemshydraulic.html Mazak317641systemshydraulic]], vendor:[[../Mazak.html#Mazak800isystemshydraulic Mazak800isystemshydraulic]])
individual(o118, data:name27, des:Name)
individual(o119, data:[[./Mazak317641systemscoolant.html Mazak317641systemscoolant]], vendor:[[../Mazak.html#Mazak800isystemscoolant Mazak800isystemscoolant]])
individual(o120, data:name28, des:Name)
individual(o121, data:Mazak317641systemscoolantTEMPERATURE, qualphys:Temperature)
individual(o122, data:[[./Mazak317641systemspneumatic.html Mazak317641systemspneumatic]], vendor:[[../Mazak.html#Mazak800isystemspneumatic Mazak800isystemspneumatic]])
individual(o123, data:name29, des:Name)
individual(o124, data:[[./Mazak317641systemslubrication.html Mazak317641systemslubrication]], vendor:[[../Mazak.html#Mazak800isystemslubrication Mazak800isystemslubrication]])
individual(o125, data:name30, des:Name)
individual(o126, data:[[./Mazak317641auxiliariesenvironmental.html Mazak317641auxiliariesenvironmental]], vendor:[[../Mazak.html#Mazak800iauxiliariesenvironmental Mazak800iauxiliariesenvironmental]])
individual(o127, data:name31, des:Name)
individual(o128, data:Mazak317641auxiliariesenvironmentalTEMPERATURE, qualphys:Temperature)
individual(o129, data:[[./Mazak317641resourcesmaterialsstock.html Mazak317641resourcesmaterialsstock]], vendor:[[../Mazak.html#Mazak800iresourcesmaterialsstock Mazak800iresourcesmaterialsstock]])
individual(o130, data:name32, des:Name)
individual(o131, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o132, data:name33, des:Name)
individual(o133, data:Mazak317641enclosureTEMPERATURE, qualphys:Temperature)
property(o0, "owl:imports", o1)
property(o2, "des:hasName", o3)
property(o2, "core:hasCapability", o4)
property(o2, "core:hasFunction", o5)
property(o2, "core:hasComponentPartAtAllTimes", o6)
property(o6, "des:hasName", o7)
property(o2, "core:hasComponentPartAtAllTimes", o8)
property(o8, "des:hasName", o9)
property(o2, "core:hasComponentPartAtAllTimes", o10)
property(o10, "des:hasName", o11)
property(o2, "core:hasComponentPartAtAllTimes", o12)
property(o12, "des:hasName", o13)
property(o2, "core:hasComponentPartAtAllTimes", o14)
property(o14, "des:hasName", o15)
property(o2, "core:hasComponentPartAtAllTimes", o16)
property(o16, "des:hasName", o17)
property(o16, "core:prescribedBy", o18)
property(o18, "core:hasValueExpressionAtAllTimes", o19)
property(o19, "ex:hasUnit", o20)
property(o18, "core:hasValueExpressionAtAllTimes", o21)
property(o21, "ex:hasUnit", o22)
property(o18, "core:hasValueExpressionAtAllTimes", o23)
property(o23, "ex:hasUnit", o22)
property(o18, "core:hasValueExpressionAtAllTimes", o24)
property(o24, "ex:hasUnit", o22)
property(o18, "core:hasValueExpressionAtAllTimes", o25)
property(o25, "ex:hasUnit", o22)
property(o16, "core:hasFunction", o26)
property(o26, "core:prescribedBy", o18)
property(o16, "core:hasComponentPartAtAllTimes", o27)
property(o27, "des:hasName", o28)
property(o16, "core:hasComponentPartAtAllTimes", o29)
property(o29, "des:hasName", o30)
property(o29, "core:prescribedBy", o31)
property(o31, "core:hasValueExpressionAtAllTimes", o32)
property(o32, "ex:hasUnit", o33)
property(o31, "core:hasValueExpressionAtAllTimes", o34)
property(o34, "ex:hasUnit", o33)
property(o16, "core:hasQuality", o35)
property(o29, "core:hasQuality", o36)
property(o2, "core:hasComponentPartAtAllTimes", o37)
property(o37, "des:hasName", o38)
property(o37, "core:prescribedBy", o39)
property(o39, "core:hasValueExpressionAtAllTimes", o40)
property(o40, "ex:hasUnit", o20)
property(o39, "core:hasValueExpressionAtAllTimes", o41)
property(o41, "ex:hasUnit", o22)
property(o39, "core:hasValueExpressionAtAllTimes", o42)
property(o42, "ex:hasUnit", o22)
property(o39, "core:hasValueExpressionAtAllTimes", o43)
property(o43, "ex:hasUnit", o22)
property(o39, "core:hasValueExpressionAtAllTimes", o44)
property(o44, "ex:hasUnit", o22)
property(o37, "core:hasFunction", o45)
property(o45, "core:prescribedBy", o39)
property(o37, "core:hasComponentPartAtAllTimes", o46)
property(o46, "des:hasName", o47)
property(o37, "core:hasComponentPartAtAllTimes", o48)
property(o48, "des:hasName", o49)
property(o48, "core:prescribedBy", o50)
property(o50, "core:hasValueExpressionAtAllTimes", o51)
property(o51, "ex:hasUnit", o33)
property(o50, "core:hasValueExpressionAtAllTimes", o52)
property(o52, "ex:hasUnit", o33)
property(o37, "core:hasQuality", o53)
property(o48, "core:hasQuality", o54)
property(o2, "core:hasComponentPartAtAllTimes", o55)
property(o55, "des:hasName", o56)
property(o55, "core:prescribedBy", o57)
property(o57, "core:hasValueExpressionAtAllTimes", o58)
property(o58, "ex:hasUnit", o20)
property(o57, "core:hasValueExpressionAtAllTimes", o59)
property(o59, "ex:hasUnit", o22)
property(o57, "core:hasValueExpressionAtAllTimes", o60)
property(o60, "ex:hasUnit", o22)
property(o57, "core:hasValueExpressionAtAllTimes", o61)
property(o61, "ex:hasUnit", o22)
property(o57, "core:hasValueExpressionAtAllTimes", o62)
property(o62, "ex:hasUnit", o22)
property(o55, "core:hasFunction", o63)
property(o63, "core:prescribedBy", o57)
property(o55, "core:hasComponentPartAtAllTimes", o64)
property(o64, "des:hasName", o65)
property(o55, "core:hasComponentPartAtAllTimes", o66)
property(o66, "des:hasName", o67)
property(o66, "core:prescribedBy", o68)
property(o68, "core:hasValueExpressionAtAllTimes", o69)
property(o69, "ex:hasUnit", o33)
property(o68, "core:hasValueExpressionAtAllTimes", o70)
property(o70, "ex:hasUnit", o33)
property(o55, "core:hasQuality", o71)
property(o66, "core:hasQuality", o72)
property(o2, "core:hasComponentPartAtAllTimes", o73)
property(o73, "des:hasName", o74)
property(o73, "core:prescribedBy", o75)
property(o75, "core:hasValueExpressionAtAllTimes", o76)
property(o76, "ex:hasUnit", o77)
property(o75, "core:hasValueExpressionAtAllTimes", o78)
property(o78, "ex:hasUnit", o77)
property(o73, "core:hasFunction", o79)
property(o79, "core:prescribedBy", o75)
property(o73, "core:hasComponentPartAtAllTimes", o80)
property(o80, "des:hasName", o81)
property(o73, "core:measuresAtSomeTime", o82)
property(o80, "core:hasQuality", o83)
property(o2, "core:hasComponentPartAtAllTimes", o84)
property(o84, "des:hasName", o85)
property(o84, "core:prescribedBy", o86)
property(o86, "core:hasValueExpressionAtAllTimes", o87)
property(o86, "core:hasValueExpressionAtAllTimes", o88)
property(o86, "core:hasValueExpressionAtAllTimes", o89)
property(o89, "ex:hasUnit", o90)
property(o86, "core:hasValueExpressionAtAllTimes", o91)
property(o91, "ex:hasUnit", o90)
property(o84, "core:hasFunction", o92)
property(o92, "core:prescribedBy", o86)
property(o84, "core:hasComponentPartAtAllTimes", o93)
property(o93, "des:hasName", o94)
property(o84, "core:hasQuality", o95)
property(o2, "core:hasComponentPartAtAllTimes", o96)
property(o96, "des:hasName", o97)
property(o96, "core:prescribedBy", o98)
property(o98, "core:hasValueExpressionAtAllTimes", o99)
property(o98, "core:hasValueExpressionAtAllTimes", o100)
property(o98, "core:hasValueExpressionAtAllTimes", o101)
property(o101, "ex:hasUnit", o90)
property(o98, "core:hasValueExpressionAtAllTimes", o102)
property(o102, "ex:hasUnit", o90)
property(o96, "core:hasFunction", o103)
property(o103, "core:prescribedBy", o98)
property(o96, "core:hasComponentPartAtAllTimes", o104)
property(o104, "des:hasName", o105)
property(o96, "core:hasQuality", o106)
property(o2, "core:hasComponentPartAtAllTimes", o107)
property(o107, "des:hasName", o108)
property(o107, "core:hasComponentPartAtAllTimes", o109)
property(o109, "des:hasName", o110)
property(o2, "core:hasComponentPartAtAllTimes", o111)
property(o111, "des:hasName", o112)
property(o2, "core:hasComponentPartAtAllTimes", o113)
property(o113, "des:hasName", o114)
property(o2, "core:hasComponentPartAtAllTimes", o115)
property(o115, "des:hasName", o116)
property(o2, "core:hasComponentPartAtAllTimes", o117)
property(o117, "des:hasName", o118)
property(o2, "core:hasComponentPartAtAllTimes", o119)
property(o119, "des:hasName", o120)
property(o119, "core:hasQuality", o121)
property(o2, "core:hasComponentPartAtAllTimes", o122)
property(o122, "des:hasName", o123)
property(o2, "core:hasComponentPartAtAllTimes", o124)
property(o124, "des:hasName", o125)
property(o2, "core:hasComponentPartAtAllTimes", o126)
property(o126, "des:hasName", o127)
property(o126, "core:hasQuality", o128)
property(o2, "core:hasComponentPartAtAllTimes", o129)
property(o129, "des:hasName", o130)
property(o2, "core:hasComponentPartAtAllTimes", o131)
property(o131, "des:hasName", o132)
property(o131, "core:hasQuality", o133)
property(o16, "ex:connectedTo", o131)
property(o16, "ex:connectedTo", o6)
property(o37, "ex:connectedTo", o6)
property(o37, "ex:connectedTo", o8)
property(o55, "ex:connectedTo", o8)
property(o55, "ex:connectedTo", o10)
property(o73, "ex:connectedTo", o10)
property(o84, "ex:connectedTo", o131)
property(o84, "ex:connectedTo", o14)
property(o96, "ex:connectedTo", o14)
property(o96, "ex:connectedTo", o12)
data(o2, "rdfs:label", "Mazak 317641 particular")
data(o3, "des:hasTextualName", "Mazak")
data(o6, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
data(o7, "des:hasTextualName", "X_AXIS")
data(o8, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
data(o9, "des:hasTextualName", "Y_AXIS")
data(o10, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
data(o11, "des:hasTextualName", "Z_AXIS")
data(o12, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
data(o13, "des:hasTextualName", "TABLE")
data(o14, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
data(o15, "des:hasTextualName", "TRUNDLE")
data(o16, "rdfs:label", "Mazak 317641 base X particular")
data(o17, "des:hasTextualName", "X")
data(o18, "rdfs:label", "Mazak800ibaseXDesign particular")
data(o19, "core:hasSimpleExpressionValue", "650.0")
data(o21, "core:hasSimpleExpressionValue", "7000.0")
data(o23, "core:hasSimpleExpressionValue", "0.0")
data(o24, "core:hasSimpleExpressionValue", "7000.0")
data(o25, "core:hasSimpleExpressionValue", "0.0")
data(o27, "rdfs:label", "Mazak 317641 base X Xballscrew particular")
data(o28, "des:hasTextualName", "Xballscrew")
data(o29, "rdfs:label", "Mazak 317641 base X Xmotor particular")
data(o30, "des:hasTextualName", "Xmotor")
data(o31, "rdfs:label", "Mazak800iMotorLINEAR_FORCE5200Design particular")
data(o32, "core:hasSimpleExpressionValue", "5200.0")
data(o34, "core:hasSimpleExpressionValue", "0.0")
data(o37, "rdfs:label", "Mazak 317641 base Y particular")
data(o38, "des:hasTextualName", "Y")
data(o39, "rdfs:label", "Mazak800ibaseYDesign particular")
data(o40, "core:hasSimpleExpressionValue", "550.0")
data(o41, "core:hasSimpleExpressionValue", "7000.0")
data(o42, "core:hasSimpleExpressionValue", "0.0")
data(o43, "core:hasSimpleExpressionValue", "7000.0")
data(o44, "core:hasSimpleExpressionValue", "0.0")
data(o46, "rdfs:label", "Mazak 317641 base Y Yballscrew particular")
data(o47, "des:hasTextualName", "Yballscrew")
data(o48, "rdfs:label", "Mazak 317641 base Y Ymotor particular")
data(o49, "des:hasTextualName", "Ymotor")
data(o50, "rdfs:label", "Mazak800iMotorLINEAR_FORCE5200Design particular")
data(o51, "core:hasSimpleExpressionValue", "5200.0")
data(o52, "core:hasSimpleExpressionValue", "0.0")
data(o55, "rdfs:label", "Mazak 317641 base Z particular")
data(o56, "des:hasTextualName", "Z")
data(o57, "rdfs:label", "Mazak800ibaseZDesign particular")
data(o58, "core:hasSimpleExpressionValue", "530.0")
data(o59, "core:hasSimpleExpressionValue", "7000.0")
data(o60, "core:hasSimpleExpressionValue", "0.0")
data(o61, "core:hasSimpleExpressionValue", "7000.0")
data(o62, "core:hasSimpleExpressionValue", "0.0")
data(o64, "rdfs:label", "Mazak 317641 base Z Zballscrew particular")
data(o65, "des:hasTextualName", "Zballscrew")
data(o66, "rdfs:label", "Mazak 317641 base Z Zmotor particular")
data(o67, "des:hasTextualName", "Zmotor")
data(o68, "rdfs:label", "Mazak800iMotorLINEAR_FORCE9600Design particular")
data(o69, "core:hasSimpleExpressionValue", "9600.0")
data(o70, "core:hasSimpleExpressionValue", "0.0")
data(o73, "rdfs:label", "Mazak 317641 base C1 particular")
data(o74, "des:hasTextualName", "C1")
data(o75, "rdfs:label", "Mazak800ibaseC1Design particular")
data(o76, "core:hasSimpleExpressionValue", "12000.0")
data(o78, "core:hasSimpleExpressionValue", "0.0")
data(o80, "rdfs:label", "Mazak 317641 base C1 Cmotor particular")
data(o81, "des:hasTextualName", "Cmotor")
data(o84, "rdfs:label", "Mazak 317641 base B particular")
data(o85, "des:hasTextualName", "B")
data(o86, "rdfs:label", "Mazak800ibaseBDesign particular")
data(o87, "core:hasSimpleExpressionValue", "120.0")
data(o88, "core:hasSimpleExpressionValue", "-30.0")
data(o89, "core:hasSimpleExpressionValue", "400.0")
data(o91, "core:hasSimpleExpressionValue", "0.0")
data(o93, "rdfs:label", "Mazak 317641 base B Bmotor particular")
data(o94, "des:hasTextualName", "Bmotor")
data(o96, "rdfs:label", "Mazak 317641 base C2 particular")
data(o97, "des:hasTextualName", "C2")
data(o98, "rdfs:label", "Mazak800ibaseC2Design particular")
data(o99, "core:hasSimpleExpressionValue", "360.0")
data(o100, "core:hasSimpleExpressionValue", "-360.0")
data(o101, "core:hasSimpleExpressionValue", "400.0")
data(o102, "core:hasSimpleExpressionValue", "0.0")
data(o104, "rdfs:label", "Mazak 317641 base C2 C2motor particular")
data(o105, "des:hasTextualName", "C2motor")
data(o107, "rdfs:label", "Mazak 317641 controller particular")
data(o108, "des:hasTextualName", "controller")
data(o109, "rdfs:label", "Mazak 317641 controller path particular")
data(o110, "des:hasTextualName", "path")
data(o111, "rdfs:label", "Mazak 317641 door particular")
data(o112, "des:hasTextualName", "door")
data(o113, "rdfs:label", "Mazak 317641 parts partocc particular")
data(o114, "des:hasTextualName", "partocc")
data(o115, "rdfs:label", "Mazak 317641 systems electric particular")
data(o116, "des:hasTextualName", "electric")
data(o117, "rdfs:label", "Mazak 317641 systems hydraulic particular")
data(o118, "des:hasTextualName", "hydraulic")
data(o119, "rdfs:label", "Mazak 317641 systems coolant particular")
data(o120, "des:hasTextualName", "coolant")
data(o122, "rdfs:label", "Mazak 317641 systems pneumatic particular")
data(o123, "des:hasTextualName", "pneumatic")
data(o124, "rdfs:label", "Mazak 317641 systems lubrication particular")
data(o125, "des:hasTextualName", "lubrication")
data(o126, "rdfs:label", "Mazak 317641 auxiliaries environmental particular")
data(o127, "des:hasTextualName", "environmental")
data(o129, "rdfs:label", "Mazak 317641 resources materials stock particular")
data(o130, "des:hasTextualName", "stock")
data(o131, "rdfs:label", "Mazak 317641 enclosure particular")
data(o132, "des:hasTextualName", "enclosure")
@enduml
