@startuml Mazak-c2-Cmotor
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak-c2-Cmotor

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:Mazak-c2-Cmotor, ex:Motor)
individual(o2, data:Mazak-c2-Cmotor-name, cmns-dsg:Name)
individual(o3, data:Mazak-c2, ex:RotaryMotionSystem)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, Cmotor)
property(o3, "bfo:has member part at some time", o1)
@enduml
