
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641systemslubrication

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641systemslubrication.html Mazak317641systemslubrication]], vendor:[[../Mazak.html#Mazak800isystemslubrication Mazak800isystemslubrication]])
individual(o1, data:Mazak317641systemslubricationEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o2, data:Mazak317641systemslubricationCapability, core:Capability)
individual(o3, data:name30, des:Name)
individual(o4, data:, owl:Thing)
individual(o5, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasRole", o1)
property(o0, "core:hasCapability", o2)
property(o0, "des:hasName", o3)
data(o3, "des:hasTextualName", "lubrication")
property(o4, "rdf:first", o0)
property(o5, "ex:hasComponent", o0)
@enduml
