
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseY

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o1, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o2, data:Mazak317641baseYLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:Mazak317641baseYVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseYVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseYVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak317641baseYVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o8, data:name11, des:Name)
individual(o9, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o10, data:mazak800imotorlinear_force5200design2, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o11, data:Mazak317641baseYTEMPERATURE, qualphys:Temperature)
individual(o12, data:name12, des:Name)
individual(o13, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o14, data:Mazak317641baseYPOSITION_ACTUAL, qualphys:Displacement)
individual(o15, data:name10, des:Name)
individual(o16, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o17, data:name2, des:Name)
individual(o18, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o19, data:name3, des:Name)
individual(o20, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "Mazak800ibaseYDesign particular")
property(o1, "core:hasValueExpressionAtSomeTime", o2)
property(o1, "core:hasValueExpressionAtSomeTime", o3)
property(o1, "core:hasValueExpressionAtSomeTime", o4)
property(o1, "core:hasValueExpressionAtSomeTime", o5)
property(o1, "core:hasValueExpressionAtSomeTime", o6)
property(o0, "core:hasComponentPartAtSomeTime", o7)
data(o7, "rdfs:label", "Mazak 317641 base Y Yballscrew particular")
property(o7, "des:hasName", o8)
property(o0, "core:hasComponentPartAtSomeTime", o9)
data(o9, "rdfs:label", "Mazak 317641 base Y Ymotor particular")
property(o9, "core:prescribedBy", o10)
property(o9, "core:hasQuality", o11)
property(o9, "des:hasName", o12)
property(o0, "core:hasFunction", o13)
property(o13, "core:prescribedBy", o1)
property(o0, "core:hasQuality", o14)
property(o0, "des:hasName", o15)
data(o15, "des:hasTextualName", "Y")
property(o0, "ex:connectedTo", o16)
data(o16, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o16, "des:hasName", o17)
property(o0, "ex:connectedTo", o18)
data(o18, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
property(o18, "des:hasName", o19)
property(o20, "core:hasComponentPartAtSomeTime", o0)
@enduml
