@startuml
skinparam linetype polyline
left to right direction
title Mazak-xaxism

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-xaxism.html data:Mazak-xaxism]]" as o1 #76608A {
 <back:#Green>type: ex:Structure</back> 
---
 }
object "data:Mazak-xaxism-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak.html data:Mazak]]" as o3 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
object "[[./Mazak-x.html data:Mazak-x]]" as o4 #76608A {
 <back:#Green>type: ex:LinearMotionSystem</back> 
---
 }
object "[[./Mazak-y.html data:Mazak-y]]" as o5 #76608A {
 <back:#Green>type: ex:LinearMotionSystem</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: X_AXIS
o3 --> o1 : obo:has member part at some time
o4 --> o1 : ex:joinedTo
o5 --> o1 : ex:joinedTo
@enduml
