@startuml
skinparam linetype polyline
left to right direction
object "[[./Mazak-pneumatic.html data:Mazak-pneumatic]]" as o1 {
 type = ex:PneumaticSystem
 }
object "data:Mazak-pneumatic-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./Mazak.html data:Mazak]]" as o3 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = pneumatic
o3 --> o1 : obo:has member part at some time
@enduml
