@startuml
skinparam linetype polyline
left to right direction
title Mazak-personnelm
object "[[./Mazak-personnelm.html data:Mazak-personnelm]]" as o1 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/Person core:Person]] 
}
object "data:Mazak-personnelm-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o3 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: personnel
o3 --> o1 : obo:has member part at some time
@enduml
