
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
individual(o1, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o2, data:name2, des:Name)
individual(o3, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o4, data:name3, des:Name)
individual(o5, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o6, data:name4, des:Name)
individual(o7, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o8, data:name5, des:Name)
individual(o9, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o10, data:name6, des:Name)
individual(o11, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o12, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o13, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800ibaseXXmotor Mazak800ibaseXXmotor]])
individual(o14, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o15, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o16, data:Mazak317641baseXPOSITION_ACTUAL, qualphys:Displacement)
individual(o17, data:name7, des:Name)
individual(o18, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o19, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o20, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o21, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800ibaseYYmotor Mazak800ibaseYYmotor]])
individual(o22, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o23, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o24, data:Mazak317641baseYPOSITION_ACTUAL, qualphys:Displacement)
individual(o25, data:name10, des:Name)
individual(o26, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o27, data:[[./Mazak317641baseZZballscrew.html Mazak317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o28, data:[[./Mazak317641baseZZmotor.html Mazak317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800ibaseZZmotor Mazak800ibaseZZmotor]])
individual(o29, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o30, data:Mazak317641baseZPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o31, data:Mazak317641baseZPOSITION_ACTUAL, qualphys:Displacement)
individual(o32, data:name13, des:Name)
individual(o33, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o34, data:[[./Mazak317641baseC1Cmotor.html Mazak317641baseC1Cmotor]], vendor:[[../Mazak.html#Mazak800ibaseC1Cmotor Mazak800ibaseC1Cmotor]])
individual(o35, data:mazak800ibasec1design1, vendor:[[../Mazak.html#Mazak800ibaseC1Design Mazak800ibaseC1Design]])
individual(o36, data:Mazak317641baseC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o37, data:Mazak317641baseC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o38, data:name16, des:Name)
individual(o39, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o40, data:[[./Mazak317641baseBBmotor.html Mazak317641baseBBmotor]], vendor:[[../Mazak.html#Mazak800ibaseBBmotor Mazak800ibaseBBmotor]])
individual(o41, data:mazak800ibasebdesign1, vendor:[[../Mazak.html#Mazak800ibaseBDesign Mazak800ibaseBDesign]])
individual(o42, data:Mazak317641baseBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o43, data:Mazak317641baseBANGLE_ACTUAL, qualphys:Angle)
individual(o44, data:name18, des:Name)
individual(o45, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o46, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o47, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o48, data:Mazak317641baseC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o49, data:Mazak317641baseC2ANGLE_ACTUAL, qualphys:Angle)
individual(o50, data:name20, des:Name)
individual(o51, data:[[./Mazak317641controller.html Mazak317641controller]], vendor:[[../Mazak.html#Mazak800icontroller Mazak800icontroller]])
individual(o52, data:[[./Mazak317641controllerpath.html Mazak317641controllerpath]], vendor:[[../Mazak.html#Mazak800icontrollerpath Mazak800icontrollerpath]])
individual(o53, data:name22, des:Name)
individual(o54, data:[[./Mazak317641door.html Mazak317641door]], vendor:[[../Mazak.html#Mazak800idoor Mazak800idoor]])
individual(o55, data:name24, des:Name)
individual(o56, data:[[./Mazak317641partspartocc.html Mazak317641partspartocc]], vendor:[[../Mazak.html#Mazak800ipartspartocc Mazak800ipartspartocc]])
individual(o57, data:name25, des:Name)
individual(o58, data:[[./Mazak317641systemselectric.html Mazak317641systemselectric]], vendor:[[../Mazak.html#Mazak800isystemselectric Mazak800isystemselectric]])
individual(o59, data:name26, des:Name)
individual(o60, data:[[./Mazak317641systemshydraulic.html Mazak317641systemshydraulic]], vendor:[[../Mazak.html#Mazak800isystemshydraulic Mazak800isystemshydraulic]])
individual(o61, data:name27, des:Name)
individual(o62, data:[[./Mazak317641systemscoolant.html Mazak317641systemscoolant]], vendor:[[../Mazak.html#Mazak800isystemscoolant Mazak800isystemscoolant]])
individual(o63, data:Mazak317641systemscoolantTEMPERATURE, qualphys:Temperature)
individual(o64, data:name28, des:Name)
individual(o65, data:[[./Mazak317641systemspneumatic.html Mazak317641systemspneumatic]], vendor:[[../Mazak.html#Mazak800isystemspneumatic Mazak800isystemspneumatic]])
individual(o66, data:name29, des:Name)
individual(o67, data:[[./Mazak317641systemslubrication.html Mazak317641systemslubrication]], vendor:[[../Mazak.html#Mazak800isystemslubrication Mazak800isystemslubrication]])
individual(o68, data:name30, des:Name)
individual(o69, data:[[./Mazak317641auxiliariesenvironmental.html Mazak317641auxiliariesenvironmental]], vendor:[[../Mazak.html#Mazak800iauxiliariesenvironmental Mazak800iauxiliariesenvironmental]])
individual(o70, data:Mazak317641auxiliariesenvironmentalTEMPERATURE, qualphys:Temperature)
individual(o71, data:name31, des:Name)
individual(o72, data:[[./Mazak317641resourcesmaterialsstock.html Mazak317641resourcesmaterialsstock]], vendor:[[../Mazak.html#Mazak800iresourcesmaterialsstock Mazak800iresourcesmaterialsstock]])
individual(o73, data:name32, des:Name)
individual(o74, data:Mazak317641enclosureTEMPERATURE, qualphys:Temperature)
individual(o75, data:name33, des:Name)
individual(o76, data:Mazak317641TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o77, data:Mazak317641MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o78, data:name1, des:Name)
property(o0, "core:hasComponentPartAtAllTimes", o1)
data(o1, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o1, "des:hasName", o2)
property(o0, "core:hasComponentPartAtAllTimes", o3)
data(o3, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
property(o3, "des:hasName", o4)
property(o0, "core:hasComponentPartAtAllTimes", o5)
data(o5, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
property(o5, "des:hasName", o6)
property(o0, "core:hasComponentPartAtAllTimes", o7)
data(o7, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
property(o7, "des:hasName", o8)
property(o0, "core:hasComponentPartAtAllTimes", o9)
data(o9, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
property(o9, "des:hasName", o10)
property(o0, "core:hasComponentPartAtAllTimes", o11)
data(o11, "rdfs:label", "Mazak 317641 base X particular")
property(o11, "core:hasComponentPartAtAllTimes", o12)
property(o11, "core:hasComponentPartAtAllTimes", o13)
property(o11, "core:prescribedBy", o14)
property(o11, "core:hasFunction", o15)
property(o11, "core:hasQuality", o16)
property(o11, "des:hasName", o17)
property(o11, "ex:connectedTo", o1)
property(o11, "ex:connectedTo", o18)
property(o0, "core:hasComponentPartAtAllTimes", o19)
data(o19, "rdfs:label", "Mazak 317641 base Y particular")
property(o19, "core:hasComponentPartAtAllTimes", o20)
property(o19, "core:hasComponentPartAtAllTimes", o21)
property(o19, "core:prescribedBy", o22)
property(o19, "core:hasFunction", o23)
property(o19, "core:hasQuality", o24)
property(o19, "des:hasName", o25)
property(o19, "ex:connectedTo", o1)
property(o19, "ex:connectedTo", o3)
property(o0, "core:hasComponentPartAtAllTimes", o26)
data(o26, "rdfs:label", "Mazak 317641 base Z particular")
property(o26, "core:hasComponentPartAtAllTimes", o27)
property(o26, "core:hasComponentPartAtAllTimes", o28)
property(o26, "core:prescribedBy", o29)
property(o26, "core:hasFunction", o30)
property(o26, "core:hasQuality", o31)
property(o26, "des:hasName", o32)
property(o26, "ex:connectedTo", o3)
property(o26, "ex:connectedTo", o5)
property(o0, "core:hasComponentPartAtAllTimes", o33)
data(o33, "rdfs:label", "Mazak 317641 base C1 particular")
property(o33, "core:hasComponentPartAtAllTimes", o34)
property(o33, "core:prescribedBy", o35)
property(o33, "core:measuresAtSomeTime", o36)
property(o33, "core:hasFunction", o37)
property(o33, "des:hasName", o38)
property(o33, "ex:connectedTo", o5)
property(o0, "core:hasComponentPartAtAllTimes", o39)
data(o39, "rdfs:label", "Mazak 317641 base B particular")
property(o39, "core:hasComponentPartAtAllTimes", o40)
property(o39, "core:prescribedBy", o41)
property(o39, "core:hasFunction", o42)
property(o39, "core:hasQuality", o43)
property(o39, "des:hasName", o44)
property(o39, "ex:connectedTo", o9)
property(o39, "ex:connectedTo", o18)
property(o0, "core:hasComponentPartAtAllTimes", o45)
data(o45, "rdfs:label", "Mazak 317641 base C2 particular")
property(o45, "core:hasComponentPartAtAllTimes", o46)
property(o45, "core:prescribedBy", o47)
property(o45, "core:hasFunction", o48)
property(o45, "core:hasQuality", o49)
property(o45, "des:hasName", o50)
property(o45, "ex:connectedTo", o7)
property(o45, "ex:connectedTo", o9)
property(o0, "core:hasComponentPartAtAllTimes", o51)
data(o51, "rdfs:label", "Mazak 317641 controller particular")
property(o51, "core:hasComponentPartAtAllTimes", o52)
property(o51, "des:hasName", o53)
property(o0, "core:hasComponentPartAtAllTimes", o54)
data(o54, "rdfs:label", "Mazak 317641 door particular")
property(o54, "des:hasName", o55)
property(o0, "core:hasComponentPartAtAllTimes", o56)
data(o56, "rdfs:label", "Mazak 317641 parts partocc particular")
property(o56, "des:hasName", o57)
property(o0, "core:hasComponentPartAtAllTimes", o58)
data(o58, "rdfs:label", "Mazak 317641 systems electric particular")
property(o58, "des:hasName", o59)
property(o0, "core:hasComponentPartAtAllTimes", o60)
data(o60, "rdfs:label", "Mazak 317641 systems hydraulic particular")
property(o60, "des:hasName", o61)
property(o0, "core:hasComponentPartAtAllTimes", o62)
data(o62, "rdfs:label", "Mazak 317641 systems coolant particular")
property(o62, "core:hasQuality", o63)
property(o62, "des:hasName", o64)
property(o0, "core:hasComponentPartAtAllTimes", o65)
data(o65, "rdfs:label", "Mazak 317641 systems pneumatic particular")
property(o65, "des:hasName", o66)
property(o0, "core:hasComponentPartAtAllTimes", o67)
data(o67, "rdfs:label", "Mazak 317641 systems lubrication particular")
property(o67, "des:hasName", o68)
property(o0, "core:hasComponentPartAtAllTimes", o69)
data(o69, "rdfs:label", "Mazak 317641 auxiliaries environmental particular")
property(o69, "core:hasQuality", o70)
property(o69, "des:hasName", o71)
property(o0, "core:hasComponentPartAtAllTimes", o72)
data(o72, "rdfs:label", "Mazak 317641 resources materials stock particular")
property(o72, "des:hasName", o73)
property(o0, "core:hasComponentPartAtAllTimes", o18)
data(o18, "rdfs:label", "Mazak 317641 enclosure particular")
property(o18, "core:hasQuality", o74)
property(o18, "des:hasName", o75)
property(o0, "core:hasCapability", o76)
property(o0, "core:hasFunction", o77)
property(o0, "des:hasName", o78)
data(o78, "des:hasTextualName", "Mazak")
@enduml
