
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseX

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o1, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o2, data:name8, des:Name)
individual(o3, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iLinearMotorLINEAR_FORCE_5200 Mazak800iLinearMotorLINEAR_FORCE_5200]])
individual(o4, data:mazak800ilinearmotorlinear_force_5200design1, vendor:[[../Mazak.html#Mazak800iLinearMotorLINEAR_FORCE_5200Design Mazak800iLinearMotorLINEAR_FORCE_5200Design]])
individual(o5, data:Mazak317641baseXTEMPERATURE, qualphys:Temperature)
individual(o6, data:name9, des:Name)
individual(o7, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o8, data:Mazak317641baseXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o9, data:Mazak317641baseXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o10, data:Mazak317641baseXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o11, data:Mazak317641baseXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o12, data:Mazak317641baseXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o13, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o14, data:Mazak317641baseXPOSITION_ACTUAL, qualphys:Displacement)
individual(o15, data:name7, des:Name)
individual(o16, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o17, data:Mazak317641enclosureTEMPERATURE, qualphys:Temperature)
individual(o18, data:name33, des:Name)
individual(o19, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o20, data:name2, des:Name)
individual(o21, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasComponentPartAtAllTimes", o1)
data(o1, "rdfs:label", "Mazak 317641 base X Xballscrew particular")
property(o1, "des:hasName", o2)
property(o0, "core:hasComponentPartAtAllTimes", o3)
data(o3, "rdfs:label", "Mazak 317641 base X Xmotor particular")
property(o3, "core:prescribedBy", o4)
property(o3, "core:hasQuality", o5)
property(o3, "des:hasName", o6)
property(o0, "core:prescribedBy", o7)
data(o7, "rdfs:label", "Mazak800ibaseXDesign particular")
property(o7, "core:hasValueExpressionAtAllTimes", o8)
property(o7, "core:hasValueExpressionAtAllTimes", o9)
property(o7, "core:hasValueExpressionAtAllTimes", o10)
property(o7, "core:hasValueExpressionAtAllTimes", o11)
property(o7, "core:hasValueExpressionAtAllTimes", o12)
property(o0, "core:hasFunction", o13)
property(o13, "core:prescribedBy", o7)
property(o0, "core:hasQuality", o14)
property(o0, "des:hasName", o15)
data(o15, "des:hasTextualName", "X")
property(o0, "ex:connectedTo", o16)
data(o16, "rdfs:label", "Mazak 317641 enclosure particular")
property(o16, "core:hasQuality", o17)
property(o16, "des:hasName", o18)
property(o0, "ex:connectedTo", o19)
data(o19, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o19, "des:hasName", o20)
property(o21, "core:hasComponentPartAtAllTimes", o0)
@enduml
