
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak_mstruct_Z_AXIS

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak_mstruct_Z_AXIS.html Mazak_mstruct_Z_AXIS]], vendor:[[../Mazak.html#MazakmstructZ_AXIS MazakmstructZ_AXIS]])
individual(o1, data:name4, des:Name)
individual(o2, data:[[./Mazak.html Mazak]], vendor:[[../Mazak.html#Mazak Mazak]])
individual(o3, data:[[./Mazak_base_Z.html Mazak_base_Z]], vendor:[[../Mazak.html#MazakbaseZ MazakbaseZ]])
individual(o4, data:[[./Mazak_base_C1.html Mazak_base_C1]], vendor:[[../Mazak.html#MazakbaseC1 MazakbaseC1]])
property(o0, "des:hasName", o1)
data(o1, "des:hasTextualName", "Z_AXIS")
property(o2, "core:hasComponentPartAtAllTimes", o0)
property(o3, "ex:joinedTo", o0)
property(o4, "ex:joinedTo", o0)
@enduml
