
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseC2

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o1, data:Mazak317641baseC2EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o2, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o3, data:Mazak317641baseC2AngleMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:Mazak317641baseC2AngleMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:Mazak317641baseC2TorqueMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:Mazak317641baseC2TorqueMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o8, data:Mazak317641baseC2C2motorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o9, data:name21, des:Name)
individual(o10, data:Mazak317641baseC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o11, data:Mazak317641baseC2ANGLE_ACTUAL, qualphys:Angle)
individual(o12, data:name20, des:Name)
individual(o13, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o14, data:Mazak317641mstructTRUNDLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o15, data:name6, des:Name)
individual(o16, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o17, data:Mazak317641mstructTABLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o18, data:name5, des:Name)
individual(o19, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasRole", o1)
property(o0, "core:prescribedBy", o2)
data(o2, "rdfs:label", "Mazak800ibaseC2Design particular")
property(o2, "core:hasValueExpressionAtSomeTime", o3)
property(o2, "core:hasValueExpressionAtSomeTime", o4)
property(o2, "core:hasValueExpressionAtSomeTime", o5)
property(o2, "core:hasValueExpressionAtSomeTime", o6)
property(o0, "core:hasComponentPartAtSomeTime", o7)
data(o7, "rdfs:label", "Mazak 317641 base C2 C2motor particular")
property(o7, "core:hasRole", o8)
property(o7, "des:hasName", o9)
property(o0, "core:hasFunction", o10)
property(o10, "core:prescribedBy", o2)
property(o0, "core:hasQuality", o11)
property(o0, "des:hasName", o12)
data(o12, "des:hasTextualName", "C2")
property(o0, "ex:connectedTo", o13)
data(o13, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
property(o13, "core:hasRole", o14)
property(o13, "des:hasName", o15)
property(o0, "ex:connectedTo", o16)
data(o16, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
property(o16, "core:hasRole", o17)
property(o16, "des:hasName", o18)
property(o19, "core:hasComponentPartAtSomeTime", o0)
@enduml
