
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title MazakFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, vendor:ontology1, owl:Ontology)
individual(o2, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
individual(o3, data:name1, des:Name)
individual(o4, data:Mazak317641Capability, core:Capability)
individual(o5, data:Mazak317641TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o6, data:Mazak317641MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o7, data:Mazak317641EquipmentRole, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o8, data:Mazak317641EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o9, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o10, data:name2, des:Name)
individual(o11, data:Mazak317641mstructX_AXISCapability, core:Capability)
individual(o12, data:Mazak317641mstructX_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o13, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o14, data:name3, des:Name)
individual(o15, data:Mazak317641mstructY_AXISCapability, core:Capability)
individual(o16, data:Mazak317641mstructY_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o17, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o18, data:name4, des:Name)
individual(o19, data:Mazak317641mstructZ_AXISCapability, core:Capability)
individual(o20, data:Mazak317641mstructZ_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o21, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o22, data:name5, des:Name)
individual(o23, data:Mazak317641mstructTABLECapability, core:Capability)
individual(o24, data:Mazak317641mstructTABLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o25, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o26, data:name6, des:Name)
individual(o27, data:Mazak317641mstructTRUNDLECapability, core:Capability)
individual(o28, data:Mazak317641mstructTRUNDLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o29, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o30, data:name7, des:Name)
individual(o31, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o32, data:Mazak317641baseXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o33, units:MilliM, units:Unit)
individual(o34, data:Mazak317641baseXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o35, units:MilliM-PER-SEC, units:Unit)
individual(o36, data:Mazak317641baseXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o37, data:Mazak317641baseXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o38, data:Mazak317641baseXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o39, data:Mazak317641baseXCapability, core:Capability)
individual(o40, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o41, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o42, data:name8, des:Name)
individual(o43, data:Mazak317641baseXXballscrewCapability, core:Capability)
individual(o44, data:Mazak317641baseXXballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o45, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o46, data:name9, des:Name)
individual(o47, data:mazak800imotorlinear_force5200design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o48, data:Mazak317641baseXXmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o49, units:N, units:Unit)
individual(o50, data:Mazak317641baseXXmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o51, data:Mazak317641baseXXmotorCapability, core:Capability)
individual(o52, data:Mazak317641baseXXmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o53, data:Mazak317641baseXPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o54, data:Mazak317641baseXTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o55, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o56, data:name10, des:Name)
individual(o57, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o58, data:Mazak317641baseYLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o59, data:Mazak317641baseYVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o60, data:Mazak317641baseYVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o61, data:Mazak317641baseYVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o62, data:Mazak317641baseYVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o63, data:Mazak317641baseYCapability, core:Capability)
individual(o64, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o65, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o66, data:name11, des:Name)
individual(o67, data:Mazak317641baseYYballscrewCapability, core:Capability)
individual(o68, data:Mazak317641baseYYballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o69, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o70, data:name12, des:Name)
individual(o71, data:mazak800imotorlinear_force5200design2, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200Design Mazak800iMotorLINEAR_FORCE5200Design]])
individual(o72, data:Mazak317641baseYYmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o73, data:Mazak317641baseYYmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o74, data:Mazak317641baseYYmotorCapability, core:Capability)
individual(o75, data:Mazak317641baseYYmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o76, data:Mazak317641baseYPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o77, data:Mazak317641baseYTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o78, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o79, data:name13, des:Name)
individual(o80, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o81, data:Mazak317641baseZLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o82, data:Mazak317641baseZVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o83, data:Mazak317641baseZVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o84, data:Mazak317641baseZVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o85, data:Mazak317641baseZVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o86, data:Mazak317641baseZCapability, core:Capability)
individual(o87, data:Mazak317641baseZPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o88, data:[[./Mazak317641baseZZballscrew.html Mazak317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o89, data:name14, des:Name)
individual(o90, data:Mazak317641baseZZballscrewCapability, core:Capability)
individual(o91, data:Mazak317641baseZZballscrewMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o92, data:[[./Mazak317641baseZZmotor.html Mazak317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600 Mazak800iMotorLINEAR_FORCE9600]])
individual(o93, data:name15, des:Name)
individual(o94, data:mazak800imotorlinear_force9600design1, vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600Design Mazak800iMotorLINEAR_FORCE9600Design]])
individual(o95, data:Mazak317641baseZZmotorLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o96, data:Mazak317641baseZZmotorLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o97, data:Mazak317641baseZZmotorCapability, core:Capability)
individual(o98, data:Mazak317641baseZZmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o99, data:Mazak317641baseZPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o100, data:Mazak317641baseZTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o101, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o102, data:name16, des:Name)
individual(o103, data:mazak800ibasec1design1, vendor:[[../Mazak.html#Mazak800ibaseC1Design Mazak800ibaseC1Design]])
individual(o104, data:Mazak317641baseC1Rotary_velocityMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o105, units:REV-PER-MIN, units:Unit)
individual(o106, data:Mazak317641baseC1Rotary_velocityMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o107, data:Mazak317641baseC1Capability, core:Capability)
individual(o108, data:Mazak317641baseC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o109, data:[[./Mazak317641baseC1Cmotor.html Mazak317641baseC1Cmotor]], vendor:[[../Mazak.html#Mazak800ibaseC1Cmotor Mazak800ibaseC1Cmotor]])
individual(o110, data:name17, des:Name)
individual(o111, data:Mazak317641baseC1CmotorCapability, core:Capability)
individual(o112, data:Mazak317641baseC1CmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o113, data:Mazak317641baseC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o114, data:Mazak317641baseC1TEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o115, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o116, data:name18, des:Name)
individual(o117, data:mazak800ibasebdesign1, vendor:[[../Mazak.html#Mazak800ibaseBDesign Mazak800ibaseBDesign]])
individual(o118, data:Mazak317641baseBAngleMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o119, units:DEG, units:Unit)
individual(o120, data:Mazak317641baseBAngleMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o121, data:Mazak317641baseBTorqueMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o122, units:N-M, units:Unit)
individual(o123, data:Mazak317641baseBTorqueMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o124, data:Mazak317641baseBCapability, core:Capability)
individual(o125, data:Mazak317641baseBIndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o126, data:[[./Mazak317641baseBBmotor.html Mazak317641baseBBmotor]], vendor:[[../Mazak.html#Mazak800ibaseBBmotor Mazak800ibaseBBmotor]])
individual(o127, data:name19, des:Name)
individual(o128, data:Mazak317641baseBBmotorCapability, core:Capability)
individual(o129, data:Mazak317641baseBBmotorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o130, data:Mazak317641baseBANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o131, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o132, data:name20, des:Name)
individual(o133, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o134, data:Mazak317641baseC2AngleMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o135, data:Mazak317641baseC2AngleMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o136, data:Mazak317641baseC2TorqueMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o137, data:Mazak317641baseC2TorqueMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o138, data:Mazak317641baseC2Capability, core:Capability)
individual(o139, data:Mazak317641baseC2IndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o140, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o141, data:name21, des:Name)
individual(o142, data:Mazak317641baseC2C2motorCapability, core:Capability)
individual(o143, data:Mazak317641baseC2C2motorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o144, data:Mazak317641baseC2ANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o145, data:[[./Mazak317641controller.html Mazak317641controller]], vendor:[[../Mazak.html#Mazak800icontroller Mazak800icontroller]])
individual(o146, data:name22, des:Name)
individual(o147, data:Mazak317641controllerCapability, core:Capability)
individual(o148, data:Mazak317641controllerEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o149, data:[[./Mazak317641controllerpath.html Mazak317641controllerpath]], vendor:[[../Mazak.html#Mazak800icontrollerpath Mazak800icontrollerpath]])
individual(o150, data:name23, des:Name)
individual(o151, data:Mazak317641controllerpathCapability, core:Capability)
individual(o152, data:Mazak317641controllerpathEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o153, data:Mazak317641controllerpathPATH_POSITION, ex:[[../Example.html#ThreeSpaceDisplacement ThreeSpaceDisplacement]])
individual(o154, data:Mazak317641controllerpathEXECUTION, ex:[[../Example.html#ExecutionState ExecutionState]])
individual(o155, data:Mazak317641controllerpathCONTROLLER_MODE, ex:[[../Example.html#ControllerMode ControllerMode]])
individual(o156, data:[[./Mazak317641door.html Mazak317641door]], vendor:[[../Mazak.html#Mazak800idoor Mazak800idoor]])
individual(o157, data:name24, des:Name)
individual(o158, data:Mazak317641doorCapability, core:Capability)
individual(o159, data:Mazak317641doorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o160, data:[[./Mazak317641partspartocc.html Mazak317641partspartocc]], vendor:[[../Mazak.html#Mazak800ipartspartocc Mazak800ipartspartocc]])
individual(o161, data:name25, des:Name)
individual(o162, data:Mazak317641partspartoccCapability, core:Capability)
individual(o163, data:Mazak317641partspartoccMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o164, data:[[./Mazak317641systemselectric.html Mazak317641systemselectric]], vendor:[[../Mazak.html#Mazak800isystemselectric Mazak800isystemselectric]])
individual(o165, data:name26, des:Name)
individual(o166, data:Mazak317641systemselectricCapability, core:Capability)
individual(o167, data:Mazak317641systemselectricEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o168, data:[[./Mazak317641systemshydraulic.html Mazak317641systemshydraulic]], vendor:[[../Mazak.html#Mazak800isystemshydraulic Mazak800isystemshydraulic]])
individual(o169, data:name27, des:Name)
individual(o170, data:Mazak317641systemshydraulicCapability, core:Capability)
individual(o171, data:Mazak317641systemshydraulicEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o172, data:[[./Mazak317641systemscoolant.html Mazak317641systemscoolant]], vendor:[[../Mazak.html#Mazak800isystemscoolant Mazak800isystemscoolant]])
individual(o173, data:name28, des:Name)
individual(o174, data:Mazak317641systemscoolantCapability, core:Capability)
individual(o175, data:Mazak317641systemscoolantEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o176, data:Mazak317641systemscoolantTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o177, data:[[./Mazak317641systemspneumatic.html Mazak317641systemspneumatic]], vendor:[[../Mazak.html#Mazak800isystemspneumatic Mazak800isystemspneumatic]])
individual(o178, data:name29, des:Name)
individual(o179, data:Mazak317641systemspneumaticCapability, core:Capability)
individual(o180, data:Mazak317641systemspneumaticEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o181, data:[[./Mazak317641systemslubrication.html Mazak317641systemslubrication]], vendor:[[../Mazak.html#Mazak800isystemslubrication Mazak800isystemslubrication]])
individual(o182, data:name30, des:Name)
individual(o183, data:Mazak317641systemslubricationCapability, core:Capability)
individual(o184, data:Mazak317641systemslubricationEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o185, data:Mazak317641auxiliariesenvironmental, vendor:[[../Mazak.html#Mazak800iauxiliariesenvironmental Mazak800iauxiliariesenvironmental]])
individual(o186, data:name31, des:Name)
individual(o187, data:Mazak317641auxiliariesenvironmentalCapability, core:Capability)
individual(o188, data:Mazak317641auxiliariesenvironmentalTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o189, data:[[./Mazak317641resourcesmaterialsstock.html Mazak317641resourcesmaterialsstock]], vendor:[[../Mazak.html#Mazak800iresourcesmaterialsstock Mazak800iresourcesmaterialsstock]])
individual(o190, data:name32, des:Name)
individual(o191, data:Mazak317641resourcesmaterialsstockCapability, core:Capability)
individual(o192, data:Mazak317641resourcesmaterialsstockMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o193, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o194, data:name33, des:Name)
individual(o195, data:Mazak317641enclosureCapability, core:Capability)
individual(o196, data:Mazak317641enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o197, data:Mazak317641enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
property(o0, "owl:imports", o1)
property(o2, "des:hasName", o3)
property(o2, "core:hasCapability", o4)
property(o2, "core:hasCapability", o5)
property(o2, "core:hasFunction", o6)
property(o2, "core:hasRole", o7)
property(o2, "core:hasRole", o8)
property(o2, "core:hasComponentPartAtSomeTime", o9)
property(o9, "des:hasName", o10)
property(o9, "core:hasCapability", o11)
property(o9, "core:hasRole", o12)
property(o2, "core:hasComponentPartAtSomeTime", o13)
property(o13, "des:hasName", o14)
property(o13, "core:hasCapability", o15)
property(o13, "core:hasRole", o16)
property(o2, "core:hasComponentPartAtSomeTime", o17)
property(o17, "des:hasName", o18)
property(o17, "core:hasCapability", o19)
property(o17, "core:hasRole", o20)
property(o2, "core:hasComponentPartAtSomeTime", o21)
property(o21, "des:hasName", o22)
property(o21, "core:hasCapability", o23)
property(o21, "core:hasRole", o24)
property(o2, "core:hasComponentPartAtSomeTime", o25)
property(o25, "des:hasName", o26)
property(o25, "core:hasCapability", o27)
property(o25, "core:hasRole", o28)
property(o2, "core:hasComponentPartAtSomeTime", o29)
property(o29, "des:hasName", o30)
property(o29, "core:prescribedBy", o31)
property(o31, "core:hasValueExpressionAtSomeTime", o32)
property(o32, "ex:hasUnit", o33)
property(o31, "core:hasValueExpressionAtSomeTime", o34)
property(o34, "ex:hasUnit", o35)
property(o31, "core:hasValueExpressionAtSomeTime", o36)
property(o36, "ex:hasUnit", o35)
property(o31, "core:hasValueExpressionAtSomeTime", o37)
property(o37, "ex:hasUnit", o35)
property(o31, "core:hasValueExpressionAtSomeTime", o38)
property(o38, "ex:hasUnit", o35)
property(o29, "core:hasCapability", o39)
property(o29, "core:hasFunction", o40)
property(o40, "core:prescribedBy", o31)
property(o29, "core:hasComponentPartAtSomeTime", o41)
property(o41, "des:hasName", o42)
property(o41, "core:hasCapability", o43)
property(o41, "core:hasRole", o44)
property(o29, "core:hasComponentPartAtSomeTime", o45)
property(o45, "des:hasName", o46)
property(o45, "core:prescribedBy", o47)
property(o47, "core:hasValueExpressionAtSomeTime", o48)
property(o48, "ex:hasUnit", o49)
property(o47, "core:hasValueExpressionAtSomeTime", o50)
property(o50, "ex:hasUnit", o49)
property(o45, "core:hasCapability", o51)
property(o45, "core:hasRole", o52)
property(o29, "core:hasQuality", o53)
property(o45, "core:hasQuality", o54)
property(o2, "core:hasComponentPartAtSomeTime", o55)
property(o55, "des:hasName", o56)
property(o55, "core:prescribedBy", o57)
property(o57, "core:hasValueExpressionAtSomeTime", o58)
property(o58, "ex:hasUnit", o33)
property(o57, "core:hasValueExpressionAtSomeTime", o59)
property(o59, "ex:hasUnit", o35)
property(o57, "core:hasValueExpressionAtSomeTime", o60)
property(o60, "ex:hasUnit", o35)
property(o57, "core:hasValueExpressionAtSomeTime", o61)
property(o61, "ex:hasUnit", o35)
property(o57, "core:hasValueExpressionAtSomeTime", o62)
property(o62, "ex:hasUnit", o35)
property(o55, "core:hasCapability", o63)
property(o55, "core:hasFunction", o64)
property(o64, "core:prescribedBy", o57)
property(o55, "core:hasComponentPartAtSomeTime", o65)
property(o65, "des:hasName", o66)
property(o65, "core:hasCapability", o67)
property(o65, "core:hasRole", o68)
property(o55, "core:hasComponentPartAtSomeTime", o69)
property(o69, "des:hasName", o70)
property(o69, "core:prescribedBy", o71)
property(o71, "core:hasValueExpressionAtSomeTime", o72)
property(o72, "ex:hasUnit", o49)
property(o71, "core:hasValueExpressionAtSomeTime", o73)
property(o73, "ex:hasUnit", o49)
property(o69, "core:hasCapability", o74)
property(o69, "core:hasRole", o75)
property(o55, "core:hasQuality", o76)
property(o69, "core:hasQuality", o77)
property(o2, "core:hasComponentPartAtSomeTime", o78)
property(o78, "des:hasName", o79)
property(o78, "core:prescribedBy", o80)
property(o80, "core:hasValueExpressionAtSomeTime", o81)
property(o81, "ex:hasUnit", o33)
property(o80, "core:hasValueExpressionAtSomeTime", o82)
property(o82, "ex:hasUnit", o35)
property(o80, "core:hasValueExpressionAtSomeTime", o83)
property(o83, "ex:hasUnit", o35)
property(o80, "core:hasValueExpressionAtSomeTime", o84)
property(o84, "ex:hasUnit", o35)
property(o80, "core:hasValueExpressionAtSomeTime", o85)
property(o85, "ex:hasUnit", o35)
property(o78, "core:hasCapability", o86)
property(o78, "core:hasFunction", o87)
property(o87, "core:prescribedBy", o80)
property(o78, "core:hasComponentPartAtSomeTime", o88)
property(o88, "des:hasName", o89)
property(o88, "core:hasCapability", o90)
property(o88, "core:hasRole", o91)
property(o78, "core:hasComponentPartAtSomeTime", o92)
property(o92, "des:hasName", o93)
property(o92, "core:prescribedBy", o94)
property(o94, "core:hasValueExpressionAtSomeTime", o95)
property(o95, "ex:hasUnit", o49)
property(o94, "core:hasValueExpressionAtSomeTime", o96)
property(o96, "ex:hasUnit", o49)
property(o92, "core:hasCapability", o97)
property(o92, "core:hasRole", o98)
property(o78, "core:hasQuality", o99)
property(o92, "core:hasQuality", o100)
property(o2, "core:hasComponentPartAtSomeTime", o101)
property(o101, "des:hasName", o102)
property(o101, "core:prescribedBy", o103)
property(o103, "core:hasValueExpressionAtSomeTime", o104)
property(o104, "ex:hasUnit", o105)
property(o103, "core:hasValueExpressionAtSomeTime", o106)
property(o106, "ex:hasUnit", o105)
property(o101, "core:hasCapability", o107)
property(o101, "core:hasFunction", o108)
property(o108, "core:prescribedBy", o103)
property(o101, "core:hasComponentPartAtSomeTime", o109)
property(o109, "des:hasName", o110)
property(o109, "core:hasCapability", o111)
property(o109, "core:hasRole", o112)
property(o101, "core:measuresAtSomeTime", o113)
property(o109, "core:hasQuality", o114)
property(o2, "core:hasComponentPartAtSomeTime", o115)
property(o115, "des:hasName", o116)
property(o115, "core:prescribedBy", o117)
property(o117, "core:hasValueExpressionAtSomeTime", o118)
property(o118, "ex:hasUnit", o119)
property(o117, "core:hasValueExpressionAtSomeTime", o120)
property(o120, "ex:hasUnit", o119)
property(o117, "core:hasValueExpressionAtSomeTime", o121)
property(o121, "ex:hasUnit", o122)
property(o117, "core:hasValueExpressionAtSomeTime", o123)
property(o123, "ex:hasUnit", o122)
property(o115, "core:hasCapability", o124)
property(o115, "core:hasFunction", o125)
property(o125, "core:prescribedBy", o117)
property(o115, "core:hasComponentPartAtSomeTime", o126)
property(o126, "des:hasName", o127)
property(o126, "core:hasCapability", o128)
property(o126, "core:hasRole", o129)
property(o115, "core:hasQuality", o130)
property(o2, "core:hasComponentPartAtSomeTime", o131)
property(o131, "des:hasName", o132)
property(o131, "core:prescribedBy", o133)
property(o133, "core:hasValueExpressionAtSomeTime", o134)
property(o134, "ex:hasUnit", o119)
property(o133, "core:hasValueExpressionAtSomeTime", o135)
property(o135, "ex:hasUnit", o119)
property(o133, "core:hasValueExpressionAtSomeTime", o136)
property(o136, "ex:hasUnit", o122)
property(o133, "core:hasValueExpressionAtSomeTime", o137)
property(o137, "ex:hasUnit", o122)
property(o131, "core:hasCapability", o138)
property(o131, "core:hasFunction", o139)
property(o139, "core:prescribedBy", o133)
property(o131, "core:hasComponentPartAtSomeTime", o140)
property(o140, "des:hasName", o141)
property(o140, "core:hasCapability", o142)
property(o140, "core:hasRole", o143)
property(o131, "core:hasQuality", o144)
property(o2, "core:hasComponentPartAtSomeTime", o145)
property(o145, "des:hasName", o146)
property(o145, "core:hasCapability", o147)
property(o145, "core:hasRole", o148)
property(o145, "core:hasComponentPartAtSomeTime", o149)
property(o149, "des:hasName", o150)
property(o149, "core:hasCapability", o151)
property(o149, "core:hasRole", o152)
property(o149, "core:hasQuality", o153)
property(o149, "core:observesAtSomeTime", o154)
property(o149, "core:observesAtSomeTime", o155)
property(o2, "core:hasComponentPartAtSomeTime", o156)
property(o156, "des:hasName", o157)
property(o156, "core:hasCapability", o158)
property(o156, "core:hasRole", o159)
property(o2, "core:hasComponentPartAtSomeTime", o160)
property(o160, "des:hasName", o161)
property(o160, "core:hasCapability", o162)
property(o160, "core:hasRole", o163)
property(o2, "core:hasComponentPartAtSomeTime", o164)
property(o164, "des:hasName", o165)
property(o164, "core:hasCapability", o166)
property(o164, "core:hasRole", o167)
property(o2, "core:hasComponentPartAtSomeTime", o168)
property(o168, "des:hasName", o169)
property(o168, "core:hasCapability", o170)
property(o168, "core:hasRole", o171)
property(o2, "core:hasComponentPartAtSomeTime", o172)
property(o172, "des:hasName", o173)
property(o172, "core:hasCapability", o174)
property(o172, "core:hasRole", o175)
property(o172, "core:hasQuality", o176)
property(o2, "core:hasComponentPartAtSomeTime", o177)
property(o177, "des:hasName", o178)
property(o177, "core:hasCapability", o179)
property(o177, "core:hasRole", o180)
property(o2, "core:hasComponentPartAtSomeTime", o181)
property(o181, "des:hasName", o182)
property(o181, "core:hasCapability", o183)
property(o181, "core:hasRole", o184)
property(o185, "des:hasName", o186)
property(o185, "core:hasCapability", o187)
property(o185, "core:hasQuality", o188)
property(o2, "core:hasComponentPartAtSomeTime", o189)
property(o189, "des:hasName", o190)
property(o189, "core:hasCapability", o191)
property(o189, "core:hasRole", o192)
property(o2, "core:hasComponentPartAtSomeTime", o193)
property(o193, "des:hasName", o194)
property(o193, "core:hasCapability", o195)
property(o193, "core:hasRole", o196)
property(o193, "core:hasQuality", o197)
property(o29, "ex:connectedTo", o193)
property(o29, "ex:connectedTo", o9)
property(o55, "ex:connectedTo", o9)
property(o55, "ex:connectedTo", o13)
property(o78, "ex:connectedTo", o13)
property(o78, "ex:connectedTo", o17)
property(o101, "ex:connectedTo", o17)
property(o115, "ex:connectedTo", o193)
property(o115, "ex:connectedTo", o25)
property(o131, "ex:connectedTo", o25)
property(o131, "ex:connectedTo", o21)
data(o2, "rdfs:label", "Mazak 317641 particular")
data(o3, "des:hasTextualName", "Mazak")
data(o9, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
data(o10, "des:hasTextualName", "X_AXIS")
data(o13, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
data(o14, "des:hasTextualName", "Y_AXIS")
data(o17, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
data(o18, "des:hasTextualName", "Z_AXIS")
data(o21, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
data(o22, "des:hasTextualName", "TABLE")
data(o25, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
data(o26, "des:hasTextualName", "TRUNDLE")
data(o29, "rdfs:label", "Mazak 317641 base X particular")
data(o30, "des:hasTextualName", "X")
data(o31, "rdfs:label", "Mazak800ibaseXDesign particular")
data(o32, "core:hasSimpleExpressionValue", "650.0")
data(o34, "core:hasSimpleExpressionValue", "7000.0")
data(o36, "core:hasSimpleExpressionValue", "0.0")
data(o37, "core:hasSimpleExpressionValue", "7000.0")
data(o38, "core:hasSimpleExpressionValue", "0.0")
data(o41, "rdfs:label", "Mazak 317641 base X Xballscrew particular")
data(o42, "des:hasTextualName", "Xballscrew")
data(o45, "rdfs:label", "Mazak 317641 base X Xmotor particular")
data(o46, "des:hasTextualName", "Xmotor")
data(o47, "rdfs:label", "Mazak800iMotorLINEAR_FORCE5200Design particular")
data(o48, "core:hasSimpleExpressionValue", "5200.0")
data(o50, "core:hasSimpleExpressionValue", "0.0")
data(o55, "rdfs:label", "Mazak 317641 base Y particular")
data(o56, "des:hasTextualName", "Y")
data(o57, "rdfs:label", "Mazak800ibaseYDesign particular")
data(o58, "core:hasSimpleExpressionValue", "550.0")
data(o59, "core:hasSimpleExpressionValue", "7000.0")
data(o60, "core:hasSimpleExpressionValue", "0.0")
data(o61, "core:hasSimpleExpressionValue", "7000.0")
data(o62, "core:hasSimpleExpressionValue", "0.0")
data(o65, "rdfs:label", "Mazak 317641 base Y Yballscrew particular")
data(o66, "des:hasTextualName", "Yballscrew")
data(o69, "rdfs:label", "Mazak 317641 base Y Ymotor particular")
data(o70, "des:hasTextualName", "Ymotor")
data(o71, "rdfs:label", "Mazak800iMotorLINEAR_FORCE5200Design particular")
data(o72, "core:hasSimpleExpressionValue", "5200.0")
data(o73, "core:hasSimpleExpressionValue", "0.0")
data(o78, "rdfs:label", "Mazak 317641 base Z particular")
data(o79, "des:hasTextualName", "Z")
data(o80, "rdfs:label", "Mazak800ibaseZDesign particular")
data(o81, "core:hasSimpleExpressionValue", "530.0")
data(o82, "core:hasSimpleExpressionValue", "7000.0")
data(o83, "core:hasSimpleExpressionValue", "0.0")
data(o84, "core:hasSimpleExpressionValue", "7000.0")
data(o85, "core:hasSimpleExpressionValue", "0.0")
data(o88, "rdfs:label", "Mazak 317641 base Z Zballscrew particular")
data(o89, "des:hasTextualName", "Zballscrew")
data(o92, "rdfs:label", "Mazak 317641 base Z Zmotor particular")
data(o93, "des:hasTextualName", "Zmotor")
data(o94, "rdfs:label", "Mazak800iMotorLINEAR_FORCE9600Design particular")
data(o95, "core:hasSimpleExpressionValue", "9600.0")
data(o96, "core:hasSimpleExpressionValue", "0.0")
data(o101, "rdfs:label", "Mazak 317641 base C1 particular")
data(o102, "des:hasTextualName", "C1")
data(o103, "rdfs:label", "Mazak800ibaseC1Design particular")
data(o104, "core:hasSimpleExpressionValue", "12000.0")
data(o106, "core:hasSimpleExpressionValue", "0.0")
data(o109, "rdfs:label", "Mazak 317641 base C1 Cmotor particular")
data(o110, "des:hasTextualName", "Cmotor")
data(o115, "rdfs:label", "Mazak 317641 base B particular")
data(o116, "des:hasTextualName", "B")
data(o117, "rdfs:label", "Mazak800ibaseBDesign particular")
data(o118, "core:hasSimpleExpressionValue", "120.0")
data(o120, "core:hasSimpleExpressionValue", "-30.0")
data(o121, "core:hasSimpleExpressionValue", "400.0")
data(o123, "core:hasSimpleExpressionValue", "0.0")
data(o126, "rdfs:label", "Mazak 317641 base B Bmotor particular")
data(o127, "des:hasTextualName", "Bmotor")
data(o131, "rdfs:label", "Mazak 317641 base C2 particular")
data(o132, "des:hasTextualName", "C2")
data(o133, "rdfs:label", "Mazak800ibaseC2Design particular")
data(o134, "core:hasSimpleExpressionValue", "360.0")
data(o135, "core:hasSimpleExpressionValue", "-360.0")
data(o136, "core:hasSimpleExpressionValue", "400.0")
data(o137, "core:hasSimpleExpressionValue", "0.0")
data(o140, "rdfs:label", "Mazak 317641 base C2 C2motor particular")
data(o141, "des:hasTextualName", "C2motor")
data(o145, "rdfs:label", "Mazak 317641 controller particular")
data(o146, "des:hasTextualName", "controller")
data(o149, "rdfs:label", "Mazak 317641 controller path particular")
data(o150, "des:hasTextualName", "path")
data(o156, "rdfs:label", "Mazak 317641 door particular")
data(o157, "des:hasTextualName", "door")
data(o160, "rdfs:label", "Mazak 317641 parts partocc particular")
data(o161, "des:hasTextualName", "partocc")
data(o164, "rdfs:label", "Mazak 317641 systems electric particular")
data(o165, "des:hasTextualName", "electric")
data(o168, "rdfs:label", "Mazak 317641 systems hydraulic particular")
data(o169, "des:hasTextualName", "hydraulic")
data(o172, "rdfs:label", "Mazak 317641 systems coolant particular")
data(o173, "des:hasTextualName", "coolant")
data(o177, "rdfs:label", "Mazak 317641 systems pneumatic particular")
data(o178, "des:hasTextualName", "pneumatic")
data(o181, "rdfs:label", "Mazak 317641 systems lubrication particular")
data(o182, "des:hasTextualName", "lubrication")
data(o185, "rdfs:label", "Mazak 317641 auxiliaries environmental particular")
data(o186, "des:hasTextualName", "environmental")
data(o189, "rdfs:label", "Mazak 317641 resources materials stock particular")
data(o190, "des:hasTextualName", "stock")
data(o193, "rdfs:label", "Mazak 317641 enclosure particular")
data(o194, "des:hasTextualName", "enclosure")
@enduml
