
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641baseC2

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o1, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o2, data:Mazak317641baseC2AngleMaximum, _:ValueExpression)
individual(o3, data:Mazak317641baseC2AngleMinimum, _:ValueExpression)
individual(o4, data:Mazak317641baseC2TorqueMaximum, _:ValueExpression)
individual(o5, data:Mazak317641baseC2TorqueMinimum, _:ValueExpression)
individual(o6, data:Mazak317641baseC2Capability, _:Capability)
individual(o7, data:Mazak317641baseC2IndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o8, data:Mazak317641baseC2ANGLE_ACTUAL, _:[[../MTConnect.html#Angle Angle]])
individual(o9, data:name20, des:Name)
individual(o10, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o11, data:Mazak317641mstructTRUNDLEMaterialArtifactRole, _:[[../MTConnect.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o12, data:Mazak317641mstructTRUNDLECapability, _:Capability)
individual(o13, data:name6, des:Name)
individual(o14, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o15, data:Mazak317641mstructTABLEMaterialArtifactRole, _:[[../MTConnect.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o16, data:Mazak317641mstructTABLECapability, _:Capability)
individual(o17, data:name5, des:Name)
individual(o18, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o19, data:Mazak317641baseC2C2motorMaterialArtifactRole, _:[[../MTConnect.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o20, data:Mazak317641baseC2C2motorCapability, _:Capability)
individual(o21, data:name21, des:Name)
individual(o22, data:, owl:Thing)
individual(o23, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "_:prescribedBy", o1)
data(o1, "rdfs:label", "Mazak800ibaseC2Design particular")
property(o1, "_:hasValueExpressionAtSomeTime", o2)
property(o1, "_:hasValueExpressionAtSomeTime", o3)
property(o1, "_:hasValueExpressionAtSomeTime", o4)
property(o1, "_:hasValueExpressionAtSomeTime", o5)
property(o0, "_:hasCapability", o6)
property(o0, "_:hasFunction", o7)
property(o7, "_:prescribedBy", o1)
property(o0, "_:hasQuality", o8)
property(o0, "des:hasName", o9)
data(o9, "des:hasTextualName", "C2")
property(o0, "_:connectedTo", o10)
data(o10, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
property(o10, "_:hasRole", o11)
property(o10, "_:hasCapability", o12)
property(o10, "des:hasName", o13)
property(o0, "_:connectedTo", o14)
data(o14, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
property(o14, "_:hasRole", o15)
property(o14, "_:hasCapability", o16)
property(o14, "des:hasName", o17)
property(o0, "_:hasComponent", o18)
data(o18, "rdfs:label", "Mazak 317641 base C2 C2motor particular")
property(o18, "_:hasRole", o19)
property(o18, "_:hasCapability", o20)
property(o18, "des:hasName", o21)
property(o22, "rdf:first", o0)
property(o23, "_:hasComponent", o0)
@enduml
