@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-enclosurem

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, vendor:MazakEnclosureenclosure, owl:Class)
individual(o2, ex:Structure)
individual(o3, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], vendor:MazakEnclosureenclosure)
individual(o4, data:Mazak-enclosurem-name, cmns-dsg:Name)
individual(o5, data:Mazak-enclosurem-temperature, qp:Temperature)
individual(o6, data:[[./Mazak.html Mazak]], vendor:MazakDeviceMazak)
individual(o7, data:[[./Mazak-x.html Mazak-x]], vendor:MazakLinearX)
individual(o8, data:[[./Mazak-br.html Mazak-br]], vendor:MazakRotaryB)
property(o1, rdfs:subClassOf, o2)
property(o3, cmns-dsg:hasName, o4)
data(o4, cmns-dsg:hasTextualName, enclosure)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o5)
property(o6, "bfo:has member part at some time", o3)
property(o7, ex:joinedTo, o3)
property(o8, ex:joinedTo, o3)
@enduml
