@startuml
skinparam linetype polyline
left to right direction
title Mazak-z-Zballscrew
object "[[./Mazak-z-Zballscrew.html data:Mazak-z-Zballscrew]]" as o1 {
 type: ex:Ballscrew 
}
object "data:Mazak-z-Zballscrew-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak-z.html data:Mazak-z]]" as o3 {
 type: ex:LinearMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Zballscrew
o3 --> o1 : obo:has member part at some time
@enduml
