
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak_auxiliaries_environmental

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak_auxiliaries_environmental.html Mazak_auxiliaries_environmental]], vendor:[[../Mazak.html#Mazakauxiliariesenvironmental Mazakauxiliariesenvironmental]])
individual(o1, data:Mazak_auxiliaries_environmentalTEMPERATURE, qualphys:Temperature)
individual(o2, data:name31, des:Name)
individual(o3, data:[[./Mazak.html Mazak]], vendor:[[../Mazak.html#Mazak Mazak]])
property(o0, "core:hasQuality", o1)
property(o0, "des:hasName", o2)
data(o2, "des:hasTextualName", "environmental")
property(o3, "bfo:has_member_part_at_some_time", o0)
@enduml
