@startuml Mazak
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title Mazak

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
oIndividual(data:Mazak, ex:Machine)
oIndividual(data:Mazak-name, cmns-dsg:Name)
oIndividual(data:Mazak-function, ex:MillingCapability)
oIndividual(data:Mazak-capability, ex:TurningCapability)
oIndividual(data:Mazak-role, [[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole core:EquipmentRole]])
oIndividual(data:Mazak-xaxism, ex:Structure)
oIndividual(data:Mazak-xaxism-name, cmns-dsg:Name)
oIndividual(data:Mazak-yaxism, ex:Structure)
oIndividual(data:Mazak-yaxism-name, cmns-dsg:Name)
oIndividual(data:Mazak-zaxis, ex:Structure)
oIndividual(data:Mazak-zaxis-name, cmns-dsg:Name)
oIndividual(data:Mazak-table, ex:Structure)
oIndividual(data:Mazak-table-name, cmns-dsg:Name)
oIndividual(data:Mazak-trundle, ex:Structure)
oIndividual(data:Mazak-trundle-name, cmns-dsg:Name)
oIndividual(data:Mazak-x, ex:LinearMotionSystem)
oIndividual(data:Mazak-x-name, cmns-dsg:Name)
oIndividual(data:Mazak-x-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-enclosurem, ex:Structure)
oIndividual(data:Mazak-x-function, ex:PrismaticMotionCapability)
oIndividual(data:Mazak-x-position-actual, qp:Displacement)
oIndividual(data:Mazak-x-Xballscrew, ex:Ballscrew)
oIndividual(data:Mazak-x-Xmotor, ex:Motor)
oIndividual(data:Mazak-y, ex:LinearMotionSystem)
oIndividual(data:Mazak-y-name, cmns-dsg:Name)
oIndividual(data:Mazak-y-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-y-function, ex:PrismaticMotionCapability)
oIndividual(data:Mazak-y-position-actual, qp:Displacement)
oIndividual(data:Mazak-y-Yballscrew, ex:Ballscrew)
oIndividual(data:Mazak-y-Ymotor, ex:Motor)
oIndividual(data:Mazak-z, ex:LinearMotionSystem)
oIndividual(data:Mazak-z-name, cmns-dsg:Name)
oIndividual(data:Mazak-z-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-z-function, ex:PrismaticMotionCapability)
oIndividual(data:Mazak-z-position-actual, qp:Displacement)
oIndividual(data:Mazak-z-Zballscrew, ex:Ballscrew)
oIndividual(data:Mazak-z-Zmotor, ex:Motor)
oIndividual(data:Mazak-c, ex:RotaryMotionSystem)
oIndividual(data:Mazak-c-name, cmns-dsg:Name)
oIndividual(data:Mazak-c-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-c-function, ex:ContinuousMotionCapability)
oIndividual(data:Mazak-c-rotary_velocity-actual, qp:Speed)
oIndividual(data:Mazak-c-C2motor, ex:Motor)
oIndividual(data:Mazak-br, ex:RotaryMotionSystem)
oIndividual(data:Mazak-br-name, cmns-dsg:Name)
oIndividual(data:Mazak-br-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-br-function, ex:RevoluteMotionCapability)
oIndividual(data:Mazak-br-angle-actual, qp:Angle)
oIndividual(data:Mazak-br-Bmotor, ex:Motor)
oIndividual(data:Mazak-c2, ex:RotaryMotionSystem)
oIndividual(data:Mazak-c2-name, cmns-dsg:Name)
oIndividual(data:Mazak-c2-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
oIndividual(data:Mazak-c2-function, ex:RevoluteMotionCapability)
oIndividual(data:Mazak-c2-angle-actual, qp:Angle)
oIndividual(data:Mazak-c2-Cmotor, ex:Motor)
oIndividual(data:Mazak-cont, ex:ControlSystem)
oIndividual(data:Mazak-cont-name, cmns-dsg:Name)
oIndividual(data:Mazak-cont-path1, ex:ControlSystemPath)
oIndividual(data:Mazak-door1, "bfo:object")
oIndividual(data:Mazak-door1-name, cmns-dsg:Name)
oIndividual(data:Mazak-partocc, ex:Part)
oIndividual(data:Mazak-partocc-name, cmns-dsg:Name)
oIndividual(data:Mazak-elec, ex:ElectricalSystem)
oIndividual(data:Mazak-elec-name, cmns-dsg:Name)
oIndividual(data:Mazak-hydraulic, ex:HydraulicSystem)
oIndividual(data:Mazak-hydraulic-name, cmns-dsg:Name)
oIndividual(data:Mazak-coolant, "bfo:object")
oIndividual(data:Mazak-coolant-name, cmns-dsg:Name)
oIndividual(data:Mazak-coolant-temperature, qp:Temperature)
oIndividual(data:Mazak-pneumatic, ex:PneumaticSystem)
oIndividual(data:Mazak-pneumatic-name, cmns-dsg:Name)
oIndividual(data:Mazak-lubrication, ex:LubricationSystem)
oIndividual(data:Mazak-lubrication-name, cmns-dsg:Name)
oIndividual(data:Mazak-personnelm, [[https://spec.industrialontologies.org/ontology/core/Core/Person core:Person]])
oIndividual(data:Mazak-personnelm-name, cmns-dsg:Name)
oIndividual(data:Mazak-procstock, ex:Stock)
oIndividual(data:Mazak-procstock-name, cmns-dsg:Name)
oIndividual(data:Mazak-enclosurem-name, cmns-dsg:Name)
oIndividual(data:Mazak-enclosurem-temperature, qp:Temperature)
property(data:Mazak, cmns-dsg:hasName, data:Mazak-name, down)
data(data:Mazak-name, cmns-dsg:hasTextualName, Mazak)
property(data:Mazak, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-function, down)
property(data:Mazak, [[https://spec.industrialontologies.org/ontology/core/Core/hasCapability core:hasCapability]], data:Mazak-capability, down)
property(data:Mazak, [[https://spec.industrialontologies.org/ontology/core/Core/hasRole core:hasRole]], data:Mazak-role, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-xaxism, down)
property(data:Mazak-xaxism, cmns-dsg:hasName, data:Mazak-xaxism-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-yaxism, down)
property(data:Mazak-yaxism, cmns-dsg:hasName, data:Mazak-yaxism-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-zaxis, down)
property(data:Mazak-zaxis, cmns-dsg:hasName, data:Mazak-zaxis-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-table, down)
property(data:Mazak-table, cmns-dsg:hasName, data:Mazak-table-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-trundle, down)
property(data:Mazak-trundle, cmns-dsg:hasName, data:Mazak-trundle-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-x, down)
property(data:Mazak-x, cmns-dsg:hasName, data:Mazak-x-name, down)
property(data:Mazak-x, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-x-spec, down)
property(data:Mazak-x, ex:joinedTo, data:Mazak-enclosurem, down)
property(data:Mazak-x, ex:joinedTo, data:Mazak-xaxism, down)
property(data:Mazak-x, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-x-function, down)
property(data:Mazak-x, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-x-position-actual, down)
property(data:Mazak-x, "bfo:has member part at some time", data:Mazak-x-Xballscrew, down)
property(data:Mazak-x, "bfo:has member part at some time", data:Mazak-x-Xmotor, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-y, down)
property(data:Mazak-y, cmns-dsg:hasName, data:Mazak-y-name, down)
property(data:Mazak-y, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-y-spec, down)
property(data:Mazak-y, ex:joinedTo, data:Mazak-xaxism, down)
property(data:Mazak-y, ex:joinedTo, data:Mazak-yaxism, down)
property(data:Mazak-y, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-y-function, down)
property(data:Mazak-y, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-y-position-actual, down)
property(data:Mazak-y, "bfo:has member part at some time", data:Mazak-y-Yballscrew, down)
property(data:Mazak-y, "bfo:has member part at some time", data:Mazak-y-Ymotor, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-z, down)
property(data:Mazak-z, cmns-dsg:hasName, data:Mazak-z-name, down)
property(data:Mazak-z, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-z-spec, down)
property(data:Mazak-z, ex:joinedTo, data:Mazak-yaxism, down)
property(data:Mazak-z, ex:joinedTo, data:Mazak-zaxis, down)
property(data:Mazak-z, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-z-function, down)
property(data:Mazak-z, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-z-position-actual, down)
property(data:Mazak-z, "bfo:has member part at some time", data:Mazak-z-Zballscrew, down)
property(data:Mazak-z, "bfo:has member part at some time", data:Mazak-z-Zmotor, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-c, down)
property(data:Mazak-c, cmns-dsg:hasName, data:Mazak-c-name, down)
property(data:Mazak-c, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-c-spec, down)
property(data:Mazak-c, ex:joinedTo, data:Mazak-zaxis, down)
property(data:Mazak-c, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-c-function, down)
property(data:Mazak-c, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-c-rotary_velocity-actual, down)
property(data:Mazak-c, "bfo:has member part at some time", data:Mazak-c-C2motor, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-br, down)
property(data:Mazak-br, cmns-dsg:hasName, data:Mazak-br-name, down)
property(data:Mazak-br, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-br-spec, down)
property(data:Mazak-br, ex:joinedTo, data:Mazak-enclosurem, down)
property(data:Mazak-br, ex:joinedTo, data:Mazak-trundle, down)
property(data:Mazak-br, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-br-function, down)
property(data:Mazak-br, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-br-angle-actual, down)
property(data:Mazak-br, "bfo:has member part at some time", data:Mazak-br-Bmotor, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-c2, down)
property(data:Mazak-c2, cmns-dsg:hasName, data:Mazak-c2-name, down)
property(data:Mazak-c2, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], data:Mazak-c2-spec, down)
property(data:Mazak-c2, ex:joinedTo, data:Mazak-trundle, down)
property(data:Mazak-c2, ex:joinedTo, data:Mazak-table, down)
property(data:Mazak-c2, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], data:Mazak-c2-function, down)
property(data:Mazak-c2, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-c2-angle-actual, down)
property(data:Mazak-c2, "bfo:has member part at some time", data:Mazak-c2-Cmotor, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-cont, down)
property(data:Mazak-cont, cmns-dsg:hasName, data:Mazak-cont-name, down)
property(data:Mazak-cont, "bfo:has member part at some time", data:Mazak-cont-path1, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-door1, down)
property(data:Mazak-door1, cmns-dsg:hasName, data:Mazak-door1-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-partocc, down)
property(data:Mazak-partocc, cmns-dsg:hasName, data:Mazak-partocc-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-elec, down)
property(data:Mazak-elec, cmns-dsg:hasName, data:Mazak-elec-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-hydraulic, down)
property(data:Mazak-hydraulic, cmns-dsg:hasName, data:Mazak-hydraulic-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-coolant, down)
property(data:Mazak-coolant, cmns-dsg:hasName, data:Mazak-coolant-name, down)
property(data:Mazak-coolant, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-coolant-temperature, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-pneumatic, down)
property(data:Mazak-pneumatic, cmns-dsg:hasName, data:Mazak-pneumatic-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-lubrication, down)
property(data:Mazak-lubrication, cmns-dsg:hasName, data:Mazak-lubrication-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-personnelm, down)
property(data:Mazak-personnelm, cmns-dsg:hasName, data:Mazak-personnelm-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-procstock, down)
property(data:Mazak-procstock, cmns-dsg:hasName, data:Mazak-procstock-name, down)
property(data:Mazak, "bfo:has member part at some time", data:Mazak-enclosurem, down)
property(data:Mazak-enclosurem, cmns-dsg:hasName, data:Mazak-enclosurem-name, down)
property(data:Mazak-enclosurem, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], data:Mazak-enclosurem-temperature, down)
@enduml
