
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title MazakTopo

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o1, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o2, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o3, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o4, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o5, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o6, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o7, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o8, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o9, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o10, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o11, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
property(o0, "ex:connectedTo", o1)
property(o0, "ex:connectedTo", o2)
property(o3, "ex:connectedTo", o2)
property(o3, "ex:connectedTo", o4)
property(o5, "ex:connectedTo", o4)
property(o5, "ex:connectedTo", o6)
property(o7, "ex:connectedTo", o6)
property(o8, "ex:connectedTo", o1)
property(o8, "ex:connectedTo", o9)
property(o10, "ex:connectedTo", o9)
property(o10, "ex:connectedTo", o11)
@enduml
