@startuml
skinparam linetype polyline
left to right direction
title Mazak-door1
object "[[./Mazak-door1.html data:Mazak-door1]]" as o1 {
 type: obo:object 
}
object "data:Mazak-door1-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o3 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: door
o3 --> o1 : obo:has member part at some time
@enduml
