
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641controller

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641controller.html Mazak317641controller]], vendor:[[../Mazak.html#Mazak800icontroller Mazak800icontroller]])
individual(o1, data:Mazak317641controllerEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o2, data:Mazak317641controllerCapability, core:Capability)
individual(o3, data:[[./Mazak317641controllerpath.html Mazak317641controllerpath]], vendor:[[../Mazak.html#Mazak800icontrollerpath Mazak800icontrollerpath]])
individual(o4, data:Mazak317641controllerpathEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o5, data:Mazak317641controllerpathCapability, core:Capability)
individual(o6, data:Mazak317641controllerpathPATH_POSITION, ex:[[../Example.html#ThreeSpaceDisplacement ThreeSpaceDisplacement]])
individual(o7, data:Mazak317641controllerpathEXECUTION, ex:[[../Example.html#ExecutionState ExecutionState]])
individual(o8, data:Mazak317641controllerpathCONTROLLER_MODE, ex:[[../Example.html#ControllerMode ControllerMode]])
individual(o9, data:name23, des:Name)
individual(o10, data:name22, des:Name)
individual(o11, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
property(o0, "core:hasRole", o1)
property(o0, "core:hasCapability", o2)
property(o0, "core:hasComponentPartAtSomeTime", o3)
data(o3, "rdfs:label", "Mazak 317641 controller path particular")
property(o3, "core:hasRole", o4)
property(o3, "core:hasCapability", o5)
property(o3, "core:hasQuality", o6)
property(o3, "core:observesAtSomeTime", o7)
property(o3, "core:observesAtSomeTime", o8)
property(o3, "des:hasName", o9)
property(o0, "des:hasName", o10)
data(o10, "des:hasTextualName", "controller")
property(o11, "core:hasComponentPartAtSomeTime", o0)
@enduml
