@startuml
skinparam linetype polyline
left to right direction
title Mazak-lubrication
object "[[./Mazak-lubrication.html data:Mazak-lubrication]]" as o1 {
 type: ex:LubricationSystem 
}
object "data:Mazak-lubrication-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o3 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: lubrication
o3 --> o1 : obo:has member part at some time
@enduml
