@startuml
skinparam linetype polyline
left to right direction
title Mazak-cont

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./Mazak-cont.html data:Mazak-cont]]" as o1 #76608A {
 <back:#Green>type: ex:ControlSystem</back> 
---
 }
object "data:Mazak-cont-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak-cont-path1.html data:Mazak-cont-path1]]" as o3 #76608A {
 <back:#Green>type: ex:ControlSystemPath</back> 
---
 }
object "data:Mazak-cont-path1-name" as o4 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./Mazak.html data:Mazak]]" as o5 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: controller
o1 --> o3 : obo:has member part at some time
o3 --> o4 : cmns-dsg:hasName
o5 --> o1 : obo:has member part at some time
@enduml
