
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
individual(o1, data:Mazak317641EquipmentRole, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o2, data:Mazak317641EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o3, data:Mazak317641Capability, core:Capability)
individual(o4, data:name1, des:Name)
individual(o5, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o6, data:Mazak317641mstructX_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o7, data:Mazak317641mstructX_AXISCapability, core:Capability)
individual(o8, data:name2, des:Name)
individual(o9, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o10, data:Mazak317641mstructY_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o11, data:Mazak317641mstructY_AXISCapability, core:Capability)
individual(o12, data:name3, des:Name)
individual(o13, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o14, data:Mazak317641mstructZ_AXISMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o15, data:Mazak317641mstructZ_AXISCapability, core:Capability)
individual(o16, data:name4, des:Name)
individual(o17, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o18, data:Mazak317641mstructTABLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o19, data:Mazak317641mstructTABLECapability, core:Capability)
individual(o20, data:name5, des:Name)
individual(o21, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o22, data:Mazak317641mstructTRUNDLEMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o23, data:Mazak317641mstructTRUNDLECapability, core:Capability)
individual(o24, data:name6, des:Name)
individual(o25, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o26, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o27, data:Mazak317641baseXCapability, core:Capability)
individual(o28, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o29, data:Mazak317641baseXPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o30, data:name7, des:Name)
individual(o31, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o32, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o33, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o34, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o35, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o36, data:Mazak317641baseYCapability, core:Capability)
individual(o37, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o38, data:Mazak317641baseYPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o39, data:name10, des:Name)
individual(o40, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o41, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o42, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o43, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o44, data:Mazak317641baseZCapability, core:Capability)
individual(o45, data:Mazak317641baseZPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o46, data:Mazak317641baseZPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o47, data:name13, des:Name)
individual(o48, data:[[./Mazak317641baseZZballscrew.html Mazak317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o49, data:[[./Mazak317641baseZZmotor.html Mazak317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600 Mazak800iMotorLINEAR_FORCE9600]])
individual(o50, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o51, data:mazak800ibasec1design1, vendor:[[../Mazak.html#Mazak800ibaseC1Design Mazak800ibaseC1Design]])
individual(o52, data:Mazak317641baseC1Capability, core:Capability)
individual(o53, data:Mazak317641baseC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o54, data:Mazak317641baseC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o55, data:name16, des:Name)
individual(o56, data:[[./Mazak317641baseC1Cmotor.html Mazak317641baseC1Cmotor]], vendor:[[../Mazak.html#Mazak800ibaseC1Cmotor Mazak800ibaseC1Cmotor]])
individual(o57, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o58, data:mazak800ibasebdesign1, vendor:[[../Mazak.html#Mazak800ibaseBDesign Mazak800ibaseBDesign]])
individual(o59, data:Mazak317641baseBCapability, core:Capability)
individual(o60, data:Mazak317641baseBIndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o61, data:Mazak317641baseBANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o62, data:name18, des:Name)
individual(o63, data:[[./Mazak317641baseBBmotor.html Mazak317641baseBBmotor]], vendor:[[../Mazak.html#Mazak800ibaseBBmotor Mazak800ibaseBBmotor]])
individual(o64, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o65, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o66, data:Mazak317641baseC2Capability, core:Capability)
individual(o67, data:Mazak317641baseC2IndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o68, data:Mazak317641baseC2ANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o69, data:name20, des:Name)
individual(o70, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o71, data:[[./Mazak317641controller.html Mazak317641controller]], vendor:[[../Mazak.html#Mazak800icontroller Mazak800icontroller]])
individual(o72, data:Mazak317641controllerEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o73, data:Mazak317641controllerCapability, core:Capability)
individual(o74, data:name22, des:Name)
individual(o75, data:[[./Mazak317641controllerpath.html Mazak317641controllerpath]], vendor:[[../Mazak.html#Mazak800icontrollerpath Mazak800icontrollerpath]])
individual(o76, data:[[./Mazak317641door.html Mazak317641door]], vendor:[[../Mazak.html#Mazak800idoor Mazak800idoor]])
individual(o77, data:Mazak317641doorMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o78, data:Mazak317641doorCapability, core:Capability)
individual(o79, data:name24, des:Name)
individual(o80, data:[[./Mazak317641partspartocc.html Mazak317641partspartocc]], vendor:[[../Mazak.html#Mazak800ipartspartocc Mazak800ipartspartocc]])
individual(o81, data:Mazak317641partspartoccMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o82, data:Mazak317641partspartoccCapability, core:Capability)
individual(o83, data:name25, des:Name)
individual(o84, data:[[./Mazak317641systemselectric.html Mazak317641systemselectric]], vendor:[[../Mazak.html#Mazak800isystemselectric Mazak800isystemselectric]])
individual(o85, data:Mazak317641systemselectricEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o86, data:Mazak317641systemselectricCapability, core:Capability)
individual(o87, data:name26, des:Name)
individual(o88, data:[[./Mazak317641systemshydraulic.html Mazak317641systemshydraulic]], vendor:[[../Mazak.html#Mazak800isystemshydraulic Mazak800isystemshydraulic]])
individual(o89, data:Mazak317641systemshydraulicEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o90, data:Mazak317641systemshydraulicCapability, core:Capability)
individual(o91, data:name27, des:Name)
individual(o92, data:[[./Mazak317641systemscoolant.html Mazak317641systemscoolant]], vendor:[[../Mazak.html#Mazak800isystemscoolant Mazak800isystemscoolant]])
individual(o93, data:Mazak317641systemscoolantEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o94, data:Mazak317641systemscoolantCapability, core:Capability)
individual(o95, data:Mazak317641systemscoolantTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o96, data:name28, des:Name)
individual(o97, data:[[./Mazak317641systemspneumatic.html Mazak317641systemspneumatic]], vendor:[[../Mazak.html#Mazak800isystemspneumatic Mazak800isystemspneumatic]])
individual(o98, data:Mazak317641systemspneumaticEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o99, data:Mazak317641systemspneumaticCapability, core:Capability)
individual(o100, data:name29, des:Name)
individual(o101, data:[[./Mazak317641systemslubrication.html Mazak317641systemslubrication]], vendor:[[../Mazak.html#Mazak800isystemslubrication Mazak800isystemslubrication]])
individual(o102, data:Mazak317641systemslubricationEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o103, data:Mazak317641systemslubricationCapability, core:Capability)
individual(o104, data:name30, des:Name)
individual(o105, data:[[./Mazak317641resourcesmaterialsstock.html Mazak317641resourcesmaterialsstock]], vendor:[[../Mazak.html#Mazak800iresourcesmaterialsstock Mazak800iresourcesmaterialsstock]])
individual(o106, data:Mazak317641resourcesmaterialsstockMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o107, data:Mazak317641resourcesmaterialsstockCapability, core:Capability)
individual(o108, data:name32, des:Name)
individual(o109, data:Mazak317641enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o110, data:Mazak317641enclosureCapability, core:Capability)
individual(o111, data:Mazak317641enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
individual(o112, data:name33, des:Name)
property(o0, "core:hasRole", o1)
property(o0, "core:hasRole", o2)
property(o0, "core:hasCapability", o3)
property(o0, "des:hasName", o4)
data(o4, "des:hasTextualName", "Mazak")
property(o0, "ex:hasComponent", o5)
data(o5, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o5, "core:hasRole", o6)
property(o5, "core:hasCapability", o7)
property(o5, "des:hasName", o8)
property(o0, "ex:hasComponent", o9)
data(o9, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
property(o9, "core:hasRole", o10)
property(o9, "core:hasCapability", o11)
property(o9, "des:hasName", o12)
property(o0, "ex:hasComponent", o13)
data(o13, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
property(o13, "core:hasRole", o14)
property(o13, "core:hasCapability", o15)
property(o13, "des:hasName", o16)
property(o0, "ex:hasComponent", o17)
data(o17, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
property(o17, "core:hasRole", o18)
property(o17, "core:hasCapability", o19)
property(o17, "des:hasName", o20)
property(o0, "ex:hasComponent", o21)
data(o21, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
property(o21, "core:hasRole", o22)
property(o21, "core:hasCapability", o23)
property(o21, "des:hasName", o24)
property(o0, "ex:hasComponent", o25)
data(o25, "rdfs:label", "Mazak 317641 base X particular")
property(o25, "core:prescribedBy", o26)
property(o25, "core:hasCapability", o27)
property(o25, "core:hasFunction", o28)
property(o25, "core:hasQuality", o29)
property(o25, "des:hasName", o30)
property(o25, "ex:connectedTo", o5)
property(o25, "ex:connectedTo", o31)
property(o25, "ex:hasComponent", o32)
property(o25, "ex:hasComponent", o33)
property(o0, "ex:hasComponent", o34)
data(o34, "rdfs:label", "Mazak 317641 base Y particular")
property(o34, "core:prescribedBy", o35)
property(o34, "core:hasCapability", o36)
property(o34, "core:hasFunction", o37)
property(o34, "core:hasQuality", o38)
property(o34, "des:hasName", o39)
property(o34, "ex:connectedTo", o5)
property(o34, "ex:connectedTo", o9)
property(o34, "ex:hasComponent", o40)
property(o34, "ex:hasComponent", o41)
property(o0, "ex:hasComponent", o42)
data(o42, "rdfs:label", "Mazak 317641 base Z particular")
property(o42, "core:prescribedBy", o43)
property(o42, "core:hasCapability", o44)
property(o42, "core:hasFunction", o45)
property(o42, "core:hasQuality", o46)
property(o42, "des:hasName", o47)
property(o42, "ex:connectedTo", o9)
property(o42, "ex:connectedTo", o13)
property(o42, "ex:hasComponent", o48)
property(o42, "ex:hasComponent", o49)
property(o0, "ex:hasComponent", o50)
data(o50, "rdfs:label", "Mazak 317641 base C1 particular")
property(o50, "core:prescribedBy", o51)
property(o50, "core:hasCapability", o52)
property(o50, "core:measuresAtSomeTime", o53)
property(o50, "core:hasFunction", o54)
property(o50, "des:hasName", o55)
property(o50, "ex:connectedTo", o13)
property(o50, "ex:hasComponent", o56)
property(o0, "ex:hasComponent", o57)
data(o57, "rdfs:label", "Mazak 317641 base B particular")
property(o57, "core:prescribedBy", o58)
property(o57, "core:hasCapability", o59)
property(o57, "core:hasFunction", o60)
property(o57, "core:hasQuality", o61)
property(o57, "des:hasName", o62)
property(o57, "ex:connectedTo", o21)
property(o57, "ex:connectedTo", o31)
property(o57, "ex:hasComponent", o63)
property(o0, "ex:hasComponent", o64)
data(o64, "rdfs:label", "Mazak 317641 base C2 particular")
property(o64, "core:prescribedBy", o65)
property(o64, "core:hasCapability", o66)
property(o64, "core:hasFunction", o67)
property(o64, "core:hasQuality", o68)
property(o64, "des:hasName", o69)
property(o64, "ex:connectedTo", o17)
property(o64, "ex:connectedTo", o21)
property(o64, "ex:hasComponent", o70)
property(o0, "ex:hasComponent", o71)
data(o71, "rdfs:label", "Mazak 317641 controller particular")
property(o71, "core:hasRole", o72)
property(o71, "core:hasCapability", o73)
property(o71, "des:hasName", o74)
property(o71, "ex:hasComponent", o75)
property(o0, "ex:hasComponent", o76)
data(o76, "rdfs:label", "Mazak 317641 door particular")
property(o76, "core:hasRole", o77)
property(o76, "core:hasCapability", o78)
property(o76, "des:hasName", o79)
property(o0, "ex:hasComponent", o80)
data(o80, "rdfs:label", "Mazak 317641 parts partocc particular")
property(o80, "core:hasRole", o81)
property(o80, "core:hasCapability", o82)
property(o80, "des:hasName", o83)
property(o0, "ex:hasComponent", o84)
data(o84, "rdfs:label", "Mazak 317641 systems electric particular")
property(o84, "core:hasRole", o85)
property(o84, "core:hasCapability", o86)
property(o84, "des:hasName", o87)
property(o0, "ex:hasComponent", o88)
data(o88, "rdfs:label", "Mazak 317641 systems hydraulic particular")
property(o88, "core:hasRole", o89)
property(o88, "core:hasCapability", o90)
property(o88, "des:hasName", o91)
property(o0, "ex:hasComponent", o92)
data(o92, "rdfs:label", "Mazak 317641 systems coolant particular")
property(o92, "core:hasRole", o93)
property(o92, "core:hasCapability", o94)
property(o92, "core:hasQuality", o95)
property(o92, "des:hasName", o96)
property(o0, "ex:hasComponent", o97)
data(o97, "rdfs:label", "Mazak 317641 systems pneumatic particular")
property(o97, "core:hasRole", o98)
property(o97, "core:hasCapability", o99)
property(o97, "des:hasName", o100)
property(o0, "ex:hasComponent", o101)
data(o101, "rdfs:label", "Mazak 317641 systems lubrication particular")
property(o101, "core:hasRole", o102)
property(o101, "core:hasCapability", o103)
property(o101, "des:hasName", o104)
property(o0, "ex:hasComponent", o105)
data(o105, "rdfs:label", "Mazak 317641 resources materials stock particular")
property(o105, "core:hasRole", o106)
property(o105, "core:hasCapability", o107)
property(o105, "des:hasName", o108)
property(o0, "ex:hasComponent", o31)
data(o31, "rdfs:label", "Mazak 317641 enclosure particular")
property(o31, "core:hasRole", o109)
property(o31, "core:hasCapability", o110)
property(o31, "core:hasQuality", o111)
property(o31, "des:hasName", o112)
@enduml
