
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak_base_C1

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak_base_C1.html Mazak_base_C1]], vendor:[[../Mazak.html#MazakbaseC1 MazakbaseC1]])
individual(o1, data:mazakbasec1design1, vendor:[[../Mazak.html#MazakbaseC1Design MazakbaseC1Design]])
individual(o2, data:Mazak_base_C1ROTARY_VELOCITYMaximum, core:ValueExpression)
individual(o3, data:Mazak_base_C1ROTARY_VELOCITYMinimum, core:ValueExpression)
individual(o4, data:Mazak_base_C1ROTARY_VELOCITY_ACTUAL, ex:RevoluteVelocity)
individual(o5, data:Mazak_base_C1ContinuousMotionCapability, ex:ContinuousMotionCapability)
individual(o6, data:name17, des:Name)
individual(o7, data:[[./Mazak_mstruct_Z_AXIS.html Mazak_mstruct_Z_AXIS]], vendor:[[../Mazak.html#MazakmstructZ_AXIS MazakmstructZ_AXIS]])
individual(o8, data:name4, des:Name)
individual(o9, data:[[./Mazak.html Mazak]], vendor:[[../Mazak.html#Mazak Mazak]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "MazakbaseC1Design particular")
property(o1, "core:hasValueExpressionAtAllTimes", o2)
property(o1, "core:hasValueExpressionAtAllTimes", o3)
property(o0, "core:measuresAtSomeTime", o4)
property(o0, "core:hasFunction", o5)
property(o0, "des:hasName", o6)
data(o6, "des:hasTextualName", "C1")
property(o0, "ex:joinedTo", o7)
data(o7, "rdfs:label", "Mazak mstruct Z_AXIS particular")
property(o7, "des:hasName", o8)
property(o9, "bfo:has_member_part_at_some_time", o0)
@enduml
