
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak317641

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./Mazak317641.html Mazak317641]], vendor:[[../Mazak.html#Mazak800i Mazak800i]])
individual(o1, data:Mazak317641TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o2, data:[[./Mazak317641mstructX_AXIS.html Mazak317641mstructX_AXIS]], vendor:[[../Mazak.html#Mazak800imstructX_AXIS Mazak800imstructX_AXIS]])
individual(o3, data:name2, des:Name)
individual(o4, data:[[./Mazak317641mstructY_AXIS.html Mazak317641mstructY_AXIS]], vendor:[[../Mazak.html#Mazak800imstructY_AXIS Mazak800imstructY_AXIS]])
individual(o5, data:name3, des:Name)
individual(o6, data:[[./Mazak317641mstructZ_AXIS.html Mazak317641mstructZ_AXIS]], vendor:[[../Mazak.html#Mazak800imstructZ_AXIS Mazak800imstructZ_AXIS]])
individual(o7, data:name4, des:Name)
individual(o8, data:[[./Mazak317641mstructTABLE.html Mazak317641mstructTABLE]], vendor:[[../Mazak.html#Mazak800imstructTABLE Mazak800imstructTABLE]])
individual(o9, data:name5, des:Name)
individual(o10, data:[[./Mazak317641mstructTRUNDLE.html Mazak317641mstructTRUNDLE]], vendor:[[../Mazak.html#Mazak800imstructTRUNDLE Mazak800imstructTRUNDLE]])
individual(o11, data:name6, des:Name)
individual(o12, data:[[./Mazak317641baseX.html Mazak317641baseX]], vendor:[[../Mazak.html#Mazak800ibaseX Mazak800ibaseX]])
individual(o13, data:mazak800ibasexdesign1, vendor:[[../Mazak.html#Mazak800ibaseXDesign Mazak800ibaseXDesign]])
individual(o14, data:[[./Mazak317641baseXXballscrew.html Mazak317641baseXXballscrew]], vendor:[[../Mazak.html#Mazak800ibaseXXballscrew Mazak800ibaseXXballscrew]])
individual(o15, data:[[./Mazak317641baseXXmotor.html Mazak317641baseXXmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o16, data:Mazak317641baseXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o17, data:Mazak317641baseXPOSITION_ACTUAL, qualphys:Displacement)
individual(o18, data:name7, des:Name)
individual(o19, data:[[./Mazak317641enclosure.html Mazak317641enclosure]], vendor:[[../Mazak.html#Mazak800ienclosure Mazak800ienclosure]])
individual(o20, data:[[./Mazak317641baseY.html Mazak317641baseY]], vendor:[[../Mazak.html#Mazak800ibaseY Mazak800ibaseY]])
individual(o21, data:mazak800ibaseydesign1, vendor:[[../Mazak.html#Mazak800ibaseYDesign Mazak800ibaseYDesign]])
individual(o22, data:[[./Mazak317641baseYYballscrew.html Mazak317641baseYYballscrew]], vendor:[[../Mazak.html#Mazak800ibaseYYballscrew Mazak800ibaseYYballscrew]])
individual(o23, data:[[./Mazak317641baseYYmotor.html Mazak317641baseYYmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE5200 Mazak800iMotorLINEAR_FORCE5200]])
individual(o24, data:Mazak317641baseYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o25, data:Mazak317641baseYPOSITION_ACTUAL, qualphys:Displacement)
individual(o26, data:name10, des:Name)
individual(o27, data:[[./Mazak317641baseZ.html Mazak317641baseZ]], vendor:[[../Mazak.html#Mazak800ibaseZ Mazak800ibaseZ]])
individual(o28, data:mazak800ibasezdesign1, vendor:[[../Mazak.html#Mazak800ibaseZDesign Mazak800ibaseZDesign]])
individual(o29, data:[[./Mazak317641baseZZballscrew.html Mazak317641baseZZballscrew]], vendor:[[../Mazak.html#Mazak800ibaseZZballscrew Mazak800ibaseZZballscrew]])
individual(o30, data:[[./Mazak317641baseZZmotor.html Mazak317641baseZZmotor]], vendor:[[../Mazak.html#Mazak800iMotorLINEAR_FORCE9600 Mazak800iMotorLINEAR_FORCE9600]])
individual(o31, data:Mazak317641baseZPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o32, data:Mazak317641baseZPOSITION_ACTUAL, qualphys:Displacement)
individual(o33, data:name13, des:Name)
individual(o34, data:[[./Mazak317641baseC1.html Mazak317641baseC1]], vendor:[[../Mazak.html#Mazak800ibaseC1 Mazak800ibaseC1]])
individual(o35, data:mazak800ibasec1design1, vendor:[[../Mazak.html#Mazak800ibaseC1Design Mazak800ibaseC1Design]])
individual(o36, data:Mazak317641baseC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o37, data:[[./Mazak317641baseC1Cmotor.html Mazak317641baseC1Cmotor]], vendor:[[../Mazak.html#Mazak800ibaseC1Cmotor Mazak800ibaseC1Cmotor]])
individual(o38, data:Mazak317641baseC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o39, data:name16, des:Name)
individual(o40, data:[[./Mazak317641baseB.html Mazak317641baseB]], vendor:[[../Mazak.html#Mazak800ibaseB Mazak800ibaseB]])
individual(o41, data:mazak800ibasebdesign1, vendor:[[../Mazak.html#Mazak800ibaseBDesign Mazak800ibaseBDesign]])
individual(o42, data:[[./Mazak317641baseBBmotor.html Mazak317641baseBBmotor]], vendor:[[../Mazak.html#Mazak800ibaseBBmotor Mazak800ibaseBBmotor]])
individual(o43, data:Mazak317641baseBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o44, data:Mazak317641baseBANGLE_ACTUAL, qualphys:Angle)
individual(o45, data:name18, des:Name)
individual(o46, data:[[./Mazak317641baseC2.html Mazak317641baseC2]], vendor:[[../Mazak.html#Mazak800ibaseC2 Mazak800ibaseC2]])
individual(o47, data:mazak800ibasec2design1, vendor:[[../Mazak.html#Mazak800ibaseC2Design Mazak800ibaseC2Design]])
individual(o48, data:[[./Mazak317641baseC2C2motor.html Mazak317641baseC2C2motor]], vendor:[[../Mazak.html#Mazak800ibaseC2C2motor Mazak800ibaseC2C2motor]])
individual(o49, data:Mazak317641baseC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o50, data:Mazak317641baseC2ANGLE_ACTUAL, qualphys:Angle)
individual(o51, data:name20, des:Name)
individual(o52, data:[[./Mazak317641controller.html Mazak317641controller]], vendor:[[../Mazak.html#Mazak800icontroller Mazak800icontroller]])
individual(o53, data:[[./Mazak317641controllerpath.html Mazak317641controllerpath]], vendor:[[../Mazak.html#Mazak800icontrollerpath Mazak800icontrollerpath]])
individual(o54, data:name22, des:Name)
individual(o55, data:[[./Mazak317641door.html Mazak317641door]], vendor:[[../Mazak.html#Mazak800idoor Mazak800idoor]])
individual(o56, data:name24, des:Name)
individual(o57, data:[[./Mazak317641partspartocc.html Mazak317641partspartocc]], vendor:[[../Mazak.html#Mazak800ipartspartocc Mazak800ipartspartocc]])
individual(o58, data:name25, des:Name)
individual(o59, data:[[./Mazak317641systemselectric.html Mazak317641systemselectric]], vendor:[[../Mazak.html#Mazak800isystemselectric Mazak800isystemselectric]])
individual(o60, data:name26, des:Name)
individual(o61, data:[[./Mazak317641systemshydraulic.html Mazak317641systemshydraulic]], vendor:[[../Mazak.html#Mazak800isystemshydraulic Mazak800isystemshydraulic]])
individual(o62, data:name27, des:Name)
individual(o63, data:[[./Mazak317641systemscoolant.html Mazak317641systemscoolant]], vendor:[[../Mazak.html#Mazak800isystemscoolant Mazak800isystemscoolant]])
individual(o64, data:Mazak317641systemscoolantTEMPERATURE, qualphys:Temperature)
individual(o65, data:name28, des:Name)
individual(o66, data:[[./Mazak317641systemspneumatic.html Mazak317641systemspneumatic]], vendor:[[../Mazak.html#Mazak800isystemspneumatic Mazak800isystemspneumatic]])
individual(o67, data:name29, des:Name)
individual(o68, data:[[./Mazak317641systemslubrication.html Mazak317641systemslubrication]], vendor:[[../Mazak.html#Mazak800isystemslubrication Mazak800isystemslubrication]])
individual(o69, data:name30, des:Name)
individual(o70, data:[[./Mazak317641resourcesmaterialsstock.html Mazak317641resourcesmaterialsstock]], vendor:[[../Mazak.html#Mazak800iresourcesmaterialsstock Mazak800iresourcesmaterialsstock]])
individual(o71, data:name32, des:Name)
individual(o72, data:Mazak317641enclosureTEMPERATURE, qualphys:Temperature)
individual(o73, data:name33, des:Name)
individual(o74, data:Mazak317641MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o75, data:name1, des:Name)
property(o0, "core:hasCapability", o1)
property(o0, "core:hasComponentPartAtSomeTime", o2)
data(o2, "rdfs:label", "Mazak 317641 mstruct X_AXIS particular")
property(o2, "des:hasName", o3)
property(o0, "core:hasComponentPartAtSomeTime", o4)
data(o4, "rdfs:label", "Mazak 317641 mstruct Y_AXIS particular")
property(o4, "des:hasName", o5)
property(o0, "core:hasComponentPartAtSomeTime", o6)
data(o6, "rdfs:label", "Mazak 317641 mstruct Z_AXIS particular")
property(o6, "des:hasName", o7)
property(o0, "core:hasComponentPartAtSomeTime", o8)
data(o8, "rdfs:label", "Mazak 317641 mstruct TABLE particular")
property(o8, "des:hasName", o9)
property(o0, "core:hasComponentPartAtSomeTime", o10)
data(o10, "rdfs:label", "Mazak 317641 mstruct TRUNDLE particular")
property(o10, "des:hasName", o11)
property(o0, "core:hasComponentPartAtSomeTime", o12)
data(o12, "rdfs:label", "Mazak 317641 base X particular")
property(o12, "core:prescribedBy", o13)
property(o12, "core:hasComponentPartAtSomeTime", o14)
property(o12, "core:hasComponentPartAtSomeTime", o15)
property(o12, "core:hasFunction", o16)
property(o12, "core:hasQuality", o17)
property(o12, "des:hasName", o18)
property(o12, "ex:connectedTo", o2)
property(o12, "ex:connectedTo", o19)
property(o0, "core:hasComponentPartAtSomeTime", o20)
data(o20, "rdfs:label", "Mazak 317641 base Y particular")
property(o20, "core:prescribedBy", o21)
property(o20, "core:hasComponentPartAtSomeTime", o22)
property(o20, "core:hasComponentPartAtSomeTime", o23)
property(o20, "core:hasFunction", o24)
property(o20, "core:hasQuality", o25)
property(o20, "des:hasName", o26)
property(o20, "ex:connectedTo", o2)
property(o20, "ex:connectedTo", o4)
property(o0, "core:hasComponentPartAtSomeTime", o27)
data(o27, "rdfs:label", "Mazak 317641 base Z particular")
property(o27, "core:prescribedBy", o28)
property(o27, "core:hasComponentPartAtSomeTime", o29)
property(o27, "core:hasComponentPartAtSomeTime", o30)
property(o27, "core:hasFunction", o31)
property(o27, "core:hasQuality", o32)
property(o27, "des:hasName", o33)
property(o27, "ex:connectedTo", o4)
property(o27, "ex:connectedTo", o6)
property(o0, "core:hasComponentPartAtSomeTime", o34)
data(o34, "rdfs:label", "Mazak 317641 base C1 particular")
property(o34, "core:prescribedBy", o35)
property(o34, "core:measuresAtSomeTime", o36)
property(o34, "core:hasComponentPartAtSomeTime", o37)
property(o34, "core:hasFunction", o38)
property(o34, "des:hasName", o39)
property(o34, "ex:connectedTo", o6)
property(o0, "core:hasComponentPartAtSomeTime", o40)
data(o40, "rdfs:label", "Mazak 317641 base B particular")
property(o40, "core:prescribedBy", o41)
property(o40, "core:hasComponentPartAtSomeTime", o42)
property(o40, "core:hasFunction", o43)
property(o40, "core:hasQuality", o44)
property(o40, "des:hasName", o45)
property(o40, "ex:connectedTo", o10)
property(o40, "ex:connectedTo", o19)
property(o0, "core:hasComponentPartAtSomeTime", o46)
data(o46, "rdfs:label", "Mazak 317641 base C2 particular")
property(o46, "core:prescribedBy", o47)
property(o46, "core:hasComponentPartAtSomeTime", o48)
property(o46, "core:hasFunction", o49)
property(o46, "core:hasQuality", o50)
property(o46, "des:hasName", o51)
property(o46, "ex:connectedTo", o8)
property(o46, "ex:connectedTo", o10)
property(o0, "core:hasComponentPartAtSomeTime", o52)
data(o52, "rdfs:label", "Mazak 317641 controller particular")
property(o52, "core:hasComponentPartAtSomeTime", o53)
property(o52, "des:hasName", o54)
property(o0, "core:hasComponentPartAtSomeTime", o55)
data(o55, "rdfs:label", "Mazak 317641 door particular")
property(o55, "des:hasName", o56)
property(o0, "core:hasComponentPartAtSomeTime", o57)
data(o57, "rdfs:label", "Mazak 317641 parts partocc particular")
property(o57, "des:hasName", o58)
property(o0, "core:hasComponentPartAtSomeTime", o59)
data(o59, "rdfs:label", "Mazak 317641 systems electric particular")
property(o59, "des:hasName", o60)
property(o0, "core:hasComponentPartAtSomeTime", o61)
data(o61, "rdfs:label", "Mazak 317641 systems hydraulic particular")
property(o61, "des:hasName", o62)
property(o0, "core:hasComponentPartAtSomeTime", o63)
data(o63, "rdfs:label", "Mazak 317641 systems coolant particular")
property(o63, "core:hasQuality", o64)
property(o63, "des:hasName", o65)
property(o0, "core:hasComponentPartAtSomeTime", o66)
data(o66, "rdfs:label", "Mazak 317641 systems pneumatic particular")
property(o66, "des:hasName", o67)
property(o0, "core:hasComponentPartAtSomeTime", o68)
data(o68, "rdfs:label", "Mazak 317641 systems lubrication particular")
property(o68, "des:hasName", o69)
property(o0, "core:hasComponentPartAtSomeTime", o70)
data(o70, "rdfs:label", "Mazak 317641 resources materials stock particular")
property(o70, "des:hasName", o71)
property(o0, "core:hasComponentPartAtSomeTime", o19)
data(o19, "rdfs:label", "Mazak 317641 enclosure particular")
property(o19, "core:hasQuality", o72)
property(o19, "des:hasName", o73)
property(o0, "core:hasFunction", o74)
property(o0, "des:hasName", o75)
data(o75, "des:hasTextualName", "Mazak")
@enduml
