@startuml
skinparam linetype polyline
left to right direction
title Mazak-partocc
object "[[./Mazak-partocc.html data:Mazak-partocc]]" as o1 {
 type: ex:Part 
}
object "data:Mazak-partocc-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./Mazak.html data:Mazak]]" as o3 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: partocc
o3 --> o1 : obo:has member part at some time
@enduml
