@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor LightBlue
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-room

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:[[./Mazak-room.html Mazak-room]], ex:Room)
individual(o2, data:Mazak-room-name, cmns-dsg:Name)
individual(o3, data:Mazak-room-temperature, qp:Temperature)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, environmental)
property(o1, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o3)
@enduml
