@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-LWasteDisposalSystem1
object "[[./OKUMA.123456-LWasteDisposalSystem1.html data:OKUMA.123456-LWasteDisposalSystem1]]" as o1 {
 type = obo:object
 }
object "data:OKUMA.123456-LWasteDisposalSystem1-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o3 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = WasteDisposalSystem1
o3 --> o1 : obo:has member part at some time
@enduml
