
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o1, data:OKUMA123456TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o2, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o3, data:name2, des:Name)
individual(o4, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o5, data:name3, des:Name)
individual(o6, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o7, data:name4, des:Name)
individual(o8, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o9, data:name5, des:Name)
individual(o10, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o11, data:name6, des:Name)
individual(o12, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o13, data:name7, des:Name)
individual(o14, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o15, data:name8, des:Name)
individual(o16, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o17, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o18, data:OKUMA123456AxesXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o19, data:OKUMA123456AxesXPOSITION_ACTUAL, qualphys:Displacement)
individual(o20, data:name9, des:Name)
individual(o21, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o22, data:okumamult_u3000axesydesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesYDesign OKUMAMULT_U3000AxesYDesign]])
individual(o23, data:OKUMA123456AxesYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o24, data:OKUMA123456AxesYPOSITION_ACTUAL, qualphys:Displacement)
individual(o25, data:name10, des:Name)
individual(o26, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o27, data:okumamult_u3000axesz1design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1Design OKUMAMULT_U3000AxesZ1Design]])
individual(o28, data:OKUMA123456AxesZ1PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o29, data:OKUMA123456AxesZ1POSITION_ACTUAL, qualphys:Displacement)
individual(o30, data:name11, des:Name)
individual(o31, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o32, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o33, data:OKUMA123456AxesBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o34, data:OKUMA123456AxesBANGLE_ACTUAL, qualphys:Angle)
individual(o35, data:name12, des:Name)
individual(o36, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o37, data:OKUMA123456AxesC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o38, data:OKUMA123456AxesC1ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o39, data:OKUMA123456AxesC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o40, data:name13, des:Name)
individual(o41, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o42, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o43, data:OKUMA123456AxesZ4PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o44, data:OKUMA123456AxesZ4POSITION_ACTUAL, qualphys:Displacement)
individual(o45, data:name14, des:Name)
individual(o46, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o47, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o48, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o49, data:OKUMA123456AxesC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o50, data:name15, des:Name)
individual(o51, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o52, data:OKUMA123456AxesC3RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o53, data:OKUMA123456AxesC3ANGLE_ACTUAL, qualphys:Angle)
individual(o54, data:name16, des:Name)
individual(o55, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o56, data:OKUMA123456AxesC6ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o57, data:OKUMA123456AxesC6ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o58, data:name17, des:Name)
individual(o59, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o60, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o61, data:name18, des:Name)
individual(o62, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o63, data:name20, des:Name)
individual(o64, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o65, data:name21, des:Name)
individual(o66, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o67, data:name22, des:Name)
individual(o68, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o69, data:name23, des:Name)
individual(o70, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o71, data:name24, des:Name)
individual(o72, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o73, data:name25, des:Name)
individual(o74, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o75, data:name26, des:Name)
individual(o76, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o77, data:name27, des:Name)
individual(o78, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o79, data:name28, des:Name)
individual(o80, data:OKUMA123456enclosureTEMPERATURE, qualphys:Temperature)
individual(o81, data:name29, des:Name)
individual(o82, data:OKUMA123456MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o83, data:name1, des:Name)
property(o0, "core:hasCapability", o1)
property(o0, "core:hasComponentPartAtSomeTime", o2)
data(o2, "rdfs:label", "OKUMA 123456 struct x_axis particular")
property(o2, "des:hasName", o3)
property(o0, "core:hasComponentPartAtSomeTime", o4)
data(o4, "rdfs:label", "OKUMA 123456 struct y_axis particular")
property(o4, "des:hasName", o5)
property(o0, "core:hasComponentPartAtSomeTime", o6)
data(o6, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
property(o6, "des:hasName", o7)
property(o0, "core:hasComponentPartAtSomeTime", o8)
data(o8, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
property(o8, "des:hasName", o9)
property(o0, "core:hasComponentPartAtSomeTime", o10)
data(o10, "rdfs:label", "OKUMA 123456 struct b_axis particular")
property(o10, "des:hasName", o11)
property(o0, "core:hasComponentPartAtSomeTime", o12)
data(o12, "rdfs:label", "OKUMA 123456 struct c1_axis particular")
property(o12, "des:hasName", o13)
property(o0, "core:hasComponentPartAtSomeTime", o14)
data(o14, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
property(o14, "des:hasName", o15)
property(o0, "core:hasComponentPartAtSomeTime", o16)
data(o16, "rdfs:label", "OKUMA 123456 Axes X particular")
property(o16, "core:prescribedBy", o17)
property(o16, "core:hasFunction", o18)
property(o16, "core:hasQuality", o19)
property(o16, "des:hasName", o20)
property(o16, "ex:connectedTo", o2)
property(o16, "ex:connectedTo", o6)
property(o0, "core:hasComponentPartAtSomeTime", o21)
data(o21, "rdfs:label", "OKUMA 123456 Axes Y particular")
property(o21, "core:prescribedBy", o22)
property(o21, "core:hasFunction", o23)
property(o21, "core:hasQuality", o24)
property(o21, "des:hasName", o25)
property(o21, "ex:connectedTo", o2)
property(o21, "ex:connectedTo", o4)
property(o0, "core:hasComponentPartAtSomeTime", o26)
data(o26, "rdfs:label", "OKUMA 123456 Axes Z1 particular")
property(o26, "core:prescribedBy", o27)
property(o26, "core:hasFunction", o28)
property(o26, "core:hasQuality", o29)
property(o26, "des:hasName", o30)
property(o26, "ex:connectedTo", o6)
property(o26, "ex:connectedTo", o31)
property(o0, "core:hasComponentPartAtSomeTime", o32)
data(o32, "rdfs:label", "OKUMA 123456 Axes B particular")
property(o32, "core:hasFunction", o33)
property(o32, "core:hasQuality", o34)
property(o32, "des:hasName", o35)
property(o32, "ex:connectedTo", o4)
property(o32, "ex:connectedTo", o10)
property(o0, "core:hasComponentPartAtSomeTime", o36)
data(o36, "rdfs:label", "OKUMA 123456 Axes C1 particular")
property(o36, "core:measuresAtSomeTime", o37)
property(o36, "core:measuresAtSomeTime", o38)
property(o36, "core:hasFunction", o39)
property(o36, "des:hasName", o40)
property(o36, "ex:connectedTo", o31)
property(o0, "core:hasComponentPartAtSomeTime", o41)
data(o41, "rdfs:label", "OKUMA 123456 Axes Z4 particular")
property(o41, "core:prescribedBy", o42)
property(o41, "core:hasFunction", o43)
property(o41, "core:hasQuality", o44)
property(o41, "des:hasName", o45)
property(o41, "ex:connectedTo", o8)
property(o41, "ex:connectedTo", o31)
property(o0, "core:hasComponentPartAtSomeTime", o46)
data(o46, "rdfs:label", "OKUMA 123456 Axes C2 particular")
property(o46, "core:measuresAtSomeTime", o47)
property(o46, "core:measuresAtSomeTime", o48)
property(o46, "core:hasFunction", o49)
property(o46, "des:hasName", o50)
property(o46, "ex:connectedTo", o8)
property(o46, "ex:connectedTo", o14)
property(o0, "core:hasComponentPartAtSomeTime", o51)
data(o51, "rdfs:label", "OKUMA 123456 Axes C3 particular")
property(o51, "core:hasFunction", o52)
property(o51, "core:hasQuality", o53)
property(o51, "des:hasName", o54)
property(o51, "ex:connectedTo", o8)
property(o51, "ex:connectedTo", o14)
property(o0, "core:hasComponentPartAtSomeTime", o55)
data(o55, "rdfs:label", "OKUMA 123456 Axes C6 particular")
property(o55, "core:measuresAtSomeTime", o56)
property(o55, "core:measuresAtSomeTime", o57)
property(o55, "des:hasName", o58)
property(o0, "core:hasComponentPartAtSomeTime", o59)
data(o59, "rdfs:label", "OKUMA 123456 Controller particular")
property(o59, "core:hasComponentPartAtSomeTime", o60)
property(o59, "des:hasName", o61)
property(o0, "core:hasComponentPartAtSomeTime", o62)
data(o62, "rdfs:label", "OKUMA 123456 Systems1 CoolantSystem1 particular")
property(o62, "des:hasName", o63)
property(o0, "core:hasComponentPartAtSomeTime", o64)
data(o64, "rdfs:label", "OKUMA 123456 Systems1 ElectricSystem1 particular")
property(o64, "des:hasName", o65)
property(o0, "core:hasComponentPartAtSomeTime", o66)
data(o66, "rdfs:label", "OKUMA 123456 Systems1 HydraulicSystem1 particular")
property(o66, "des:hasName", o67)
property(o0, "core:hasComponentPartAtSomeTime", o68)
data(o68, "rdfs:label", "OKUMA 123456 Systems1 LubricationSystem1 particular")
property(o68, "des:hasName", o69)
property(o0, "core:hasComponentPartAtSomeTime", o70)
data(o70, "rdfs:label", "OKUMA 123456 Systems1 PneumaticSystem1 particular")
property(o70, "des:hasName", o71)
property(o0, "core:hasComponentPartAtSomeTime", o72)
data(o72, "rdfs:label", "OKUMA 123456 LAux1 LoaderSystem1 particular")
property(o72, "des:hasName", o73)
property(o0, "core:hasComponentPartAtSomeTime", o74)
data(o74, "rdfs:label", "OKUMA 123456 LAux1 WasteDisposalSystem1 particular")
property(o74, "des:hasName", o75)
property(o0, "core:hasComponentPartAtSomeTime", o76)
data(o76, "rdfs:label", "OKUMA 123456 LAux1 ToolingDeliverySystem1 particular")
property(o76, "des:hasName", o77)
property(o0, "core:hasComponentPartAtSomeTime", o78)
data(o78, "rdfs:label", "OKUMA 123456 LAux1 BarFeederSystem1 particular")
property(o78, "des:hasName", o79)
property(o0, "core:hasComponentPartAtSomeTime", o31)
data(o31, "rdfs:label", "OKUMA 123456 enclosure particular")
property(o31, "core:hasQuality", o80)
property(o31, "des:hasName", o81)
property(o0, "core:hasFunction", o82)
property(o0, "des:hasName", o83)
data(o83, "des:hasTextualName", "OKUMA")
@enduml
