
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456_Axes_X

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA.123456_Axes_X.html OKUMA.123456_Axes_X]], vendor:[[../OKUMA.html#OKUMA.123456AxesX OKUMA.123456AxesX]])
individual(o1, data:okuma.123456axesxdesign1, vendor:[[../OKUMA.html#OKUMA.123456AxesXDesign OKUMA.123456AxesXDesign]])
individual(o2, data:OKUMA.123456_Axes_XLengthNominal, core:ValueExpression)
individual(o3, data:OKUMA.123456_Axes_XLinear_forceMaximum, core:ValueExpression)
individual(o4, data:OKUMA.123456_Axes_XLinear_forceMinimum, core:ValueExpression)
individual(o5, data:OKUMA.123456_Axes_XVelocityRapidMaximum, core:ValueExpression)
individual(o6, data:OKUMA.123456_Axes_XVelocityRapidMinimum, core:ValueExpression)
individual(o7, data:OKUMA.123456_Axes_XVelocityProgrammedMaximum, core:ValueExpression)
individual(o8, data:OKUMA.123456_Axes_XVelocityProgrammedMinimum, core:ValueExpression)
individual(o9, data:OKUMA.123456_Axes_XPrismaticMotionCapability, ex:PrismaticMotionCapability)
individual(o10, data:OKUMA.123456_Axes_XPOSITION_ACTUAL, qualphys:Displacement)
individual(o11, data:name9, des:Name)
individual(o12, data:[[./OKUMA.123456_struct_z1_axis.html OKUMA.123456_struct_z1_axis]], vendor:[[../OKUMA.html#OKUMA.123456structz1_axis OKUMA.123456structz1_axis]])
individual(o13, data:name4, des:Name)
individual(o14, data:[[./OKUMA.123456_struct_x_axis.html OKUMA.123456_struct_x_axis]], vendor:[[../OKUMA.html#OKUMA.123456structx_axis OKUMA.123456structx_axis]])
individual(o15, data:name2, des:Name)
individual(o16, data:[[./OKUMA.123456.html OKUMA.123456]], vendor:[[../OKUMA.html#OKUMA.123456 OKUMA.123456]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "OKUMA.123456AxesXDesign particular")
property(o1, "core:hasValueExpressionAtAllTimes", o2)
property(o1, "core:hasValueExpressionAtAllTimes", o3)
property(o1, "core:hasValueExpressionAtAllTimes", o4)
property(o1, "core:hasValueExpressionAtAllTimes", o5)
property(o1, "core:hasValueExpressionAtAllTimes", o6)
property(o1, "core:hasValueExpressionAtAllTimes", o7)
property(o1, "core:hasValueExpressionAtAllTimes", o8)
property(o0, "core:hasFunction", o9)
property(o0, "core:hasQuality", o10)
property(o0, "des:hasName", o11)
data(o11, "des:hasTextualName", "X")
property(o0, "ex:joinedTo", o12)
data(o12, "rdfs:label", "OKUMA.123456 struct z1_axis particular")
property(o12, "des:hasName", o13)
property(o0, "ex:joinedTo", o14)
data(o14, "rdfs:label", "OKUMA.123456 struct x_axis particular")
property(o14, "des:hasName", o15)
property(o16, "core:hasComponentPartAtAllTimes", o0)
@enduml
