
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMAFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, vendor:ontology1, owl:Ontology)
individual(o2, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o3, data:name1, des:Name)
individual(o4, data:OKUMA123456TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o5, data:OKUMA123456MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o6, data:OKUMA123456EquipmentRole, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o7, data:OKUMA123456EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o8, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o9, data:name2, des:Name)
individual(o10, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o11, data:name3, des:Name)
individual(o12, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o13, data:name4, des:Name)
individual(o14, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o15, data:name5, des:Name)
individual(o16, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o17, data:name6, des:Name)
individual(o18, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o19, data:name7, des:Name)
individual(o20, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o21, data:name8, des:Name)
individual(o22, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o23, data:name9, des:Name)
individual(o24, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o25, data:OKUMA123456AxesXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o26, units:MilliM, units:Unit)
individual(o27, data:OKUMA123456AxesXLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o28, units:N, units:Unit)
individual(o29, data:OKUMA123456AxesXLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o30, data:OKUMA123456AxesXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o31, units:MilliM-PER-SEC, units:Unit)
individual(o32, data:OKUMA123456AxesXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o33, data:OKUMA123456AxesXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o34, data:OKUMA123456AxesXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o35, data:OKUMA123456AxesXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o36, data:OKUMA123456AxesXEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o37, data:OKUMA123456AxesXPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o38, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o39, data:name10, des:Name)
individual(o40, data:okumamult_u3000axesydesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesYDesign OKUMAMULT_U3000AxesYDesign]])
individual(o41, data:OKUMA123456AxesYLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o42, data:OKUMA123456AxesYLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o43, data:OKUMA123456AxesYLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o44, data:OKUMA123456AxesYVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o45, data:OKUMA123456AxesYVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o46, data:OKUMA123456AxesYVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o47, data:OKUMA123456AxesYVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o48, data:OKUMA123456AxesYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o49, data:OKUMA123456AxesYEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o50, data:OKUMA123456AxesYPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o51, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o52, data:name11, des:Name)
individual(o53, data:okumamult_u3000axesz1design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1Design OKUMAMULT_U3000AxesZ1Design]])
individual(o54, data:OKUMA123456AxesZ1LengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o55, data:OKUMA123456AxesZ1Linear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o56, data:OKUMA123456AxesZ1Linear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o57, data:OKUMA123456AxesZ1VelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o58, data:OKUMA123456AxesZ1VelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o59, data:OKUMA123456AxesZ1VelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o60, data:OKUMA123456AxesZ1VelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o61, data:OKUMA123456AxesZ1PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o62, data:OKUMA123456AxesZ1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o63, data:OKUMA123456AxesZ1POSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o64, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o65, data:name12, des:Name)
individual(o66, data:OKUMA123456AxesBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o67, data:OKUMA123456AxesBEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o68, data:OKUMA123456AxesBANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o69, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o70, data:name13, des:Name)
individual(o71, data:OKUMA123456AxesC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o72, data:OKUMA123456AxesC1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o73, data:OKUMA123456AxesC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o74, data:OKUMA123456AxesC1ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o75, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o76, data:name14, des:Name)
individual(o77, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o78, data:OKUMA123456AxesZ4LengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o79, data:OKUMA123456AxesZ4Linear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o80, data:OKUMA123456AxesZ4Linear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o81, data:OKUMA123456AxesZ4VelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o82, data:OKUMA123456AxesZ4VelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o83, data:OKUMA123456AxesZ4VelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o84, data:OKUMA123456AxesZ4VelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o85, data:OKUMA123456AxesZ4PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o86, data:OKUMA123456AxesZ4EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o87, data:OKUMA123456AxesZ4POSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o88, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o89, data:name15, des:Name)
individual(o90, data:OKUMA123456AxesC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o91, data:OKUMA123456AxesC2EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o92, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o93, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o94, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o95, data:name16, des:Name)
individual(o96, data:OKUMA123456AxesC3RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o97, data:OKUMA123456AxesC3EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o98, data:OKUMA123456AxesC3ANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o99, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o100, data:name17, des:Name)
individual(o101, data:OKUMA123456AxesC6EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o102, data:OKUMA123456AxesC6ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o103, data:OKUMA123456AxesC6ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o104, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o105, data:name18, des:Name)
individual(o106, data:OKUMA123456ControllerEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o107, data:OKUMA123456ControllerCONTROLLER_MODE, ex:[[../Example.html#ControllerMode ControllerMode]])
individual(o108, data:OKUMA123456ControllerEXECUTION, ex:[[../Example.html#ExecutionState ExecutionState]])
individual(o109, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o110, data:name19, des:Name)
individual(o111, data:OKUMA123456ControllerpathEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o112, data:OKUMA123456ControllerpathPATH_POSITION_ACTUAL, ex:[[../Example.html#ThreeSpaceDisplacement ThreeSpaceDisplacement]])
individual(o113, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o114, data:name20, des:Name)
individual(o115, data:OKUMA123456Systems1CoolantSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o116, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o117, data:name21, des:Name)
individual(o118, data:OKUMA123456Systems1ElectricSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o119, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o120, data:name22, des:Name)
individual(o121, data:OKUMA123456Systems1HydraulicSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o122, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o123, data:name23, des:Name)
individual(o124, data:OKUMA123456Systems1LubricationSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o125, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o126, data:name24, des:Name)
individual(o127, data:OKUMA123456Systems1PneumaticSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o128, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o129, data:name25, des:Name)
individual(o130, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o131, data:name26, des:Name)
individual(o132, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o133, data:name27, des:Name)
individual(o134, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o135, data:name28, des:Name)
individual(o136, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o137, data:name29, des:Name)
individual(o138, data:OKUMA123456enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o139, data:OKUMA123456enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
property(o0, "owl:imports", o1)
property(o2, "des:hasName", o3)
property(o2, "core:hasCapability", o4)
property(o2, "core:hasFunction", o5)
property(o2, "core:hasRole", o6)
property(o2, "core:hasRole", o7)
property(o2, "core:hasComponentPartAtSomeTime", o8)
property(o8, "des:hasName", o9)
property(o2, "core:hasComponentPartAtSomeTime", o10)
property(o10, "des:hasName", o11)
property(o2, "core:hasComponentPartAtSomeTime", o12)
property(o12, "des:hasName", o13)
property(o2, "core:hasComponentPartAtSomeTime", o14)
property(o14, "des:hasName", o15)
property(o2, "core:hasComponentPartAtSomeTime", o16)
property(o16, "des:hasName", o17)
property(o2, "core:hasComponentPartAtSomeTime", o18)
property(o18, "des:hasName", o19)
property(o2, "core:hasComponentPartAtSomeTime", o20)
property(o20, "des:hasName", o21)
property(o2, "core:hasComponentPartAtSomeTime", o22)
property(o22, "des:hasName", o23)
property(o22, "core:prescribedBy", o24)
property(o24, "core:hasValueExpressionAtSomeTime", o25)
property(o25, "ex:hasUnit", o26)
property(o24, "core:hasValueExpressionAtSomeTime", o27)
property(o27, "ex:hasUnit", o28)
property(o24, "core:hasValueExpressionAtSomeTime", o29)
property(o29, "ex:hasUnit", o28)
property(o24, "core:hasValueExpressionAtSomeTime", o30)
property(o30, "ex:hasUnit", o31)
property(o24, "core:hasValueExpressionAtSomeTime", o32)
property(o32, "ex:hasUnit", o31)
property(o24, "core:hasValueExpressionAtSomeTime", o33)
property(o33, "ex:hasUnit", o31)
property(o24, "core:hasValueExpressionAtSomeTime", o34)
property(o34, "ex:hasUnit", o31)
property(o22, "core:hasFunction", o35)
property(o35, "core:prescribedBy", o24)
property(o22, "core:hasRole", o36)
property(o22, "core:hasQuality", o37)
property(o2, "core:hasComponentPartAtSomeTime", o38)
property(o38, "des:hasName", o39)
property(o38, "core:prescribedBy", o40)
property(o40, "core:hasValueExpressionAtSomeTime", o41)
property(o41, "ex:hasUnit", o26)
property(o40, "core:hasValueExpressionAtSomeTime", o42)
property(o42, "ex:hasUnit", o28)
property(o40, "core:hasValueExpressionAtSomeTime", o43)
property(o43, "ex:hasUnit", o28)
property(o40, "core:hasValueExpressionAtSomeTime", o44)
property(o44, "ex:hasUnit", o31)
property(o40, "core:hasValueExpressionAtSomeTime", o45)
property(o45, "ex:hasUnit", o31)
property(o40, "core:hasValueExpressionAtSomeTime", o46)
property(o46, "ex:hasUnit", o31)
property(o40, "core:hasValueExpressionAtSomeTime", o47)
property(o47, "ex:hasUnit", o31)
property(o38, "core:hasFunction", o48)
property(o48, "core:prescribedBy", o40)
property(o38, "core:hasRole", o49)
property(o38, "core:hasQuality", o50)
property(o2, "core:hasComponentPartAtSomeTime", o51)
property(o51, "des:hasName", o52)
property(o51, "core:prescribedBy", o53)
property(o53, "core:hasValueExpressionAtSomeTime", o54)
property(o54, "ex:hasUnit", o26)
property(o53, "core:hasValueExpressionAtSomeTime", o55)
property(o55, "ex:hasUnit", o28)
property(o53, "core:hasValueExpressionAtSomeTime", o56)
property(o56, "ex:hasUnit", o28)
property(o53, "core:hasValueExpressionAtSomeTime", o57)
property(o57, "ex:hasUnit", o31)
property(o53, "core:hasValueExpressionAtSomeTime", o58)
property(o58, "ex:hasUnit", o31)
property(o53, "core:hasValueExpressionAtSomeTime", o59)
property(o59, "ex:hasUnit", o31)
property(o53, "core:hasValueExpressionAtSomeTime", o60)
property(o60, "ex:hasUnit", o31)
property(o51, "core:hasFunction", o61)
property(o61, "core:prescribedBy", o53)
property(o51, "core:hasRole", o62)
property(o51, "core:hasQuality", o63)
property(o2, "core:hasComponentPartAtSomeTime", o64)
property(o64, "des:hasName", o65)
property(o64, "core:hasFunction", o66)
property(o64, "core:hasRole", o67)
property(o64, "core:hasQuality", o68)
property(o2, "core:hasComponentPartAtSomeTime", o69)
property(o69, "des:hasName", o70)
property(o69, "core:hasFunction", o71)
property(o69, "core:hasRole", o72)
property(o69, "core:measuresAtSomeTime", o73)
property(o69, "core:measuresAtSomeTime", o74)
property(o2, "core:hasComponentPartAtSomeTime", o75)
property(o75, "des:hasName", o76)
property(o75, "core:prescribedBy", o77)
property(o77, "core:hasValueExpressionAtSomeTime", o78)
property(o78, "ex:hasUnit", o26)
property(o77, "core:hasValueExpressionAtSomeTime", o79)
property(o79, "ex:hasUnit", o28)
property(o77, "core:hasValueExpressionAtSomeTime", o80)
property(o80, "ex:hasUnit", o28)
property(o77, "core:hasValueExpressionAtSomeTime", o81)
property(o81, "ex:hasUnit", o31)
property(o77, "core:hasValueExpressionAtSomeTime", o82)
property(o82, "ex:hasUnit", o31)
property(o77, "core:hasValueExpressionAtSomeTime", o83)
property(o83, "ex:hasUnit", o31)
property(o77, "core:hasValueExpressionAtSomeTime", o84)
property(o84, "ex:hasUnit", o31)
property(o75, "core:hasFunction", o85)
property(o85, "core:prescribedBy", o77)
property(o75, "core:hasRole", o86)
property(o75, "core:hasQuality", o87)
property(o2, "core:hasComponentPartAtSomeTime", o88)
property(o88, "des:hasName", o89)
property(o88, "core:hasFunction", o90)
property(o88, "core:hasRole", o91)
property(o88, "core:measuresAtSomeTime", o92)
property(o88, "core:measuresAtSomeTime", o93)
property(o2, "core:hasComponentPartAtSomeTime", o94)
property(o94, "des:hasName", o95)
property(o94, "core:hasFunction", o96)
property(o94, "core:hasRole", o97)
property(o94, "core:hasQuality", o98)
property(o2, "core:hasComponentPartAtSomeTime", o99)
property(o99, "des:hasName", o100)
property(o99, "core:hasRole", o101)
property(o99, "core:measuresAtSomeTime", o102)
property(o99, "core:measuresAtSomeTime", o103)
property(o2, "core:hasComponentPartAtSomeTime", o104)
property(o104, "des:hasName", o105)
property(o104, "core:hasRole", o106)
property(o104, "core:observesAtSomeTime", o107)
property(o104, "core:observesAtSomeTime", o108)
property(o104, "core:hasComponentPartAtSomeTime", o109)
property(o109, "des:hasName", o110)
property(o109, "core:hasRole", o111)
property(o109, "core:hasQuality", o112)
property(o2, "core:hasComponentPartAtSomeTime", o113)
property(o113, "des:hasName", o114)
property(o113, "core:hasRole", o115)
property(o2, "core:hasComponentPartAtSomeTime", o116)
property(o116, "des:hasName", o117)
property(o116, "core:hasRole", o118)
property(o2, "core:hasComponentPartAtSomeTime", o119)
property(o119, "des:hasName", o120)
property(o119, "core:hasRole", o121)
property(o2, "core:hasComponentPartAtSomeTime", o122)
property(o122, "des:hasName", o123)
property(o122, "core:hasRole", o124)
property(o2, "core:hasComponentPartAtSomeTime", o125)
property(o125, "des:hasName", o126)
property(o125, "core:hasRole", o127)
property(o2, "core:hasComponentPartAtSomeTime", o128)
property(o128, "des:hasName", o129)
property(o2, "core:hasComponentPartAtSomeTime", o130)
property(o130, "des:hasName", o131)
property(o2, "core:hasComponentPartAtSomeTime", o132)
property(o132, "des:hasName", o133)
property(o2, "core:hasComponentPartAtSomeTime", o134)
property(o134, "des:hasName", o135)
property(o2, "core:hasComponentPartAtSomeTime", o136)
property(o136, "des:hasName", o137)
property(o136, "core:hasRole", o138)
property(o136, "core:hasQuality", o139)
property(o22, "ex:connectedTo", o12)
property(o22, "ex:connectedTo", o8)
property(o38, "ex:connectedTo", o8)
property(o38, "ex:connectedTo", o10)
property(o51, "ex:connectedTo", o136)
property(o51, "ex:connectedTo", o12)
property(o64, "ex:connectedTo", o10)
property(o64, "ex:connectedTo", o16)
property(o69, "ex:connectedTo", o136)
property(o75, "ex:connectedTo", o136)
property(o75, "ex:connectedTo", o14)
property(o88, "ex:connectedTo", o14)
property(o88, "ex:connectedTo", o20)
property(o94, "ex:connectedTo", o14)
property(o94, "ex:connectedTo", o20)
data(o2, "rdfs:label", "OKUMA 123456 particular")
data(o3, "des:hasTextualName", "OKUMA")
data(o8, "rdfs:label", "OKUMA 123456 struct x_axis particular")
data(o9, "des:hasTextualName", "x_axis")
data(o10, "rdfs:label", "OKUMA 123456 struct y_axis particular")
data(o11, "des:hasTextualName", "y_axis")
data(o12, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
data(o13, "des:hasTextualName", "z1_axis")
data(o14, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
data(o15, "des:hasTextualName", "z4_axis")
data(o16, "rdfs:label", "OKUMA 123456 struct b_axis particular")
data(o17, "des:hasTextualName", "b_axis")
data(o18, "rdfs:label", "OKUMA 123456 struct c1_axis particular")
data(o19, "des:hasTextualName", "c1_axis")
data(o20, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
data(o21, "des:hasTextualName", "c2_axis")
data(o22, "rdfs:label", "OKUMA 123456 Axes X particular")
data(o23, "des:hasTextualName", "X")
data(o24, "rdfs:label", "OKUMAMULT_U3000AxesXDesign particular")
data(o25, "core:hasSimpleExpressionValue", "650.0")
data(o27, "core:hasSimpleExpressionValue", "5200.0")
data(o29, "core:hasSimpleExpressionValue", "0.0")
data(o30, "core:hasSimpleExpressionValue", "7000.0")
data(o32, "core:hasSimpleExpressionValue", "1.0")
data(o33, "core:hasSimpleExpressionValue", "7000.0")
data(o34, "core:hasSimpleExpressionValue", "1.0")
data(o38, "rdfs:label", "OKUMA 123456 Axes Y particular")
data(o39, "des:hasTextualName", "Y")
data(o40, "rdfs:label", "OKUMAMULT_U3000AxesYDesign particular")
data(o41, "core:hasSimpleExpressionValue", "650.0")
data(o42, "core:hasSimpleExpressionValue", "5200.0")
data(o43, "core:hasSimpleExpressionValue", "0.0")
data(o44, "core:hasSimpleExpressionValue", "7000.0")
data(o45, "core:hasSimpleExpressionValue", "1.0")
data(o46, "core:hasSimpleExpressionValue", "7000.0")
data(o47, "core:hasSimpleExpressionValue", "1.0")
data(o51, "rdfs:label", "OKUMA 123456 Axes Z1 particular")
data(o52, "des:hasTextualName", "Z1")
data(o53, "rdfs:label", "OKUMAMULT_U3000AxesZ1Design particular")
data(o54, "core:hasSimpleExpressionValue", "650.0")
data(o55, "core:hasSimpleExpressionValue", "5200.0")
data(o56, "core:hasSimpleExpressionValue", "0.0")
data(o57, "core:hasSimpleExpressionValue", "7000.0")
data(o58, "core:hasSimpleExpressionValue", "1.0")
data(o59, "core:hasSimpleExpressionValue", "7000.0")
data(o60, "core:hasSimpleExpressionValue", "1.0")
data(o64, "rdfs:label", "OKUMA 123456 Axes B particular")
data(o65, "des:hasTextualName", "B")
data(o69, "rdfs:label", "OKUMA 123456 Axes C1 particular")
data(o70, "des:hasTextualName", "C1")
data(o75, "rdfs:label", "OKUMA 123456 Axes Z4 particular")
data(o76, "des:hasTextualName", "Z4")
data(o77, "rdfs:label", "OKUMAMULT_U3000AxesZ4Design particular")
data(o78, "core:hasSimpleExpressionValue", "650.0")
data(o79, "core:hasSimpleExpressionValue", "5200.0")
data(o80, "core:hasSimpleExpressionValue", "0.0")
data(o81, "core:hasSimpleExpressionValue", "7000.0")
data(o82, "core:hasSimpleExpressionValue", "1.0")
data(o83, "core:hasSimpleExpressionValue", "7000.0")
data(o84, "core:hasSimpleExpressionValue", "1.0")
data(o88, "rdfs:label", "OKUMA 123456 Axes C2 particular")
data(o89, "des:hasTextualName", "C2")
data(o94, "rdfs:label", "OKUMA 123456 Axes C3 particular")
data(o95, "des:hasTextualName", "C3")
data(o99, "rdfs:label", "OKUMA 123456 Axes C6 particular")
data(o100, "des:hasTextualName", "C6")
data(o104, "rdfs:label", "OKUMA 123456 Controller particular")
data(o105, "des:hasTextualName", "Controller")
data(o109, "rdfs:label", "OKUMA 123456 Controller path particular")
data(o110, "des:hasTextualName", "path")
data(o113, "rdfs:label", "OKUMA 123456 Systems1 CoolantSystem1 particular")
data(o114, "des:hasTextualName", "CoolantSystem1")
data(o116, "rdfs:label", "OKUMA 123456 Systems1 ElectricSystem1 particular")
data(o117, "des:hasTextualName", "ElectricSystem1")
data(o119, "rdfs:label", "OKUMA 123456 Systems1 HydraulicSystem1 particular")
data(o120, "des:hasTextualName", "HydraulicSystem1")
data(o122, "rdfs:label", "OKUMA 123456 Systems1 LubricationSystem1 particular")
data(o123, "des:hasTextualName", "LubricationSystem1")
data(o125, "rdfs:label", "OKUMA 123456 Systems1 PneumaticSystem1 particular")
data(o126, "des:hasTextualName", "PneumaticSystem1")
data(o128, "rdfs:label", "OKUMA 123456 LAux1 LoaderSystem1 particular")
data(o129, "des:hasTextualName", "LoaderSystem1")
data(o130, "rdfs:label", "OKUMA 123456 LAux1 WasteDisposalSystem1 particular")
data(o131, "des:hasTextualName", "WasteDisposalSystem1")
data(o132, "rdfs:label", "OKUMA 123456 LAux1 ToolingDeliverySystem1 particular")
data(o133, "des:hasTextualName", "ToolingDeliverySystem1")
data(o134, "rdfs:label", "OKUMA 123456 LAux1 BarFeederSystem1 particular")
data(o135, "des:hasTextualName", "BarFeederSystem1")
data(o136, "rdfs:label", "OKUMA 123456 enclosure particular")
data(o137, "des:hasTextualName", "enclosure")
@enduml
