
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456AxesZ4

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o1, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o2, data:OKUMA123456AxesZ4LengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:OKUMA123456AxesZ4Linear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:OKUMA123456AxesZ4Linear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:OKUMA123456AxesZ4VelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:OKUMA123456AxesZ4VelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:OKUMA123456AxesZ4VelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o8, data:OKUMA123456AxesZ4VelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o9, data:OKUMA123456AxesZ4PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o10, data:OKUMA123456AxesZ4POSITION_ACTUAL, qualphys:Displacement)
individual(o11, data:name14, des:Name)
individual(o12, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o13, data:OKUMA123456enclosureTEMPERATURE, qualphys:Temperature)
individual(o14, data:name29, des:Name)
individual(o15, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o16, data:name5, des:Name)
individual(o17, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "OKUMAMULT_U3000AxesZ4Design particular")
property(o1, "core:hasValueExpressionAtSomeTime", o2)
property(o1, "core:hasValueExpressionAtSomeTime", o3)
property(o1, "core:hasValueExpressionAtSomeTime", o4)
property(o1, "core:hasValueExpressionAtSomeTime", o5)
property(o1, "core:hasValueExpressionAtSomeTime", o6)
property(o1, "core:hasValueExpressionAtSomeTime", o7)
property(o1, "core:hasValueExpressionAtSomeTime", o8)
property(o0, "core:hasFunction", o9)
property(o9, "core:prescribedBy", o1)
property(o0, "core:hasQuality", o10)
property(o0, "des:hasName", o11)
data(o11, "des:hasTextualName", "Z4")
property(o0, "ex:connectedTo", o12)
data(o12, "rdfs:label", "OKUMA 123456 enclosure particular")
property(o12, "core:hasQuality", o13)
property(o12, "des:hasName", o14)
property(o0, "ex:connectedTo", o15)
data(o15, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
property(o15, "des:hasName", o16)
property(o17, "core:hasComponentPartAtSomeTime", o0)
@enduml
