
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMATopo

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o1, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o2, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o3, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o4, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o5, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o6, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o7, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o8, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o9, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o10, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o11, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o12, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o13, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o14, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
property(o0, "ex:joinedTo", o1)
property(o0, "ex:joinedTo", o2)
property(o3, "ex:joinedTo", o2)
property(o3, "ex:joinedTo", o4)
property(o5, "ex:joinedTo", o6)
property(o5, "ex:joinedTo", o1)
property(o7, "ex:joinedTo", o4)
property(o7, "ex:joinedTo", o8)
property(o9, "ex:joinedTo", o6)
property(o10, "ex:joinedTo", o6)
property(o10, "ex:joinedTo", o11)
property(o12, "ex:joinedTo", o11)
property(o12, "ex:joinedTo", o13)
property(o14, "ex:joinedTo", o11)
property(o14, "ex:joinedTo", o13)
@enduml
