
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o1, data:OKUMA123456EquipmentRole, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o2, data:OKUMA123456EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o3, data:OKUMA123456TurningCapability, ex:[[../Example.html#TurningCapability TurningCapability]])
individual(o4, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o5, data:name2, des:Name)
individual(o6, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o7, data:name3, des:Name)
individual(o8, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o9, data:name4, des:Name)
individual(o10, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o11, data:name5, des:Name)
individual(o12, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o13, data:name6, des:Name)
individual(o14, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o15, data:name7, des:Name)
individual(o16, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o17, data:name8, des:Name)
individual(o18, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o19, data:OKUMA123456AxesXEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o20, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o21, data:OKUMA123456AxesXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o22, data:OKUMA123456AxesXPOSITION_ACTUAL, qualphys:Displacement)
individual(o23, data:name9, des:Name)
individual(o24, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o25, data:OKUMA123456AxesYEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o26, data:okumamult_u3000axesydesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesYDesign OKUMAMULT_U3000AxesYDesign]])
individual(o27, data:OKUMA123456AxesYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o28, data:OKUMA123456AxesYPOSITION_ACTUAL, qualphys:Displacement)
individual(o29, data:name10, des:Name)
individual(o30, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o31, data:OKUMA123456AxesZ1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o32, data:okumamult_u3000axesz1design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1Design OKUMAMULT_U3000AxesZ1Design]])
individual(o33, data:OKUMA123456AxesZ1PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o34, data:OKUMA123456AxesZ1POSITION_ACTUAL, qualphys:Displacement)
individual(o35, data:name11, des:Name)
individual(o36, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o37, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o38, data:OKUMA123456AxesBEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o39, data:OKUMA123456AxesBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o40, data:OKUMA123456AxesBANGLE_ACTUAL, qualphys:Angle)
individual(o41, data:name12, des:Name)
individual(o42, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o43, data:OKUMA123456AxesC1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o44, data:OKUMA123456AxesC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o45, data:OKUMA123456AxesC1ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o46, data:OKUMA123456AxesC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o47, data:name13, des:Name)
individual(o48, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o49, data:OKUMA123456AxesZ4EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o50, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o51, data:OKUMA123456AxesZ4PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o52, data:OKUMA123456AxesZ4POSITION_ACTUAL, qualphys:Displacement)
individual(o53, data:name14, des:Name)
individual(o54, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o55, data:OKUMA123456AxesC2EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o56, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o57, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o58, data:OKUMA123456AxesC2RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o59, data:name15, des:Name)
individual(o60, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o61, data:OKUMA123456AxesC3EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o62, data:OKUMA123456AxesC3RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o63, data:OKUMA123456AxesC3ANGLE_ACTUAL, qualphys:Angle)
individual(o64, data:name16, des:Name)
individual(o65, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o66, data:OKUMA123456AxesC6EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o67, data:OKUMA123456AxesC6ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o68, data:OKUMA123456AxesC6ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o69, data:name17, des:Name)
individual(o70, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o71, data:OKUMA123456ControllerEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o72, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o73, data:OKUMA123456ControllerCONTROLLER_MODE, ex:[[../Example.html#ControllerMode ControllerMode]])
individual(o74, data:OKUMA123456ControllerEXECUTION, ex:[[../Example.html#ExecutionState ExecutionState]])
individual(o75, data:name18, des:Name)
individual(o76, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o77, data:OKUMA123456Systems1CoolantSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o78, data:name20, des:Name)
individual(o79, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o80, data:OKUMA123456Systems1ElectricSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o81, data:name21, des:Name)
individual(o82, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o83, data:OKUMA123456Systems1HydraulicSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o84, data:name22, des:Name)
individual(o85, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o86, data:OKUMA123456Systems1LubricationSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o87, data:name23, des:Name)
individual(o88, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o89, data:OKUMA123456Systems1PneumaticSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o90, data:name24, des:Name)
individual(o91, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o92, data:name25, des:Name)
individual(o93, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o94, data:name26, des:Name)
individual(o95, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o96, data:name27, des:Name)
individual(o97, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o98, data:name28, des:Name)
individual(o99, data:OKUMA123456enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o100, data:OKUMA123456enclosureTEMPERATURE, qualphys:Temperature)
individual(o101, data:name29, des:Name)
individual(o102, data:OKUMA123456MillingCapability, ex:[[../Example.html#MillingCapability MillingCapability]])
individual(o103, data:name1, des:Name)
property(o0, "core:hasRole", o1)
property(o0, "core:hasRole", o2)
property(o0, "core:hasCapability", o3)
property(o0, "core:hasComponentPartAtSomeTime", o4)
data(o4, "rdfs:label", "OKUMA 123456 struct x_axis particular")
property(o4, "des:hasName", o5)
property(o0, "core:hasComponentPartAtSomeTime", o6)
data(o6, "rdfs:label", "OKUMA 123456 struct y_axis particular")
property(o6, "des:hasName", o7)
property(o0, "core:hasComponentPartAtSomeTime", o8)
data(o8, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
property(o8, "des:hasName", o9)
property(o0, "core:hasComponentPartAtSomeTime", o10)
data(o10, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
property(o10, "des:hasName", o11)
property(o0, "core:hasComponentPartAtSomeTime", o12)
data(o12, "rdfs:label", "OKUMA 123456 struct b_axis particular")
property(o12, "des:hasName", o13)
property(o0, "core:hasComponentPartAtSomeTime", o14)
data(o14, "rdfs:label", "OKUMA 123456 struct c1_axis particular")
property(o14, "des:hasName", o15)
property(o0, "core:hasComponentPartAtSomeTime", o16)
data(o16, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
property(o16, "des:hasName", o17)
property(o0, "core:hasComponentPartAtSomeTime", o18)
data(o18, "rdfs:label", "OKUMA 123456 Axes X particular")
property(o18, "core:hasRole", o19)
property(o18, "core:prescribedBy", o20)
property(o18, "core:hasFunction", o21)
property(o18, "core:hasQuality", o22)
property(o18, "des:hasName", o23)
property(o18, "ex:connectedTo", o4)
property(o18, "ex:connectedTo", o8)
property(o0, "core:hasComponentPartAtSomeTime", o24)
data(o24, "rdfs:label", "OKUMA 123456 Axes Y particular")
property(o24, "core:hasRole", o25)
property(o24, "core:prescribedBy", o26)
property(o24, "core:hasFunction", o27)
property(o24, "core:hasQuality", o28)
property(o24, "des:hasName", o29)
property(o24, "ex:connectedTo", o4)
property(o24, "ex:connectedTo", o6)
property(o0, "core:hasComponentPartAtSomeTime", o30)
data(o30, "rdfs:label", "OKUMA 123456 Axes Z1 particular")
property(o30, "core:hasRole", o31)
property(o30, "core:prescribedBy", o32)
property(o30, "core:hasFunction", o33)
property(o30, "core:hasQuality", o34)
property(o30, "des:hasName", o35)
property(o30, "ex:connectedTo", o8)
property(o30, "ex:connectedTo", o36)
property(o0, "core:hasComponentPartAtSomeTime", o37)
data(o37, "rdfs:label", "OKUMA 123456 Axes B particular")
property(o37, "core:hasRole", o38)
property(o37, "core:hasFunction", o39)
property(o37, "core:hasQuality", o40)
property(o37, "des:hasName", o41)
property(o37, "ex:connectedTo", o6)
property(o37, "ex:connectedTo", o12)
property(o0, "core:hasComponentPartAtSomeTime", o42)
data(o42, "rdfs:label", "OKUMA 123456 Axes C1 particular")
property(o42, "core:hasRole", o43)
property(o42, "core:measuresAtSomeTime", o44)
property(o42, "core:measuresAtSomeTime", o45)
property(o42, "core:hasFunction", o46)
property(o42, "des:hasName", o47)
property(o42, "ex:connectedTo", o36)
property(o0, "core:hasComponentPartAtSomeTime", o48)
data(o48, "rdfs:label", "OKUMA 123456 Axes Z4 particular")
property(o48, "core:hasRole", o49)
property(o48, "core:prescribedBy", o50)
property(o48, "core:hasFunction", o51)
property(o48, "core:hasQuality", o52)
property(o48, "des:hasName", o53)
property(o48, "ex:connectedTo", o10)
property(o48, "ex:connectedTo", o36)
property(o0, "core:hasComponentPartAtSomeTime", o54)
data(o54, "rdfs:label", "OKUMA 123456 Axes C2 particular")
property(o54, "core:hasRole", o55)
property(o54, "core:measuresAtSomeTime", o56)
property(o54, "core:measuresAtSomeTime", o57)
property(o54, "core:hasFunction", o58)
property(o54, "des:hasName", o59)
property(o54, "ex:connectedTo", o10)
property(o54, "ex:connectedTo", o16)
property(o0, "core:hasComponentPartAtSomeTime", o60)
data(o60, "rdfs:label", "OKUMA 123456 Axes C3 particular")
property(o60, "core:hasRole", o61)
property(o60, "core:hasFunction", o62)
property(o60, "core:hasQuality", o63)
property(o60, "des:hasName", o64)
property(o60, "ex:connectedTo", o10)
property(o60, "ex:connectedTo", o16)
property(o0, "core:hasComponentPartAtSomeTime", o65)
data(o65, "rdfs:label", "OKUMA 123456 Axes C6 particular")
property(o65, "core:hasRole", o66)
property(o65, "core:measuresAtSomeTime", o67)
property(o65, "core:measuresAtSomeTime", o68)
property(o65, "des:hasName", o69)
property(o0, "core:hasComponentPartAtSomeTime", o70)
data(o70, "rdfs:label", "OKUMA 123456 Controller particular")
property(o70, "core:hasRole", o71)
property(o70, "core:hasComponentPartAtSomeTime", o72)
property(o70, "core:observesAtSomeTime", o73)
property(o70, "core:observesAtSomeTime", o74)
property(o70, "des:hasName", o75)
property(o0, "core:hasComponentPartAtSomeTime", o76)
data(o76, "rdfs:label", "OKUMA 123456 Systems1 CoolantSystem1 particular")
property(o76, "core:hasRole", o77)
property(o76, "des:hasName", o78)
property(o0, "core:hasComponentPartAtSomeTime", o79)
data(o79, "rdfs:label", "OKUMA 123456 Systems1 ElectricSystem1 particular")
property(o79, "core:hasRole", o80)
property(o79, "des:hasName", o81)
property(o0, "core:hasComponentPartAtSomeTime", o82)
data(o82, "rdfs:label", "OKUMA 123456 Systems1 HydraulicSystem1 particular")
property(o82, "core:hasRole", o83)
property(o82, "des:hasName", o84)
property(o0, "core:hasComponentPartAtSomeTime", o85)
data(o85, "rdfs:label", "OKUMA 123456 Systems1 LubricationSystem1 particular")
property(o85, "core:hasRole", o86)
property(o85, "des:hasName", o87)
property(o0, "core:hasComponentPartAtSomeTime", o88)
data(o88, "rdfs:label", "OKUMA 123456 Systems1 PneumaticSystem1 particular")
property(o88, "core:hasRole", o89)
property(o88, "des:hasName", o90)
property(o0, "core:hasComponentPartAtSomeTime", o91)
data(o91, "rdfs:label", "OKUMA 123456 LAux1 LoaderSystem1 particular")
property(o91, "des:hasName", o92)
property(o0, "core:hasComponentPartAtSomeTime", o93)
data(o93, "rdfs:label", "OKUMA 123456 LAux1 WasteDisposalSystem1 particular")
property(o93, "des:hasName", o94)
property(o0, "core:hasComponentPartAtSomeTime", o95)
data(o95, "rdfs:label", "OKUMA 123456 LAux1 ToolingDeliverySystem1 particular")
property(o95, "des:hasName", o96)
property(o0, "core:hasComponentPartAtSomeTime", o97)
data(o97, "rdfs:label", "OKUMA 123456 LAux1 BarFeederSystem1 particular")
property(o97, "des:hasName", o98)
property(o0, "core:hasComponentPartAtSomeTime", o36)
data(o36, "rdfs:label", "OKUMA 123456 enclosure particular")
property(o36, "core:hasRole", o99)
property(o36, "core:hasQuality", o100)
property(o36, "des:hasName", o101)
property(o0, "core:hasFunction", o102)
property(o0, "des:hasName", o103)
data(o103, "des:hasTextualName", "OKUMA")
@enduml
