@startuml OKUMA.123456-personnel
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor LightBlue
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456-personnel

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:[[./OKUMA.123456-personnel.html OKUMA.123456-personnel]], [[https://spec.industrialontologies.org/ontology/core/Core/Person core:Person]])
individual(o2, data:OKUMA.123456-personnel-name, cmns-dsg:Name)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, personnel)
@enduml
