
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMAMULT_U3000123456AxesC6

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMAMULT_U3000123456AxesC6.html OKUMAMULT_U3000123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o1, data:OKUMAMULT_U3000123456AxesC6ROTARY_VELOCITY_ACTUAL, ex:RevoluteVelocity)
individual(o2, data:OKUMAMULT_U3000123456AxesC6ROTARY_VELOCITY_PROGRAMMED, ex:RevoluteVelocity)
individual(o3, data:name17, des:Name)
individual(o4, data:[[./OKUMAMULT_U3000123456.html OKUMAMULT_U3000123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
property(o0, "core:measuresAtSomeTime", o1)
property(o0, "core:measuresAtSomeTime", o2)
property(o0, "des:hasName", o3)
data(o3, "des:hasTextualName", "C6")
property(o4, "core:hasComponentPartAtAllTimes", o0)
@enduml
