
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456AxesX

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o1, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o2, data:OKUMA123456AxesXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o3, data:OKUMA123456AxesXLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o4, data:OKUMA123456AxesXLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o5, data:OKUMA123456AxesXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o6, data:OKUMA123456AxesXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:OKUMA123456AxesXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o8, data:OKUMA123456AxesXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o9, data:OKUMA123456AxesXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o10, data:OKUMA123456AxesXPOSITION_ACTUAL, qualphys:Displacement)
individual(o11, data:name9, des:Name)
individual(o12, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o13, data:name4, des:Name)
individual(o14, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o15, data:name2, des:Name)
individual(o16, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
property(o0, "core:prescribedBy", o1)
data(o1, "rdfs:label", "OKUMAMULT_U3000AxesXDesign particular")
property(o1, "core:hasValueExpressionAtAllTimes", o2)
property(o1, "core:hasValueExpressionAtAllTimes", o3)
property(o1, "core:hasValueExpressionAtAllTimes", o4)
property(o1, "core:hasValueExpressionAtAllTimes", o5)
property(o1, "core:hasValueExpressionAtAllTimes", o6)
property(o1, "core:hasValueExpressionAtAllTimes", o7)
property(o1, "core:hasValueExpressionAtAllTimes", o8)
property(o0, "core:hasFunction", o9)
property(o9, "core:prescribedBy", o1)
property(o0, "core:hasQuality", o10)
property(o0, "des:hasName", o11)
data(o11, "des:hasTextualName", "X")
property(o0, "ex:connectedTo", o12)
data(o12, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
property(o12, "des:hasName", o13)
property(o0, "ex:connectedTo", o14)
data(o14, "rdfs:label", "OKUMA 123456 struct x_axis particular")
property(o14, "des:hasName", o15)
property(o16, "core:hasComponentPartAtAllTimes", o0)
@enduml
