
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456AxesB

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o1, data:OKUMA123456AxesBEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o2, data:OKUMA123456AxesBRevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o3, data:OKUMA123456AxesBANGLE_ACTUAL, qualphys:Angle)
individual(o4, data:name12, des:Name)
individual(o5, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o6, data:name3, des:Name)
individual(o7, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o8, data:name6, des:Name)
individual(o9, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
property(o0, "core:hasRole", o1)
property(o0, "core:hasFunction", o2)
property(o0, "core:hasQuality", o3)
property(o0, "des:hasName", o4)
data(o4, "des:hasTextualName", "B")
property(o0, "ex:connectedTo", o5)
data(o5, "rdfs:label", "OKUMA 123456 struct y_axis particular")
property(o5, "des:hasName", o6)
property(o0, "ex:connectedTo", o7)
data(o7, "rdfs:label", "OKUMA 123456 struct b_axis particular")
property(o7, "des:hasName", o8)
property(o9, "core:hasComponentPartAtSomeTime", o0)
@enduml
