@startuml
skinparam linetype polyline
left to right direction
object "[[./OKUMA.123456-Lc6.html data:OKUMA.123456-Lc6]]" as o1 {
 type = ex:RotaryMotionSystem
 }
object "data:OKUMA.123456-Lc6-name" as o2 {
 type = cmns-dsg:Name
 }
object "data:OKUMA.123456-Lc6-rotary_velocity-actual" as o3 {
 type = qp:Speed
 }
object "data:OKUMA.123456-Lc6-rotary_velocity-programmed" as o4 {
 type = qp:Speed
 }
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o5 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = C6
o1 --> o3 : core:measuresAtSomeTime
o1 --> o4 : core:measuresAtSomeTime
o5 --> o1 : obo:has member part at some time
@enduml
