@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-b_axis
object "[[./OKUMA.123456-b_axis.html data:OKUMA.123456-b_axis]]" as o1 {
 type: ex:Structure 
}
object "data:OKUMA.123456-b_axis-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o3 {
 type: ex:Machine 
}
object "[[./OKUMA.123456-Lb1.html data:OKUMA.123456-Lb1]]" as o4 {
 type: ex:RotaryMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: b_axis
o3 --> o1 : obo:has member part at some time
o4 --> o1 : ex:joinedTo
@enduml
