
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456AxesC3

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o1, data:OKUMA123456AxesC3RevoluteMotionCapability, ex:[[../Example.html#RevoluteMotionCapability RevoluteMotionCapability]])
individual(o2, data:OKUMA123456AxesC3ANGLE_ACTUAL, qualphys:Angle)
individual(o3, data:name16, des:Name)
individual(o4, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o5, data:name5, des:Name)
individual(o6, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o7, data:name8, des:Name)
individual(o8, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
property(o0, "core:hasFunction", o1)
property(o0, "core:hasQuality", o2)
property(o0, "des:hasName", o3)
data(o3, "des:hasTextualName", "C3")
property(o0, "ex:connectedTo", o4)
data(o4, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
property(o4, "des:hasName", o5)
property(o0, "ex:connectedTo", o6)
data(o6, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
property(o6, "des:hasName", o7)
property(o8, "core:hasComponentPartAtSomeTime", o0)
@enduml
