
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456_Axes_B

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA.123456_Axes_B.html OKUMA.123456_Axes_B]], vendor:[[../OKUMA.html#OKUMA.123456AxesB OKUMA.123456AxesB]])
individual(o1, data:OKUMA.123456_Axes_BRevoluteMotionCapability, ex:RevoluteMotionCapability)
individual(o2, data:OKUMA.123456_Axes_BANGLE_ACTUAL, qualphys:Angle)
individual(o3, data:name12, des:Name)
individual(o4, data:[[./OKUMA.123456_struct_y_axis.html OKUMA.123456_struct_y_axis]], vendor:[[../OKUMA.html#OKUMA.123456structy_axis OKUMA.123456structy_axis]])
individual(o5, data:name3, des:Name)
individual(o6, data:[[./OKUMA.123456_struct_b_axis.html OKUMA.123456_struct_b_axis]], vendor:[[../OKUMA.html#OKUMA.123456structb_axis OKUMA.123456structb_axis]])
individual(o7, data:name6, des:Name)
individual(o8, data:[[./OKUMA.123456.html OKUMA.123456]], vendor:[[../OKUMA.html#OKUMA.123456 OKUMA.123456]])
property(o0, "core:hasFunction", o1)
property(o0, "core:hasQuality", o2)
property(o0, "des:hasName", o3)
data(o3, "des:hasTextualName", "B")
property(o0, "ex:joinedTo", o4)
data(o4, "rdfs:label", "OKUMA.123456 struct y_axis particular")
property(o4, "des:hasName", o5)
property(o0, "ex:joinedTo", o6)
data(o6, "rdfs:label", "OKUMA.123456 struct b_axis particular")
property(o6, "des:hasName", o7)
property(o8, "core:hasComponentPartAtAllTimes", o0)
@enduml
