
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMAFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, vendor:ontology1, owl:Ontology)
individual(o2, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o3, data:name1, des:Name)
individual(o4, data:OKUMA123456Capability, core:Capability)
individual(o5, data:OKUMA123456EquipmentRole, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o6, data:OKUMA123456EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o7, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o8, data:name2, des:Name)
individual(o9, data:OKUMA123456structx_axisCapability, core:Capability)
individual(o10, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o11, data:name3, des:Name)
individual(o12, data:OKUMA123456structy_axisCapability, core:Capability)
individual(o13, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o14, data:name4, des:Name)
individual(o15, data:OKUMA123456structz1_axisCapability, core:Capability)
individual(o16, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o17, data:name5, des:Name)
individual(o18, data:OKUMA123456structz4_axisCapability, core:Capability)
individual(o19, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o20, data:name6, des:Name)
individual(o21, data:OKUMA123456structb_axisCapability, core:Capability)
individual(o22, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o23, data:name7, des:Name)
individual(o24, data:OKUMA123456structc1_axisCapability, core:Capability)
individual(o25, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o26, data:name8, des:Name)
individual(o27, data:OKUMA123456structc2_axisCapability, core:Capability)
individual(o28, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o29, data:name9, des:Name)
individual(o30, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o31, data:OKUMA123456AxesXLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o32, units:MilliM, units:Unit)
individual(o33, data:OKUMA123456AxesXLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o34, units:N, units:Unit)
individual(o35, data:OKUMA123456AxesXLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o36, data:OKUMA123456AxesXVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o37, units:MilliM-PER-SEC, units:Unit)
individual(o38, data:OKUMA123456AxesXVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o39, data:OKUMA123456AxesXVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o40, data:OKUMA123456AxesXVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o41, data:OKUMA123456AxesXCapability, core:Capability)
individual(o42, data:OKUMA123456AxesXPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o43, data:OKUMA123456AxesXPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o44, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o45, data:name10, des:Name)
individual(o46, data:okumamult_u3000axesydesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesYDesign OKUMAMULT_U3000AxesYDesign]])
individual(o47, data:OKUMA123456AxesYLengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o48, data:OKUMA123456AxesYLinear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o49, data:OKUMA123456AxesYLinear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o50, data:OKUMA123456AxesYVelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o51, data:OKUMA123456AxesYVelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o52, data:OKUMA123456AxesYVelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o53, data:OKUMA123456AxesYVelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o54, data:OKUMA123456AxesYCapability, core:Capability)
individual(o55, data:OKUMA123456AxesYPrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o56, data:OKUMA123456AxesYPOSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o57, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o58, data:name11, des:Name)
individual(o59, data:okumamult_u3000axesz1design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1Design OKUMAMULT_U3000AxesZ1Design]])
individual(o60, data:OKUMA123456AxesZ1LengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o61, data:OKUMA123456AxesZ1Linear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o62, data:OKUMA123456AxesZ1Linear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o63, data:OKUMA123456AxesZ1VelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o64, data:OKUMA123456AxesZ1VelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o65, data:OKUMA123456AxesZ1VelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o66, data:OKUMA123456AxesZ1VelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o67, data:OKUMA123456AxesZ1Capability, core:Capability)
individual(o68, data:OKUMA123456AxesZ1PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o69, data:OKUMA123456AxesZ1POSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o70, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o71, data:name12, des:Name)
individual(o72, data:OKUMA123456AxesBCapability, core:Capability)
individual(o73, data:OKUMA123456AxesBIndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o74, data:OKUMA123456AxesBANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o75, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o76, data:name13, des:Name)
individual(o77, data:OKUMA123456AxesC1Capability, core:Capability)
individual(o78, data:OKUMA123456AxesC1ContinuousRevoluteCapability, ex:[[../Example.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o79, data:OKUMA123456AxesC1ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o80, data:OKUMA123456AxesC1ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o81, data:[[./OKUMA123456AxesC1lc1chuck.html OKUMA123456AxesC1lc1chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1lc1chuck OKUMAMULT_U3000AxesC1lc1chuck]])
individual(o82, data:name14, des:Name)
individual(o83, data:OKUMA123456AxesC1lc1chuckCapability, core:Capability)
individual(o84, data:OKUMA123456AxesC1lc1chuckCHUCK_STATE, ex:[[../Example.html#ChuckState ChuckState]])
individual(o85, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o86, data:name15, des:Name)
individual(o87, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o88, data:OKUMA123456AxesZ4LengthNominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o89, data:OKUMA123456AxesZ4Linear_forceMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o90, data:OKUMA123456AxesZ4Linear_forceMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o91, data:OKUMA123456AxesZ4VelocityRapidMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o92, data:OKUMA123456AxesZ4VelocityRapidMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o93, data:OKUMA123456AxesZ4VelocityProgrammedMaximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o94, data:OKUMA123456AxesZ4VelocityProgrammedMinimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o95, data:OKUMA123456AxesZ4Capability, core:Capability)
individual(o96, data:OKUMA123456AxesZ4PrismaticMotionCapability, ex:[[../Example.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o97, data:OKUMA123456AxesZ4POSITION_ACTUAL, ex:[[../Example.html#Displacement Displacement]])
individual(o98, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o99, data:name16, des:Name)
individual(o100, data:OKUMA123456AxesC2Capability, core:Capability)
individual(o101, data:OKUMA123456AxesC2IndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o102, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o103, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o104, data:[[./OKUMA123456AxesC2lc2chuck.html OKUMA123456AxesC2lc2chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2lc2chuck OKUMAMULT_U3000AxesC2lc2chuck]])
individual(o105, data:name17, des:Name)
individual(o106, data:OKUMA123456AxesC2lc2chuckCapability, core:Capability)
individual(o107, data:OKUMA123456AxesC2lc2chuckCHUCK_STATE, ex:[[../Example.html#ChuckState ChuckState]])
individual(o108, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o109, data:name18, des:Name)
individual(o110, data:OKUMA123456AxesC3Capability, core:Capability)
individual(o111, data:OKUMA123456AxesC3IndexedRevoluteCapability, ex:[[../Example.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o112, data:OKUMA123456AxesC3ANGLE_ACTUAL, ex:[[../Example.html#Angle Angle]])
individual(o113, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o114, data:name19, des:Name)
individual(o115, data:OKUMA123456AxesC6Capability, core:Capability)
individual(o116, data:OKUMA123456AxesC6ROTARY_VELOCITY_ACTUAL, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o117, data:OKUMA123456AxesC6ROTARY_VELOCITY_PROGRAMMED, ex:[[../Example.html#RevoluteVelocity RevoluteVelocity]])
individual(o118, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o119, data:name20, des:Name)
individual(o120, data:OKUMA123456ControllerCapability, core:Capability)
individual(o121, data:OKUMA123456ControllerEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o122, data:OKUMA123456ControllerCONTROLLER_MODE, ex:[[../Example.html#ControllerMode ControllerMode]])
individual(o123, data:OKUMA123456ControllerEXECUTION, ex:[[../Example.html#ExecutionState ExecutionState]])
individual(o124, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o125, data:name21, des:Name)
individual(o126, data:OKUMA123456ControllerpathCapability, core:Capability)
individual(o127, data:OKUMA123456ControllerpathEngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o128, data:OKUMA123456ControllerpathPATH_POSITION_ACTUAL, ex:[[../Example.html#ThreeSpaceDisplacement ThreeSpaceDisplacement]])
individual(o129, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o130, data:name22, des:Name)
individual(o131, data:OKUMA123456Systems1CoolantSystem1Capability, core:Capability)
individual(o132, data:OKUMA123456Systems1CoolantSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o133, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o134, data:name23, des:Name)
individual(o135, data:OKUMA123456Systems1ElectricSystem1Capability, core:Capability)
individual(o136, data:OKUMA123456Systems1ElectricSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o137, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o138, data:name24, des:Name)
individual(o139, data:OKUMA123456Systems1HydraulicSystem1Capability, core:Capability)
individual(o140, data:OKUMA123456Systems1HydraulicSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o141, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o142, data:name25, des:Name)
individual(o143, data:OKUMA123456Systems1LubricationSystem1Capability, core:Capability)
individual(o144, data:OKUMA123456Systems1LubricationSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o145, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o146, data:name26, des:Name)
individual(o147, data:OKUMA123456Systems1PneumaticSystem1Capability, core:Capability)
individual(o148, data:OKUMA123456Systems1PneumaticSystem1EngineeredSystemRole, ex:[[../Example.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o149, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o150, data:name27, des:Name)
individual(o151, data:OKUMA123456LAux1LoaderSystem1Capability, core:Capability)
individual(o152, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o153, data:name28, des:Name)
individual(o154, data:OKUMA123456LAux1WasteDisposalSystem1Capability, core:Capability)
individual(o155, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o156, data:name29, des:Name)
individual(o157, data:OKUMA123456LAux1ToolingDeliverySystem1Capability, core:Capability)
individual(o158, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o159, data:name30, des:Name)
individual(o160, data:OKUMA123456LAux1BarFeederSystem1Capability, core:Capability)
individual(o161, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o162, data:name31, des:Name)
individual(o163, data:OKUMA123456enclosureCapability, core:Capability)
individual(o164, data:OKUMA123456enclosureMaterialArtifactRole, ex:[[../Example.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o165, data:OKUMA123456enclosureTEMPERATURE, ex:[[../Example.html#Temperature Temperature]])
property(o0, "owl:imports", o1)
property(o2, "des:hasName", o3)
property(o2, "core:hasCapability", o4)
property(o2, "core:hasRole", o5)
property(o2, "core:hasRole", o6)
property(o2, "ex:hasComponent", o7)
property(o7, "des:hasName", o8)
property(o7, "core:hasCapability", o9)
property(o2, "ex:hasComponent", o10)
property(o10, "des:hasName", o11)
property(o10, "core:hasCapability", o12)
property(o2, "ex:hasComponent", o13)
property(o13, "des:hasName", o14)
property(o13, "core:hasCapability", o15)
property(o2, "ex:hasComponent", o16)
property(o16, "des:hasName", o17)
property(o16, "core:hasCapability", o18)
property(o2, "ex:hasComponent", o19)
property(o19, "des:hasName", o20)
property(o19, "core:hasCapability", o21)
property(o2, "ex:hasComponent", o22)
property(o22, "des:hasName", o23)
property(o22, "core:hasCapability", o24)
property(o2, "ex:hasComponent", o25)
property(o25, "des:hasName", o26)
property(o25, "core:hasCapability", o27)
property(o2, "ex:hasComponent", o28)
property(o28, "des:hasName", o29)
property(o28, "core:prescribedBy", o30)
property(o30, "core:hasValueExpressionAtSomeTime", o31)
property(o31, "ex:hasUnit", o32)
property(o30, "core:hasValueExpressionAtSomeTime", o33)
property(o33, "ex:hasUnit", o34)
property(o30, "core:hasValueExpressionAtSomeTime", o35)
property(o35, "ex:hasUnit", o34)
property(o30, "core:hasValueExpressionAtSomeTime", o36)
property(o36, "ex:hasUnit", o37)
property(o30, "core:hasValueExpressionAtSomeTime", o38)
property(o38, "ex:hasUnit", o37)
property(o30, "core:hasValueExpressionAtSomeTime", o39)
property(o39, "ex:hasUnit", o37)
property(o30, "core:hasValueExpressionAtSomeTime", o40)
property(o40, "ex:hasUnit", o37)
property(o28, "core:hasCapability", o41)
property(o28, "core:hasFunction", o42)
property(o42, "core:prescribedBy", o30)
property(o28, "core:hasQuality", o43)
property(o2, "ex:hasComponent", o44)
property(o44, "des:hasName", o45)
property(o44, "core:prescribedBy", o46)
property(o46, "core:hasValueExpressionAtSomeTime", o47)
property(o47, "ex:hasUnit", o32)
property(o46, "core:hasValueExpressionAtSomeTime", o48)
property(o48, "ex:hasUnit", o34)
property(o46, "core:hasValueExpressionAtSomeTime", o49)
property(o49, "ex:hasUnit", o34)
property(o46, "core:hasValueExpressionAtSomeTime", o50)
property(o50, "ex:hasUnit", o37)
property(o46, "core:hasValueExpressionAtSomeTime", o51)
property(o51, "ex:hasUnit", o37)
property(o46, "core:hasValueExpressionAtSomeTime", o52)
property(o52, "ex:hasUnit", o37)
property(o46, "core:hasValueExpressionAtSomeTime", o53)
property(o53, "ex:hasUnit", o37)
property(o44, "core:hasCapability", o54)
property(o44, "core:hasFunction", o55)
property(o55, "core:prescribedBy", o46)
property(o44, "core:hasQuality", o56)
property(o2, "ex:hasComponent", o57)
property(o57, "des:hasName", o58)
property(o57, "core:prescribedBy", o59)
property(o59, "core:hasValueExpressionAtSomeTime", o60)
property(o60, "ex:hasUnit", o32)
property(o59, "core:hasValueExpressionAtSomeTime", o61)
property(o61, "ex:hasUnit", o34)
property(o59, "core:hasValueExpressionAtSomeTime", o62)
property(o62, "ex:hasUnit", o34)
property(o59, "core:hasValueExpressionAtSomeTime", o63)
property(o63, "ex:hasUnit", o37)
property(o59, "core:hasValueExpressionAtSomeTime", o64)
property(o64, "ex:hasUnit", o37)
property(o59, "core:hasValueExpressionAtSomeTime", o65)
property(o65, "ex:hasUnit", o37)
property(o59, "core:hasValueExpressionAtSomeTime", o66)
property(o66, "ex:hasUnit", o37)
property(o57, "core:hasCapability", o67)
property(o57, "core:hasFunction", o68)
property(o68, "core:prescribedBy", o59)
property(o57, "core:hasQuality", o69)
property(o2, "ex:hasComponent", o70)
property(o70, "des:hasName", o71)
property(o70, "core:hasCapability", o72)
property(o70, "core:hasFunction", o73)
property(o70, "core:hasQuality", o74)
property(o2, "ex:hasComponent", o75)
property(o75, "des:hasName", o76)
property(o75, "core:hasCapability", o77)
property(o75, "core:hasFunction", o78)
property(o75, "core:measuresAtSomeTime", o79)
property(o75, "core:measuresAtSomeTime", o80)
property(o75, "ex:hasComponent", o81)
property(o81, "des:hasName", o82)
property(o81, "core:hasCapability", o83)
property(o81, "core:observesAtSomeTime", o84)
property(o2, "ex:hasComponent", o85)
property(o85, "des:hasName", o86)
property(o85, "core:prescribedBy", o87)
property(o87, "core:hasValueExpressionAtSomeTime", o88)
property(o88, "ex:hasUnit", o32)
property(o87, "core:hasValueExpressionAtSomeTime", o89)
property(o89, "ex:hasUnit", o34)
property(o87, "core:hasValueExpressionAtSomeTime", o90)
property(o90, "ex:hasUnit", o34)
property(o87, "core:hasValueExpressionAtSomeTime", o91)
property(o91, "ex:hasUnit", o37)
property(o87, "core:hasValueExpressionAtSomeTime", o92)
property(o92, "ex:hasUnit", o37)
property(o87, "core:hasValueExpressionAtSomeTime", o93)
property(o93, "ex:hasUnit", o37)
property(o87, "core:hasValueExpressionAtSomeTime", o94)
property(o94, "ex:hasUnit", o37)
property(o85, "core:hasCapability", o95)
property(o85, "core:hasFunction", o96)
property(o96, "core:prescribedBy", o87)
property(o85, "core:hasQuality", o97)
property(o2, "ex:hasComponent", o98)
property(o98, "des:hasName", o99)
property(o98, "core:hasCapability", o100)
property(o98, "core:hasFunction", o101)
property(o98, "core:measuresAtSomeTime", o102)
property(o98, "core:measuresAtSomeTime", o103)
property(o98, "ex:hasComponent", o104)
property(o104, "des:hasName", o105)
property(o104, "core:hasCapability", o106)
property(o104, "core:observesAtSomeTime", o107)
property(o2, "ex:hasComponent", o108)
property(o108, "des:hasName", o109)
property(o108, "core:hasCapability", o110)
property(o108, "core:hasFunction", o111)
property(o108, "core:hasQuality", o112)
property(o2, "ex:hasComponent", o113)
property(o113, "des:hasName", o114)
property(o113, "core:hasCapability", o115)
property(o113, "core:measuresAtSomeTime", o116)
property(o113, "core:measuresAtSomeTime", o117)
property(o2, "ex:hasComponent", o118)
property(o118, "des:hasName", o119)
property(o118, "core:hasCapability", o120)
property(o118, "core:hasRole", o121)
property(o118, "core:observesAtSomeTime", o122)
property(o118, "core:observesAtSomeTime", o123)
property(o118, "ex:hasComponent", o124)
property(o124, "des:hasName", o125)
property(o124, "core:hasCapability", o126)
property(o124, "core:hasRole", o127)
property(o124, "core:hasQuality", o128)
property(o2, "ex:hasComponent", o129)
property(o129, "des:hasName", o130)
property(o129, "core:hasCapability", o131)
property(o129, "core:hasRole", o132)
property(o2, "ex:hasComponent", o133)
property(o133, "des:hasName", o134)
property(o133, "core:hasCapability", o135)
property(o133, "core:hasRole", o136)
property(o2, "ex:hasComponent", o137)
property(o137, "des:hasName", o138)
property(o137, "core:hasCapability", o139)
property(o137, "core:hasRole", o140)
property(o2, "ex:hasComponent", o141)
property(o141, "des:hasName", o142)
property(o141, "core:hasCapability", o143)
property(o141, "core:hasRole", o144)
property(o2, "ex:hasComponent", o145)
property(o145, "des:hasName", o146)
property(o145, "core:hasCapability", o147)
property(o145, "core:hasRole", o148)
property(o2, "ex:hasComponent", o149)
property(o149, "des:hasName", o150)
property(o149, "core:hasCapability", o151)
property(o2, "ex:hasComponent", o152)
property(o152, "des:hasName", o153)
property(o152, "core:hasCapability", o154)
property(o2, "ex:hasComponent", o155)
property(o155, "des:hasName", o156)
property(o155, "core:hasCapability", o157)
property(o2, "ex:hasComponent", o158)
property(o158, "des:hasName", o159)
property(o158, "core:hasCapability", o160)
property(o2, "ex:hasComponent", o161)
property(o161, "des:hasName", o162)
property(o161, "core:hasCapability", o163)
property(o161, "core:hasRole", o164)
property(o161, "core:hasQuality", o165)
property(o28, "ex:connectedTo", o13)
property(o28, "ex:connectedTo", o7)
property(o44, "ex:connectedTo", o7)
property(o44, "ex:connectedTo", o10)
property(o57, "ex:connectedTo", o161)
property(o57, "ex:connectedTo", o13)
property(o70, "ex:connectedTo", o10)
property(o70, "ex:connectedTo", o19)
property(o75, "ex:connectedTo", o161)
property(o85, "ex:connectedTo", o161)
property(o85, "ex:connectedTo", o16)
property(o98, "ex:connectedTo", o16)
property(o98, "ex:connectedTo", o25)
property(o108, "ex:connectedTo", o16)
property(o108, "ex:connectedTo", o25)
data(o2, "rdfs:label", "OKUMA 123456 particular")
data(o3, "des:hasTextualName", "OKUMA")
data(o7, "rdfs:label", "OKUMA 123456 struct x_axis particular")
data(o8, "des:hasTextualName", "x_axis")
data(o10, "rdfs:label", "OKUMA 123456 struct y_axis particular")
data(o11, "des:hasTextualName", "y_axis")
data(o13, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
data(o14, "des:hasTextualName", "z1_axis")
data(o16, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
data(o17, "des:hasTextualName", "z4_axis")
data(o19, "rdfs:label", "OKUMA 123456 struct b_axis particular")
data(o20, "des:hasTextualName", "b_axis")
data(o22, "rdfs:label", "OKUMA 123456 struct c1_axis particular")
data(o23, "des:hasTextualName", "c1_axis")
data(o25, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
data(o26, "des:hasTextualName", "c2_axis")
data(o28, "rdfs:label", "OKUMA 123456 Axes X particular")
data(o29, "des:hasTextualName", "X")
data(o30, "rdfs:label", "OKUMAMULT_U3000AxesXDesign particular")
data(o31, "core:hasSimpleExpressionValue", "650.0")
data(o33, "core:hasSimpleExpressionValue", "5200.0")
data(o35, "core:hasSimpleExpressionValue", "0.0")
data(o36, "core:hasSimpleExpressionValue", "7000.0")
data(o38, "core:hasSimpleExpressionValue", "1.0")
data(o39, "core:hasSimpleExpressionValue", "7000.0")
data(o40, "core:hasSimpleExpressionValue", "1.0")
data(o44, "rdfs:label", "OKUMA 123456 Axes Y particular")
data(o45, "des:hasTextualName", "Y")
data(o46, "rdfs:label", "OKUMAMULT_U3000AxesYDesign particular")
data(o47, "core:hasSimpleExpressionValue", "650.0")
data(o48, "core:hasSimpleExpressionValue", "5200.0")
data(o49, "core:hasSimpleExpressionValue", "0.0")
data(o50, "core:hasSimpleExpressionValue", "7000.0")
data(o51, "core:hasSimpleExpressionValue", "1.0")
data(o52, "core:hasSimpleExpressionValue", "7000.0")
data(o53, "core:hasSimpleExpressionValue", "1.0")
data(o57, "rdfs:label", "OKUMA 123456 Axes Z1 particular")
data(o58, "des:hasTextualName", "Z1")
data(o59, "rdfs:label", "OKUMAMULT_U3000AxesZ1Design particular")
data(o60, "core:hasSimpleExpressionValue", "650.0")
data(o61, "core:hasSimpleExpressionValue", "5200.0")
data(o62, "core:hasSimpleExpressionValue", "0.0")
data(o63, "core:hasSimpleExpressionValue", "7000.0")
data(o64, "core:hasSimpleExpressionValue", "1.0")
data(o65, "core:hasSimpleExpressionValue", "7000.0")
data(o66, "core:hasSimpleExpressionValue", "1.0")
data(o70, "rdfs:label", "OKUMA 123456 Axes B particular")
data(o71, "des:hasTextualName", "B")
data(o75, "rdfs:label", "OKUMA 123456 Axes C1 particular")
data(o76, "des:hasTextualName", "C1")
data(o81, "rdfs:label", "OKUMA 123456 Axes C1 lc1chuck particular")
data(o82, "des:hasTextualName", "lc1chuck")
data(o85, "rdfs:label", "OKUMA 123456 Axes Z4 particular")
data(o86, "des:hasTextualName", "Z4")
data(o87, "rdfs:label", "OKUMAMULT_U3000AxesZ4Design particular")
data(o88, "core:hasSimpleExpressionValue", "650.0")
data(o89, "core:hasSimpleExpressionValue", "5200.0")
data(o90, "core:hasSimpleExpressionValue", "0.0")
data(o91, "core:hasSimpleExpressionValue", "7000.0")
data(o92, "core:hasSimpleExpressionValue", "1.0")
data(o93, "core:hasSimpleExpressionValue", "7000.0")
data(o94, "core:hasSimpleExpressionValue", "1.0")
data(o98, "rdfs:label", "OKUMA 123456 Axes C2 particular")
data(o99, "des:hasTextualName", "C2")
data(o104, "rdfs:label", "OKUMA 123456 Axes C2 lc2chuck particular")
data(o105, "des:hasTextualName", "lc2chuck")
data(o108, "rdfs:label", "OKUMA 123456 Axes C3 particular")
data(o109, "des:hasTextualName", "C3")
data(o113, "rdfs:label", "OKUMA 123456 Axes C6 particular")
data(o114, "des:hasTextualName", "C6")
data(o118, "rdfs:label", "OKUMA 123456 Controller particular")
data(o119, "des:hasTextualName", "Controller")
data(o124, "rdfs:label", "OKUMA 123456 Controller path particular")
data(o125, "des:hasTextualName", "path")
data(o129, "rdfs:label", "OKUMA 123456 Systems1 CoolantSystem1 particular")
data(o130, "des:hasTextualName", "CoolantSystem1")
data(o133, "rdfs:label", "OKUMA 123456 Systems1 ElectricSystem1 particular")
data(o134, "des:hasTextualName", "ElectricSystem1")
data(o137, "rdfs:label", "OKUMA 123456 Systems1 HydraulicSystem1 particular")
data(o138, "des:hasTextualName", "HydraulicSystem1")
data(o141, "rdfs:label", "OKUMA 123456 Systems1 LubricationSystem1 particular")
data(o142, "des:hasTextualName", "LubricationSystem1")
data(o145, "rdfs:label", "OKUMA 123456 Systems1 PneumaticSystem1 particular")
data(o146, "des:hasTextualName", "PneumaticSystem1")
data(o149, "rdfs:label", "OKUMA 123456 LAux1 LoaderSystem1 particular")
data(o150, "des:hasTextualName", "LoaderSystem1")
data(o152, "rdfs:label", "OKUMA 123456 LAux1 WasteDisposalSystem1 particular")
data(o153, "des:hasTextualName", "WasteDisposalSystem1")
data(o155, "rdfs:label", "OKUMA 123456 LAux1 ToolingDeliverySystem1 particular")
data(o156, "des:hasTextualName", "ToolingDeliverySystem1")
data(o158, "rdfs:label", "OKUMA 123456 LAux1 BarFeederSystem1 particular")
data(o159, "des:hasTextualName", "BarFeederSystem1")
data(o161, "rdfs:label", "OKUMA 123456 enclosure particular")
data(o162, "des:hasTextualName", "enclosure")
@enduml
