
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMAMere

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o1, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o2, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o3, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o4, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o5, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o6, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o7, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o8, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o9, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o10, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o11, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o12, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o13, data:[[./OKUMA123456AxesC1lc1chuck.html OKUMA123456AxesC1lc1chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1lc1chuck OKUMAMULT_U3000AxesC1lc1chuck]])
individual(o14, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o15, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o16, data:[[./OKUMA123456AxesC2lc2chuck.html OKUMA123456AxesC2lc2chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2lc2chuck OKUMAMULT_U3000AxesC2lc2chuck]])
individual(o17, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o18, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o19, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o20, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o21, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o22, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o23, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o24, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o25, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o26, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o27, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o28, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o29, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o30, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
property(o0, "_:hasComponent", o1)
property(o0, "_:hasComponent", o2)
property(o0, "_:hasComponent", o3)
property(o0, "_:hasComponent", o4)
property(o0, "_:hasComponent", o5)
property(o0, "_:hasComponent", o6)
property(o0, "_:hasComponent", o7)
property(o0, "_:hasComponent", o8)
property(o0, "_:hasComponent", o9)
property(o0, "_:hasComponent", o10)
property(o0, "_:hasComponent", o11)
property(o0, "_:hasComponent", o12)
property(o12, "_:hasComponent", o13)
property(o0, "_:hasComponent", o14)
property(o0, "_:hasComponent", o15)
property(o15, "_:hasComponent", o16)
property(o0, "_:hasComponent", o17)
property(o0, "_:hasComponent", o18)
property(o0, "_:hasComponent", o19)
property(o19, "_:hasComponent", o20)
property(o0, "_:hasComponent", o21)
property(o0, "_:hasComponent", o22)
property(o0, "_:hasComponent", o23)
property(o0, "_:hasComponent", o24)
property(o0, "_:hasComponent", o25)
property(o0, "_:hasComponent", o26)
property(o0, "_:hasComponent", o27)
property(o0, "_:hasComponent", o28)
property(o0, "_:hasComponent", o29)
property(o0, "_:hasComponent", o30)
@enduml
