@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-Lx1
object "[[./OKUMA.123456-Lx1.html data:OKUMA.123456-Lx1]]" as o1 {
 type = ex:LinearMotionSystem
 }
object "data:OKUMA.123456-Lx1-name" as o2 {
 type = cmns-dsg:Name
 }
object "data:OKUMA.123456-Lx1-spec" as o3 {
 type = core:DesignSpecification
 }
object "data:OKUMA.123456-Lx1-spec-LENGTH-Nominal" as o4 {
 type = core:ValueExpression
 }
object "data:OKUMA.123456-Lx1-spec-LINEAR_FORCE-Maximum" as o5 {
 type = core:ValueExpression
 }
object "data:OKUMA.123456-Lx1-spec-LINEAR_FORCE-Minimum" as o6 {
 type = core:ValueExpression
 }
object "data:OKUMA.123456-Lx1-spec-VELOCITY-RAPID-Maximum" as o7 {
 type = core:ValueExpression
 }
object "data:OKUMA.123456-Lx1-spec-VELOCITY-RAPID-Minimum" as o8 {
 type = core:ValueExpression
 }
object "data:OKUMA.123456-Lx1-spec-VELOCITY-PROGRAMMED-Maximum" as o9 {
 type = core:ValueExpression
 }
object "data:OKUMA.123456-Lx1-spec-VELOCITY-PROGRAMMED-Minimum" as o10 {
 type = core:ValueExpression
 }
object "[[./OKUMA.123456-z1_axis.html data:OKUMA.123456-z1_axis]]" as o11 {
 type = ex:Structure
 }
object "data:OKUMA.123456-z1_axis-name" as o12 {
 type = cmns-dsg:Name
 }
object "[[./OKUMA.123456-x_axis.html data:OKUMA.123456-x_axis]]" as o13 {
 type = ex:Structure
 }
object "data:OKUMA.123456-x_axis-name" as o14 {
 type = cmns-dsg:Name
 }
object "data:OKUMA.123456-Lx1-function" as o15 {
 type = ex:PrismaticMotionCapability
 }
object "data:OKUMA.123456-Lx1-position-actual" as o16 {
 type = qp:Displacement
 }
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o17 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = X
o1 --> o3 : core:prescribedBy
o3 --> o4 : core:hasValueExpressionAtAllTimes
o4 : core:hasSimpleExpressionValue = 650.0
o3 --> o5 : core:hasValueExpressionAtAllTimes
o5 : core:hasSimpleExpressionValue = 5200.0
o3 --> o6 : core:hasValueExpressionAtAllTimes
o6 : core:hasSimpleExpressionValue = 0.0
o3 --> o7 : core:hasValueExpressionAtAllTimes
o7 : core:hasSimpleExpressionValue = 7000.0
o3 --> o8 : core:hasValueExpressionAtAllTimes
o8 : core:hasSimpleExpressionValue = 1.0
o3 --> o9 : core:hasValueExpressionAtAllTimes
o9 : core:hasSimpleExpressionValue = 7000.0
o3 --> o10 : core:hasValueExpressionAtAllTimes
o10 : core:hasSimpleExpressionValue = 1.0
o1 --> o11 : ex:joinedTo
o11 --> o12 : cmns-dsg:hasName
o12 : core:hasSimpleExpressionValue = z1_axis
o1 --> o13 : ex:joinedTo
o13 --> o14 : cmns-dsg:hasName
o14 : core:hasSimpleExpressionValue = x_axis
o1 --> o15 : core:hasFunction
o1 --> o16 : core:measuresAtSomeTime
o17 --> o1 : obo:has member part at some time
@enduml
