@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-Lct1-Lp1
object "[[./OKUMA.123456-Lct1-Lp1.html data:OKUMA.123456-Lct1-Lp1]]" as o1 {
 type = ex:ControlSystemPath
 }
object "data:OKUMA.123456-Lct1-Lp1-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./OKUMA.123456-Lct1.html data:OKUMA.123456-Lct1]]" as o3 {
 type = ex:ControlSystem
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = path
o3 --> o1 : obo:has member part at some time
@enduml
