@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-LYI1
object "[[./OKUMA.123456-LYI1.html data:OKUMA.123456-LYI1]]" as o1 {
 type: ex:LinearMotionSystem 
}
object "data:OKUMA.123456-LYI1-name" as o2 {
 type: cmns-dsg:Name 
}
object "data:OKUMA.123456-LYI1-spec" as o3 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]] 
}
object "data:OKUMA.123456-LYI1-spec-LENGTH-Nominal" as o4 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "data:OKUMA.123456-LYI1-spec-LINEAR_FORCE-Maximum" as o5 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "data:OKUMA.123456-LYI1-spec-LINEAR_FORCE-Minimum" as o6 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "data:OKUMA.123456-LYI1-spec-VELOCITY-RAPID-Maximum" as o7 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "data:OKUMA.123456-LYI1-spec-VELOCITY-RAPID-Minimum" as o8 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "data:OKUMA.123456-LYI1-spec-VELOCITY-PROGRAMMED-Maximum" as o9 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "data:OKUMA.123456-LYI1-spec-VELOCITY-PROGRAMMED-Minimum" as o10 {
 type: [[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression core:ValueExpression]] 
}
object "[[./OKUMA.123456-x_axis.html data:OKUMA.123456-x_axis]]" as o11 {
 type: ex:Structure 
}
object "data:OKUMA.123456-x_axis-name" as o12 {
 type: cmns-dsg:Name 
}
object "[[./OKUMA.123456-y_axis.html data:OKUMA.123456-y_axis]]" as o13 {
 type: ex:Structure 
}
object "data:OKUMA.123456-y_axis-name" as o14 {
 type: cmns-dsg:Name 
}
object "data:OKUMA.123456-LYI1-function" as o15 {
 type: ex:PrismaticMotionCapability 
}
object "data:OKUMA.123456-LYI1-position-actual" as o16 {
 type: qp:Displacement 
}
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o17 {
 type: ex:Machine 
}
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: Y
o1 --> o3 : [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]]
o3 --> o4 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o4 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 650.0
o3 --> o5 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o5 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 5200.0
o3 --> o6 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o6 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 0.0
o3 --> o7 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o7 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 7000.0
o3 --> o8 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o8 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 1.0
o3 --> o9 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o9 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 7000.0
o3 --> o10 : [[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes core:hasValueExpressionAtAllTimes]]
o10 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: 1.0
o1 --> o11 : ex:joinedTo
o11 --> o12 : cmns-dsg:hasName
o1 --> o13 : ex:joinedTo
o13 --> o14 : cmns-dsg:hasName
o1 --> o15 : [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]]
o1 --> o16 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o17 --> o1 : obo:has member part at some time
@enduml
