@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-x_axis
object "[[./OKUMA.123456-x_axis.html data:OKUMA.123456-x_axis]]" as o1 {
 type: ex:Structure 
}
object "data:OKUMA.123456-x_axis-name" as o2 {
 type: cmns-dsg:Name 
}
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o3 {
 type: ex:Machine 
}
object "[[./OKUMA.123456-Lx1.html data:OKUMA.123456-Lx1]]" as o4 {
 type: ex:LinearMotionSystem 
}
object "[[./OKUMA.123456-LYI1.html data:OKUMA.123456-LYI1]]" as o5 {
 type: ex:LinearMotionSystem 
}
o1 --> o2 : cmns-dsg:hasName
o2 : [[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue core:hasSimpleExpressionValue]]: x_axis
o3 --> o1 : obo:has member part at some time
o4 --> o1 : ex:joinedTo
o5 --> o1 : ex:joinedTo
@enduml
