
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o1, data:OKUMA123456EquipmentRole, _:EquipmentRole)
individual(o2, data:OKUMA123456EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o3, data:OKUMA123456Capability, _:Capability)
individual(o4, data:name1, des:Name)
individual(o5, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o6, data:OKUMA123456structx_axisCapability, _:Capability)
individual(o7, data:name2, des:Name)
individual(o8, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o9, data:OKUMA123456structy_axisCapability, _:Capability)
individual(o10, data:name3, des:Name)
individual(o11, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o12, data:OKUMA123456structz1_axisCapability, _:Capability)
individual(o13, data:name4, des:Name)
individual(o14, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o15, data:OKUMA123456structz4_axisCapability, _:Capability)
individual(o16, data:name5, des:Name)
individual(o17, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o18, data:OKUMA123456structb_axisCapability, _:Capability)
individual(o19, data:name6, des:Name)
individual(o20, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o21, data:OKUMA123456structc1_axisCapability, _:Capability)
individual(o22, data:name7, des:Name)
individual(o23, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o24, data:OKUMA123456structc2_axisCapability, _:Capability)
individual(o25, data:name8, des:Name)
individual(o26, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o27, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o28, data:OKUMA123456AxesXCapability, _:Capability)
individual(o29, data:OKUMA123456AxesXPrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o30, data:OKUMA123456AxesXPOSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o31, data:name9, des:Name)
individual(o32, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o33, data:okumamult_u3000axesydesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesYDesign OKUMAMULT_U3000AxesYDesign]])
individual(o34, data:OKUMA123456AxesYCapability, _:Capability)
individual(o35, data:OKUMA123456AxesYPrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o36, data:OKUMA123456AxesYPOSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o37, data:name10, des:Name)
individual(o38, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o39, data:okumamult_u3000axesz1design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1Design OKUMAMULT_U3000AxesZ1Design]])
individual(o40, data:OKUMA123456AxesZ1Capability, _:Capability)
individual(o41, data:OKUMA123456AxesZ1PrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o42, data:OKUMA123456AxesZ1POSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o43, data:name11, des:Name)
individual(o44, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o45, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o46, data:OKUMA123456AxesBCapability, _:Capability)
individual(o47, data:OKUMA123456AxesBIndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o48, data:OKUMA123456AxesBANGLE_ACTUAL, _:[[../MTConnect.html#Angle Angle]])
individual(o49, data:name12, des:Name)
individual(o50, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o51, data:OKUMA123456AxesC1Capability, _:Capability)
individual(o52, data:OKUMA123456AxesC1ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o53, data:OKUMA123456AxesC1ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o54, data:OKUMA123456AxesC1ContinuousRevoluteCapability, _:[[../MTConnect.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o55, data:name13, des:Name)
individual(o56, data:[[./OKUMA123456AxesC1lc1chuck.html OKUMA123456AxesC1lc1chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1lc1chuck OKUMAMULT_U3000AxesC1lc1chuck]])
individual(o57, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o58, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o59, data:OKUMA123456AxesZ4Capability, _:Capability)
individual(o60, data:OKUMA123456AxesZ4PrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o61, data:OKUMA123456AxesZ4POSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o62, data:name15, des:Name)
individual(o63, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o64, data:OKUMA123456AxesC2Capability, _:Capability)
individual(o65, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o66, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o67, data:OKUMA123456AxesC2IndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o68, data:name16, des:Name)
individual(o69, data:[[./OKUMA123456AxesC2lc2chuck.html OKUMA123456AxesC2lc2chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2lc2chuck OKUMAMULT_U3000AxesC2lc2chuck]])
individual(o70, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o71, data:OKUMA123456AxesC3Capability, _:Capability)
individual(o72, data:OKUMA123456AxesC3IndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o73, data:OKUMA123456AxesC3ANGLE_ACTUAL, _:[[../MTConnect.html#Angle Angle]])
individual(o74, data:name18, des:Name)
individual(o75, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o76, data:OKUMA123456AxesC6Capability, _:Capability)
individual(o77, data:OKUMA123456AxesC6ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o78, data:OKUMA123456AxesC6ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o79, data:name19, des:Name)
individual(o80, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o81, data:OKUMA123456ControllerEngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o82, data:OKUMA123456ControllerCapability, _:Capability)
individual(o83, data:OKUMA123456ControllerCONTROLLER_MODE, _:[[../MTConnect.html#ControllerMode ControllerMode]])
individual(o84, data:OKUMA123456ControllerEXECUTION, _:[[../MTConnect.html#ExecutionState ExecutionState]])
individual(o85, data:name20, des:Name)
individual(o86, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o87, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o88, data:OKUMA123456Systems1CoolantSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o89, data:OKUMA123456Systems1CoolantSystem1Capability, _:Capability)
individual(o90, data:name22, des:Name)
individual(o91, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o92, data:OKUMA123456Systems1ElectricSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o93, data:OKUMA123456Systems1ElectricSystem1Capability, _:Capability)
individual(o94, data:name23, des:Name)
individual(o95, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o96, data:OKUMA123456Systems1HydraulicSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o97, data:OKUMA123456Systems1HydraulicSystem1Capability, _:Capability)
individual(o98, data:name24, des:Name)
individual(o99, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o100, data:OKUMA123456Systems1LubricationSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o101, data:OKUMA123456Systems1LubricationSystem1Capability, _:Capability)
individual(o102, data:name25, des:Name)
individual(o103, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o104, data:OKUMA123456Systems1PneumaticSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o105, data:OKUMA123456Systems1PneumaticSystem1Capability, _:Capability)
individual(o106, data:name26, des:Name)
individual(o107, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o108, data:OKUMA123456LAux1LoaderSystem1Capability, _:Capability)
individual(o109, data:name27, des:Name)
individual(o110, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o111, data:OKUMA123456LAux1WasteDisposalSystem1Capability, _:Capability)
individual(o112, data:name28, des:Name)
individual(o113, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o114, data:OKUMA123456LAux1ToolingDeliverySystem1Capability, _:Capability)
individual(o115, data:name29, des:Name)
individual(o116, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o117, data:OKUMA123456LAux1BarFeederSystem1Capability, _:Capability)
individual(o118, data:name30, des:Name)
individual(o119, data:OKUMA123456enclosureMaterialArtifactRole, _:[[../MTConnect.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o120, data:OKUMA123456enclosureCapability, _:Capability)
individual(o121, data:OKUMA123456enclosureTEMPERATURE, _:[[../MTConnect.html#Temperature Temperature]])
individual(o122, data:name31, des:Name)
property(o0, "_:hasRole", o1)
property(o0, "_:hasRole", o2)
property(o0, "_:hasCapability", o3)
property(o0, "des:hasName", o4)
data(o4, "des:hasTextualName", "OKUMA")
property(o0, "_:hasComponent", o5)
data(o5, "rdfs:label", "OKUMA 123456 struct x_axis particular")
property(o5, "_:hasCapability", o6)
property(o5, "des:hasName", o7)
property(o0, "_:hasComponent", o8)
data(o8, "rdfs:label", "OKUMA 123456 struct y_axis particular")
property(o8, "_:hasCapability", o9)
property(o8, "des:hasName", o10)
property(o0, "_:hasComponent", o11)
data(o11, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
property(o11, "_:hasCapability", o12)
property(o11, "des:hasName", o13)
property(o0, "_:hasComponent", o14)
data(o14, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
property(o14, "_:hasCapability", o15)
property(o14, "des:hasName", o16)
property(o0, "_:hasComponent", o17)
data(o17, "rdfs:label", "OKUMA 123456 struct b_axis particular")
property(o17, "_:hasCapability", o18)
property(o17, "des:hasName", o19)
property(o0, "_:hasComponent", o20)
data(o20, "rdfs:label", "OKUMA 123456 struct c1_axis particular")
property(o20, "_:hasCapability", o21)
property(o20, "des:hasName", o22)
property(o0, "_:hasComponent", o23)
data(o23, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
property(o23, "_:hasCapability", o24)
property(o23, "des:hasName", o25)
property(o0, "_:hasComponent", o26)
data(o26, "rdfs:label", "OKUMA 123456 Axes X particular")
property(o26, "_:prescribedBy", o27)
property(o26, "_:hasCapability", o28)
property(o26, "_:hasFunction", o29)
property(o26, "_:hasQuality", o30)
property(o26, "des:hasName", o31)
property(o26, "_:connectedTo", o5)
property(o26, "_:connectedTo", o11)
property(o0, "_:hasComponent", o32)
data(o32, "rdfs:label", "OKUMA 123456 Axes Y particular")
property(o32, "_:prescribedBy", o33)
property(o32, "_:hasCapability", o34)
property(o32, "_:hasFunction", o35)
property(o32, "_:hasQuality", o36)
property(o32, "des:hasName", o37)
property(o32, "_:connectedTo", o5)
property(o32, "_:connectedTo", o8)
property(o0, "_:hasComponent", o38)
data(o38, "rdfs:label", "OKUMA 123456 Axes Z1 particular")
property(o38, "_:prescribedBy", o39)
property(o38, "_:hasCapability", o40)
property(o38, "_:hasFunction", o41)
property(o38, "_:hasQuality", o42)
property(o38, "des:hasName", o43)
property(o38, "_:connectedTo", o11)
property(o38, "_:connectedTo", o44)
property(o0, "_:hasComponent", o45)
data(o45, "rdfs:label", "OKUMA 123456 Axes B particular")
property(o45, "_:hasCapability", o46)
property(o45, "_:hasFunction", o47)
property(o45, "_:hasQuality", o48)
property(o45, "des:hasName", o49)
property(o45, "_:connectedTo", o8)
property(o45, "_:connectedTo", o17)
property(o0, "_:hasComponent", o50)
data(o50, "rdfs:label", "OKUMA 123456 Axes C1 particular")
property(o50, "_:hasCapability", o51)
property(o50, "_:measuresAtSomeTime", o52)
property(o50, "_:measuresAtSomeTime", o53)
property(o50, "_:hasFunction", o54)
property(o50, "des:hasName", o55)
property(o50, "_:hasComponent", o56)
property(o50, "_:connectedTo", o44)
property(o0, "_:hasComponent", o57)
data(o57, "rdfs:label", "OKUMA 123456 Axes Z4 particular")
property(o57, "_:prescribedBy", o58)
property(o57, "_:hasCapability", o59)
property(o57, "_:hasFunction", o60)
property(o57, "_:hasQuality", o61)
property(o57, "des:hasName", o62)
property(o57, "_:connectedTo", o14)
property(o57, "_:connectedTo", o44)
property(o0, "_:hasComponent", o63)
data(o63, "rdfs:label", "OKUMA 123456 Axes C2 particular")
property(o63, "_:hasCapability", o64)
property(o63, "_:measuresAtSomeTime", o65)
property(o63, "_:measuresAtSomeTime", o66)
property(o63, "_:hasFunction", o67)
property(o63, "des:hasName", o68)
property(o63, "_:hasComponent", o69)
property(o63, "_:connectedTo", o14)
property(o63, "_:connectedTo", o23)
property(o0, "_:hasComponent", o70)
data(o70, "rdfs:label", "OKUMA 123456 Axes C3 particular")
property(o70, "_:hasCapability", o71)
property(o70, "_:hasFunction", o72)
property(o70, "_:hasQuality", o73)
property(o70, "des:hasName", o74)
property(o70, "_:connectedTo", o14)
property(o70, "_:connectedTo", o23)
property(o0, "_:hasComponent", o75)
data(o75, "rdfs:label", "OKUMA 123456 Axes C6 particular")
property(o75, "_:hasCapability", o76)
property(o75, "_:measuresAtSomeTime", o77)
property(o75, "_:measuresAtSomeTime", o78)
property(o75, "des:hasName", o79)
property(o0, "_:hasComponent", o80)
data(o80, "rdfs:label", "OKUMA 123456 Controller particular")
property(o80, "_:hasRole", o81)
property(o80, "_:hasCapability", o82)
property(o80, "_:observesAtSomeTime", o83)
property(o80, "_:observesAtSomeTime", o84)
property(o80, "des:hasName", o85)
property(o80, "_:hasComponent", o86)
property(o0, "_:hasComponent", o87)
data(o87, "rdfs:label", "OKUMA 123456 Systems1 CoolantSystem1 particular")
property(o87, "_:hasRole", o88)
property(o87, "_:hasCapability", o89)
property(o87, "des:hasName", o90)
property(o0, "_:hasComponent", o91)
data(o91, "rdfs:label", "OKUMA 123456 Systems1 ElectricSystem1 particular")
property(o91, "_:hasRole", o92)
property(o91, "_:hasCapability", o93)
property(o91, "des:hasName", o94)
property(o0, "_:hasComponent", o95)
data(o95, "rdfs:label", "OKUMA 123456 Systems1 HydraulicSystem1 particular")
property(o95, "_:hasRole", o96)
property(o95, "_:hasCapability", o97)
property(o95, "des:hasName", o98)
property(o0, "_:hasComponent", o99)
data(o99, "rdfs:label", "OKUMA 123456 Systems1 LubricationSystem1 particular")
property(o99, "_:hasRole", o100)
property(o99, "_:hasCapability", o101)
property(o99, "des:hasName", o102)
property(o0, "_:hasComponent", o103)
data(o103, "rdfs:label", "OKUMA 123456 Systems1 PneumaticSystem1 particular")
property(o103, "_:hasRole", o104)
property(o103, "_:hasCapability", o105)
property(o103, "des:hasName", o106)
property(o0, "_:hasComponent", o107)
data(o107, "rdfs:label", "OKUMA 123456 LAux1 LoaderSystem1 particular")
property(o107, "_:hasCapability", o108)
property(o107, "des:hasName", o109)
property(o0, "_:hasComponent", o110)
data(o110, "rdfs:label", "OKUMA 123456 LAux1 WasteDisposalSystem1 particular")
property(o110, "_:hasCapability", o111)
property(o110, "des:hasName", o112)
property(o0, "_:hasComponent", o113)
data(o113, "rdfs:label", "OKUMA 123456 LAux1 ToolingDeliverySystem1 particular")
property(o113, "_:hasCapability", o114)
property(o113, "des:hasName", o115)
property(o0, "_:hasComponent", o116)
data(o116, "rdfs:label", "OKUMA 123456 LAux1 BarFeederSystem1 particular")
property(o116, "_:hasCapability", o117)
property(o116, "des:hasName", o118)
property(o0, "_:hasComponent", o44)
data(o44, "rdfs:label", "OKUMA 123456 enclosure particular")
property(o44, "_:hasRole", o119)
property(o44, "_:hasCapability", o120)
property(o44, "_:hasQuality", o121)
property(o44, "des:hasName", o122)
@enduml
