@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456-Lc2

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./OKUMA.123456-Lc2.html OKUMA.123456-Lc2]], ex:RotaryMotionSystem)
individual(o2, data:OKUMA.123456-Lc2-name, cmns-dsg:Name)
individual(o3, data:[[./OKUMA.123456-z4_axis.html OKUMA.123456-z4_axis]], ex:Structure)
individual(o4, data:OKUMA.123456-z4_axis-name, cmns-dsg:Name)
individual(o5, data:[[./OKUMA.123456-c2_axis.html OKUMA.123456-c2_axis]], ex:Structure)
individual(o6, data:OKUMA.123456-c2_axis-name, cmns-dsg:Name)
individual(o7, data:OKUMA.123456-Lc2-function, ex:RevoluteMotionCapability)
individual(o8, data:OKUMA.123456-Lc2-rotary_velocity-actual, qp:Speed)
individual(o9, data:OKUMA.123456-Lc2-rotary_velocity-programmed, qp:Speed)
individual(o10, data:[[./OKUMA.123456.html OKUMA.123456]], ex:Machine)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, C2)
property(o1, ex:joinedTo, o3)
property(o3, cmns-dsg:hasName, o4)
property(o1, ex:joinedTo, o5)
property(o5, cmns-dsg:hasName, o6)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o7)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime measuresAtSomeTime]], o8)
property(o1, core:[[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime measuresAtSomeTime]], o9)
property(o10, "bfo:has member part at some time", o1)
@enduml
