@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-x_axis

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./OKUMA.123456-x_axis.html data:OKUMA.123456-x_axis]]" as o1 #76608A {
 <back:#Green>type: ex:Structure</back> 
---
 }
object "data:OKUMA.123456-x_axis-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o3 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
object "[[./OKUMA.123456-Lx1.html data:OKUMA.123456-Lx1]]" as o4 #76608A {
 <back:#Green>type: ex:LinearMotionSystem</back> 
---
 }
object "[[./OKUMA.123456-LYI1.html data:OKUMA.123456-LYI1]]" as o5 #76608A {
 <back:#Green>type: ex:LinearMotionSystem</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: x_axis
o3 --> o1 : obo:has member part at some time
o4 --> o1 : ex:joinedTo
o5 --> o1 : ex:joinedTo
@enduml
