
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA123456AxesC2

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o1, data:OKUMA123456AxesC2Capability, _:Capability)
individual(o2, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o3, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o4, data:OKUMA123456AxesC2IndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o5, data:name16, des:Name)
individual(o6, data:[[./OKUMA123456AxesC2lc2chuck.html OKUMA123456AxesC2lc2chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2lc2chuck OKUMAMULT_U3000AxesC2lc2chuck]])
individual(o7, data:OKUMA123456AxesC2lc2chuckCapability, _:Capability)
individual(o8, data:OKUMA123456AxesC2lc2chuckCHUCK_STATE, _:[[../MTConnect.html#ChuckState ChuckState]])
individual(o9, data:name17, des:Name)
individual(o10, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o11, data:OKUMA123456structz4_axisCapability, _:Capability)
individual(o12, data:name5, des:Name)
individual(o13, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o14, data:OKUMA123456structc2_axisCapability, _:Capability)
individual(o15, data:name8, des:Name)
individual(o16, data:, owl:Thing)
individual(o17, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
property(o0, "_:hasCapability", o1)
property(o0, "_:measuresAtSomeTime", o2)
property(o0, "_:measuresAtSomeTime", o3)
property(o0, "_:hasFunction", o4)
property(o0, "des:hasName", o5)
data(o5, "des:hasTextualName", "C2")
property(o0, "_:hasComponent", o6)
data(o6, "rdfs:label", "OKUMA 123456 Axes C2 lc2chuck particular")
property(o6, "_:hasCapability", o7)
property(o6, "_:observesAtSomeTime", o8)
property(o6, "des:hasName", o9)
property(o0, "_:connectedTo", o10)
data(o10, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
property(o10, "_:hasCapability", o11)
property(o10, "des:hasName", o12)
property(o0, "_:connectedTo", o13)
data(o13, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
property(o13, "_:hasCapability", o14)
property(o13, "des:hasName", o15)
property(o16, "rdf:first", o0)
property(o17, "_:hasComponent", o0)
@enduml
