@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456-x_axis

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./OKUMA.123456-x_axis.html OKUMA.123456-x_axis]], ex:Structure)
individual(o2, data:OKUMA.123456-x_axis-name, cmns-dsg:Name)
individual(o3, data:[[./OKUMA.123456.html OKUMA.123456]], ex:Machine)
individual(o4, data:[[./OKUMA.123456-Lx1.html OKUMA.123456-Lx1]], ex:LinearMotionSystem)
individual(o5, data:[[./OKUMA.123456-LYI1.html OKUMA.123456-LYI1]], ex:LinearMotionSystem)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, x_axis)
property(o3, "bfo:has member part at some time", o1)
property(o4, ex:joinedTo, o1)
property(o5, ex:joinedTo, o1)
@enduml
