
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMAFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, vendor:ontology1, owl:Ontology)
individual(o2, data:[[./OKUMA123456.html OKUMA123456]], vendor:[[../OKUMA.html#OKUMAMULT_U3000 OKUMAMULT_U3000]])
individual(o3, data:name1, des:Name)
individual(o4, data:OKUMA123456Capability, _:Capability)
individual(o5, data:OKUMA123456EquipmentRole, _:EquipmentRole)
individual(o6, data:OKUMA123456EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o7, data:[[./OKUMA123456structx_axis.html OKUMA123456structx_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structx_axis OKUMAMULT_U3000structx_axis]])
individual(o8, data:name2, des:Name)
individual(o9, data:OKUMA123456structx_axisCapability, _:Capability)
individual(o10, data:[[./OKUMA123456structy_axis.html OKUMA123456structy_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structy_axis OKUMAMULT_U3000structy_axis]])
individual(o11, data:name3, des:Name)
individual(o12, data:OKUMA123456structy_axisCapability, _:Capability)
individual(o13, data:[[./OKUMA123456structz1_axis.html OKUMA123456structz1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz1_axis OKUMAMULT_U3000structz1_axis]])
individual(o14, data:name4, des:Name)
individual(o15, data:OKUMA123456structz1_axisCapability, _:Capability)
individual(o16, data:[[./OKUMA123456structz4_axis.html OKUMA123456structz4_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structz4_axis OKUMAMULT_U3000structz4_axis]])
individual(o17, data:name5, des:Name)
individual(o18, data:OKUMA123456structz4_axisCapability, _:Capability)
individual(o19, data:[[./OKUMA123456structb_axis.html OKUMA123456structb_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structb_axis OKUMAMULT_U3000structb_axis]])
individual(o20, data:name6, des:Name)
individual(o21, data:OKUMA123456structb_axisCapability, _:Capability)
individual(o22, data:[[./OKUMA123456structc1_axis.html OKUMA123456structc1_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc1_axis OKUMAMULT_U3000structc1_axis]])
individual(o23, data:name7, des:Name)
individual(o24, data:OKUMA123456structc1_axisCapability, _:Capability)
individual(o25, data:[[./OKUMA123456structc2_axis.html OKUMA123456structc2_axis]], vendor:[[../OKUMA.html#OKUMAMULT_U3000structc2_axis OKUMAMULT_U3000structc2_axis]])
individual(o26, data:name8, des:Name)
individual(o27, data:OKUMA123456structc2_axisCapability, _:Capability)
individual(o28, data:[[./OKUMA123456AxesX.html OKUMA123456AxesX]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesX OKUMAMULT_U3000AxesX]])
individual(o29, data:name9, des:Name)
individual(o30, data:okumamult_u3000axesxdesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesXDesign OKUMAMULT_U3000AxesXDesign]])
individual(o31, data:OKUMA123456AxesXLengthNominal, _:ValueExpression)
individual(o32, units:MilliM, units:Unit)
individual(o33, data:OKUMA123456AxesXLinear_forceMaximum, _:ValueExpression)
individual(o34, units:N, units:Unit)
individual(o35, data:OKUMA123456AxesXLinear_forceMinimum, _:ValueExpression)
individual(o36, data:OKUMA123456AxesXVelocityRapidMaximum, _:ValueExpression)
individual(o37, units:MilliM-PER-SEC, units:Unit)
individual(o38, data:OKUMA123456AxesXVelocityRapidMinimum, _:ValueExpression)
individual(o39, data:OKUMA123456AxesXVelocityProgrammedMaximum, _:ValueExpression)
individual(o40, data:OKUMA123456AxesXVelocityProgrammedMinimum, _:ValueExpression)
individual(o41, data:OKUMA123456AxesXCapability, _:Capability)
individual(o42, data:OKUMA123456AxesXPrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o43, data:OKUMA123456AxesXPOSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o44, data:[[./OKUMA123456AxesY.html OKUMA123456AxesY]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesY OKUMAMULT_U3000AxesY]])
individual(o45, data:name10, des:Name)
individual(o46, data:okumamult_u3000axesydesign1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesYDesign OKUMAMULT_U3000AxesYDesign]])
individual(o47, data:OKUMA123456AxesYLengthNominal, _:ValueExpression)
individual(o48, data:OKUMA123456AxesYLinear_forceMaximum, _:ValueExpression)
individual(o49, data:OKUMA123456AxesYLinear_forceMinimum, _:ValueExpression)
individual(o50, data:OKUMA123456AxesYVelocityRapidMaximum, _:ValueExpression)
individual(o51, data:OKUMA123456AxesYVelocityRapidMinimum, _:ValueExpression)
individual(o52, data:OKUMA123456AxesYVelocityProgrammedMaximum, _:ValueExpression)
individual(o53, data:OKUMA123456AxesYVelocityProgrammedMinimum, _:ValueExpression)
individual(o54, data:OKUMA123456AxesYCapability, _:Capability)
individual(o55, data:OKUMA123456AxesYPrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o56, data:OKUMA123456AxesYPOSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o57, data:[[./OKUMA123456AxesZ1.html OKUMA123456AxesZ1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1 OKUMAMULT_U3000AxesZ1]])
individual(o58, data:name11, des:Name)
individual(o59, data:okumamult_u3000axesz1design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ1Design OKUMAMULT_U3000AxesZ1Design]])
individual(o60, data:OKUMA123456AxesZ1LengthNominal, _:ValueExpression)
individual(o61, data:OKUMA123456AxesZ1Linear_forceMaximum, _:ValueExpression)
individual(o62, data:OKUMA123456AxesZ1Linear_forceMinimum, _:ValueExpression)
individual(o63, data:OKUMA123456AxesZ1VelocityRapidMaximum, _:ValueExpression)
individual(o64, data:OKUMA123456AxesZ1VelocityRapidMinimum, _:ValueExpression)
individual(o65, data:OKUMA123456AxesZ1VelocityProgrammedMaximum, _:ValueExpression)
individual(o66, data:OKUMA123456AxesZ1VelocityProgrammedMinimum, _:ValueExpression)
individual(o67, data:OKUMA123456AxesZ1Capability, _:Capability)
individual(o68, data:OKUMA123456AxesZ1PrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o69, data:OKUMA123456AxesZ1POSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o70, data:[[./OKUMA123456AxesB.html OKUMA123456AxesB]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesB OKUMAMULT_U3000AxesB]])
individual(o71, data:name12, des:Name)
individual(o72, data:OKUMA123456AxesBCapability, _:Capability)
individual(o73, data:OKUMA123456AxesBIndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o74, data:OKUMA123456AxesBANGLE_ACTUAL, _:[[../MTConnect.html#Angle Angle]])
individual(o75, data:[[./OKUMA123456AxesC1.html OKUMA123456AxesC1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1 OKUMAMULT_U3000AxesC1]])
individual(o76, data:name13, des:Name)
individual(o77, data:OKUMA123456AxesC1Capability, _:Capability)
individual(o78, data:OKUMA123456AxesC1ContinuousRevoluteCapability, _:[[../MTConnect.html#ContinuousRevoluteCapability ContinuousRevoluteCapability]])
individual(o79, data:OKUMA123456AxesC1ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o80, data:OKUMA123456AxesC1ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o81, data:[[./OKUMA123456AxesC1lc1chuck.html OKUMA123456AxesC1lc1chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC1lc1chuck OKUMAMULT_U3000AxesC1lc1chuck]])
individual(o82, data:name14, des:Name)
individual(o83, data:OKUMA123456AxesC1lc1chuckCapability, _:Capability)
individual(o84, data:OKUMA123456AxesC1lc1chuckCHUCK_STATE, _:[[../MTConnect.html#ChuckState ChuckState]])
individual(o85, data:[[./OKUMA123456AxesZ4.html OKUMA123456AxesZ4]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4 OKUMAMULT_U3000AxesZ4]])
individual(o86, data:name15, des:Name)
individual(o87, data:okumamult_u3000axesz4design1, vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesZ4Design OKUMAMULT_U3000AxesZ4Design]])
individual(o88, data:OKUMA123456AxesZ4LengthNominal, _:ValueExpression)
individual(o89, data:OKUMA123456AxesZ4Linear_forceMaximum, _:ValueExpression)
individual(o90, data:OKUMA123456AxesZ4Linear_forceMinimum, _:ValueExpression)
individual(o91, data:OKUMA123456AxesZ4VelocityRapidMaximum, _:ValueExpression)
individual(o92, data:OKUMA123456AxesZ4VelocityRapidMinimum, _:ValueExpression)
individual(o93, data:OKUMA123456AxesZ4VelocityProgrammedMaximum, _:ValueExpression)
individual(o94, data:OKUMA123456AxesZ4VelocityProgrammedMinimum, _:ValueExpression)
individual(o95, data:OKUMA123456AxesZ4Capability, _:Capability)
individual(o96, data:OKUMA123456AxesZ4PrismaticMotionCapability, _:[[../MTConnect.html#PrismaticMotionCapability PrismaticMotionCapability]])
individual(o97, data:OKUMA123456AxesZ4POSITION_ACTUAL, _:[[../MTConnect.html#Displacement Displacement]])
individual(o98, data:[[./OKUMA123456AxesC2.html OKUMA123456AxesC2]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2 OKUMAMULT_U3000AxesC2]])
individual(o99, data:name16, des:Name)
individual(o100, data:OKUMA123456AxesC2Capability, _:Capability)
individual(o101, data:OKUMA123456AxesC2IndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o102, data:OKUMA123456AxesC2ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o103, data:OKUMA123456AxesC2ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o104, data:[[./OKUMA123456AxesC2lc2chuck.html OKUMA123456AxesC2lc2chuck]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC2lc2chuck OKUMAMULT_U3000AxesC2lc2chuck]])
individual(o105, data:name17, des:Name)
individual(o106, data:OKUMA123456AxesC2lc2chuckCapability, _:Capability)
individual(o107, data:OKUMA123456AxesC2lc2chuckCHUCK_STATE, _:[[../MTConnect.html#ChuckState ChuckState]])
individual(o108, data:[[./OKUMA123456AxesC3.html OKUMA123456AxesC3]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC3 OKUMAMULT_U3000AxesC3]])
individual(o109, data:name18, des:Name)
individual(o110, data:OKUMA123456AxesC3Capability, _:Capability)
individual(o111, data:OKUMA123456AxesC3IndexedRevoluteCapability, _:[[../MTConnect.html#IndexedRevoluteCapability IndexedRevoluteCapability]])
individual(o112, data:OKUMA123456AxesC3ANGLE_ACTUAL, _:[[../MTConnect.html#Angle Angle]])
individual(o113, data:[[./OKUMA123456AxesC6.html OKUMA123456AxesC6]], vendor:[[../OKUMA.html#OKUMAMULT_U3000AxesC6 OKUMAMULT_U3000AxesC6]])
individual(o114, data:name19, des:Name)
individual(o115, data:OKUMA123456AxesC6Capability, _:Capability)
individual(o116, data:OKUMA123456AxesC6ROTARY_VELOCITY_ACTUAL, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o117, data:OKUMA123456AxesC6ROTARY_VELOCITY_PROGRAMMED, _:[[../MTConnect.html#RevoluteVelocity RevoluteVelocity]])
individual(o118, data:[[./OKUMA123456Controller.html OKUMA123456Controller]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controller OKUMAMULT_U3000Controller]])
individual(o119, data:name20, des:Name)
individual(o120, data:OKUMA123456ControllerCapability, _:Capability)
individual(o121, data:OKUMA123456ControllerEngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o122, data:OKUMA123456ControllerCONTROLLER_MODE, _:[[../MTConnect.html#ControllerMode ControllerMode]])
individual(o123, data:OKUMA123456ControllerEXECUTION, _:[[../MTConnect.html#ExecutionState ExecutionState]])
individual(o124, data:[[./OKUMA123456Controllerpath.html OKUMA123456Controllerpath]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Controllerpath OKUMAMULT_U3000Controllerpath]])
individual(o125, data:name21, des:Name)
individual(o126, data:OKUMA123456ControllerpathCapability, _:Capability)
individual(o127, data:OKUMA123456ControllerpathEngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o128, data:OKUMA123456ControllerpathPATH_POSITION_ACTUAL, _:[[../MTConnect.html#ThreeSpaceDisplacement ThreeSpaceDisplacement]])
individual(o129, data:[[./OKUMA123456Systems1CoolantSystem1.html OKUMA123456Systems1CoolantSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1CoolantSystem1 OKUMAMULT_U3000Systems1CoolantSystem1]])
individual(o130, data:name22, des:Name)
individual(o131, data:OKUMA123456Systems1CoolantSystem1Capability, _:Capability)
individual(o132, data:OKUMA123456Systems1CoolantSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o133, data:[[./OKUMA123456Systems1ElectricSystem1.html OKUMA123456Systems1ElectricSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1ElectricSystem1 OKUMAMULT_U3000Systems1ElectricSystem1]])
individual(o134, data:name23, des:Name)
individual(o135, data:OKUMA123456Systems1ElectricSystem1Capability, _:Capability)
individual(o136, data:OKUMA123456Systems1ElectricSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o137, data:[[./OKUMA123456Systems1HydraulicSystem1.html OKUMA123456Systems1HydraulicSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1HydraulicSystem1 OKUMAMULT_U3000Systems1HydraulicSystem1]])
individual(o138, data:name24, des:Name)
individual(o139, data:OKUMA123456Systems1HydraulicSystem1Capability, _:Capability)
individual(o140, data:OKUMA123456Systems1HydraulicSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o141, data:[[./OKUMA123456Systems1LubricationSystem1.html OKUMA123456Systems1LubricationSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1LubricationSystem1 OKUMAMULT_U3000Systems1LubricationSystem1]])
individual(o142, data:name25, des:Name)
individual(o143, data:OKUMA123456Systems1LubricationSystem1Capability, _:Capability)
individual(o144, data:OKUMA123456Systems1LubricationSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o145, data:[[./OKUMA123456Systems1PneumaticSystem1.html OKUMA123456Systems1PneumaticSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000Systems1PneumaticSystem1 OKUMAMULT_U3000Systems1PneumaticSystem1]])
individual(o146, data:name26, des:Name)
individual(o147, data:OKUMA123456Systems1PneumaticSystem1Capability, _:Capability)
individual(o148, data:OKUMA123456Systems1PneumaticSystem1EngineeredSystemRole, _:[[../MTConnect.html#EngineeredSystemRole EngineeredSystemRole]])
individual(o149, data:[[./OKUMA123456LAux1LoaderSystem1.html OKUMA123456LAux1LoaderSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1LoaderSystem1 OKUMAMULT_U3000LAux1LoaderSystem1]])
individual(o150, data:name27, des:Name)
individual(o151, data:OKUMA123456LAux1LoaderSystem1Capability, _:Capability)
individual(o152, data:[[./OKUMA123456LAux1WasteDisposalSystem1.html OKUMA123456LAux1WasteDisposalSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1WasteDisposalSystem1 OKUMAMULT_U3000LAux1WasteDisposalSystem1]])
individual(o153, data:name28, des:Name)
individual(o154, data:OKUMA123456LAux1WasteDisposalSystem1Capability, _:Capability)
individual(o155, data:[[./OKUMA123456LAux1ToolingDeliverySystem1.html OKUMA123456LAux1ToolingDeliverySystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1ToolingDeliverySystem1 OKUMAMULT_U3000LAux1ToolingDeliverySystem1]])
individual(o156, data:name29, des:Name)
individual(o157, data:OKUMA123456LAux1ToolingDeliverySystem1Capability, _:Capability)
individual(o158, data:[[./OKUMA123456LAux1BarFeederSystem1.html OKUMA123456LAux1BarFeederSystem1]], vendor:[[../OKUMA.html#OKUMAMULT_U3000LAux1BarFeederSystem1 OKUMAMULT_U3000LAux1BarFeederSystem1]])
individual(o159, data:name30, des:Name)
individual(o160, data:OKUMA123456LAux1BarFeederSystem1Capability, _:Capability)
individual(o161, data:[[./OKUMA123456enclosure.html OKUMA123456enclosure]], vendor:[[../OKUMA.html#OKUMAMULT_U3000enclosure OKUMAMULT_U3000enclosure]])
individual(o162, data:name31, des:Name)
individual(o163, data:OKUMA123456enclosureCapability, _:Capability)
individual(o164, data:OKUMA123456enclosureMaterialArtifactRole, _:[[../MTConnect.html#MaterialArtifactRole MaterialArtifactRole]])
individual(o165, data:OKUMA123456enclosureTEMPERATURE, _:[[../MTConnect.html#Temperature Temperature]])
property(o0, "owl:imports", o1)
property(o2, "des:hasName", o3)
property(o2, "_:hasCapability", o4)
property(o2, "_:hasRole", o5)
property(o2, "_:hasRole", o6)
property(o2, "_:hasComponent", o7)
property(o7, "des:hasName", o8)
property(o7, "_:hasCapability", o9)
property(o2, "_:hasComponent", o10)
property(o10, "des:hasName", o11)
property(o10, "_:hasCapability", o12)
property(o2, "_:hasComponent", o13)
property(o13, "des:hasName", o14)
property(o13, "_:hasCapability", o15)
property(o2, "_:hasComponent", o16)
property(o16, "des:hasName", o17)
property(o16, "_:hasCapability", o18)
property(o2, "_:hasComponent", o19)
property(o19, "des:hasName", o20)
property(o19, "_:hasCapability", o21)
property(o2, "_:hasComponent", o22)
property(o22, "des:hasName", o23)
property(o22, "_:hasCapability", o24)
property(o2, "_:hasComponent", o25)
property(o25, "des:hasName", o26)
property(o25, "_:hasCapability", o27)
property(o2, "_:hasComponent", o28)
property(o28, "des:hasName", o29)
property(o28, "_:prescribedBy", o30)
property(o30, "_:hasValueExpressionAtSomeTime", o31)
property(o31, "_:hasUnit", o32)
property(o30, "_:hasValueExpressionAtSomeTime", o33)
property(o33, "_:hasUnit", o34)
property(o30, "_:hasValueExpressionAtSomeTime", o35)
property(o35, "_:hasUnit", o34)
property(o30, "_:hasValueExpressionAtSomeTime", o36)
property(o36, "_:hasUnit", o37)
property(o30, "_:hasValueExpressionAtSomeTime", o38)
property(o38, "_:hasUnit", o37)
property(o30, "_:hasValueExpressionAtSomeTime", o39)
property(o39, "_:hasUnit", o37)
property(o30, "_:hasValueExpressionAtSomeTime", o40)
property(o40, "_:hasUnit", o37)
property(o28, "_:hasCapability", o41)
property(o28, "_:hasFunction", o42)
property(o42, "_:prescribedBy", o30)
property(o28, "_:hasQuality", o43)
property(o2, "_:hasComponent", o44)
property(o44, "des:hasName", o45)
property(o44, "_:prescribedBy", o46)
property(o46, "_:hasValueExpressionAtSomeTime", o47)
property(o47, "_:hasUnit", o32)
property(o46, "_:hasValueExpressionAtSomeTime", o48)
property(o48, "_:hasUnit", o34)
property(o46, "_:hasValueExpressionAtSomeTime", o49)
property(o49, "_:hasUnit", o34)
property(o46, "_:hasValueExpressionAtSomeTime", o50)
property(o50, "_:hasUnit", o37)
property(o46, "_:hasValueExpressionAtSomeTime", o51)
property(o51, "_:hasUnit", o37)
property(o46, "_:hasValueExpressionAtSomeTime", o52)
property(o52, "_:hasUnit", o37)
property(o46, "_:hasValueExpressionAtSomeTime", o53)
property(o53, "_:hasUnit", o37)
property(o44, "_:hasCapability", o54)
property(o44, "_:hasFunction", o55)
property(o55, "_:prescribedBy", o46)
property(o44, "_:hasQuality", o56)
property(o2, "_:hasComponent", o57)
property(o57, "des:hasName", o58)
property(o57, "_:prescribedBy", o59)
property(o59, "_:hasValueExpressionAtSomeTime", o60)
property(o60, "_:hasUnit", o32)
property(o59, "_:hasValueExpressionAtSomeTime", o61)
property(o61, "_:hasUnit", o34)
property(o59, "_:hasValueExpressionAtSomeTime", o62)
property(o62, "_:hasUnit", o34)
property(o59, "_:hasValueExpressionAtSomeTime", o63)
property(o63, "_:hasUnit", o37)
property(o59, "_:hasValueExpressionAtSomeTime", o64)
property(o64, "_:hasUnit", o37)
property(o59, "_:hasValueExpressionAtSomeTime", o65)
property(o65, "_:hasUnit", o37)
property(o59, "_:hasValueExpressionAtSomeTime", o66)
property(o66, "_:hasUnit", o37)
property(o57, "_:hasCapability", o67)
property(o57, "_:hasFunction", o68)
property(o68, "_:prescribedBy", o59)
property(o57, "_:hasQuality", o69)
property(o2, "_:hasComponent", o70)
property(o70, "des:hasName", o71)
property(o70, "_:hasCapability", o72)
property(o70, "_:hasFunction", o73)
property(o70, "_:hasQuality", o74)
property(o2, "_:hasComponent", o75)
property(o75, "des:hasName", o76)
property(o75, "_:hasCapability", o77)
property(o75, "_:hasFunction", o78)
property(o75, "_:measuresAtSomeTime", o79)
property(o75, "_:measuresAtSomeTime", o80)
property(o75, "_:hasComponent", o81)
property(o81, "des:hasName", o82)
property(o81, "_:hasCapability", o83)
property(o81, "_:observesAtSomeTime", o84)
property(o2, "_:hasComponent", o85)
property(o85, "des:hasName", o86)
property(o85, "_:prescribedBy", o87)
property(o87, "_:hasValueExpressionAtSomeTime", o88)
property(o88, "_:hasUnit", o32)
property(o87, "_:hasValueExpressionAtSomeTime", o89)
property(o89, "_:hasUnit", o34)
property(o87, "_:hasValueExpressionAtSomeTime", o90)
property(o90, "_:hasUnit", o34)
property(o87, "_:hasValueExpressionAtSomeTime", o91)
property(o91, "_:hasUnit", o37)
property(o87, "_:hasValueExpressionAtSomeTime", o92)
property(o92, "_:hasUnit", o37)
property(o87, "_:hasValueExpressionAtSomeTime", o93)
property(o93, "_:hasUnit", o37)
property(o87, "_:hasValueExpressionAtSomeTime", o94)
property(o94, "_:hasUnit", o37)
property(o85, "_:hasCapability", o95)
property(o85, "_:hasFunction", o96)
property(o96, "_:prescribedBy", o87)
property(o85, "_:hasQuality", o97)
property(o2, "_:hasComponent", o98)
property(o98, "des:hasName", o99)
property(o98, "_:hasCapability", o100)
property(o98, "_:hasFunction", o101)
property(o98, "_:measuresAtSomeTime", o102)
property(o98, "_:measuresAtSomeTime", o103)
property(o98, "_:hasComponent", o104)
property(o104, "des:hasName", o105)
property(o104, "_:hasCapability", o106)
property(o104, "_:observesAtSomeTime", o107)
property(o2, "_:hasComponent", o108)
property(o108, "des:hasName", o109)
property(o108, "_:hasCapability", o110)
property(o108, "_:hasFunction", o111)
property(o108, "_:hasQuality", o112)
property(o2, "_:hasComponent", o113)
property(o113, "des:hasName", o114)
property(o113, "_:hasCapability", o115)
property(o113, "_:measuresAtSomeTime", o116)
property(o113, "_:measuresAtSomeTime", o117)
property(o2, "_:hasComponent", o118)
property(o118, "des:hasName", o119)
property(o118, "_:hasCapability", o120)
property(o118, "_:hasRole", o121)
property(o118, "_:observesAtSomeTime", o122)
property(o118, "_:observesAtSomeTime", o123)
property(o118, "_:hasComponent", o124)
property(o124, "des:hasName", o125)
property(o124, "_:hasCapability", o126)
property(o124, "_:hasRole", o127)
property(o124, "_:hasQuality", o128)
property(o2, "_:hasComponent", o129)
property(o129, "des:hasName", o130)
property(o129, "_:hasCapability", o131)
property(o129, "_:hasRole", o132)
property(o2, "_:hasComponent", o133)
property(o133, "des:hasName", o134)
property(o133, "_:hasCapability", o135)
property(o133, "_:hasRole", o136)
property(o2, "_:hasComponent", o137)
property(o137, "des:hasName", o138)
property(o137, "_:hasCapability", o139)
property(o137, "_:hasRole", o140)
property(o2, "_:hasComponent", o141)
property(o141, "des:hasName", o142)
property(o141, "_:hasCapability", o143)
property(o141, "_:hasRole", o144)
property(o2, "_:hasComponent", o145)
property(o145, "des:hasName", o146)
property(o145, "_:hasCapability", o147)
property(o145, "_:hasRole", o148)
property(o2, "_:hasComponent", o149)
property(o149, "des:hasName", o150)
property(o149, "_:hasCapability", o151)
property(o2, "_:hasComponent", o152)
property(o152, "des:hasName", o153)
property(o152, "_:hasCapability", o154)
property(o2, "_:hasComponent", o155)
property(o155, "des:hasName", o156)
property(o155, "_:hasCapability", o157)
property(o2, "_:hasComponent", o158)
property(o158, "des:hasName", o159)
property(o158, "_:hasCapability", o160)
property(o2, "_:hasComponent", o161)
property(o161, "des:hasName", o162)
property(o161, "_:hasCapability", o163)
property(o161, "_:hasRole", o164)
property(o161, "_:hasQuality", o165)
property(o28, "_:connectedTo", o13)
property(o28, "_:connectedTo", o7)
property(o44, "_:connectedTo", o7)
property(o44, "_:connectedTo", o10)
property(o57, "_:connectedTo", o161)
property(o57, "_:connectedTo", o13)
property(o70, "_:connectedTo", o10)
property(o70, "_:connectedTo", o19)
property(o75, "_:connectedTo", o161)
property(o85, "_:connectedTo", o161)
property(o85, "_:connectedTo", o16)
property(o98, "_:connectedTo", o16)
property(o98, "_:connectedTo", o25)
property(o108, "_:connectedTo", o16)
property(o108, "_:connectedTo", o25)
data(o2, "rdfs:label", "OKUMA 123456 particular")
data(o3, "des:hasTextualName", "OKUMA")
data(o7, "rdfs:label", "OKUMA 123456 struct x_axis particular")
data(o8, "des:hasTextualName", "x_axis")
data(o10, "rdfs:label", "OKUMA 123456 struct y_axis particular")
data(o11, "des:hasTextualName", "y_axis")
data(o13, "rdfs:label", "OKUMA 123456 struct z1_axis particular")
data(o14, "des:hasTextualName", "z1_axis")
data(o16, "rdfs:label", "OKUMA 123456 struct z4_axis particular")
data(o17, "des:hasTextualName", "z4_axis")
data(o19, "rdfs:label", "OKUMA 123456 struct b_axis particular")
data(o20, "des:hasTextualName", "b_axis")
data(o22, "rdfs:label", "OKUMA 123456 struct c1_axis particular")
data(o23, "des:hasTextualName", "c1_axis")
data(o25, "rdfs:label", "OKUMA 123456 struct c2_axis particular")
data(o26, "des:hasTextualName", "c2_axis")
data(o28, "rdfs:label", "OKUMA 123456 Axes X particular")
data(o29, "des:hasTextualName", "X")
data(o30, "rdfs:label", "OKUMAMULT_U3000AxesXDesign particular")
data(o31, "_:hasSimpleExpressionValue", "650.0")
data(o33, "_:hasSimpleExpressionValue", "5200.0")
data(o35, "_:hasSimpleExpressionValue", "0.0")
data(o36, "_:hasSimpleExpressionValue", "7000.0")
data(o38, "_:hasSimpleExpressionValue", "1.0")
data(o39, "_:hasSimpleExpressionValue", "7000.0")
data(o40, "_:hasSimpleExpressionValue", "1.0")
data(o44, "rdfs:label", "OKUMA 123456 Axes Y particular")
data(o45, "des:hasTextualName", "Y")
data(o46, "rdfs:label", "OKUMAMULT_U3000AxesYDesign particular")
data(o47, "_:hasSimpleExpressionValue", "650.0")
data(o48, "_:hasSimpleExpressionValue", "5200.0")
data(o49, "_:hasSimpleExpressionValue", "0.0")
data(o50, "_:hasSimpleExpressionValue", "7000.0")
data(o51, "_:hasSimpleExpressionValue", "1.0")
data(o52, "_:hasSimpleExpressionValue", "7000.0")
data(o53, "_:hasSimpleExpressionValue", "1.0")
data(o57, "rdfs:label", "OKUMA 123456 Axes Z1 particular")
data(o58, "des:hasTextualName", "Z1")
data(o59, "rdfs:label", "OKUMAMULT_U3000AxesZ1Design particular")
data(o60, "_:hasSimpleExpressionValue", "650.0")
data(o61, "_:hasSimpleExpressionValue", "5200.0")
data(o62, "_:hasSimpleExpressionValue", "0.0")
data(o63, "_:hasSimpleExpressionValue", "7000.0")
data(o64, "_:hasSimpleExpressionValue", "1.0")
data(o65, "_:hasSimpleExpressionValue", "7000.0")
data(o66, "_:hasSimpleExpressionValue", "1.0")
data(o70, "rdfs:label", "OKUMA 123456 Axes B particular")
data(o71, "des:hasTextualName", "B")
data(o75, "rdfs:label", "OKUMA 123456 Axes C1 particular")
data(o76, "des:hasTextualName", "C1")
data(o81, "rdfs:label", "OKUMA 123456 Axes C1 lc1chuck particular")
data(o82, "des:hasTextualName", "lc1chuck")
data(o85, "rdfs:label", "OKUMA 123456 Axes Z4 particular")
data(o86, "des:hasTextualName", "Z4")
data(o87, "rdfs:label", "OKUMAMULT_U3000AxesZ4Design particular")
data(o88, "_:hasSimpleExpressionValue", "650.0")
data(o89, "_:hasSimpleExpressionValue", "5200.0")
data(o90, "_:hasSimpleExpressionValue", "0.0")
data(o91, "_:hasSimpleExpressionValue", "7000.0")
data(o92, "_:hasSimpleExpressionValue", "1.0")
data(o93, "_:hasSimpleExpressionValue", "7000.0")
data(o94, "_:hasSimpleExpressionValue", "1.0")
data(o98, "rdfs:label", "OKUMA 123456 Axes C2 particular")
data(o99, "des:hasTextualName", "C2")
data(o104, "rdfs:label", "OKUMA 123456 Axes C2 lc2chuck particular")
data(o105, "des:hasTextualName", "lc2chuck")
data(o108, "rdfs:label", "OKUMA 123456 Axes C3 particular")
data(o109, "des:hasTextualName", "C3")
data(o113, "rdfs:label", "OKUMA 123456 Axes C6 particular")
data(o114, "des:hasTextualName", "C6")
data(o118, "rdfs:label", "OKUMA 123456 Controller particular")
data(o119, "des:hasTextualName", "Controller")
data(o124, "rdfs:label", "OKUMA 123456 Controller path particular")
data(o125, "des:hasTextualName", "path")
data(o129, "rdfs:label", "OKUMA 123456 Systems1 CoolantSystem1 particular")
data(o130, "des:hasTextualName", "CoolantSystem1")
data(o133, "rdfs:label", "OKUMA 123456 Systems1 ElectricSystem1 particular")
data(o134, "des:hasTextualName", "ElectricSystem1")
data(o137, "rdfs:label", "OKUMA 123456 Systems1 HydraulicSystem1 particular")
data(o138, "des:hasTextualName", "HydraulicSystem1")
data(o141, "rdfs:label", "OKUMA 123456 Systems1 LubricationSystem1 particular")
data(o142, "des:hasTextualName", "LubricationSystem1")
data(o145, "rdfs:label", "OKUMA 123456 Systems1 PneumaticSystem1 particular")
data(o146, "des:hasTextualName", "PneumaticSystem1")
data(o149, "rdfs:label", "OKUMA 123456 LAux1 LoaderSystem1 particular")
data(o150, "des:hasTextualName", "LoaderSystem1")
data(o152, "rdfs:label", "OKUMA 123456 LAux1 WasteDisposalSystem1 particular")
data(o153, "des:hasTextualName", "WasteDisposalSystem1")
data(o155, "rdfs:label", "OKUMA 123456 LAux1 ToolingDeliverySystem1 particular")
data(o156, "des:hasTextualName", "ToolingDeliverySystem1")
data(o158, "rdfs:label", "OKUMA 123456 LAux1 BarFeederSystem1 particular")
data(o159, "des:hasTextualName", "BarFeederSystem1")
data(o161, "rdfs:label", "OKUMA 123456 enclosure particular")
data(o162, "des:hasTextualName", "enclosure")
@enduml
