@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-Lc1

skinparam roundCorner 10

skinparam object {
  BackgroundColor 76608A
  fontColor White
  BorderColor White 
  FontName Helvetica   
}

skinparam class{
   BackgroundColor White
   fontColor black
   FontStyle bold
   FontName Helvetica
}

object "[[./OKUMA.123456-Lc1.html data:OKUMA.123456-Lc1]]" as o1 #76608A {
 <back:#Green>type: ex:RotaryMotionSystem</back> 
---
 }
object "data:OKUMA.123456-Lc1-name" as o2 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "[[./OKUMA.123456-enclosure.html data:OKUMA.123456-enclosure]]" as o3 #76608A {
 <back:#Green>type: ex:Structure</back> 
---
 }
object "data:OKUMA.123456-enclosure-name" as o4 #76608A {
 <back:#DarkGrey>type: cmns-dsg:Name</back> 
---
 }
object "data:OKUMA.123456-enclosure-temperature" as o5 #76608A {
 <back:#1E90FF>type: qp:Temperature</back> 
---
 }
object "data:OKUMA.123456-Lc1-function" as o6 #76608A {
 <back:#Green>type: ex:ContinuousMotionCapability</back> 
---
 }
object "data:OKUMA.123456-Lc1-rotary_velocity-actual" as o7 #76608A {
 <back:#1E90FF>type: qp:Speed</back> 
---
 }
object "data:OKUMA.123456-Lc1-rotary_velocity-programmed" as o8 #76608A {
 <back:#1E90FF>type: qp:Speed</back> 
---
 }
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o9 #76608A {
 <back:#Green>type: ex:Machine</back> 
---
 }
o1 --> o2 : cmns-dsg:hasName
o2 : cmns-dsg:hasTextualName: C1
o1 --> o3 : ex:joinedTo
o3 --> o4 : cmns-dsg:hasName
o3 --> o5 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o1 --> o6 : [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]]
o1 --> o7 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o1 --> o8 : [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]]
o9 --> o1 : obo:has member part at some time
@enduml
