@startuml
skinparam linetype polyline
left to right direction
title OKUMA.123456-Lc1
object "[[./OKUMA.123456-Lc1.html data:OKUMA.123456-Lc1]]" as o1 {
 type = ex:RotaryMotionSystem
 }
object "data:OKUMA.123456-Lc1-name" as o2 {
 type = cmns-dsg:Name
 }
object "[[./OKUMA.123456-enclosure.html data:OKUMA.123456-enclosure]]" as o3 {
 type = ex:Structure
 }
object "data:OKUMA.123456-enclosure-name" as o4 {
 type = cmns-dsg:Name
 }
object "data:OKUMA.123456-enclosure-temperature" as o5 {
 type = qp:Temperature
 }
object "data:OKUMA.123456-Lc1-function" as o6 {
 type = ex:ContinuousMotionCapability
 }
object "data:OKUMA.123456-Lc1-rotary_velocity-actual" as o7 {
 type = qp:Speed
 }
object "data:OKUMA.123456-Lc1-rotary_velocity-programmed" as o8 {
 type = qp:Speed
 }
object "[[./OKUMA.123456.html data:OKUMA.123456]]" as o9 {
 type = ex:Machine
 }
o1 --> o2 : cmns-dsg:hasName
o2 : core:hasSimpleExpressionValue = C1
o1 --> o3 : ex:joinedTo
o3 --> o4 : cmns-dsg:hasName
o4 : core:hasSimpleExpressionValue = enclosure
o3 --> o5 : core:measuresAtSomeTime
o1 --> o6 : core:hasFunction
o1 --> o7 : core:measuresAtSomeTime
o1 --> o8 : core:measuresAtSomeTime
o9 --> o1 : obo:has member part at some time
@enduml
