@startuml OKUMA.123456
!include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml

left to right direction
skinparam linetype polyline
title OKUMA.123456

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"1E90FF","units":"Blue"
}
individual(o1, data:OKUMA.123456, ex:Machine)
individual(o2, data:OKUMA.123456-name, cmns-dsg:Name)
individual(o3, data:OKUMA.123456-function, ex:MillingCapability)
individual(o4, data:OKUMA.123456-capability, ex:TurningCapability)
individual(o5, data:OKUMA.123456-role, [[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole core:EquipmentRole]])
individual(o6, data:OKUMA.123456-x_axis, ex:Structure)
individual(o7, data:OKUMA.123456-x_axis-name, cmns-dsg:Name)
individual(o8, data:OKUMA.123456-y_axis, ex:Structure)
individual(o9, data:OKUMA.123456-y_axis-name, cmns-dsg:Name)
individual(o10, data:OKUMA.123456-z1_axis, ex:Structure)
individual(o11, data:OKUMA.123456-z1_axis-name, cmns-dsg:Name)
individual(o12, data:OKUMA.123456-z4_axis, ex:Structure)
individual(o13, data:OKUMA.123456-z4_axis-name, cmns-dsg:Name)
individual(o14, data:OKUMA.123456-b_axis, ex:Structure)
individual(o15, data:OKUMA.123456-b_axis-name, cmns-dsg:Name)
individual(o16, data:OKUMA.123456-c1_axis, ex:Structure)
individual(o17, data:OKUMA.123456-c1_axis-name, cmns-dsg:Name)
individual(o18, data:OKUMA.123456-c2_axis, ex:Structure)
individual(o19, data:OKUMA.123456-c2_axis-name, cmns-dsg:Name)
individual(o20, data:OKUMA.123456-Lx1, ex:LinearMotionSystem)
individual(o21, data:OKUMA.123456-Lx1-name, cmns-dsg:Name)
individual(o22, data:OKUMA.123456-Lx1-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o23, data:OKUMA.123456-Lx1-function, ex:PrismaticMotionCapability)
individual(o24, data:OKUMA.123456-Lx1-position-actual, qp:Displacement)
individual(o25, data:OKUMA.123456-LYI1, ex:LinearMotionSystem)
individual(o26, data:OKUMA.123456-LYI1-name, cmns-dsg:Name)
individual(o27, data:OKUMA.123456-LYI1-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o28, data:OKUMA.123456-LYI1-function, ex:PrismaticMotionCapability)
individual(o29, data:OKUMA.123456-LYI1-position-actual, qp:Displacement)
individual(o30, data:OKUMA.123456-Lz1, ex:LinearMotionSystem)
individual(o31, data:OKUMA.123456-Lz1-name, cmns-dsg:Name)
individual(o32, data:OKUMA.123456-Lz1-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o33, data:OKUMA.123456-enclosure, ex:Structure)
individual(o34, data:OKUMA.123456-Lz1-function, ex:PrismaticMotionCapability)
individual(o35, data:OKUMA.123456-Lz1-position-actual, qp:Displacement)
individual(o36, data:OKUMA.123456-Lb1, ex:RotaryMotionSystem)
individual(o37, data:OKUMA.123456-Lb1-name, cmns-dsg:Name)
individual(o38, data:OKUMA.123456-Lb1-function, ex:RevoluteMotionCapability)
individual(o39, data:OKUMA.123456-Lb1-angle-actual, qp:Angle)
individual(o40, data:OKUMA.123456-Lc1, ex:RotaryMotionSystem)
individual(o41, data:OKUMA.123456-Lc1-name, cmns-dsg:Name)
individual(o42, data:OKUMA.123456-Lc1-function, ex:ContinuousMotionCapability)
individual(o43, data:OKUMA.123456-Lc1-rotary_velocity-actual, qp:Speed)
individual(o44, data:OKUMA.123456-Lc1-rotary_velocity-programmed, qp:Speed)
individual(o45, data:OKUMA.123456-Lz4, ex:LinearMotionSystem)
individual(o46, data:OKUMA.123456-Lz4-name, cmns-dsg:Name)
individual(o47, data:OKUMA.123456-Lz4-spec, [[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification core:DesignSpecification]])
individual(o48, data:OKUMA.123456-Lz4-function, ex:PrismaticMotionCapability)
individual(o49, data:OKUMA.123456-Lz4-position-actual, qp:Displacement)
individual(o50, data:OKUMA.123456-Lc2, ex:RotaryMotionSystem)
individual(o51, data:OKUMA.123456-Lc2-name, cmns-dsg:Name)
individual(o52, data:OKUMA.123456-Lc2-function, ex:RevoluteMotionCapability)
individual(o53, data:OKUMA.123456-Lc2-rotary_velocity-actual, qp:Speed)
individual(o54, data:OKUMA.123456-Lc2-rotary_velocity-programmed, qp:Speed)
individual(o55, data:OKUMA.123456-Lc3, ex:RotaryMotionSystem)
individual(o56, data:OKUMA.123456-Lc3-name, cmns-dsg:Name)
individual(o57, data:OKUMA.123456-Lc3-function, ex:RevoluteMotionCapability)
individual(o58, data:OKUMA.123456-Lc3-angle-actual, qp:Angle)
individual(o59, data:OKUMA.123456-Lc6, ex:RotaryMotionSystem)
individual(o60, data:OKUMA.123456-Lc6-name, cmns-dsg:Name)
individual(o61, data:OKUMA.123456-Lc6-rotary_velocity-actual, qp:Speed)
individual(o62, data:OKUMA.123456-Lc6-rotary_velocity-programmed, qp:Speed)
individual(o63, data:OKUMA.123456-Lct1, ex:ControlSystem)
individual(o64, data:OKUMA.123456-Lct1-name, cmns-dsg:Name)
individual(o65, data:OKUMA.123456-Lct1-Lp1, ex:ControlSystemPath)
individual(o66, data:OKUMA.123456-LCoolantSystem1, "bfo:object")
individual(o67, data:OKUMA.123456-LCoolantSystem1-name, cmns-dsg:Name)
individual(o68, data:OKUMA.123456-LElectricSystem1, ex:ElectricalSystem)
individual(o69, data:OKUMA.123456-LElectricSystem1-name, cmns-dsg:Name)
individual(o70, data:OKUMA.123456-LHydraulicSystem1, ex:HydraulicSystem)
individual(o71, data:OKUMA.123456-LHydraulicSystem1-name, cmns-dsg:Name)
individual(o72, data:OKUMA.123456-LLubricationSystem1, ex:LubricationSystem)
individual(o73, data:OKUMA.123456-LLubricationSystem1-name, cmns-dsg:Name)
individual(o74, data:OKUMA.123456-LPneumaticSystem1, ex:PneumaticSystem)
individual(o75, data:OKUMA.123456-LPneumaticSystem1-name, cmns-dsg:Name)
individual(o76, data:OKUMA.123456-LLoaderSystem1, "bfo:object")
individual(o77, data:OKUMA.123456-LLoaderSystem1-name, cmns-dsg:Name)
individual(o78, data:OKUMA.123456-LWasteDisposalSystem1, "bfo:object")
individual(o79, data:OKUMA.123456-LWasteDisposalSystem1-name, cmns-dsg:Name)
individual(o80, data:OKUMA.123456-LToolingDeliverySystem1, "bfo:object")
individual(o81, data:OKUMA.123456-LToolingDeliverySystem1-name, cmns-dsg:Name)
individual(o82, data:OKUMA.123456-LBarFeederSystem1, "bfo:object")
individual(o83, data:OKUMA.123456-LBarFeederSystem1-name, cmns-dsg:Name)
individual(o84, data:OKUMA.123456-personnel, [[https://spec.industrialontologies.org/ontology/core/Core/Person core:Person]])
individual(o85, data:OKUMA.123456-personnel-name, cmns-dsg:Name)
individual(o86, data:OKUMA.123456-enclosure-name, cmns-dsg:Name)
individual(o87, data:OKUMA.123456-enclosure-temperature, qp:Temperature)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, OKUMA)
property(o1, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o3)
property(o1, [[https://spec.industrialontologies.org/ontology/core/Core/hasCapability core:hasCapability]], o4)
property(o1, [[https://spec.industrialontologies.org/ontology/core/Core/hasRole core:hasRole]], o5)
property(o1, "bfo:has member part at some time", o6)
property(o6, cmns-dsg:hasName, o7)
property(o1, "bfo:has member part at some time", o8)
property(o8, cmns-dsg:hasName, o9)
property(o1, "bfo:has member part at some time", o10)
property(o10, cmns-dsg:hasName, o11)
property(o1, "bfo:has member part at some time", o12)
property(o12, cmns-dsg:hasName, o13)
property(o1, "bfo:has member part at some time", o14)
property(o14, cmns-dsg:hasName, o15)
property(o1, "bfo:has member part at some time", o16)
property(o16, cmns-dsg:hasName, o17)
property(o1, "bfo:has member part at some time", o18)
property(o18, cmns-dsg:hasName, o19)
property(o1, "bfo:has member part at some time", o20)
property(o20, cmns-dsg:hasName, o21)
property(o20, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o22)
property(o20, ex:joinedTo, o10)
property(o20, ex:joinedTo, o6)
property(o20, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o23)
property(o20, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o24)
property(o1, "bfo:has member part at some time", o25)
property(o25, cmns-dsg:hasName, o26)
property(o25, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o27)
property(o25, ex:joinedTo, o6)
property(o25, ex:joinedTo, o8)
property(o25, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o28)
property(o25, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o29)
property(o1, "bfo:has member part at some time", o30)
property(o30, cmns-dsg:hasName, o31)
property(o30, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o32)
property(o30, ex:joinedTo, o33)
property(o30, ex:joinedTo, o10)
property(o30, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o34)
property(o30, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o35)
property(o1, "bfo:has member part at some time", o36)
property(o36, cmns-dsg:hasName, o37)
property(o36, ex:joinedTo, o8)
property(o36, ex:joinedTo, o14)
property(o36, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o38)
property(o36, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o39)
property(o1, "bfo:has member part at some time", o40)
property(o40, cmns-dsg:hasName, o41)
property(o40, ex:joinedTo, o33)
property(o40, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o42)
property(o40, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o43)
property(o40, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o44)
property(o1, "bfo:has member part at some time", o45)
property(o45, cmns-dsg:hasName, o46)
property(o45, [[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy core:prescribedBy]], o47)
property(o45, ex:joinedTo, o33)
property(o45, ex:joinedTo, o12)
property(o45, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o48)
property(o45, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o49)
property(o1, "bfo:has member part at some time", o50)
property(o50, cmns-dsg:hasName, o51)
property(o50, ex:joinedTo, o12)
property(o50, ex:joinedTo, o18)
property(o50, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o52)
property(o50, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o53)
property(o50, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o54)
property(o1, "bfo:has member part at some time", o55)
property(o55, cmns-dsg:hasName, o56)
property(o55, ex:joinedTo, o12)
property(o55, ex:joinedTo, o18)
property(o55, [[https://spec.industrialontologies.org/ontology/core/Core/hasFunction core:hasFunction]], o57)
property(o55, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o58)
property(o1, "bfo:has member part at some time", o59)
property(o59, cmns-dsg:hasName, o60)
property(o59, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o61)
property(o59, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o62)
property(o1, "bfo:has member part at some time", o63)
property(o63, cmns-dsg:hasName, o64)
property(o63, "bfo:has member part at some time", o65)
property(o1, "bfo:has member part at some time", o66)
property(o66, cmns-dsg:hasName, o67)
property(o1, "bfo:has member part at some time", o68)
property(o68, cmns-dsg:hasName, o69)
property(o1, "bfo:has member part at some time", o70)
property(o70, cmns-dsg:hasName, o71)
property(o1, "bfo:has member part at some time", o72)
property(o72, cmns-dsg:hasName, o73)
property(o1, "bfo:has member part at some time", o74)
property(o74, cmns-dsg:hasName, o75)
property(o1, "bfo:has member part at some time", o76)
property(o76, cmns-dsg:hasName, o77)
property(o1, "bfo:has member part at some time", o78)
property(o78, cmns-dsg:hasName, o79)
property(o1, "bfo:has member part at some time", o80)
property(o80, cmns-dsg:hasName, o81)
property(o1, "bfo:has member part at some time", o82)
property(o82, cmns-dsg:hasName, o83)
property(o1, "bfo:has member part at some time", o84)
property(o84, cmns-dsg:hasName, o85)
property(o1, "bfo:has member part at some time", o33)
property(o33, cmns-dsg:hasName, o86)
property(o33, [[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime core:measuresAtSomeTime]], o87)
@enduml
