
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456_Systems1_CoolantSystem1

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA.123456_Systems1_CoolantSystem1.html OKUMA.123456_Systems1_CoolantSystem1]], vendor:[[../OKUMA.html#OKUMA.123456Systems1CoolantSystem1 OKUMA.123456Systems1CoolantSystem1]])
individual(o1, data:name20, des:Name)
individual(o2, data:[[./OKUMA.123456.html OKUMA.123456]], vendor:[[../OKUMA.html#OKUMA.123456 OKUMA.123456]])
property(o0, "des:hasName", o1)
data(o1, "des:hasTextualName", "CoolantSystem1")
property(o2, "bfo:has_member_part_at_some_time", o0)
@enduml
