
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456_Controller

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "ex":"Green",
                      "data":"76608A",
                      "vendor":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:[[./OKUMA.123456_Controller.html OKUMA.123456_Controller]], vendor:[[../OKUMA.html#OKUMA.123456Controller OKUMA.123456Controller]])
individual(o1, data:[[./OKUMA.123456_Controller_path.html OKUMA.123456_Controller_path]], vendor:[[../OKUMA.html#OKUMA.123456Controllerpath OKUMA.123456Controllerpath]])
individual(o2, data:name19, des:Name)
individual(o3, data:name18, des:Name)
individual(o4, data:[[./OKUMA.123456.html OKUMA.123456]], vendor:[[../OKUMA.html#OKUMA.123456 OKUMA.123456]])
property(o0, "bfo:has_member_part_at_some_time", o1)
data(o1, "rdfs:label", "OKUMA.123456 Controller path particular")
property(o1, "des:hasName", o2)
property(o0, "des:hasName", o3)
data(o3, "des:hasTextualName", "Controller")
property(o4, "bfo:has_member_part_at_some_time", o0)
@enduml
