@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, vendor:MazakDeviceMazak, owl:Class)
individual(o2, ex:Machine)
individual(o3, data:[[./Mazak.html Mazak]], vendor:MazakDeviceMazak)
individual(o4, data:Mazak-name, cmns-dsg:Name)
individual(o5, data:Mazak-function, ex:MillingCapability)
individual(o6, data:Mazak-capability, ex:TurningCapability)
individual(o7, data:Mazak-role, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o8, data:[[./Mazak-xaxism.html Mazak-xaxism]], vendor:MazakLinkX_AXIS)
individual(o9, data:Mazak-xaxism-name, cmns-dsg:Name)
individual(o10, data:[[./Mazak-yaxism.html Mazak-yaxism]], vendor:MazakLinkY_AXIS)
individual(o11, data:Mazak-yaxism-name, cmns-dsg:Name)
individual(o12, data:[[./Mazak-zaxis.html Mazak-zaxis]], vendor:MazakLinkZ_AXIS)
individual(o13, data:Mazak-zaxis-name, cmns-dsg:Name)
individual(o14, data:[[./Mazak-table.html Mazak-table]], vendor:MazakLinkTABLE)
individual(o15, data:Mazak-table-name, cmns-dsg:Name)
individual(o16, data:[[./Mazak-trundle.html Mazak-trundle]], vendor:MazakLinkTRUNDLE)
individual(o17, data:Mazak-trundle-name, cmns-dsg:Name)
individual(o18, data:[[./Mazak-x.html Mazak-x]], vendor:MazakLinearX)
individual(o19, data:Mazak-x-name, cmns-dsg:Name)
individual(o20, data:Mazak-x-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o21, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], vendor:MazakEnclosureenclosure)
individual(o22, data:Mazak-x-function, ex:PrismaticMotionCapability)
individual(o23, data:Mazak-x-position-actual, qp:Displacement)
individual(o24, data:[[./Mazak-x-Xballscrew.html Mazak-x-Xballscrew]], vendor:MazakBALLSCREWXballscrew)
individual(o25, data:[[./Mazak-x-Xmotor.html Mazak-x-Xmotor]], vendor:MazakMOTORXmotor)
individual(o26, data:[[./Mazak-y.html Mazak-y]], vendor:MazakLinearY)
individual(o27, data:Mazak-y-name, cmns-dsg:Name)
individual(o28, data:Mazak-y-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o29, data:Mazak-y-function, ex:PrismaticMotionCapability)
individual(o30, data:Mazak-y-position-actual, qp:Displacement)
individual(o31, data:[[./Mazak-y-Yballscrew.html Mazak-y-Yballscrew]], vendor:MazakBALLSCREWYballscrew)
individual(o32, data:[[./Mazak-y-Ymotor.html Mazak-y-Ymotor]], vendor:MazakMOTORYmotor)
individual(o33, data:[[./Mazak-z.html Mazak-z]], vendor:MazakLinearZ)
individual(o34, data:Mazak-z-name, cmns-dsg:Name)
individual(o35, data:Mazak-z-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o36, data:Mazak-z-function, ex:PrismaticMotionCapability)
individual(o37, data:Mazak-z-temperature, qp:Temperature)
individual(o38, data:Mazak-z-position-actual, qp:Displacement)
individual(o39, data:[[./Mazak-z-Zballscrew.html Mazak-z-Zballscrew]], vendor:MazakBALLSCREWZballscrew)
individual(o40, data:[[./Mazak-z-Zmotor.html Mazak-z-Zmotor]], vendor:MazakMOTORZmotor)
individual(o41, data:[[./Mazak-c.html Mazak-c]], vendor:MazakRotaryC1)
individual(o42, data:Mazak-c-name, cmns-dsg:Name)
individual(o43, data:Mazak-c-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o44, data:Mazak-c-function, ex:ContinuousMotionCapability)
individual(o45, data:Mazak-c-rotary_velocity-actual, ex:RevoluteVelocity)
individual(o46, data:[[./Mazak-c-Cmotor.html Mazak-c-Cmotor]], vendor:MazakMOTORCmotor)
individual(o47, data:[[./Mazak-br.html Mazak-br]], vendor:MazakRotaryB)
individual(o48, data:Mazak-br-name, cmns-dsg:Name)
individual(o49, data:Mazak-br-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o50, data:Mazak-br-function, ex:RevoluteMotionCapability)
individual(o51, data:Mazak-br-angle-actual, qp:Angle)
individual(o52, data:[[./Mazak-br-Bmotor.html Mazak-br-Bmotor]], vendor:MazakMOTORBmotor)
individual(o53, data:[[./Mazak-c2.html Mazak-c2]], vendor:MazakRotaryC2)
individual(o54, data:Mazak-c2-name, cmns-dsg:Name)
individual(o55, data:Mazak-c2-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o56, data:Mazak-c2-function, ex:RevoluteMotionCapability)
individual(o57, data:Mazak-c2-angle-actual, qp:Angle)
individual(o58, data:[[./Mazak-c2-C2motor.html Mazak-c2-C2motor]], vendor:MazakMOTORC2motor)
individual(o59, data:[[./Mazak-cont.html Mazak-cont]], vendor:MazakControllercontroller)
individual(o60, data:Mazak-cont-name, cmns-dsg:Name)
individual(o61, data:[[./Mazak-cont-path1.html Mazak-cont-path1]], vendor:MazakPathpath)
individual(o62, data:[[./Mazak-door1.html Mazak-door1]], vendor:MazakDoordoor)
individual(o63, data:Mazak-door1-name, cmns-dsg:Name)
individual(o64, data:[[./Mazak-partocc.html Mazak-partocc]], vendor:MazakPartOccurrencepartocc)
individual(o65, data:Mazak-partocc-name, cmns-dsg:Name)
individual(o66, data:[[./Mazak-elec.html Mazak-elec]], vendor:MazakElectricelectric)
individual(o67, data:Mazak-elec-name, cmns-dsg:Name)
individual(o68, data:[[./Mazak-hydraulic.html Mazak-hydraulic]], vendor:MazakHydraulichydraulic)
individual(o69, data:Mazak-hydraulic-name, cmns-dsg:Name)
individual(o70, data:[[./Mazak-coolant.html Mazak-coolant]], vendor:MazakCoolantcoolant)
individual(o71, data:Mazak-coolant-name, cmns-dsg:Name)
individual(o72, data:Mazak-coolant-temperature, qp:Temperature)
individual(o73, data:[[./Mazak-pneumatic.html Mazak-pneumatic]], vendor:MazakPneumaticpneumatic)
individual(o74, data:Mazak-pneumatic-name, cmns-dsg:Name)
individual(o75, data:[[./Mazak-lubrication.html Mazak-lubrication]], vendor:MazakLubricationlubrication)
individual(o76, data:Mazak-lubrication-name, cmns-dsg:Name)
individual(o77, data:[[./Mazak-procstock.html Mazak-procstock]], vendor:MazakStockstock)
individual(o78, data:Mazak-procstock-name, cmns-dsg:Name)
individual(o79, data:Mazak-enclosurem-name, cmns-dsg:Name)
individual(o80, data:Mazak-enclosurem-temperature, qp:Temperature)
property(o1, rdfs:subClassOf, o2)
property(o3, cmns-dsg:hasName, o4)
data(o4, cmns-dsg:hasTextualName, Mazak)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o5)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasCapability hasCapability]], o6)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasRole hasRole]], o7)
property(o3, "bfo:has member part at some time", o8)
property(o8, cmns-dsg:hasName, o9)
property(o3, "bfo:has member part at some time", o10)
property(o10, cmns-dsg:hasName, o11)
property(o3, "bfo:has member part at some time", o12)
property(o12, cmns-dsg:hasName, o13)
property(o3, "bfo:has member part at some time", o14)
property(o14, cmns-dsg:hasName, o15)
property(o3, "bfo:has member part at some time", o16)
property(o16, cmns-dsg:hasName, o17)
property(o3, "bfo:has member part at some time", o18)
property(o18, cmns-dsg:hasName, o19)
property(o18, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o20)
property(o18, ex:joinedTo, o21)
property(o18, ex:joinedTo, o8)
property(o18, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o22)
property(o18, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o23)
property(o18, "bfo:has member part at some time", o24)
property(o18, "bfo:has member part at some time", o25)
property(o3, "bfo:has member part at some time", o26)
property(o26, cmns-dsg:hasName, o27)
property(o26, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o28)
property(o26, ex:joinedTo, o8)
property(o26, ex:joinedTo, o10)
property(o26, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o29)
property(o26, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o30)
property(o26, "bfo:has member part at some time", o31)
property(o26, "bfo:has member part at some time", o32)
property(o3, "bfo:has member part at some time", o33)
property(o33, cmns-dsg:hasName, o34)
property(o33, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o35)
property(o33, ex:joinedTo, o10)
property(o33, ex:joinedTo, o12)
property(o33, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o36)
property(o33, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o37)
property(o33, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o38)
property(o33, "bfo:has member part at some time", o39)
property(o33, "bfo:has member part at some time", o40)
property(o3, "bfo:has member part at some time", o41)
property(o41, cmns-dsg:hasName, o42)
property(o41, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o43)
property(o41, ex:joinedTo, o12)
property(o41, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o44)
property(o41, core:[[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime measuresAtSomeTime]], o45)
property(o41, "bfo:has member part at some time", o46)
property(o3, "bfo:has member part at some time", o47)
property(o47, cmns-dsg:hasName, o48)
property(o47, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o49)
property(o47, ex:joinedTo, o21)
property(o47, ex:joinedTo, o16)
property(o47, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o50)
property(o47, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o51)
property(o47, "bfo:has member part at some time", o52)
property(o3, "bfo:has member part at some time", o53)
property(o53, cmns-dsg:hasName, o54)
property(o53, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o55)
property(o53, ex:joinedTo, o16)
property(o53, ex:joinedTo, o14)
property(o53, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o56)
property(o53, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o57)
property(o53, "bfo:has member part at some time", o58)
property(o3, "bfo:has member part at some time", o59)
property(o59, cmns-dsg:hasName, o60)
property(o59, "bfo:has member part at some time", o61)
property(o3, "bfo:has member part at some time", o62)
property(o62, cmns-dsg:hasName, o63)
property(o3, "bfo:has member part at some time", o64)
property(o64, cmns-dsg:hasName, o65)
property(o3, "bfo:has member part at some time", o66)
property(o66, cmns-dsg:hasName, o67)
property(o3, "bfo:has member part at some time", o68)
property(o68, cmns-dsg:hasName, o69)
property(o3, "bfo:has member part at some time", o70)
property(o70, cmns-dsg:hasName, o71)
property(o70, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o72)
property(o3, "bfo:has member part at some time", o73)
property(o73, cmns-dsg:hasName, o74)
property(o3, "bfo:has member part at some time", o75)
property(o75, cmns-dsg:hasName, o76)
property(o3, "bfo:has member part at some time", o77)
property(o77, cmns-dsg:hasName, o78)
property(o3, "bfo:has member part at some time", o21)
property(o21, cmns-dsg:hasName, o79)
property(o21, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o80)
@enduml
