@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-x

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, vendor:MazakLinearX, owl:Class)
individual(o2, ex:LinearMotionSystem)
individual(o3, data:[[./Mazak-x.html Mazak-x]], vendor:MazakLinearX)
individual(o4, data:Mazak-x-name, cmns-dsg:Name)
individual(o5, data:Mazak-x-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o6, data:Mazak-x-spec-LENGTH-Nominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:Mazak-x-spec-LINEAR_FORCE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o8, data:Mazak-x-spec-LINEAR_FORCE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o9, data:Mazak-x-spec-VELOCITY-RAPID-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o10, data:Mazak-x-spec-VELOCITY-RAPID-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o11, data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o12, data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o13, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], vendor:MazakEnclosureenclosure)
individual(o14, data:Mazak-enclosurem-name, cmns-dsg:Name)
individual(o15, data:Mazak-enclosurem-temperature, qp:Temperature)
individual(o16, data:[[./Mazak-xaxism.html Mazak-xaxism]], vendor:MazakLinkX_AXIS)
individual(o17, data:Mazak-xaxism-name, cmns-dsg:Name)
individual(o18, data:Mazak-x-function, ex:PrismaticMotionCapability)
individual(o19, data:Mazak-x-position-actual, qp:Displacement)
individual(o20, data:[[./Mazak-x-Xballscrew.html Mazak-x-Xballscrew]], vendor:MazakBALLSCREWXballscrew)
individual(o21, data:Mazak-x-Xballscrew-name, cmns-dsg:Name)
individual(o22, data:[[./Mazak-x-Xmotor.html Mazak-x-Xmotor]], vendor:MazakMOTORXmotor)
individual(o23, data:Mazak-x-Xmotor-temperature, qp:Temperature)
individual(o24, data:Mazak-x-Xmotor-name, cmns-dsg:Name)
individual(o25, data:[[./Mazak.html Mazak]], vendor:MazakDeviceMazak)
property(o1, rdfs:subClassOf, o2)
property(o3, cmns-dsg:hasName, o4)
data(o4, cmns-dsg:hasTextualName, X)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o5)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o6)
data(o6, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 650.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o7)
data(o7, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 5200.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o8)
data(o8, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o9)
data(o9, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o10)
data(o10, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o11)
data(o11, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o12)
data(o12, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o3, ex:joinedTo, o13)
property(o13, cmns-dsg:hasName, o14)
property(o13, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o15)
property(o3, ex:joinedTo, o16)
property(o16, cmns-dsg:hasName, o17)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o18)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o19)
property(o3, "bfo:has member part at some time", o20)
property(o20, cmns-dsg:hasName, o21)
property(o3, "bfo:has member part at some time", o22)
property(o22, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o23)
property(o22, cmns-dsg:hasName, o24)
property(o25, "bfo:has member part at some time", o3)
@enduml
