@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-br

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, vendor:MazakRotaryB, owl:Class)
individual(o2, ex:RotaryMotionSystem)
individual(o3, data:[[./Mazak-br.html Mazak-br]], vendor:MazakRotaryB)
individual(o4, data:Mazak-br-name, cmns-dsg:Name)
individual(o5, data:Mazak-br-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o6, data:Mazak-br-spec-ANGLE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o7, data:Mazak-br-spec-ANGLE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o8, data:Mazak-br-spec-TORQUE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o9, data:Mazak-br-spec-TORQUE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o10, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], vendor:MazakEnclosureenclosure)
individual(o11, data:Mazak-enclosurem-name, cmns-dsg:Name)
individual(o12, data:Mazak-enclosurem-temperature, qp:Temperature)
individual(o13, data:[[./Mazak-trundle.html Mazak-trundle]], vendor:MazakLinkTRUNDLE)
individual(o14, data:Mazak-trundle-name, cmns-dsg:Name)
individual(o15, data:Mazak-br-function, ex:RevoluteMotionCapability)
individual(o16, data:Mazak-br-angle-actual, qp:Angle)
individual(o17, data:[[./Mazak-br-Bmotor.html Mazak-br-Bmotor]], vendor:MazakMOTORBmotor)
individual(o18, data:Mazak-br-Bmotor-name, cmns-dsg:Name)
individual(o19, data:[[./Mazak.html Mazak]], vendor:MazakDeviceMazak)
property(o1, rdfs:subClassOf, o2)
property(o3, cmns-dsg:hasName, o4)
data(o4, cmns-dsg:hasTextualName, B)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o5)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o6)
data(o6, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 120.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o7)
data(o7, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], -30.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o8)
data(o8, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 400.0)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o9)
data(o9, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o3, ex:joinedTo, o10)
property(o10, cmns-dsg:hasName, o11)
property(o10, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o12)
property(o3, ex:joinedTo, o13)
property(o13, cmns-dsg:hasName, o14)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o15)
property(o3, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o16)
property(o3, "bfo:has member part at some time", o17)
property(o17, cmns-dsg:hasName, o18)
property(o19, "bfo:has member part at some time", o3)
@enduml
