@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title MazakFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:, owl:Ontology)
individual(o2, ex:)
individual(o3, vendor:MazakDeviceMazak, owl:Class)
individual(o4, ex:Machine)
individual(o5, data:[[./Mazak.html Mazak]], vendor:MazakDeviceMazak)
individual(o6, data:Mazak-name, cmns-dsg:Name)
individual(o7, data:Mazak-function, ex:MillingCapability)
individual(o8, data:Mazak-capability, ex:TurningCapability)
individual(o9, data:Mazak-role, core:[[https://spec.industrialontologies.org/ontology/core/Core/EquipmentRole EquipmentRole]])
individual(o10, data:[[./Mazak-xaxism.html Mazak-xaxism]], vendor:MazakLinkX_AXIS)
individual(o11, data:[[./Mazak-yaxism.html Mazak-yaxism]], vendor:MazakLinkY_AXIS)
individual(o12, data:[[./Mazak-zaxis.html Mazak-zaxis]], vendor:MazakLinkZ_AXIS)
individual(o13, data:[[./Mazak-table.html Mazak-table]], vendor:MazakLinkTABLE)
individual(o14, data:[[./Mazak-trundle.html Mazak-trundle]], vendor:MazakLinkTRUNDLE)
individual(o15, data:[[./Mazak-x.html Mazak-x]], vendor:MazakLinearX)
individual(o16, data:[[./Mazak-y.html Mazak-y]], vendor:MazakLinearY)
individual(o17, data:[[./Mazak-z.html Mazak-z]], vendor:MazakLinearZ)
individual(o18, data:[[./Mazak-c.html Mazak-c]], vendor:MazakRotaryC1)
individual(o19, data:[[./Mazak-br.html Mazak-br]], vendor:MazakRotaryB)
individual(o20, data:[[./Mazak-c2.html Mazak-c2]], vendor:MazakRotaryC2)
individual(o21, data:[[./Mazak-cont.html Mazak-cont]], vendor:MazakControllercontroller)
individual(o22, data:[[./Mazak-door1.html Mazak-door1]], vendor:MazakDoordoor)
individual(o23, data:[[./Mazak-partocc.html Mazak-partocc]], vendor:MazakPartOccurrencepartocc)
individual(o24, data:[[./Mazak-elec.html Mazak-elec]], vendor:MazakElectricelectric)
individual(o25, data:[[./Mazak-hydraulic.html Mazak-hydraulic]], vendor:MazakHydraulichydraulic)
individual(o26, data:[[./Mazak-coolant.html Mazak-coolant]], vendor:MazakCoolantcoolant)
individual(o27, data:[[./Mazak-pneumatic.html Mazak-pneumatic]], vendor:MazakPneumaticpneumatic)
individual(o28, data:[[./Mazak-lubrication.html Mazak-lubrication]], vendor:MazakLubricationlubrication)
individual(o29, data:[[./Mazak-procstock.html Mazak-procstock]], vendor:MazakStockstock)
individual(o30, data:[[./Mazak-enclosurem.html Mazak-enclosurem]], vendor:MazakEnclosureenclosure)
individual(o31, vendor:MazakLinkX_AXIS, owl:Class)
individual(o32, ex:Structure)
individual(o33, data:Mazak-xaxism-name, cmns-dsg:Name)
individual(o34, vendor:MazakLinkY_AXIS, owl:Class)
individual(o35, data:Mazak-yaxism-name, cmns-dsg:Name)
individual(o36, vendor:MazakLinkZ_AXIS, owl:Class)
individual(o37, data:Mazak-zaxis-name, cmns-dsg:Name)
individual(o38, vendor:MazakLinkTABLE, owl:Class)
individual(o39, data:Mazak-table-name, cmns-dsg:Name)
individual(o40, vendor:MazakLinkTRUNDLE, owl:Class)
individual(o41, data:Mazak-trundle-name, cmns-dsg:Name)
individual(o42, vendor:MazakLinearX, owl:Class)
individual(o43, ex:LinearMotionSystem)
individual(o44, data:Mazak-x-name, cmns-dsg:Name)
individual(o45, data:Mazak-x-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o46, data:Mazak-x-function, ex:PrismaticMotionCapability)
individual(o47, data:Mazak-x-position-actual, qp:Displacement)
individual(o48, data:[[./Mazak-x-Xballscrew.html Mazak-x-Xballscrew]], vendor:MazakBALLSCREWXballscrew)
individual(o49, data:[[./Mazak-x-Xmotor.html Mazak-x-Xmotor]], vendor:MazakMOTORXmotor)
individual(o50, data:Mazak-x-spec-LENGTH-Nominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o51, data:Mazak-x-spec-LINEAR_FORCE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o52, data:Mazak-x-spec-LINEAR_FORCE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o53, data:Mazak-x-spec-VELOCITY-RAPID-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o54, data:Mazak-x-spec-VELOCITY-RAPID-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o55, data:Mazak-x-spec-VELOCITY-PROGRAMMED-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o56, data:Mazak-x-spec-VELOCITY-PROGRAMMED-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o57, units:MilliM)
individual(o58, units:N)
individual(o59, units:MilliM-PER-SEC)
individual(o60, vendor:Mazak-x-Constr, owl:Class)
individual(o61, _:g197776, owl:Class)
individual(o62, _:g197896, owl:Class)
individual(o63, ex:PrismaticVelocity, rdfv:Description)
individual(o64, _:g197800)
individual(o65, _:g197784, owl:Restriction)
individual(o66, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasMeasuredValueAtSomeTime hasMeasuredValueAtSomeTime]])
individual(o67, _:g197808, owl:Class)
individual(o68, _:g197792)
individual(o70, _:g197832)
individual(o71, _:g197816, owl:Restriction)
individual(o72, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]])
individual(o73, _:g197840, rdfs:Datatype)
individual(o74, _:g197824)
individual(o75, core:[[https://spec.industrialontologies.org/ontology/core/Core/MeasuredValueExpression MeasuredValueExpression]], rdfv:Description)
individual(o76, xs:float)
individual(o77, _:g197872)
individual(o78, _:g197848)
individual(o79, _:g197856)
individual(o80, _:g197864)
individual(o81, _:g197920)
individual(o82, _:g197904, owl:Restriction)
individual(o83, _:g197928, owl:Class)
individual(o84, _:g197912)
individual(o85, _:g197952)
individual(o86, _:g197936, owl:Restriction)
individual(o87, _:g197960, rdfs:Datatype)
individual(o88, _:g197944)
individual(o89, _:g197992)
individual(o90, _:g197968)
individual(o91, _:g197976)
individual(o92, _:g197984)
individual(o93, data:Mazak-x-Xmotor-temperature, qp:Temperature)
individual(o94, data:Mazak-x-Xmotor-name, cmns-dsg:Name)
individual(o95, vendor:MazakBALLSCREWXballscrew, owl:Class)
individual(o96, ex:Ballscrew)
individual(o97, data:Mazak-x-Xballscrew-name, cmns-dsg:Name)
individual(o98, vendor:MazakMOTORXmotor, owl:Class)
individual(o99, ex:Motor)
individual(o100, vendor:MazakLinearY, owl:Class)
individual(o101, data:Mazak-y-name, cmns-dsg:Name)
individual(o102, data:Mazak-y-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o103, data:Mazak-y-function, ex:PrismaticMotionCapability)
individual(o104, data:Mazak-y-position-actual, qp:Displacement)
individual(o105, data:[[./Mazak-y-Yballscrew.html Mazak-y-Yballscrew]], vendor:MazakBALLSCREWYballscrew)
individual(o106, data:[[./Mazak-y-Ymotor.html Mazak-y-Ymotor]], vendor:MazakMOTORYmotor)
individual(o107, data:Mazak-y-spec-LENGTH-Nominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o108, data:Mazak-y-spec-LINEAR_FORCE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o109, data:Mazak-y-spec-LINEAR_FORCE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o110, data:Mazak-y-spec-VELOCITY-RAPID-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o111, data:Mazak-y-spec-VELOCITY-RAPID-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o112, data:Mazak-y-spec-VELOCITY-PROGRAMMED-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o113, data:Mazak-y-spec-VELOCITY-PROGRAMMED-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o114, vendor:Mazak-y-Constr, owl:Class)
individual(o115, _:g198240, owl:Class)
individual(o116, _:g198360, owl:Class)
individual(o117, _:g198264)
individual(o118, _:g198248, owl:Restriction)
individual(o119, _:g198272, owl:Class)
individual(o120, _:g198256)
individual(o121, _:g198296)
individual(o122, _:g198280, owl:Restriction)
individual(o123, _:g198304, rdfs:Datatype)
individual(o124, _:g198288)
individual(o125, _:g198336)
individual(o126, _:g198312)
individual(o127, _:g198320)
individual(o128, _:g198328)
individual(o129, _:g198384)
individual(o130, _:g198368, owl:Restriction)
individual(o131, _:g198392, owl:Class)
individual(o132, _:g198376)
individual(o133, _:g198416)
individual(o134, _:g198400, owl:Restriction)
individual(o135, _:g198424, rdfs:Datatype)
individual(o136, _:g198408)
individual(o137, _:g198456)
individual(o138, _:g198432)
individual(o139, _:g198440)
individual(o140, _:g198448)
individual(o141, data:Mazak-y-Ymotor-temperature, qp:Temperature)
individual(o142, data:Mazak-y-Ymotor-name, cmns-dsg:Name)
individual(o143, vendor:MazakBALLSCREWYballscrew, owl:Class)
individual(o144, data:Mazak-y-Yballscrew-name, cmns-dsg:Name)
individual(o145, vendor:MazakMOTORYmotor, owl:Class)
individual(o146, vendor:MazakLinearZ, owl:Class)
individual(o147, data:Mazak-z-name, cmns-dsg:Name)
individual(o148, data:Mazak-z-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o149, data:Mazak-z-function, ex:PrismaticMotionCapability)
individual(o150, data:Mazak-z-temperature, qp:Temperature)
individual(o151, data:Mazak-z-position-actual, qp:Displacement)
individual(o152, data:[[./Mazak-z-Zballscrew.html Mazak-z-Zballscrew]], vendor:MazakBALLSCREWZballscrew)
individual(o153, data:[[./Mazak-z-Zmotor.html Mazak-z-Zmotor]], vendor:MazakMOTORZmotor)
individual(o154, data:Mazak-z-spec-LENGTH-Nominal, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o155, data:Mazak-z-spec-LINEAR_FORCE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o156, data:Mazak-z-spec-LINEAR_FORCE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o157, data:Mazak-z-spec-VELOCITY-RAPID-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o158, data:Mazak-z-spec-VELOCITY-RAPID-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o159, data:Mazak-z-spec-VELOCITY-PROGRAMMED-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o160, data:Mazak-z-spec-VELOCITY-PROGRAMMED-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o161, vendor:Mazak-z-Constr, owl:Class)
individual(o162, _:g198616, owl:Class)
individual(o163, _:g198736, owl:Class)
individual(o164, _:g198640)
individual(o165, _:g198624, owl:Restriction)
individual(o166, _:g198648, owl:Class)
individual(o167, _:g198632)
individual(o168, _:g198672)
individual(o169, _:g198656, owl:Restriction)
individual(o170, _:g198680, rdfs:Datatype)
individual(o171, _:g198664)
individual(o172, _:g198712)
individual(o173, _:g198688)
individual(o174, _:g198696)
individual(o175, _:g198704)
individual(o176, _:g198760)
individual(o177, _:g198744, owl:Restriction)
individual(o178, _:g198768, owl:Class)
individual(o179, _:g198752)
individual(o180, _:g198792)
individual(o181, _:g198776, owl:Restriction)
individual(o182, _:g198800, rdfs:Datatype)
individual(o183, _:g198784)
individual(o184, _:g198832)
individual(o185, _:g198808)
individual(o186, _:g198816)
individual(o187, _:g198824)
individual(o188, data:Mazak-z-Zmotor-temperature, qp:Temperature)
individual(o189, data:Mazak-z-Zmotor-name, cmns-dsg:Name)
individual(o190, vendor:MazakBALLSCREWZballscrew, owl:Class)
individual(o191, data:Mazak-z-Zballscrew-name, cmns-dsg:Name)
individual(o192, vendor:MazakMOTORZmotor, owl:Class)
individual(o193, vendor:MazakRotaryC1, owl:Class)
individual(o194, ex:RotaryMotionSystem)
individual(o195, data:Mazak-c-name, cmns-dsg:Name)
individual(o196, data:Mazak-c-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o197, data:Mazak-c-function, ex:ContinuousMotionCapability)
individual(o198, data:Mazak-c-rotary_velocity-actual, ex:RevoluteVelocity)
individual(o199, data:[[./Mazak-c-Cmotor.html Mazak-c-Cmotor]], vendor:MazakMOTORCmotor)
individual(o200, data:Mazak-c-spec-VELOCITY-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o201, data:Mazak-c-spec-VELOCITY-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o202, units:REV-PER-MIN)
individual(o203, vendor:Mazak-c-Constr, owl:Class)
individual(o204, _:g198976, owl:Class)
individual(o205, _:g199000)
individual(o206, _:g198984, owl:Restriction)
individual(o207, _:g199008, owl:Class)
individual(o208, _:g198992)
individual(o209, _:g199032)
individual(o210, _:g199016, owl:Restriction)
individual(o211, _:g199040, rdfs:Datatype)
individual(o212, _:g199024)
individual(o213, _:g199072)
individual(o214, _:g199048)
individual(o215, _:g199056)
individual(o216, _:g199064)
individual(o217, data:Mazak-c-Cmotor-temperature, qp:Temperature)
individual(o218, data:Mazak-c-Cmotor-name, cmns-dsg:Name)
individual(o219, vendor:MazakMOTORCmotor, owl:Class)
individual(o220, vendor:MazakRotaryB, owl:Class)
individual(o221, data:Mazak-br-name, cmns-dsg:Name)
individual(o222, data:Mazak-br-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o223, data:Mazak-br-function, ex:RevoluteMotionCapability)
individual(o224, data:Mazak-br-angle-actual, qp:Angle)
individual(o225, data:[[./Mazak-br-Bmotor.html Mazak-br-Bmotor]], vendor:MazakMOTORBmotor)
individual(o226, data:Mazak-br-spec-ANGLE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o227, data:Mazak-br-spec-ANGLE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o228, data:Mazak-br-spec-TORQUE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o229, data:Mazak-br-spec-TORQUE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o230, units:DEG)
individual(o231, vendor:Mazak-br-Constr, owl:Class)
individual(o232, _:g199224, owl:Class)
individual(o233, qp:Angle, rdfv:Description)
individual(o234, _:g199248)
individual(o235, _:g199232, owl:Restriction)
individual(o236, _:g199256, owl:Class)
individual(o237, _:g199240)
individual(o238, _:g199280)
individual(o239, _:g199264, owl:Restriction)
individual(o240, _:g199288, rdfs:Datatype)
individual(o241, _:g199272)
individual(o242, _:g199320)
individual(o243, _:g199296)
individual(o244, _:g199304)
individual(o245, _:g199312)
individual(o246, units:N-M)
individual(o247, vendor:MazakMOTORBmotor, owl:Class)
individual(o248, data:Mazak-br-Bmotor-name, cmns-dsg:Name)
individual(o249, vendor:MazakRotaryC2, owl:Class)
individual(o250, data:Mazak-c2-name, cmns-dsg:Name)
individual(o251, data:Mazak-c2-spec, core:[[https://spec.industrialontologies.org/ontology/core/Core/DesignSpecification DesignSpecification]])
individual(o252, data:Mazak-c2-function, ex:RevoluteMotionCapability)
individual(o253, data:Mazak-c2-angle-actual, qp:Angle)
individual(o254, data:[[./Mazak-c2-C2motor.html Mazak-c2-C2motor]], vendor:MazakMOTORC2motor)
individual(o255, data:Mazak-c2-spec-ANGLE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o256, data:Mazak-c2-spec-ANGLE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o257, data:Mazak-c2-spec-TORQUE-Maximum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o258, data:Mazak-c2-spec-TORQUE-Minimum, core:[[https://spec.industrialontologies.org/ontology/core/Core/ValueExpression ValueExpression]])
individual(o259, vendor:Mazak-c2-Constr, owl:Class)
individual(o260, _:g199448, owl:Class)
individual(o261, _:g199472)
individual(o262, _:g199456, owl:Restriction)
individual(o263, _:g199480, owl:Class)
individual(o264, _:g199464)
individual(o265, _:g199504)
individual(o266, _:g199488, owl:Restriction)
individual(o267, _:g199512, rdfs:Datatype)
individual(o268, _:g199496)
individual(o269, _:g199544)
individual(o270, _:g199520)
individual(o271, _:g199528)
individual(o272, _:g199536)
individual(o273, vendor:MazakMOTORC2motor, owl:Class)
individual(o274, data:Mazak-c2-C2motor-name, cmns-dsg:Name)
individual(o275, vendor:MazakControllercontroller, owl:Class)
individual(o276, ex:ControlSystem)
individual(o277, data:Mazak-cont-name, cmns-dsg:Name)
individual(o278, data:[[./Mazak-cont-path1.html Mazak-cont-path1]], vendor:MazakPathpath)
individual(o279, vendor:MazakPathpath, owl:Class)
individual(o280, ex:ControlSystemPath)
individual(o281, data:Mazak-cont-path1-name, cmns-dsg:Name)
individual(o282, vendor:MazakDoordoor, owl:Class)
individual(o283, "bfo:object")
individual(o284, data:Mazak-door1-name, cmns-dsg:Name)
individual(o285, vendor:MazakPartOccurrencepartocc, owl:Class)
individual(o286, ex:Part)
individual(o287, data:Mazak-partocc-name, cmns-dsg:Name)
individual(o288, vendor:MazakElectricelectric, owl:Class)
individual(o289, ex:ElectricalSystem)
individual(o290, data:Mazak-elec-name, cmns-dsg:Name)
individual(o291, vendor:MazakHydraulichydraulic, owl:Class)
individual(o292, ex:HydraulicSystem)
individual(o293, data:Mazak-hydraulic-name, cmns-dsg:Name)
individual(o294, vendor:MazakCoolantcoolant, owl:Class)
individual(o295, data:Mazak-coolant-name, cmns-dsg:Name)
individual(o296, data:Mazak-coolant-temperature, qp:Temperature)
individual(o297, vendor:MazakPneumaticpneumatic, owl:Class)
individual(o298, ex:PneumaticSystem)
individual(o299, data:Mazak-pneumatic-name, cmns-dsg:Name)
individual(o300, vendor:MazakLubricationlubrication, owl:Class)
individual(o301, ex:LubricationSystem)
individual(o302, data:Mazak-lubrication-name, cmns-dsg:Name)
individual(o303, vendor:MazakEnvironmentalenvironmental, owl:Class)
individual(o304, ex:Room)
individual(o305, data:Mazak-room, vendor:MazakEnvironmentalenvironmental)
individual(o306, data:Mazak-room-name, cmns-dsg:Name)
individual(o307, data:Mazak-room-temperature, qp:Temperature)
individual(o308, vendor:MazakPersonnelpersonnel, owl:Class)
individual(o309, core:[[https://spec.industrialontologies.org/ontology/core/Core/Person Person]])
individual(o310, data:Mazak-personnelm, vendor:MazakPersonnelpersonnel)
individual(o311, data:Mazak-personnelm-name, cmns-dsg:Name)
individual(o312, vendor:MazakStockstock, owl:Class)
individual(o313, ex:Stock)
individual(o314, data:Mazak-procstock-name, cmns-dsg:Name)
individual(o315, vendor:MazakEnclosureenclosure, owl:Class)
individual(o316, data:Mazak-enclosurem-name, cmns-dsg:Name)
individual(o317, data:Mazak-enclosurem-temperature, qp:Temperature)
data(o1, rdfs:label, Machine Ontology)
property(o1, owl:imports, o2)
property(o3, rdfs:subClassOf, o4)
property(o5, cmns-dsg:hasName, o6)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o7)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasCapability hasCapability]], o8)
property(o5, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasRole hasRole]], o9)
property(o5, "bfo:has member part at some time", o10)
property(o5, "bfo:has member part at some time", o11)
property(o5, "bfo:has member part at some time", o12)
property(o5, "bfo:has member part at some time", o13)
property(o5, "bfo:has member part at some time", o14)
property(o5, "bfo:has member part at some time", o15)
property(o5, "bfo:has member part at some time", o16)
property(o5, "bfo:has member part at some time", o17)
property(o5, "bfo:has member part at some time", o18)
property(o5, "bfo:has member part at some time", o19)
property(o5, "bfo:has member part at some time", o20)
property(o5, "bfo:has member part at some time", o21)
property(o5, "bfo:has member part at some time", o22)
property(o5, "bfo:has member part at some time", o23)
property(o5, "bfo:has member part at some time", o24)
property(o5, "bfo:has member part at some time", o25)
property(o5, "bfo:has member part at some time", o26)
property(o5, "bfo:has member part at some time", o27)
property(o5, "bfo:has member part at some time", o28)
property(o5, "bfo:has member part at some time", o29)
property(o5, "bfo:has member part at some time", o30)
data(o6, cmns-dsg:hasTextualName, Mazak)
property(o31, rdfs:subClassOf, o32)
property(o10, cmns-dsg:hasName, o33)
data(o33, cmns-dsg:hasTextualName, X_AXIS)
property(o34, rdfs:subClassOf, o32)
property(o11, cmns-dsg:hasName, o35)
data(o35, cmns-dsg:hasTextualName, Y_AXIS)
property(o36, rdfs:subClassOf, o32)
property(o12, cmns-dsg:hasName, o37)
data(o37, cmns-dsg:hasTextualName, Z_AXIS)
property(o38, rdfs:subClassOf, o32)
property(o13, cmns-dsg:hasName, o39)
data(o39, cmns-dsg:hasTextualName, TABLE)
property(o40, rdfs:subClassOf, o32)
property(o14, cmns-dsg:hasName, o41)
data(o41, cmns-dsg:hasTextualName, TRUNDLE)
property(o42, rdfs:subClassOf, o43)
property(o15, cmns-dsg:hasName, o44)
property(o15, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o45)
property(o15, ex:joinedTo, o30)
property(o15, ex:joinedTo, o10)
property(o15, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o46)
property(o15, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o47)
property(o15, "bfo:has member part at some time", o48)
property(o15, "bfo:has member part at some time", o49)
data(o44, cmns-dsg:hasTextualName, X)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o50)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o51)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o52)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o53)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o54)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o55)
property(o45, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o56)
data(o50, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 650.0)
property(o50, units:hasUnit, o57)
data(o51, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 5200.0)
property(o51, units:hasUnit, o58)
data(o52, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o52, units:hasUnit, o58)
data(o53, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o53, units:hasUnit, o59)
data(o54, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o54, units:hasUnit, o59)
property(o60, owl:equivalentClass, o61)
property(o60, owl:equivalentClass, o62)
property(o60, rdfs:subClassOf, o63)
property(o61, owl:intersectionOf, o64)
property(o65, owl:onProperty, o66)
property(o65, owl:someValuesFrom, o67)
property(o68, rdfv:first, o65)
property(o64, rdfv:first, o63)
property(o64, rdfv:rest, o68)
property(o67, owl:intersectionOf, o70)
property(o71, owl:onProperty, o72)
property(o71, owl:someValuesFrom, o73)
property(o74, rdfv:first, o71)
property(o70, rdfv:first, o75)
property(o70, rdfv:rest, o74)
property(o73, owl:onDatatype, o76)
property(o73, owl:withRestrictions, o77)
data(o78, xs:maxInclusive, 7000.0)
data(o79, xs:minInclusive, 1.0)
property(o80, rdfv:first, o79)
property(o77, rdfv:first, o78)
property(o77, rdfv:rest, o80)
data(o55, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o55, units:hasUnit, o59)
data(o56, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o56, units:hasUnit, o59)
property(o62, owl:intersectionOf, o81)
property(o82, owl:onProperty, o66)
property(o82, owl:someValuesFrom, o83)
property(o84, rdfv:first, o82)
property(o81, rdfv:first, o63)
property(o81, rdfv:rest, o84)
property(o83, owl:intersectionOf, o85)
property(o86, owl:onProperty, o72)
property(o86, owl:someValuesFrom, o87)
property(o88, rdfv:first, o86)
property(o85, rdfv:first, o75)
property(o85, rdfv:rest, o88)
property(o87, owl:onDatatype, o76)
property(o87, owl:withRestrictions, o89)
data(o90, xs:maxInclusive, 7000.0)
data(o91, xs:minInclusive, 1.0)
property(o92, rdfv:first, o91)
property(o89, rdfv:first, o90)
property(o89, rdfv:rest, o92)
property(o49, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o93)
property(o49, cmns-dsg:hasName, o94)
property(o95, rdfs:subClassOf, o96)
property(o48, cmns-dsg:hasName, o97)
data(o97, cmns-dsg:hasTextualName, Xballscrew)
property(o98, rdfs:subClassOf, o99)
data(o94, cmns-dsg:hasTextualName, Xmotor)
property(o100, rdfs:subClassOf, o43)
property(o16, cmns-dsg:hasName, o101)
property(o16, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o102)
property(o16, ex:joinedTo, o10)
property(o16, ex:joinedTo, o11)
property(o16, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o103)
property(o16, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o104)
property(o16, "bfo:has member part at some time", o105)
property(o16, "bfo:has member part at some time", o106)
data(o101, cmns-dsg:hasTextualName, Y)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o107)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o108)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o109)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o110)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o111)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o112)
property(o102, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o113)
data(o107, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 550.0)
property(o107, units:hasUnit, o57)
data(o108, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 5200.0)
property(o108, units:hasUnit, o58)
data(o109, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o109, units:hasUnit, o58)
data(o110, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o110, units:hasUnit, o59)
data(o111, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o111, units:hasUnit, o59)
property(o114, owl:equivalentClass, o115)
property(o114, owl:equivalentClass, o116)
property(o114, rdfs:subClassOf, o63)
property(o115, owl:intersectionOf, o117)
property(o118, owl:onProperty, o66)
property(o118, owl:someValuesFrom, o119)
property(o120, rdfv:first, o118)
property(o117, rdfv:first, o63)
property(o117, rdfv:rest, o120)
property(o119, owl:intersectionOf, o121)
property(o122, owl:onProperty, o72)
property(o122, owl:someValuesFrom, o123)
property(o124, rdfv:first, o122)
property(o121, rdfv:first, o75)
property(o121, rdfv:rest, o124)
property(o123, owl:onDatatype, o76)
property(o123, owl:withRestrictions, o125)
data(o126, xs:maxInclusive, 7000.0)
data(o127, xs:minInclusive, 1.0)
property(o128, rdfv:first, o127)
property(o125, rdfv:first, o126)
property(o125, rdfv:rest, o128)
data(o112, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o112, units:hasUnit, o59)
data(o113, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o113, units:hasUnit, o59)
property(o116, owl:intersectionOf, o129)
property(o130, owl:onProperty, o66)
property(o130, owl:someValuesFrom, o131)
property(o132, rdfv:first, o130)
property(o129, rdfv:first, o63)
property(o129, rdfv:rest, o132)
property(o131, owl:intersectionOf, o133)
property(o134, owl:onProperty, o72)
property(o134, owl:someValuesFrom, o135)
property(o136, rdfv:first, o134)
property(o133, rdfv:first, o75)
property(o133, rdfv:rest, o136)
property(o135, owl:onDatatype, o76)
property(o135, owl:withRestrictions, o137)
data(o138, xs:maxInclusive, 7000.0)
data(o139, xs:minInclusive, 1.0)
property(o140, rdfv:first, o139)
property(o137, rdfv:first, o138)
property(o137, rdfv:rest, o140)
property(o106, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o141)
property(o106, cmns-dsg:hasName, o142)
property(o143, rdfs:subClassOf, o96)
property(o105, cmns-dsg:hasName, o144)
data(o144, cmns-dsg:hasTextualName, Yballscrew)
property(o145, rdfs:subClassOf, o99)
data(o142, cmns-dsg:hasTextualName, Ymotor)
property(o146, rdfs:subClassOf, o43)
property(o17, cmns-dsg:hasName, o147)
property(o17, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o148)
property(o17, ex:joinedTo, o11)
property(o17, ex:joinedTo, o12)
property(o17, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o149)
property(o17, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o150)
property(o17, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o151)
property(o17, "bfo:has member part at some time", o152)
property(o17, "bfo:has member part at some time", o153)
data(o147, cmns-dsg:hasTextualName, Z)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o154)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o155)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o156)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o157)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o158)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o159)
property(o148, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o160)
data(o154, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 530.0)
property(o154, units:hasUnit, o57)
data(o155, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 9600.0)
property(o155, units:hasUnit, o58)
data(o156, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o156, units:hasUnit, o58)
data(o157, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o157, units:hasUnit, o59)
data(o158, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o158, units:hasUnit, o59)
property(o161, owl:equivalentClass, o162)
property(o161, owl:equivalentClass, o163)
property(o161, rdfs:subClassOf, o63)
property(o162, owl:intersectionOf, o164)
property(o165, owl:onProperty, o66)
property(o165, owl:someValuesFrom, o166)
property(o167, rdfv:first, o165)
property(o164, rdfv:first, o63)
property(o164, rdfv:rest, o167)
property(o166, owl:intersectionOf, o168)
property(o169, owl:onProperty, o72)
property(o169, owl:someValuesFrom, o170)
property(o171, rdfv:first, o169)
property(o168, rdfv:first, o75)
property(o168, rdfv:rest, o171)
property(o170, owl:onDatatype, o76)
property(o170, owl:withRestrictions, o172)
data(o173, xs:maxInclusive, 7000.0)
data(o174, xs:minInclusive, 1.0)
property(o175, rdfv:first, o174)
property(o172, rdfv:first, o173)
property(o172, rdfv:rest, o175)
data(o159, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 7000.0)
property(o159, units:hasUnit, o59)
data(o160, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 1.0)
property(o160, units:hasUnit, o59)
property(o163, owl:intersectionOf, o176)
property(o177, owl:onProperty, o66)
property(o177, owl:someValuesFrom, o178)
property(o179, rdfv:first, o177)
property(o176, rdfv:first, o63)
property(o176, rdfv:rest, o179)
property(o178, owl:intersectionOf, o180)
property(o181, owl:onProperty, o72)
property(o181, owl:someValuesFrom, o182)
property(o183, rdfv:first, o181)
property(o180, rdfv:first, o75)
property(o180, rdfv:rest, o183)
property(o182, owl:onDatatype, o76)
property(o182, owl:withRestrictions, o184)
data(o185, xs:maxInclusive, 7000.0)
data(o186, xs:minInclusive, 1.0)
property(o187, rdfv:first, o186)
property(o184, rdfv:first, o185)
property(o184, rdfv:rest, o187)
property(o153, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o188)
property(o153, cmns-dsg:hasName, o189)
property(o190, rdfs:subClassOf, o96)
property(o152, cmns-dsg:hasName, o191)
data(o191, cmns-dsg:hasTextualName, Zballscrew)
property(o192, rdfs:subClassOf, o99)
data(o189, cmns-dsg:hasTextualName, Zmotor)
property(o193, rdfs:subClassOf, o194)
property(o18, cmns-dsg:hasName, o195)
property(o18, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o196)
property(o18, ex:joinedTo, o12)
property(o18, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o197)
property(o18, core:[[https://spec.industrialontologies.org/ontology/core/Core/measuresAtSomeTime measuresAtSomeTime]], o198)
property(o18, "bfo:has member part at some time", o199)
data(o195, cmns-dsg:hasTextualName, C1)
property(o196, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o200)
property(o196, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o201)
data(o200, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 12000.0)
property(o200, units:hasUnit, o202)
data(o201, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o201, units:hasUnit, o202)
property(o203, owl:equivalentClass, o204)
property(o203, rdfs:subClassOf, o63)
property(o204, owl:intersectionOf, o205)
property(o206, owl:onProperty, o66)
property(o206, owl:someValuesFrom, o207)
property(o208, rdfv:first, o206)
property(o205, rdfv:first, o63)
property(o205, rdfv:rest, o208)
property(o207, owl:intersectionOf, o209)
property(o210, owl:onProperty, o72)
property(o210, owl:someValuesFrom, o211)
property(o212, rdfv:first, o210)
property(o209, rdfv:first, o75)
property(o209, rdfv:rest, o212)
property(o211, owl:onDatatype, o76)
property(o211, owl:withRestrictions, o213)
data(o214, xs:maxInclusive, 12000.0)
data(o215, xs:minInclusive, 0.0)
property(o216, rdfv:first, o215)
property(o213, rdfv:first, o214)
property(o213, rdfv:rest, o216)
property(o199, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o217)
property(o199, cmns-dsg:hasName, o218)
property(o219, rdfs:subClassOf, o99)
data(o218, cmns-dsg:hasTextualName, Cmotor)
property(o220, rdfs:subClassOf, o194)
property(o19, cmns-dsg:hasName, o221)
property(o19, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o222)
property(o19, ex:joinedTo, o30)
property(o19, ex:joinedTo, o14)
property(o19, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o223)
property(o19, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o224)
property(o19, "bfo:has member part at some time", o225)
data(o221, cmns-dsg:hasTextualName, B)
property(o222, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o226)
property(o222, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o227)
property(o222, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o228)
property(o222, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o229)
data(o226, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 120.0)
property(o226, units:hasUnit, o230)
data(o227, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], -30.0)
property(o227, units:hasUnit, o230)
property(o231, owl:equivalentClass, o232)
property(o231, rdfs:subClassOf, o233)
property(o232, owl:intersectionOf, o234)
property(o235, owl:onProperty, o66)
property(o235, owl:someValuesFrom, o236)
property(o237, rdfv:first, o235)
property(o234, rdfv:first, o233)
property(o234, rdfv:rest, o237)
property(o236, owl:intersectionOf, o238)
property(o239, owl:onProperty, o72)
property(o239, owl:someValuesFrom, o240)
property(o241, rdfv:first, o239)
property(o238, rdfv:first, o75)
property(o238, rdfv:rest, o241)
property(o240, owl:onDatatype, o76)
property(o240, owl:withRestrictions, o242)
data(o243, xs:maxInclusive, 120.0)
data(o244, xs:minInclusive, -30.0)
property(o245, rdfv:first, o244)
property(o242, rdfv:first, o243)
property(o242, rdfv:rest, o245)
data(o228, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 400.0)
property(o228, units:hasUnit, o246)
data(o229, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o229, units:hasUnit, o246)
property(o247, rdfs:subClassOf, o99)
property(o225, cmns-dsg:hasName, o248)
data(o248, cmns-dsg:hasTextualName, Bmotor)
property(o249, rdfs:subClassOf, o194)
property(o20, cmns-dsg:hasName, o250)
property(o20, core:[[https://spec.industrialontologies.org/ontology/core/Core/prescribedBy prescribedBy]], o251)
property(o20, ex:joinedTo, o14)
property(o20, ex:joinedTo, o13)
property(o20, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasFunction hasFunction]], o252)
property(o20, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o253)
property(o20, "bfo:has member part at some time", o254)
data(o250, cmns-dsg:hasTextualName, C2)
property(o251, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o255)
property(o251, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o256)
property(o251, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o257)
property(o251, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasValueExpressionAtAllTimes hasValueExpressionAtAllTimes]], o258)
data(o255, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 360.0)
property(o255, units:hasUnit, o230)
data(o256, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], -360.0)
property(o256, units:hasUnit, o230)
property(o259, owl:equivalentClass, o260)
property(o259, rdfs:subClassOf, o233)
property(o260, owl:intersectionOf, o261)
property(o262, owl:onProperty, o66)
property(o262, owl:someValuesFrom, o263)
property(o264, rdfv:first, o262)
property(o261, rdfv:first, o233)
property(o261, rdfv:rest, o264)
property(o263, owl:intersectionOf, o265)
property(o266, owl:onProperty, o72)
property(o266, owl:someValuesFrom, o267)
property(o268, rdfv:first, o266)
property(o265, rdfv:first, o75)
property(o265, rdfv:rest, o268)
property(o267, owl:onDatatype, o76)
property(o267, owl:withRestrictions, o269)
data(o270, xs:maxInclusive, 360.0)
data(o271, xs:minInclusive, -360.0)
property(o272, rdfv:first, o271)
property(o269, rdfv:first, o270)
property(o269, rdfv:rest, o272)
data(o257, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 400.0)
property(o257, units:hasUnit, o246)
data(o258, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasSimpleExpressionValue hasSimpleExpressionValue]], 0.0)
property(o258, units:hasUnit, o246)
property(o273, rdfs:subClassOf, o99)
property(o254, cmns-dsg:hasName, o274)
data(o274, cmns-dsg:hasTextualName, C2motor)
property(o275, rdfs:subClassOf, o276)
property(o21, cmns-dsg:hasName, o277)
property(o21, "bfo:has member part at some time", o278)
data(o277, cmns-dsg:hasTextualName, controller)
property(o279, rdfs:subClassOf, o280)
property(o278, cmns-dsg:hasName, o281)
data(o281, cmns-dsg:hasTextualName, path)
property(o282, rdfs:subClassOf, o283)
property(o22, cmns-dsg:hasName, o284)
data(o284, cmns-dsg:hasTextualName, door)
property(o285, rdfs:subClassOf, o286)
property(o23, cmns-dsg:hasName, o287)
data(o287, cmns-dsg:hasTextualName, partocc)
property(o288, rdfs:subClassOf, o289)
property(o24, cmns-dsg:hasName, o290)
data(o290, cmns-dsg:hasTextualName, electric)
property(o291, rdfs:subClassOf, o292)
property(o25, cmns-dsg:hasName, o293)
data(o293, cmns-dsg:hasTextualName, hydraulic)
property(o294, rdfs:subClassOf, o283)
property(o26, cmns-dsg:hasName, o295)
property(o26, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o296)
data(o295, cmns-dsg:hasTextualName, coolant)
property(o297, rdfs:subClassOf, o298)
property(o27, cmns-dsg:hasName, o299)
data(o299, cmns-dsg:hasTextualName, pneumatic)
property(o300, rdfs:subClassOf, o301)
property(o28, cmns-dsg:hasName, o302)
data(o302, cmns-dsg:hasTextualName, lubrication)
property(o303, rdfs:subClassOf, o304)
property(o305, cmns-dsg:hasName, o306)
property(o305, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o307)
data(o306, cmns-dsg:hasTextualName, environmental)
property(o308, rdfs:subClassOf, o309)
property(o310, cmns-dsg:hasName, o311)
data(o311, cmns-dsg:hasTextualName, personnel)
property(o312, rdfs:subClassOf, o313)
property(o29, cmns-dsg:hasName, o314)
data(o314, cmns-dsg:hasTextualName, stock)
property(o315, rdfs:subClassOf, o32)
property(o30, cmns-dsg:hasName, o316)
property(o30, core:[[https://spec.industrialontologies.org/ontology/core/Core/hasQuality hasQuality]], o317)
data(o316, cmns-dsg:hasTextualName, enclosure)
@enduml
