@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title Mazak-procstock

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, vendor:MazakStockstock, owl:Class)
individual(o2, ex:Stock)
individual(o3, data:[[./Mazak-procstock.html Mazak-procstock]], vendor:MazakStockstock)
individual(o4, data:Mazak-procstock-name, cmns-dsg:Name)
individual(o5, data:[[./Mazak.html Mazak]], vendor:MazakDeviceMazak)
property(o1, rdfs:subClassOf, o2)
property(o3, cmns-dsg:hasName, o4)
data(o4, cmns-dsg:hasTextualName, stock)
property(o5, "bfo:has member part at some time", o3)
@enduml
