@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMA.123456-LBarFeederSystem1

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
"ex":"Green","data":"76608A","core":"000000","units":"8A2D3B","qp":"641B2E","cmns-dsg":"3A0519"
}
individual(o1, data:[[./OKUMA.123456-LBarFeederSystem1.html OKUMA.123456-LBarFeederSystem1]], "bfo:object")
individual(o2, data:OKUMA.123456-LBarFeederSystem1-name, cmns-dsg:Name)
individual(o3, data:[[./OKUMA.123456.html OKUMA.123456]], ex:Machine)
property(o1, cmns-dsg:hasName, o2)
data(o2, cmns-dsg:hasTextualName, BarFeederSystem1)
property(o3, "bfo:has member part at some time", o1)
@enduml
